// DIRECTOR B — alimento (cont.) + chequeo 4 (huevos escondidos) + 5 (ácaros) + 6 (estrés) + 7 (edad) + error de los 80 (p25-49)
import { S, BI, HZP, COOP, YARD, BARN, KITCHEN, STORE, HENS } from "./dir_lib.mjs";
import { CHECKS } from "./dir_a.mjs";
export const SHOTS = [
  S(25, "", "av", "av"),
  S(25, "I mix the new feed in", "bi", "b_mixfeed", { p: BI("A galvanized bucket on the dirt floor of a farm shed half full of two kinds of chicken feed, light crumbles and darker pellets, an older woman's hand stirring them together with a metal scoop, a paper feed sack folded open beside it."), anim: "the scoop stirs the two feeds together in the bucket" }),
  S(25, "By the end of the week", "st", "st_hensyard.13"),
  S(26, "", "av", "av"),
  S(26, "So I put out oyster shell", "bi", "b_oyster", { p: BI(`${COOP}: a small separate tin dish screwed to the wall at hen height, filled with crushed white and grey oyster shell, one reddish-brown hen pecking at it, the feeder hanging to the side.`), anim: "the hen pecks at the crushed oyster shell in the dish" }),
  S(26, "The hens take what they need", "st", "st_henpeck.2"),
  S(27, "", "av", "av"),
  S(27, "Scratch grains", "st", "st_scratch.1"),
  S(27, "But scratch is mostly corn", "bi", "b_scratchpalm", { p: BI("Close view of an older woman's open weathered palm full of scratch grains: cracked yellow corn, wheat and small round red milo seeds, over a muddy chicken yard with hens looking up at the hand."), anim: "the hand tilts and a few grains fall to the hens below" }),
  S(27, "It's candy, honey", "av", "av"),
  S(28, "", "st", "st_scratch.2"),
  S(28, "So in the molt, the scratch", "bi", "b_scratchcan", { p: BI("On a wooden shelf in a farm shed: a dented metal coffee can full of scratch grains with a small tin measuring cup resting on top, holding just a little grain, a paper feed sack below."), anim: "the hand lifts the small tin cup with a little grain out of the can" }),
  S(28, "A little in the afternoon", "av", "av"),
  S(28, "a small handful of dried mealworms", "bi", "b_mealworms", { p: BI("An older woman's hand holding out a small handful of dried golden mealworms in a farm yard, three reddish-brown hens crowding and pecking at the palm."), anim: "the hens peck quickly at the mealworms in the palm" }),
  // ── 4 · ¿DE VERDAD NO PONEN?
  S(29, "", "c", "OpChecklist", { props: { items: CHECKS, active: 3, done: 3, every: 2, bed: "st_eggcollect.2" } }),
  S(29, "Because sometimes the hens", "st", "st_eggcollect.1"),
  S(30, "", "av", "av"),
  S(30, "Look in the nest boxes for wet", "c", "OpSignCard", { props: { bed: "b_eatenegg", see: "yolk and shell in the nest", means: "egg eating", ok: false, circle: { x: 940, y: 600, rx: 260, ry: 160 } } }),
  S(30, "A hen with yolk on her face", "bi", "b_yolkbeak", { p: BI(`Close view of the head of one of the ${HENS} inside a coop, a smear of bright yellow egg yolk on its beak and the feathers around it, a broken brown eggshell on the straw below.`), anim: "the hen shakes its head and pecks at the straw" }),
  S(31, "", "av", "av"),
  S(31, "Under a bush", "bi", "b_bushnest", { p: BI("A hidden clutch of seven brown eggs in a hollow of dry fallen leaves under a bare lilac bush next to an old white farmhouse foundation, a reddish-brown feather among them."), anim: "dry leaves stir slightly around the hidden eggs in the wind" }),
  S(31, "Behind the mower", "bi", "b_mowernest", { p: BI("Inside a cluttered farm shed: a nest of loose straw with five brown eggs on the floor behind the back wheel of an old green riding lawn mower, a gas can and garden tools around, light through the open door."), anim: "a hand pushes the mower seat aside revealing the eggs" }),
  S(31, "Back in the barn", "st", "st_barnhay.1"),
  S(31, "She'll lay there every day", "av", "av"),
  S(32, "", "hz", "h_checknests", { p: HZP("She leans into the row of wooden nest boxes lifting the straw with one hand to look underneath, an empty wicker basket hanging on her other arm.", COOP) }),
  S(32, "So I crossed it off my list", "bi", "b_crossoff", { p: BI("Close view of a small spiral notebook on a coop shelf with a handwritten list in pencil, an older woman's hand drawing a pencil line through one line of the list, straw dust on the page."), anim: "the pencil draws a line through one line of the list" }),
  S(32, "And that was a mistake", "av", "av"),
  S(32, "I didn't check the barn", "bi", "b_barnout", { p: BI(`The outside of the old weathered grey barn of an Indiana farm in the morning, its big sliding door open a little, dry hay spilling at the bottom, the red chicken coop small in the corner of the frame, mud and puddles.`), anim: "the big barn door drifts open a few inches in the wind" }),
  // ── 5 · ÁCAROS DE NOCHE
  S(33, "", "c", "OpChecklist", { props: { items: CHECKS, active: 4, done: 4, every: 2, bed: "st_roost.2" } }),
  S(34, "", "st", "st_roost.4"),
  S(34, "They hide in the cracks", "bi", "b_mitecrack", { p: BI("Extreme close view of the underside of an old wooden roost bar in a chicken coop: a deep crack along the grain with clusters of tiny red and grey poultry mites packed inside it, a few crawling on the wood, droppings dust."), anim: "the tiny mites crawl slowly along the crack in the wood" }),
  S(34, "and they come out at night", "st", "st_flashlight.1"),
  S(35, "", "av", "av"),
  S(35, "take a plain white paper towel", "c", "OpMiteTest", { props: { bed: "b_roostnight", found: true, verdict: "mites", steps: ["after dark", "wipe under the roost", "look with the flashlight"] } }),
  S(36, "", "av", "av"),
  S(36, "Part the feathers under her tail", "bi", "b_parttail", { p: BI("Close view of an older woman's hands gently parting the fluffy cream and reddish-brown feathers under the tail of a hen held on a folded towel, the base of the feathers visible, a flashlight on the table."), anim: "the fingers gently part the fluffy feathers" }),
  S(36, "If you see dirty gray clumps", "c", "OpSignCard", { props: { bed: "b_fowlmites", see: "gray clumps at the base of the feathers", means: "fowl mites", ok: false, circle: { x: 960, y: 540, rx: 280, ry: 180 } } }),
  S(37, "", "bi", "b_palecomb", { p: BI(`Two ${HENS.replace("with bright red combs", "")} side by side in a farm yard, heads close to the camera: the one on the left with a bright red full comb and wattles, the one on the right with a pale pink, almost white shrunken comb.`), anim: "both hens turn their heads and the pale comb hen blinks" }),
  S(37, "She stops laying because", "av", "av"),
  S(37, "A clean coop, fresh bedding", "st", "st_cleaning.1"),
  S(37, "Read the label, every word", "bi", "b_dustlabel", { p: BI("An older woman's hands holding a plain white shaker can of poultry dust close to read the small printed label on the back, reading glasses folded on the workbench below, a box of pine shavings."), anim: "the hands turn the can to read the back of the label" }),
  S(38, "", "hz", "h_scrubroost", { p: HZP("She scrubs a long wooden roost bar with a stiff brush over a galvanized bucket of soapy water on a sawhorse outside the coop, sleeves pushed up, focused.") }),
  S(38, "I throw out all the bedding", "bi", "b_beddingout", { p: BI("An older woman's hands in work gloves forking old dark soiled pine shavings out of the door of a red chicken coop into a rusty wheelbarrow, dust in the air."), anim: "the fork tosses a load of old bedding into the wheelbarrow" }),
  S(38, "Then I treat again a week later", "bi", "b_roostsun", { p: BI(`In ${YARD}: three scrubbed wooden roost bars leaning against the fence drying in the sun, the coop door open with fresh pale shavings inside, a wheelbarrow of old dark bedding beside it.`), anim: "the sunlight brightens on the drying roost bars as a cloud moves" }),
  S(38, "If you only do it once", "av", "av"),
  S(39, "", "c", "OpMiteTest", { props: { bed: "b_roostnight2", found: false, verdict: "clean", steps: ["Wednesday night", "under the roost", "under the tails"] } }),
  // ── 6 · ESTRÉS Y PREDADORES
  S(40, "", "c", "OpChecklist", { props: { items: CHECKS, active: 5, done: 5, every: 2, bed: "st_fence.1" } }),
  S(41, "", "bi", "b_raccoonnight", { p: BI("Night on a farm, lit by a flashlight beam: a raccoon standing up on its hind legs against the chicken wire of a run, its little hands gripping the wire, eyes shining, the red coop behind."), anim: "the raccoon pulls at the chicken wire with its hands" }),
  S(41, "A fox walking the fence line", "bi", "b_foxfence", { p: BI("Early dusk on a farm: a red fox trotting along the outside of a wire fence line beside a harvested field, the red chicken coop beyond the fence."), anim: "the fox trots along the fence line and looks toward the coop" }),
  S(41, "Even a neighbor's dog", "bi", "b_dogfence", { p: BI("Dusk on a small farm: a shaggy farm dog sniffing along the bottom of a chicken wire run fence, the red coop behind with its door closed, the sky fading, a porch light on in the distance."), anim: "the dog sniffs along the fence and paws at the bottom of the wire" }),
  S(41, "Just a bad night of something trying", "av", "av"),
  S(42, "", "bi", "b_tracks", { p: BI("Close view of the wet mud by the door of a red wooden chicken coop with clear raccoon tracks pressed into it, little hand-like prints with five long toes, a few straw bits."), anim: "a drop of water falls into the mud beside the tracks" }),
  S(42, "Dirt dug out along the bottom", "bi", "b_dug", { p: BI("The bottom edge of a chicken wire run fence on a farm: a fresh hole of dirt dug out underneath the wire, the loose earth thrown out, a few feathers caught in the wire."), anim: "a few crumbs of loose dirt slide back into the hole" }),
  S(42, "A few feathers outside the fence", "bi", "b_featherfence", { p: BI("A few reddish-brown chicken feathers caught on the bottom of a wire fence and lying on the wet grass outside a chicken run on a grey morning, the red coop behind."), anim: "the feathers caught on the wire flutter in the wind" }),
  S(42, "Hens that won't come out", "bi", "b_bunched", { p: BI(`${COOP}: all the ${HENS} bunched tightly together in the far corner on the shavings, the little hen door open with daylight outside, nobody going out.`), anim: "the hens shuffle closer together in the corner" }),
  S(43, "", "c", "OpSignCard", { props: { bed: "b_tracks2", see: "little hand prints in the mud", means: "a raccoon", ok: false, circle: { x: 900, y: 640, rx: 300, ry: 170 } } }),
  S(43, "My latch is a two-step latch", "bi", "b_latch2", { p: BI("Close view of a red wooden chicken coop door with a galvanized spring-loaded barrel bolt latch plus a snap hook clipped through it, an older woman's fingers pressing the spring hook open, white trim, chipped paint."), anim: "the fingers press the spring hook and slide the bolt open" }),
  S(43, "A raccoon can open a hook", "bi", "b_hooklatch", { p: BI("Close view of a simple old hook-and-eye latch on a weathered wooden shed door at night, lit by a flashlight, the hook hanging loose and open, scratch marks on the wood around it."), anim: "the loose hook swings slightly in the flashlight beam" }),
  S(43, "Still, those hens had a bad night", "av", "av"),
  // ── 7 · EDAD
  S(44, "", "c", "OpChecklist", { props: { items: CHECKS, active: 6, done: 6, every: 2, bed: "st_redhen.3" } }),
  S(45, "", "st", "st_hensyard.9"),
  S(45, "By five or six, a lot of hens", "bi", "b_oldhen", { p: BI(`An old reddish-brown hen with faded ragged feathers resting in a patch of sun against the red wall of a coop in ${YARD.split(":")[0]}, eyes half closed, content, scaly old legs tucked.`), anim: "the old hen settles lower into the warm patch of sun" }),
  S(46, "", "av", "av", { ov: { c: "OpAsk", props: { question: "How old is your oldest hen?" } } }),
  S(46, "She's earned her rest", "hz", "h_dottieporch", { p: HZP("She sits on the wooden back porch step of the farmhouse with her red hen Dottie settled on her knees, stroking it and smiling down at it, muddy boots on the step below.", "the back porch of her old white Indiana farmhouse") }),
  S(46, "She's not going in a pot", "av", "av"),
  // ── EL ERROR DE LOS 80
  S(47, "", "av", "av"),
  S(47, "back in the eighties", "bi", "b_80sphoto", { p: BI("An older woman's weathered fingers holding a small faded square 1980s color snapshot print with a white border: the photo shows a freshly painted red chicken coop with a few hens and a young sapling beside it, the colors faded orange; behind the photo an oilcloth table."), anim: "the fingers tilt the old photo slightly toward the window light" }),
  S(47, "so I bought the first thing", "bi", "b_vitamins", { p: BI(`${STORE}, an older dim corner: a man's hand in a work shirt sliding a small plastic bottle of poultry water vitamins with a plain label across a worn wooden counter, a cash register and a calendar behind.`), anim: "the hand slides the small bottle across the counter" }),
  S(47, "A bottle of vitamins for the water", "bi", "b_yellowwater", { p: BI(`${COOP}: a plastic chicken waterer filled with yellow-tinted water from vitamins, a small open vitamin bottle on the shavings beside it, two hens drinking.`), anim: "a hen dips its beak into the yellow water and lifts its head to swallow" }),
  S(47, "Two weeks later I found mites", "bi", "b_mitesthick", { p: BI("Extreme close view of the end of an old wooden roost bar where it rests on its support: crawling with a thick mass of tiny dark red mites and grey dust, a flashlight beam lighting it from the side."), anim: "the mass of tiny mites crawls slowly in the flashlight beam" }),
  S(47, "My hens had been losing blood", "av", "av"),
  S(47, "That's why I check in order now", "c", "OpChecklist", { props: { items: CHECKS, every: 4, bed: "st_hensyard.10" } }),
  S(48, "", "c", "OpChecklist", { props: { items: CHECKS, done: 7, every: 5, title: "My list", bed: "st_coop.1" } }),
  S(49, "", "av", "av"),
  S(49, "somebody is going to try to sell", "bi", "b_storeshelf", { p: BI("A feed store shelf crowded with small colorful bags, pouches and tubs of poultry supplements, treats and remedies with handwritten price tags, an endcap display."), anim: "a hand reaches in and picks up one small pouch" }),
];
