// DIRECTOR ollarder2 — «The Camp Larder That Fed 40 Men Till Spring — No Freezer, No Power»
// Componentes NUEVOS (src/ollarder2/): LarCellar3D (corte en 3D del rincón del sótano: paredes, aislación, los dos
// caños y el aire frío que entra abajo y el tibio que sale arriba) · LarThermo (el termómetro de mínima y máxima
// clavado en la puerta del sótano, con las zonas en tiza) · LarDoorTag (la tarjeta clavada en la puerta: cada método
// con su página, y el QR en el CTA) · LarZones (los tres "cuartos": frío y húmedo / frío y seco / tibio).
import { S, AG, CAMP, OLEP, OLEX, HANDS, SNAP } from "./dir_lib.mjs";
const TAG = (title, sub, page) => ({ props: { title, sub, page } });
const RULE = (n, title, line) => ({ c: "OleRuleCard", props: { n, title, line, placement: "corner" } });
const CELLAR = "inside an old earthen root cellar of a north-woods logging camp, stone and log walls, wooden slat shelves and crates, a kerosene lantern on a nail";
export const SHOTS = [
  // ── MINUTO 1: Ole abre a cámara; la mini-película del último trineo de octubre (≥20 cortes)
  S(0, "", "vl", "m1"),
  S(0, "comes up the logging road", "st", "", { q: "horse sled snow" }),
  S(0, "and the driver tells Emil", "ar", "ar_sled"),
  S(0, "After that, nothing comes in", "st", "", { q: "snowy forest" }),
  S(0, "No truck, no store", "ar", "ar_camp"),
  S(0, "no electricity in that cook shack", "st", "", { q: "kerosene lantern" }),
  S(0, "Forty men to feed", "ar", "ar_crew"),
  S(0, "That's five months", "bi", "l_calendar", { p: CAMP("An old paper wall calendar nailed to the log wall next to the stove, a pencil hanging from it on a string, several days crossed off with big X marks, a lantern beside it.") }),
  S(1, "", "ole", "o_october", { p: OLEX("standing in deep autumn mud and early snow beside a horse-drawn sled behind a log cook shack", "He heaves a heavy burlap sack of potatoes off the sled onto his shoulder, grimacing with effort, looking back at the camera, more sacks and crates on the sled.") }),
  S(1, "Every potato, every onion", "ar", "ar_harvest"),
  S(1, "Every carrot, every apple", "st", "", { q: "carrots harvest" }),
  S(1, "And if we did it wrong", "bi", "l_rot", { p: AG(`Close view ${CELLAR}: a wooden crate of rotten soft potatoes with white mold and black spots, a bad smell almost visible, a hand holding a lantern above it.`) }),
  S(1, "we'd find out in January", "st", "", { q: "winter forest snow" }),
  S(1, "with a cellar full of rot", "ar", "ar_cellar"),
  S(1, "and forty men looking", "ar", "ar_dining"),
  S(2, "", "vl", "m2"),
  S(2, "exactly how we did it", "ole", "o_cellar_door", { p: OLEX("outside an old log root cellar door set into a snowy hillside behind a logging camp", "He pulls open the heavy plank cellar door with one hand, holding a kerosene lantern in the other, and looks back at the camera inviting it to follow him down the steps.") }),
  S(2, "without a freezer", "bi", "l_unplugged", { p: AG("An old chest freezer standing in a garage with its plug pulled out and lying on the concrete floor beside it, the lid closed, a wooden pallet and a broom nearby, daylight from the garage door.") }),
  S(2, "and without a power bill", "st", "", { q: "kerosene lantern" }),
  S(2, "Three cellars you can make", "c", "LarCellar3D", { props: { mode: "tour" } }),
  S(2, "How to keep potatoes", "ar", "ar_logcellar"),
  S(2, "And the few rules", "av", ""),
  S(3, "", "c", "LarDoorTag", TAG("The order", "eat it in the order it spoils", "page 51")),
  S(3, "and it's the difference", "bi", "l_compost", { p: AG("A wheelbarrow tipped over a garden compost heap in early spring, dumping soft rotten potatoes, sprouted onions and slimy cabbage onto it, melting snow around, a shovel stuck in the heap.") }),
  S(4, "", "av", "", { ov: { c: "OleNameTag", props: { name: "Ole", sub: "78 · logging camp cook · Minnesota" } } }),
  S(4, "I cooked in the logging", "vl", "m3"),
  S(4, "starting as a sixteenyearold", "bi", "l_young", { p: SNAP("a skinny sixteen-year-old boy in a wool cap carrying two heavy buckets of potatoes down earthen steps into a root cellar, a big man in an apron holding the door open for him.") }),
  // ── CTA (~1:32): la tarjeta clavada en la puerta del sótano lleva el QR
  S(5, "", "av", ""),
  S(5, "All of it is in a little book", "ole", "o_notebook_cellar", { p: OLEX(CELLAR, "He stands at a shelf of crates writing in a small worn notebook with a stubby pencil, counting potatoes in a crate with his eyes, the lantern lighting the page.") }),
  S(5, "a chart that tells you", "c", "OleBookPage", { props: { src: "img/ollarder2/book/p11.png", keys: [[0, 0.5, 0.5, 1], [0.9, 0.5, 0.35, 1.45]], label: "A PAGE FROM THE BOOK", sub: "Potatoes Through the Winter · page 11" } }),
  S(5, "and on page three", "c", "OleBookPage", { props: { src: "img/ollarder2/book/p3.png", keys: [[0, 0.5, 0.5, 1], [0.8, 0.5, 0.4, 1.4]], label: "PAGE 3", sub: "The rules you never break" } }),
  S(5, "It costs less than one pizza", "c", "LarDoorTag", { props: { cta: true, title: "The Winter Larder", sub: "35 ways to keep food without a freezer", page: "less than one pizza delivered", qr: "qr_ollarder2.png" } }),
  S(5, "Now, let's get to it", "av", ""),
  // ── las reglas (p.3)
  S(6, "", "av", ""),
  S(6, "and these are the ways", "c", "OleBookPage", { props: { src: "img/ollarder2/book/p3.png", keys: [[0, 0.5, 0.5, 1], [0.6, 0.5, 0.3, 1.5]], label: "THE RULES YOU NEVER BREAK", sub: "page 3" } }),
  S(7, "", "bi", "l_garlicoil", { p: AG("A pretty glass bottle of olive oil with whole garlic cloves and sprigs of rosemary inside standing on a sunny kitchen counter at room temperature."), ov: { c: "OleStamp", props: { text: "NEVER", sub: "garlic in oil at room temperature", at: 0.6 } } }),
  S(7, "But oil shuts out the air", "av", "", { ov: RULE(1, "No garlic in oil out of the fridge", "fridge, and use in 4 days") }),
  S(7, "Garlic in oil goes", "bi", "l_fridge_jar", { p: AG("A small jar of garlic in oil on the shelf of an open refrigerator, a strip of masking tape on the lid, milk and eggs beside it, the cold refrigerator light.") }),
  S(8, "", "bi", "l_canjars", { p: AG("A row of home-canned glass jars of green beans, soup and meat on a basement shelf, one lid slightly bulging, dust on the shelf, a bare bulb above.") , ov: RULE(2, "Never can without a tested recipe", "low-acid food = pressure canner") }),
  S(8, "have to be pressurecanned", "bi", "l_pressure", { p: AG("A heavy old aluminum pressure canner with its gauge on top sitting on a farmhouse stove beside a printed booklet of tested recipes held open by a jar, daylight.") }),
  S(8, "can grow a poison", "av", ""),
  S(8, "My book doesn't teach canning", "ole", "o_shake_head", { p: OLEX(CELLAR, "He shakes his head slowly and firmly at the camera with one hand raised, palm out, beside a shelf of jars, his face serious and kind.") }),
  S(8, "For canning, you go", "bi", "l_tested", { p: AG("A worn printed booklet of tested home canning recipes lying open on a kitchen table next to empty clean glass jars and new lids, a pencil marking the page, daylight.") }),
  S(9, "", "bi", "l_curedham", { p: AG("A store-bought cured country ham in its cloth bag hanging from a hook on a log beam, and a slab of salt pork wrapped in butcher paper on a shelf below it, lantern light.") , ov: RULE(3, "Don't cure meat by guesswork", "buy it cured") }),
  S(9, "In camp, we bought it cured", "ar", "ar_store"),
  S(10, "", "bi", "l_pickled_fridge", { p: AG("A glass jar of pink pickled eggs on the middle shelf of an open refrigerator, the cold white light inside, a plate of leftovers covered with foil beside it.") , ov: RULE(4, "Pickled eggs & cooked food: fridge", "always") }),
  S(10, "And a cold porch", "bi", "l_porch_food", { p: AG("A pot of leftover stew sitting on a bench on a closed wooden porch in winter, frost on the window behind it, sunlight hitting the pot through the glass."), ov: { c: "OleStamp", props: { text: "NOT A FRIDGE", sub: "for cooked food", at: 0.6 } } }),
  S(11, "", "bi", "l_mold", { p: AG("Close view of an open crock of sauerkraut with patches of fuzzy blue-green and pink mold on the surface of the brine, on a cellar shelf, lantern light.") , ov: RULE(5, "If it looks wrong, it goes out", "don't taste it first") }),
  S(11, "a bulging lid", "bi", "l_bulge", { p: AG("Close view of a glass jar with a metal lid domed and bulging upward, cloudy foamy liquid inside, on a wooden shelf.") }),
  S(11, "Out it goes", "ole", "o_toss", { p: OLEX("behind a log cabin in the snow beside a compost heap", "He tips a crock of spoiled food out onto the compost heap without even looking at it, his face firm, a shovel in his other hand.") }),
  S(12, "", "c", "LarThermo", { props: { mode: "intro", lo: 34, hi: 41 } }),
  S(12, "About twelve dollars", "bi", "l_minmax", { p: AG("A simple old-fashioned min-max thermometer with two glass tubes and little blue markers screwed to a weathered plank door inside a cellar, a nail and a pencil on a string beside it, lantern light.") }),
  S(12, "Emil had one nailed", "ole", "o_read_thermo", { p: OLEX(CELLAR, "He leans close to a min-max thermometer nailed to the inside of the plank cellar door, reading it with his glasses pushed up, a tin mug of coffee in his other hand, early morning.") }),
  // ── el sótano: 3 maneras
  S(13, "", "av", ""),
  S(13, "You don't need a hole", "st", "", { q: "root cellar" }),
  S(13, "A cellar is any spot", "c", "LarZones", { props: { mode: "rule" } }),
  S(14, "", "c", "LarCellar3D", { props: { mode: "corner" } }),
  S(14, "And here's the part people get backwards", "av", ""),
  S(14, "The cold earth on the other side", "c", "LarCellar3D", { props: { mode: "earth" } }),
  S(14, "You build the two inside walls", "st", "", { q: "old basement" }),
  S(14, "and run two vent pipes", "c", "LarCellar3D", { props: { mode: "vents" } }),
  S(14, "Wooden slat shelves", "bi", "l_slat_shelves", { p: AG("A finished basement-corner root cellar: two concrete foundation walls and two new walls of studs and pink foam board, wooden slat shelves holding crates of potatoes and apples a few inches off the concrete, a vent pipe near the floor, a bare bulb.") }),
  S(14, "That runs sixty to a hundred", "c", "LarDoorTag", TAG("The basement-corner cellar", "$60–$150 · every winter", "page 8")),
  S(15, "", "av", ""),
  S(15, "The buried barrel", "bi", "l_barrel_dig", { p: AG("A clean metal trash can sunk into a fresh hole in a backyard garden in late autumn, its rim a few inches above the dirt, a shovel and a pile of dug earth beside it, bare trees and a wooden fence.") }),
  S(15, "with the rim two to four inches", "st", "", { q: "shovel digging" }),
  S(15, "You layer your vegetables in straw", "bi", "l_barrel_layers", { p: AG(`Looking down into a metal trash can buried in the ground, carrots and beets laid in layers between thick golden straw, ${HANDS} placing another layer of carrots.`) , anim: "the hands lay carrots into the straw" }),
  S(15, "then a foot or two of straw", "bi", "l_straw_top", { p: AG("A metal trash can buried in a backyard garden, its lid on and a thick heap of golden straw piled two feet high over the top, a tarp folded beside it, bare trees.") }),
  S(15, "That keeps roots crisp", "c", "LarDoorTag", TAG("The buried barrel", "$30–$50 · fall to spring", "page 9")),
  S(16, "", "av", ""),
  S(16, "An old chest cooler", "bi", "l_cooler", { p: AG("An old white chest cooler on a wooden pallet against the inside wall of an unheated garage, lid open, crates of potatoes and carrots inside, a separate small bin of onions, winter light from a garage window.") }),
  S(16, "A thermometer inside the box", "bi", "l_cooler_thermo", { p: AG("Close view inside an open chest cooler full of potatoes with a small round thermometer lying on top of them, the needle at about 38, frost on the garage window behind.") }),
  S(16, "Here's the trick", "ole", "o_warmjug", { p: OLEX("in a cold unheated garage at night", "He sets a gallon jug of steaming warm water down inside an open chest cooler full of potatoes, his breath fogging, looking at the camera with a knowing nod.") }),
  S(16, "It gives off its heat slow", "c", "LarDoorTag", TAG("The garage cooler box", "$0–$40 · a jug of warm water on cold nights", "page 10")),
  // ── qué va adentro: cada comida quiere algo distinto
  S(17, "", "av", ""),
  S(17, "Every food wants something different", "c", "LarZones", { props: { mode: "three" } }),
  S(17, "Put them all in one place", "bi", "l_mixed_rot", { p: AG(`Close view ${CELLAR}: one crate with potatoes, apples, onions and a cabbage all thrown together, the potatoes sprouting long white shoots, the onions soft, a bad mess.`) }),
  // potatoes p.11
  S(18, "", "bi", "l_brushpotato", { p: AG(`Close view of ${HANDS} brushing dry dirt off a freshly dug potato with a stiff brush, not washing it, a burlap sack of more dirty potatoes beside him on a plank floor.`) , anim: "the brush sweeps the dry dirt off the potato" }),
  S(18, "Then you cure them", "ole", "o_cure", { p: OLEX("in a dim dry log storeroom", "He spreads unwashed potatoes out in a single layer on newspaper on the plank floor, kneeling, checking each one, a lantern beside him.") }),
  S(18, "Sort out any cut", "bi", "l_sort_potatoes", { p: AG(`Close view of ${HANDS} sorting unwashed potatoes on newspaper on a plank floor, setting a cut one and a green one aside from the good ones.`) }),
  S(18, "Store only the perfect ones", "st", "", { q: "root cellar" }),
  S(18, "Colder than thirtyeight", "c", "LarThermo", { props: { mode: "potato", lo: 38, hi: 45, marks: [{ v: 38, t: "colder: sweet" }, { v: 50, t: "warmer: sprouts" }] } }),
  S(18, "And every two or three weeks", "bi", "l_soft_one", { p: AG(`Close view ${CELLAR}: ${HANDS} pulling one soft sprouting potato out of a crate of good ones and holding it up to the lantern.`) }),
  S(18, "Five to eight months", "c", "LarDoorTag", TAG("Potatoes", "5–8 months · 38–45°F, dark", "page 11")),
  // onions & garlic p.12
  S(19, "", "bi", "l_onion_braid", { p: AG("Long braids of yellow storage onions with dry rustling skins hanging from nails on a log wall in a dry storeroom, a few loose onions in a basket below.") }),
  S(19, "In a damp cellar", "bi", "l_onion_neck", { p: AG("Close view of a yellow onion rotting soft and dark at the neck, held in an old hand, other onions in a damp crate behind it.") }),
  S(19, "So you cure them", "st", "", { q: "garlic bulbs" }),
  S(19, "Then hang them where", "bi", "l_onion_cure", { p: AG("Yellow storage onions spread out in a single layer on old window screens set across sawhorses in a dry shaded shed, their necks dry and the outer skins papery, a few hanging in mesh bags behind.") }),
  S(19, "Emil kept ours in an old pair", "ole", "o_stockings", { p: OLEP("He holds up a long pair of old nylon stockings stuffed with yellow onions, each onion separated by a knot, grinning at the camera with raised eyebrows, the stocking hanging from a nail by the cabin door.") }),
  S(19, "When you need one", "bi", "l_snip", { p: CAMP(`Close view of ${HANDS} snipping off the bottom onion from a nylon stocking of onions just below a knot with a pair of old scissors.`) , anim: "the scissors snip below the knot and the onion drops into the hand" }),
  S(19, "Page twelve", "c", "LarDoorTag", TAG("Onions & garlic", "cold and DRY · hung", "page 12")),
  // carrots in sand p.13
  S(20, "", "st", "", { q: "carrots harvest" }),
  S(20, "because the greens pull water", "bi", "l_twist", { p: AG(`Close view of ${HANDS} twisting the green tops off a bunch of fresh unwashed carrots over a wooden box, leaving half an inch of stem.`) , anim: "the hands twist the greens off" }),
  S(20, "Wet some clean play sand", "bi", "l_sand_squeeze", { p: AG(`Close view of ${HANDS} squeezing a fistful of barely damp sand that holds together like a wrung-out sponge, over a wooden box half full of sand.`) }),
  S(20, "Two inches of sand in a box", "ole", "o_sand_layer", { p: OLEX(CELLAR, "He kneels by a wooden box laying carrots in a row on a bed of damp sand so none of them touch, then scooping sand over them with a tin can, concentrated.") }),
  S(20, "Keep that box in the coldest", "st", "", { q: "carrots in sand" }),
  S(20, "And if the sand dries out", "bi", "l_mist", { p: AG(`Close view ${CELLAR}: a hand misting the top of a wooden box of sand with a small tin sprinkler can, the tops of carrots just showing.`) }),
  // cabbage p.14
  S(21, "", "st", "", { q: "cabbage harvest" }),
  S(21, "The old way kept cabbage", "ar", "ar_cabbagehall"),
  S(21, "tie a string around the root", "ole", "o_hang_cabbage", { p: OLEX(CELLAR, "He reaches up to tie a big green cabbage upside down by its root to a log beam with twine, three more already hanging beside it, squinting up at the knot.") }),
  S(21, "because cabbage smells strong", "ole", "o_sniff", { p: OLEX(CELLAR, "He sniffs the air near a hanging cabbage and pulls a comic face, waving his hand in front of his nose, looking at the camera.") }),
  S(21, "When you want one", "bi", "l_cabbage_peel", { p: AG("Close view of a cabbage on a cellar shelf with its dry outer leaves peeled back to show the crisp pale green fresh head inside, a hand holding the peeled leaves.") }),
  S(21, "And a storebought cabbage", "bi", "l_newspaper_cabbage", { p: AG("A green cabbage wrapped in two sheets of old newspaper at the back of the bottom shelf of a refrigerator, a carton of eggs beside it.") }),
  // apples p.15 — el cuarto propio
  S(22, "", "av", ""),
  S(22, "A ripening apple gives off", "c", "LarZones", { props: { mode: "apple" } }),
  S(22, "That's where the old saying", "bi", "l_bad_apple", { p: AG("Close view of a wooden barrel of red apples with one brown rotten apple in the middle and the apples touching it starting to soften and brown, cellar lantern light.") }),
  S(22, "and you handle them like eggs", "st", "", { q: "apples crate" }),
  S(22, "Granny Smith, Fuji", "ar", "ar_applebarrels"),
  S(22, "Wrap every single one", "ole", "o_wrap_apple", { p: OLEP("He wraps a red apple in a square of old newspaper on the plank table with careful gentle hands, a crate of wrapped apples beside him, smiling softly.") }),
  S(22, "lay them one or two layers", "bi", "l_wrapped_box", { p: AG("A shallow wooden box of apples each wrapped in a square of old newspaper, one layer deep, on a shelf at the far end of a cellar away from the potatoes.") }),
  S(22, "Wrapped like that", "c", "LarDoorTag", TAG("Apples & pears", "their own room · 2–6 months", "page 15")),
  S(22, "Two to six months", "c", "OleBookPage", { props: { src: "img/ollarder2/book/p15.png", keys: [[0, 0.5, 0.5, 1], [0.7, 0.5, 0.35, 1.45]], label: "PAGE 15", sub: "Apples & Pears in Their Own Room" } }),
  // squash + sweet potatoes p.17-18
  S(23, "", "st", "", { q: "winter squash" }),
  S(23, "Cut the stem, never pull it", "st", "", { q: "winter squash" }),
  S(23, "And butternut gets sweeter", "st", "", { q: "pumpkins harvest" }),
  S(23, "And sweet potatoes", "st", "", { q: "sweet potatoes" }),
  S(23, "A closet on an inside wall", "st", "", { q: "sweet potatoes" }),
  S(23, "Never in the cellar", "c", "LarThermo", { props: { mode: "warm", lo: 55, hi: 60, marks: [{ v: 50, t: "below: rots" }] } }),
  // roots in the ground p.19
  S(24, "", "st", "", { q: "garden snow" }),
  S(24, "After the first hard frosts", "ole", "o_straw", { p: OLEX("in a frosty late-autumn garden behind a log cabin", "He forks a big load of golden straw over rows of carrots and parsnips, a tarp and wooden stakes ready beside him, his breath fogging.") }),
  S(24, "with a tarp on top", "st", "", { q: "snow covered garden" }),
  S(24, "When you want some", "bi", "l_dig_parsnip", { p: AG(`Close view in a snowy garden: thick straw pulled back from a row, ${HANDS} pulling a long pale parsnip out of the dark soil, snow around.`) , anim: "the hand pulls the parsnip up out of the soil" }),
  S(24, "And parsnips that sit through", "bi", "l_parsnips", { p: AG("A handful of long pale parsnips with dark soil on them lying on snow beside a garden fork, Christmas lights on a farmhouse porch in the background at dusk.") }),
  S(24, "Page nineteen", "c", "LarDoorTag", TAG("Roots left in the ground", "12–18 in. of straw · until spring", "page 19")),
  // cold porch p.21
  S(25, "", "st", "", { q: "porch winter" }),
  S(25, "But it is not a refrigerator", "av", ""),
  S(25, "You put the thermometer right where", "bi", "l_porch_thermo", { p: AG("A closed wooden winter porch with frosted windows: a latched wooden bin, a crock of sauerkraut and a min-max thermometer standing right on top of the bin, morning light.") }),
  S(25, "Between thirtythree and forty", "c", "LarThermo", { props: { mode: "porch", lo: 33, hi: 40, marks: [{ v: 40, t: "sun on the glass" }] } }),
  S(25, "And on a sunny day", "st", "", { q: "porch winter" }),
  S(25, "So no cooked food", "av", ""),
  // drying p.24-29
  S(26, "", "ole", "o_strings", { p: OLEP("He stands under strings of drying apple rings, green beans and herb bundles hanging from a wire above the black wood cookstove, reaching up to touch one, looking at the camera.") }),
  S(26, "In camp we strung", "st", "", { q: "dried herbs hanging" }),
  S(27, "", "st", "", { q: "drying apple slices" }),
  S(27, "and thread them on a clean cotton string", "st", "", { q: "drying apple slices" }),
  S(27, "They're done when they're leathery", "bi", "l_tear_ring", { p: AG("Extreme close view of two old fingers tearing a dried leathery apple ring in half, no moisture at the torn edge, more rings on a string behind.") }),
  S(27, "put them in it loose", "ole", "o_shake_jar", { p: OLEP("He shakes a big glass jar loosely filled with dried apple rings, holding it up to the window light and peering at the glass for any drops, very focused.") }),
  S(27, "That's called conditioning", "c", "LarDoorTag", TAG("Apple rings on a string", "dry · then a week of shaking", "page 24")),
  S(28, "", "st", "", { q: "green beans" }),
  S(28, "You thread whole green beans", "bi", "l_britches", { p: CAMP(`Close view of ${HANDS} pushing a big needle with heavy thread through the middle of whole green beans, a long string of beans already threaded hanging from the table edge.`) }),
  S(28, "In the winter you soak them", "bi", "l_britches_pot", { p: CAMP("Close view into a black pot of dark dried string beans simmering with a smoked ham hock, steam rising, a long brittle string of dried beans hanging on a nail behind the stove.") }),
  // jerky p.29
  S(29, "", "av", ""),
  S(29, "Lean beef, a quarter inch thick", "st", "", { q: "slicing beef" }),
  S(29, "you bring the strips up to", "ole", "o_thermometer_jerky", { p: OLEP("He holds an instant-read thermometer stuck into a strip of beef simmering in dark marinade in a black skillet on the stove, reading the dial carefully, glasses on his nose.") }),
  S(29, "That kills the germs", "c", "LarThermo", { props: { mode: "jerky", lo: 160, hi: 160, marks: [{ v: 160, t: "BEFORE drying" }] } }),
  S(29, "until a strip bends and cracks", "st", "", { q: "beef jerky" }),
  // crocks p.33
  S(30, "", "st", "", { q: "shredding cabbage" }),
  S(30, "Twentyfive pounds of cabbage", "ar", "ar_krautbarrels"),
  S(30, "Shred it thin", "bi", "l_kraut_squeeze", { p: CAMP(`Close view of ${HANDS} squeezing shredded cabbage and salt in a big tin bowl until juice runs between the fingers.`) , anim: "the hands squeeze the cabbage and juice runs" }),
  S(30, "and pack it hard", "ole", "o_pack_crock", { p: OLEP("He packs shredded cabbage hard into a big brown stoneware crock with his fist, leaning his weight into it, sleeves rolled up, a bowl of more cabbage beside him.") }),
  S(30, "A plate on top", "st", "", { q: "fermenting crock" }),
  S(30, "And if you see a white film", "c", "OleMythTrick", { props: { front: { kicker: "WHAT YOU SEE", text: "White film on the kraut brine", stamp: "YEAST" }, back: { kicker: "WHAT YOU DO", text: "Skim it off", note: "fuzzy colored mold or pink kraut: the whole batch goes", stamp: "SAFE" }, bed: "img/ollarder2/l_kraut_squeeze.jpg" } }),
  S(30, "Page thirtythree", "c", "LarDoorTag", TAG("The five-gallon kraut crock", "25 lb cabbage · about a cup of salt", "page 33")),
  // pickled eggs p.39
  S(31, "", "st", "", { q: "pickled eggs" }),
  S(31, "But I'll say it again", "av", ""),
  S(31, "Not on the counter", "bi", "l_eggs_fridge", { p: AG("A glass jar of pickled eggs being put onto a refrigerator shelf by an old hand, the cold white light inside, the door open.") , ov: { c: "OleStamp", props: { text: "FRIDGE ONLY", sub: "not for one single day", at: 0.4 } } }),
  // dry shelf p.41-45
  S(32, "", "st", "", { q: "flour sack" }),
  S(32, "When it's below zero outside", "ole", "o_flour_box", { p: OLEX("outside a log cabin in deep snow at below zero", "He sets sealed paper bags of flour into a closed metal box sitting in the snow by the cabin wall, frost on his beard, his breath a cloud.") }),
  S(32, "Otherwise, the freezer", "bi", "l_freezer_flour", { p: AG("Sealed paper bags of flour and cornmeal stacked inside an ordinary chest freezer, frost on the walls of the freezer, a strip of masking tape with a date on one bag.") }),
  S(32, "and pour them into tins", "st", "", { q: "pouring flour" }),
  S(33, "", "bi", "l_cheddar", { p: CAMP("A big block of orange cheddar cut into pieces on a wooden board, some already dipped in glossy red cheese wax, a double boiler of melted wax on the stove behind.") }),
  S(33, "Paraffin cracks in the cold", "bi", "l_wax", { p: CAMP(`Close view of ${HANDS} brushing hot red cheese wax onto a block of cheddar over a double boiler on the stove, a natural bristle brush.`) , anim: "the brush spreads the red wax" }),
  S(33, "Strain it warm", "bi", "l_lard_strain", { p: CAMP("Close view of warm golden lard pouring through a cheesecloth strainer into a small glass jar on the plank table, three full jars beside it filled to the very top.") , anim: "the lard pours through the cloth into the jar" }),
  S(33, "Small jars are better", "bi", "l_lard_jars", { p: CAMP("A row of small glass jars of white rendered lard filled to the very top with tight lids on a dark plank shelf, one big jar beside them half empty with a spoon in it.") }),
  S(33, "Six months to a year", "bi", "l_lard_shelf", { p: AG("A row of small glass jars of white lard filled right to the top, lids tight, on a dark cool cellar shelf, one jar open with a knife in it, lantern light.") }),
  // el orden (p.51)
  S(34, "", "av", ""),
  S(35, "", "ar", "ar_cook"),
  S(35, "First the things that keep worst", "c", "LarZones", { props: { mode: "order" } }),
  S(35, "Then the cabbage and the celery", "ar", "ar_cellar2"),
  S(35, "And last of all", "ar", "ar_cellar3"),
  S(35, "Do it backwards", "ole", "o_soft_squash", { p: OLEX(CELLAR, "He holds up a soft collapsing rotten squash with a disgusted look and his nose wrinkled, shaking his head at the camera.") }),
  S(36, "", "ole", "o_rootpot", { p: OLEP("He drops chunks of rutabaga, carrots and potatoes into a huge black pot on the stove where a ham bone is simmering, steam rising, talking to the camera.") }),
  S(36, "That pot was the backbone", "ar", "ar_dining2"),
  S(36, "And something sour", "st", "", { q: "sauerkraut" }),
  S(36, "That's what kept forty men", "ar", "ar_eating"),
  S(37, "", "st", "", { q: "frozen river ice" }),
  S(37, "Emil would walk down", "bi", "l_spring_count", { p: AG(`Spring: ${CELLAR}, a big man's hand with a pencil writing in a small ledger book held against a nearly empty potato crate, bright daylight streaming down the steps.`) }),
  S(37, "there was a little bit left", "ole", "o_spring_smile", { p: OLEX("standing at the open door of a log root cellar in early spring, melting snow and mud around, sunshine", "He holds up the last few good potatoes in his big hands with a proud quiet smile at the camera.") }),
  // cierre
  S(38, "", "ole", "o_door_tag", { p: OLEX(CELLAR, "He taps a cream paper card tacked to the inside of the plank cellar door with one finger, smiling at the camera, the lantern beside him.") }),
  S(38, "The code is right here", "c", "LarDoorTag", { props: { cta: true, title: "The Winter Larder", sub: "35 methods · chart for 40 foods · page 3 rules", page: "the link is the first one in the description", qr: "qr_ollarder2.png" } }),
  S(39, "", "c", "OleCTA", { props: { cover: "img/ollarder2/book/cookbook_cover.png", qr: "qr_ollarder2_book.png", kicker: "COOK FROM THAT LARDER", point: "Point your phone here", line: "73 old camp recipes", text: "The cookbook's link is in the description too" } }),
  S(40, "", "av", "", { ov: { c: "OleAsk", props: { text: "Did your folks have a root cellar? What did they keep down there?" } } }),
  S(41, "", "av", ""),
];
