// GENERATED by build_cmecalor.mjs.
export type CmecalorCue = {key:string;start:number;dur:number;type:"still"|"clip"|"float";src:string;clipDuration:number|null;kicker:string|null;side:"left"|"right"|null;anchor:string;nouns:string[];sourceMoment:string};
export const CUES_CMECALOR = [
  {
    "key": "cmec_v2_root_001_still",
    "start": 0,
    "dur": 245,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_root_001.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "La pieza del título no produce calor, no genera electricidad y por sí sola no mantiene caliente una casa.",
    "nouns": [
      "pieza",
      "calor",
      "electricidad",
      "casa"
    ],
    "sourceMoment": "cmec_v2_root_001"
  },
  {
    "key": "cmec_a_001_still",
    "start": 352,
    "dur": 323,
    "type": "still",
    "src": "img/cmecalor/cmec_a_001_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "permite alimentar únicamente la calefacción que ya tienes, sin intentar sostener cada enchufe, cada lámpara y cada aparato del hogar durante un apagón.",
    "nouns": [
      "calefacción",
      "enchufe",
      "lámpara",
      "aparato",
      "hogar",
      "apagón"
    ],
    "sourceMoment": "cmec_a_001"
  },
  {
    "key": "cmec_v2_0_001_still",
    "start": 685,
    "dur": 184,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_0_001.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si tu equipo calienta con gas puede haber una sorpresa enorme escondida detrás de su tapa.",
    "nouns": [
      "equipo a gas",
      "tapa",
      "interior"
    ],
    "sourceMoment": "cmec_v2_0_001"
  },
  {
    "key": "cmec_a_002_still",
    "start": 886,
    "dur": 352,
    "type": "still",
    "src": "img/cmecalor/cmec_a_002_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "La llama entrega miles de vatios de calor, pero la parte eléctrica quizá solo necesita unos cientos para mover el ventilador, controlar la combustión y obedecer al termostato.",
    "nouns": [
      "llama",
      "vatios",
      "parte eléctrica",
      "ventilador",
      "combustión",
      "termostato"
    ],
    "sourceMoment": "cmec_a_002"
  },
  {
    "key": "cmec_m_009_still",
    "start": 1472,
    "dur": 69,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_009_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "compres el primer tomacorriente que encuentres",
    "nouns": [
      "tomacorriente",
      "calefacción"
    ],
    "sourceMoment": "cmec_m_009"
  },
  {
    "key": "cmec_a_003_still",
    "start": 1591,
    "dur": 295,
    "type": "still",
    "src": "img/cmecalor/cmec_a_003_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "La misma idea puede ser una solución segura o una conexión capaz de incendiar una casa, dañar la placa electrónica o devolver corriente hacia la calle.",
    "nouns": [
      "conexión",
      "casa",
      "placa electrónica",
      "corriente",
      "calle"
    ],
    "sourceMoment": "cmec_a_003"
  },
  {
    "key": "cmec_v2_root_005_still",
    "start": 1900,
    "dur": 163,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_root_005.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "La diferencia no está en el precio de la pieza, está en una palabra, aislamiento.",
    "nouns": [
      "pieza",
      "aislamiento",
      "fuentes"
    ],
    "sourceMoment": "cmec_v2_root_005"
  },
  {
    "key": "cmec_a_004_still",
    "start": 2426,
    "dur": 313,
    "type": "still",
    "src": "img/cmecalor/cmec_a_004.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "una batería relativamente pequeña puede sostener una caldera a gas durante horas, pero puede agotarse en menos de una hora si intentas alimentar un calefactor eléctrico.",
    "nouns": [
      "batería",
      "caldera a gas",
      "horas",
      "calefactor eléctrico"
    ],
    "sourceMoment": "cmec_a_004"
  },
  {
    "key": "cmec_a_005_still",
    "start": 2911,
    "dur": 275,
    "type": "still",
    "src": "img/cmecalor/cmec_a_005.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "La batería parece tener potencia suficiente, el ventilador intenta arrancar y, aun así, la calefacción se bloquea.",
    "nouns": [
      "batería",
      "potencia",
      "ventilador",
      "calefacción"
    ],
    "sourceMoment": "cmec_a_005"
  },
  {
    "key": "cmec_m_022_still",
    "start": 3828,
    "dur": 92,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_022_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "no vamos a tocar un conductor ni una tubería de gas en este video.",
    "nouns": [
      "conductor",
      "tubería de gas"
    ],
    "sourceMoment": "cmec_m_022"
  },
  {
    "key": "cmec_v2_root_006_still",
    "start": 3945,
    "dur": 219,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_root_006.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "La instalación eléctrica fija y cualquier intervención dentro de un equipo de combustión se revisan con el manual,",
    "nouns": [
      "instalación eléctrica fija",
      "equipo de combustión",
      "manual"
    ],
    "sourceMoment": "cmec_v2_root_006"
  },
  {
    "key": "cmec_v2_root_006_clip",
    "start": 3945,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_root_006.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "La instalación eléctrica fija y cualquier intervención dentro de un equipo de combustión se revisan con el manual,",
    "nouns": [
      "instalación eléctrica fija",
      "equipo de combustión",
      "manual"
    ],
    "sourceMoment": "cmec_v2_root_006"
  },
  {
    "key": "cmec_v2_flow_001_still",
    "start": 4387,
    "dur": 102,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_flow_001.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "se corta la electricidad, pero el gas sigue llegando.",
    "nouns": [
      "electricidad",
      "gas",
      "calefacción",
      "línea de gas"
    ],
    "sourceMoment": "cmec_v2_flow_001"
  },
  {
    "key": "cmec_m_025_still",
    "start": 4528,
    "dur": 60,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_025_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "¿por qué se apaga una calefacción a gas?",
    "nouns": [
      "calefacción a gas",
      "apagón"
    ],
    "sourceMoment": "cmec_m_025"
  },
  {
    "key": "cmec_v2_root_007_still",
    "start": 4596,
    "dur": 164,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_root_007.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Porque el gas pone el calor, pero la electricidad dirige casi todo lo demás.",
    "nouns": [
      "gas",
      "calor",
      "electricidad",
      "control"
    ],
    "sourceMoment": "cmec_v2_root_007"
  },
  {
    "key": "cmec_v2_root_007_clip",
    "start": 4596,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_root_007.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Porque el gas pone el calor, pero la electricidad dirige casi todo lo demás.",
    "nouns": [
      "gas",
      "calor",
      "electricidad",
      "control"
    ],
    "sourceMoment": "cmec_v2_root_007"
  },
  {
    "key": "cmec_a_006_still",
    "start": 4832,
    "dur": 422,
    "type": "still",
    "src": "img/cmecalor/cmec_a_006_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "la placa recibe la orden del termostato, verifica los seguros, enciende el extractor, abre la válvula, confirma la llama y después mueve un ventilador grande para repartir el aire caliente por los conductos.",
    "nouns": [
      "placa",
      "termostato",
      "seguros",
      "extractor",
      "válvula",
      "llama",
      "ventilador",
      "conductos"
    ],
    "sourceMoment": "cmec_a_006"
  },
  {
    "key": "cmec_m_031_still",
    "start": 5107,
    "dur": 147,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_031.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "mueve un ventilador grande para repartir el aire caliente por los conductos.",
    "nouns": [
      "ventilador grande",
      "aire caliente",
      "conductos"
    ],
    "sourceMoment": "cmec_m_031"
  },
  {
    "key": "cmec_v2_0_004_still",
    "start": 5263,
    "dur": 278,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_0_004.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "En una caldera de agua, la electricidad puede alimentar la placa, el encendido y la bomba que hace circular el agua por radiadores o pisor radiante.",
    "nouns": [
      "caldera",
      "placa",
      "encendido",
      "bomba",
      "radiadores",
      "piso radiante"
    ],
    "sourceMoment": "cmec_v2_0_004"
  },
  {
    "key": "cmec_v2_root_008_still",
    "start": 5554,
    "dur": 265,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_root_008.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Sin esa pequeña parte eléctrica, puede haber combustible en la tubería y aún así no llegar una sola caloría útil a las habitaciones.",
    "nouns": [
      "parte eléctrica",
      "combustible",
      "tubería",
      "habitaciones",
      "calor"
    ],
    "sourceMoment": "cmec_v2_root_008"
  },
  {
    "key": "cmec_v2_root_008_clip",
    "start": 5554,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_root_008.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Sin esa pequeña parte eléctrica, puede haber combustible en la tubería y aún así no llegar una sola caloría útil a las habitaciones.",
    "nouns": [
      "parte eléctrica",
      "combustible",
      "tubería",
      "habitaciones",
      "calor"
    ],
    "sourceMoment": "cmec_v2_root_008"
  },
  {
    "key": "cmec_v2_flow_002_still",
    "start": 6025,
    "dur": 96,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_flow_002.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "La casa se enfría aunque el tanque de gas esté lleno.",
    "nouns": [
      "casa",
      "tanque de gas",
      "termostato",
      "frío"
    ],
    "sourceMoment": "cmec_v2_flow_002"
  },
  {
    "key": "cmec_a_007_still",
    "start": 6433,
    "dur": 330,
    "type": "still",
    "src": "img/cmecalor/cmec_a_007.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "horno o caldera que produce calor con gas, gas licuado o algún otro combustible, pero necesita electricidad para sus controles, su ventilador o su bomba.",
    "nouns": [
      "caldera",
      "gas",
      "electricidad",
      "controles",
      "ventilador",
      "bomba"
    ],
    "sourceMoment": "cmec_a_007"
  },
  {
    "key": "cmec_a_007_clip",
    "start": 6433,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_agnes/cmec_a_007.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "horno o caldera que produce calor con gas, gas licuado o algún otro combustible, pero necesita electricidad para sus controles, su ventilador o su bomba.",
    "nouns": [
      "caldera",
      "gas",
      "electricidad",
      "controles",
      "ventilador",
      "bomba"
    ],
    "sourceMoment": "cmec_a_007"
  },
  {
    "key": "cmec_m_039_still",
    "start": 6709,
    "dur": 22,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_039.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "su ventilador",
    "nouns": [
      "ventilador de calefacción"
    ],
    "sourceMoment": "cmec_m_039"
  },
  {
    "key": "cmec_v2_flow_003_still",
    "start": 6770,
    "dur": 232,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_flow_003.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Aquí el respaldo no tiene que fabricar el calor, solo tiene que mantener vivo el cerebro y mover el aire o el agua.",
    "nouns": [
      "respaldo",
      "calor",
      "cerebro",
      "aire",
      "agua",
      "caja de control",
      "ventilador",
      "batería"
    ],
    "sourceMoment": "cmec_v2_flow_003"
  },
  {
    "key": "cmec_a_008_still",
    "start": 7151,
    "dur": 417,
    "type": "still",
    "src": "img/cmecalor/cmec_a_008.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "equipos antiguos de tiro natural que funcionan con piloto permanente y sistema de milivoltios. Algunos pueden operar sin conexión a la red porque la propia llama alimenta la válvula y el calor se mueve por convección.",
    "nouns": [
      "equipos",
      "tiro natural",
      "piloto permanente",
      "milivoltios",
      "red",
      "llama",
      "válvula",
      "calor",
      "convección"
    ],
    "sourceMoment": "cmec_a_008"
  },
  {
    "key": "cmec_a_008_clip",
    "start": 7151,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_agnes/cmec_a_008.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "equipos antiguos de tiro natural que funcionan con piloto permanente y sistema de milivoltios. Algunos pueden operar sin conexión a la red porque la propia llama alimenta la válvula y el calor se mueve por convección.",
    "nouns": [
      "equipos",
      "tiro natural",
      "piloto permanente",
      "milivoltios",
      "red",
      "llama",
      "válvula",
      "calor",
      "convección"
    ],
    "sourceMoment": "cmec_a_008"
  },
  {
    "key": "cmec_v2_0_005_still",
    "start": 7798,
    "dur": 120,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_0_005.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "no lo modifiques por costumbre, revisa su placa y su manual.",
    "nouns": [
      "equipo",
      "placa",
      "manual"
    ],
    "sourceMoment": "cmec_v2_0_005"
  },
  {
    "key": "cmec_v2_0_005_clip",
    "start": 7798,
    "dur": 120,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_0_005.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "no lo modifiques por costumbre, revisa su placa y su manual.",
    "nouns": [
      "equipo",
      "placa",
      "manual"
    ],
    "sourceMoment": "cmec_v2_0_005"
  },
  {
    "key": "cmec_a_009_still",
    "start": 8039,
    "dur": 530,
    "type": "still",
    "src": "img/cmecalor/cmec_a_009_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "calefacción eléctrica por resistencia, caloventor, radiador eléctrico, bomba de calor o aire acondicionado en modo calor. La electricidad es el calor, o mueve un compresor de gran potencia.",
    "nouns": [
      "calefacción eléctrica",
      "resistencia",
      "caloventor",
      "radiador eléctrico",
      "bomba de calor",
      "aire acondicionado",
      "electricidad",
      "compresor"
    ],
    "sourceMoment": "cmec_a_009"
  },
  {
    "key": "cmec_a_010_still",
    "start": 8782,
    "dur": 352,
    "type": "still",
    "src": "img/cmecalor/cmec_a_010_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Un calefactor eléctrico portátil puede pedir alrededor de mil quinientos vatios de forma continua. Una estación de energía de un kilovatio hora puede vaciarse en bastante menos de una hora",
    "nouns": [
      "calefactor eléctrico",
      "vatios",
      "estación de energía",
      "kilovatio hora",
      "hora"
    ],
    "sourceMoment": "cmec_a_010"
  },
  {
    "key": "cmec_v2_0_002_still",
    "start": 9230,
    "dur": 220,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_0_002.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "En cambio, si una calefacción a gas consume 400 vatios cuando su ventilador está encendido y trabaja por ciclos,",
    "nouns": [
      "calefacción a gas",
      "400 vatios",
      "ventilador",
      "ciclos"
    ],
    "sourceMoment": "cmec_v2_0_002"
  },
  {
    "key": "cmec_v2_0_002_clip",
    "start": 9230,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_0_002.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "En cambio, si una calefacción a gas consume 400 vatios cuando su ventilador está encendido y trabaja por ciclos,",
    "nouns": [
      "calefacción a gas",
      "400 vatios",
      "ventilador",
      "ciclos"
    ],
    "sourceMoment": "cmec_v2_0_002"
  },
  {
    "key": "cmec_v2_0_006_still",
    "start": 9752,
    "dur": 156,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_0_006.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Ahora sí, la pieza. Lo que ves junto al equipo es un punto de conexión con tierra.",
    "nouns": [
      "pieza",
      "equipo",
      "conexión con tierra"
    ],
    "sourceMoment": "cmec_v2_0_006"
  },
  {
    "key": "cmec_v2_0_006_clip",
    "start": 9752,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_0_006.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Ahora sí, la pieza. Lo que ves junto al equipo es un punto de conexión con tierra.",
    "nouns": [
      "pieza",
      "equipo",
      "conexión con tierra"
    ],
    "sourceMoment": "cmec_v2_0_006"
  },
  {
    "key": "cmec_a_011_still",
    "start": 10066,
    "dur": 238,
    "type": "still",
    "src": "img/cmecalor/cmec_a_011.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "un electricista puede convertir la alimentación fija de la calefacción en una conexión mediante cordón y tomacorriente accesible.",
    "nouns": [
      "electricista",
      "alimentación fija",
      "calefacción",
      "conexión",
      "cordón",
      "tomacorriente"
    ],
    "sourceMoment": "cmec_a_011"
  },
  {
    "key": "cmec_v2_flow_004_still",
    "start": 10313,
    "dur": 113,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_flow_004.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "En condiciones normales, el equipo recibe energía de la red.",
    "nouns": [
      "equipo",
      "energía",
      "red",
      "tomacorriente",
      "cordón"
    ],
    "sourceMoment": "cmec_v2_flow_004"
  },
  {
    "key": "cmec_v2_0_003_still",
    "start": 10435,
    "dur": 177,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_0_003.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Durante un apagón se desconecta de esa fuente y se alimenta desde una batería con inversor",
    "nouns": [
      "apagón",
      "fuente de red",
      "batería",
      "inversor",
      "cordón"
    ],
    "sourceMoment": "cmec_v2_0_003"
  },
  {
    "key": "cmec_v2_0_003_clip",
    "start": 10435,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_0_003.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Durante un apagón se desconecta de esa fuente y se alimenta desde una batería con inversor",
    "nouns": [
      "apagón",
      "fuente de red",
      "batería",
      "inversor",
      "cordón"
    ],
    "sourceMoment": "cmec_v2_0_003"
  },
  {
    "key": "cmec_v2_0_012_still",
    "start": 10938,
    "dur": 78,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_0_012.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "El cordón debe ser apropiado para el equipo.",
    "nouns": [
      "cordón",
      "equipo"
    ],
    "sourceMoment": "cmec_v2_0_012"
  },
  {
    "key": "cmec_v2_0_012_clip",
    "start": 10938,
    "dur": 78,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_0_012.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "El cordón debe ser apropiado para el equipo.",
    "nouns": [
      "cordón",
      "equipo"
    ],
    "sourceMoment": "cmec_v2_0_012"
  },
  {
    "key": "cmec_v2_0_007_still",
    "start": 11030,
    "dur": 51,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_0_007.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "La caja debe quedar cerrada.",
    "nouns": [
      "caja eléctrica",
      "tapa",
      "tornillo"
    ],
    "sourceMoment": "cmec_v2_0_007"
  },
  {
    "key": "cmec_v2_0_007_clip",
    "start": 11030,
    "dur": 51,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_0_007.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "La caja debe quedar cerrada.",
    "nouns": [
      "caja eléctrica",
      "tapa",
      "tornillo"
    ],
    "sourceMoment": "cmec_v2_0_007"
  },
  {
    "key": "cmec_v2_0_008_still",
    "start": 11093,
    "dur": 65,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_0_008.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "La puesta a tierra debe conservarse.",
    "nouns": [
      "puesta a tierra",
      "conductor verde",
      "tornillo de tierra",
      "caja"
    ],
    "sourceMoment": "cmec_v2_0_008"
  },
  {
    "key": "cmec_v2_0_009_still",
    "start": 11166,
    "dur": 88,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_0_009.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "La protección del circuito debe seguir existiendo",
    "nouns": [
      "protección",
      "circuito",
      "disyuntor",
      "tablero"
    ],
    "sourceMoment": "cmec_v2_0_009"
  },
  {
    "key": "cmec_a_012_still",
    "start": 11654,
    "dur": 406,
    "type": "still",
    "src": "img/cmecalor/cmec_a_012_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "un conmutador de transferencia de un solo circuito. Tiene una entrada para la fuente de respaldo y un selector que conecta la calefacción a la red o al respaldo, pero nunca a los dos al mismo tiempo.",
    "nouns": [
      "conmutador de transferencia",
      "circuito",
      "entrada",
      "fuente de respaldo",
      "selector",
      "calefacción",
      "red"
    ],
    "sourceMoment": "cmec_a_012"
  },
  {
    "key": "cmec_v2_0_010_still",
    "start": 12680,
    "dur": 210,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_0_010.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "La conexión prohibida es intentar alimentar la casa enchufando un generador en un tomacorriente común.",
    "nouns": [
      "generador",
      "casa",
      "tomacorriente común",
      "conexión prohibida"
    ],
    "sourceMoment": "cmec_v2_0_010"
  },
  {
    "key": "cmec_v2_0_010_clip",
    "start": 12680,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_0_010.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "La conexión prohibida es intentar alimentar la casa enchufando un generador en un tomacorriente común.",
    "nouns": [
      "generador",
      "casa",
      "tomacorriente común",
      "conexión prohibida"
    ],
    "sourceMoment": "cmec_v2_0_010"
  },
  {
    "key": "cmec_m_070_still",
    "start": 12904,
    "dur": 72,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_070_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "A eso se le llama retroalimentación.",
    "nouns": [
      "generador",
      "cable",
      "tomacorriente",
      "barrera"
    ],
    "sourceMoment": "cmec_m_070"
  },
  {
    "key": "cmec_m_071_still",
    "start": 12994,
    "dur": 111,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_071_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Puede energizar cables que un técnico de la compañía cree muertos",
    "nouns": [
      "técnico de la compañía",
      "cables de servicio",
      "detector de tensión",
      "guantes"
    ],
    "sourceMoment": "cmec_m_071"
  },
  {
    "key": "cmec_m_072_still",
    "start": 13121,
    "dur": 179,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_072_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "puede saltarse protecciones de tu instalación y puede mandar tensión donde nunca debía aparecer.",
    "nouns": [
      "Claudio",
      "tablero cerrado",
      "protecciones",
      "cable suelto"
    ],
    "sourceMoment": "cmec_m_072"
  },
  {
    "key": "cmec_a_013_still",
    "start": 13316,
    "dur": 114,
    "type": "still",
    "src": "img/cmecalor/cmec_a_013.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Tampoco se usa un cable con clavijas macho en ambos extremos.",
    "nouns": [
      "cable",
      "clavijas macho",
      "extremos"
    ],
    "sourceMoment": "cmec_a_013"
  },
  {
    "key": "cmec_v2_0_011_still",
    "start": 13440,
    "dur": 154,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_0_011.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si tienes uno no es una herramienta de emergencia, es un riesgo de electrocución.",
    "nouns": [
      "cable con dos clavijas macho",
      "herramienta",
      "electrocución"
    ],
    "sourceMoment": "cmec_v2_0_011"
  },
  {
    "key": "cmec_v2_root_002_still",
    "start": 13608,
    "dur": 289,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_root_002.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Para una carga fija como una calefacción, la solución correcta es un sistema que garantice físicamente que la red y el respaldo no se encuentren.",
    "nouns": [
      "carga fija",
      "calefacción",
      "red",
      "respaldo",
      "aislamiento físico"
    ],
    "sourceMoment": "cmec_v2_root_002"
  },
  {
    "key": "cmec_m_078_still",
    "start": 14441,
    "dur": 222,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_078_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Ahora vamos a los números, porque aquí es donde esta idea deja de ser un truco de internet y se convierte en un plan.",
    "nouns": [
      "Claudio",
      "teléfono",
      "medidor",
      "cuaderno",
      "calculadora"
    ],
    "sourceMoment": "cmec_m_078"
  },
  {
    "key": "cmec_a_016_still",
    "start": 14670,
    "dur": 292,
    "type": "still",
    "src": "img/cmecalor/ig_dg_cmec_a_016.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Necesitas cuatro datos: potencia mientras funciona, pico de arranque, porcentaje de tiempo encendida y capacidad útil del respaldo.",
    "nouns": [
      "datos",
      "potencia",
      "pico de arranque",
      "porcentaje de tiempo",
      "capacidad útil",
      "respaldo"
    ],
    "sourceMoment": "cmec_a_016"
  },
  {
    "key": "cmec_v2_root_003_still",
    "start": 15119,
    "dur": 126,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_root_003.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "El primer dato no sale del tamaño del interruptor del tablero.",
    "nouns": [
      "dato",
      "interruptor",
      "tablero"
    ],
    "sourceMoment": "cmec_v2_root_003"
  },
  {
    "key": "cmec_a_014_still",
    "start": 15570,
    "dur": 330,
    "type": "still",
    "src": "img/cmecalor/cmec_a_014_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Para acercarte al consumo real, empieza por la placa del equipo y por su manual. Busca tensión, corriente nominal y cualquier dato del motor del ventilador o de la bomba.",
    "nouns": [
      "consumo",
      "placa del equipo",
      "manual",
      "tensión",
      "corriente nominal",
      "motor",
      "ventilador",
      "bomba"
    ],
    "sourceMoment": "cmec_a_014"
  },
  {
    "key": "cmec_v2_5_001_still",
    "start": 15967,
    "dur": 233,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_5_001.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si el equipo ya está conectado mediante un sistema autorizado, un medidor de energía apropiado puede mostrar los vatios.",
    "nouns": [
      "equipo",
      "sistema autorizado",
      "medidor de energía",
      "vatios"
    ],
    "sourceMoment": "cmec_v2_5_001"
  },
  {
    "key": "cmec_m_090_still",
    "start": 16213,
    "dur": 187,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_090_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si continúa cableado de forma fija, la medición se hace con instrumentos y procedimiento profesional.",
    "nouns": [
      "calefacción cableada",
      "electricista",
      "instrumento profesional",
      "cajas cerradas"
    ],
    "sourceMoment": "cmec_m_090"
  },
  {
    "key": "cmec_m_091_still",
    "start": 16414,
    "dur": 166,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_091_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "No abras el tablero para meter una pinza si no sabes exactamente qué estás tocando.",
    "nouns": [
      "Claudio",
      "tablero cerrado",
      "pinza amperométrica"
    ],
    "sourceMoment": "cmec_m_091"
  },
  {
    "key": "cmec_m_092_still",
    "start": 16489,
    "dur": 91,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_092_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "si no sabes exactamente qué estás tocando.",
    "nouns": [
      "electricista",
      "guantes",
      "instrumento",
      "tablero cerrado"
    ],
    "sourceMoment": "cmec_m_092"
  },
  {
    "key": "cmec_m_093_still",
    "start": 16595,
    "dur": 160,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_093_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "El objetivo es obtener un número, no convertir la prueba en una emergencia.",
    "nouns": [
      "Claudio",
      "cuaderno",
      "medidor",
      "calefacción cerrada"
    ],
    "sourceMoment": "cmec_m_093"
  },
  {
    "key": "cmec_b_002_still",
    "start": 16873,
    "dur": 205,
    "type": "still",
    "src": "img/cmecalor/ig_dg_cmec_b_002.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Imagina una calefacción a gas que consume cuatrocientos veinte vatios cuando el ventilador está trabajando.",
    "nouns": [
      "calefacción a gas",
      "ventilador",
      "medidor",
      "cuatrocientos veinte vatios"
    ],
    "sourceMoment": "cmec_b_002"
  },
  {
    "key": "cmec_v2_root_009_still",
    "start": 17096,
    "dur": 111,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_root_009.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Al arrancar, durante un instante, se acerca a 900.",
    "nouns": [
      "arranque",
      "900 vatios",
      "medidor"
    ],
    "sourceMoment": "cmec_v2_root_009"
  },
  {
    "key": "cmec_v2_root_010_still",
    "start": 17231,
    "dur": 237,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_root_010.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "En una hora fría, el quemador y el ventilador permanecen activos 24 minutos y descansan 36.",
    "nouns": [
      "hora fría",
      "quemador",
      "ventilador",
      "24 minutos",
      "36 minutos"
    ],
    "sourceMoment": "cmec_v2_root_010"
  },
  {
    "key": "cmec_v2_root_011_still",
    "start": 17577,
    "dur": 277,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_root_011.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "420 vatios multiplicados por 0,4 dan 168 vatios de promedio mientras pasan los ciclos.",
    "nouns": [
      "420 vatios",
      "0,4",
      "168 vatios",
      "promedio",
      "ciclos"
    ],
    "sourceMoment": "cmec_v2_root_011"
  },
  {
    "key": "cmec_b_003_still",
    "start": 18049,
    "dur": 409,
    "type": "still",
    "src": "img/cmecalor/ig_dg_cmec_b_003.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Una batería anunciada como de mil veinticuatro vatios hora no entrega cada uno de esos vatios hora al enchufe: el inversor consume parte, el frío reduce rendimiento y conviene dejar reserva.",
    "nouns": [
      "batería",
      "inversor",
      "enchufe",
      "frío",
      "reserva"
    ],
    "sourceMoment": "cmec_b_003"
  },
  {
    "key": "cmec_v2_root_012_still",
    "start": 18469,
    "dur": 274,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_root_012.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si cuentas con algo más de 800 vatios hora útiles y divides por 180, obtienes alrededor de 4 horas y media.",
    "nouns": [
      "800 vatios hora útiles",
      "180 vatios",
      "4 horas y media",
      "calculadora"
    ],
    "sourceMoment": "cmec_v2_root_012"
  },
  {
    "key": "cmec_m_105_still",
    "start": 18748,
    "dur": 102,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_105_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Ese resultado vale para ese ejemplo, no para tu casa.",
    "nouns": [
      "Claudio",
      "cuaderno de ejemplo",
      "casa",
      "calefacción real"
    ],
    "sourceMoment": "cmec_m_105"
  },
  {
    "key": "cmec_v2_5_002_still",
    "start": 18977,
    "dur": 170,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_5_002.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si la vivienda pierde calor rápido y la calefacción trabaja casi sin parar, disminuye.",
    "nouns": [
      "vivienda",
      "pérdida de calor",
      "calefacción",
      "tiempo"
    ],
    "sourceMoment": "cmec_v2_5_002"
  },
  {
    "key": "cmec_v2_5_002_clip",
    "start": 18977,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_5_002.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Si la vivienda pierde calor rápido y la calefacción trabaja casi sin parar, disminuye.",
    "nouns": [
      "vivienda",
      "pérdida de calor",
      "calefacción",
      "tiempo"
    ],
    "sourceMoment": "cmec_v2_5_002"
  },
  {
    "key": "cmec_b_004_still",
    "start": 19156,
    "dur": 169,
    "type": "still",
    "src": "img/cmecalor/cmec_b_004.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si la batería está fría, envejecida o alimenta otras cargas, también disminuye.",
    "nouns": [
      "batería fría",
      "batería envejecida",
      "otras cargas",
      "teléfono"
    ],
    "sourceMoment": "cmec_b_004"
  },
  {
    "key": "cmec_m_109_still",
    "start": 19345,
    "dur": 189,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_109_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "la cifra honesta no está impresa en la caja de la estación. Sale de tu consumo y de tu ciclo real.",
    "nouns": [
      "caja de estación",
      "medidor",
      "reloj",
      "calefacción"
    ],
    "sourceMoment": "cmec_m_109"
  },
  {
    "key": "cmec_v2_root_013_still",
    "start": 19654,
    "dur": 307,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_root_013.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "La fuente de respaldo puede soportar 400 vatios continuos y apagarse cada vez que el motor intenta arrancar porque durante una fracción de segundo pide mucho más.",
    "nouns": [
      "fuente de respaldo",
      "400 vatios continuos",
      "motor",
      "arranque",
      "pico"
    ],
    "sourceMoment": "cmec_v2_root_013"
  },
  {
    "key": "cmec_b_007_still",
    "start": 20528,
    "dur": 494,
    "type": "still",
    "src": "img/cmecalor/ig_dg_cmec_b_007.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Arriba hay tres columnas. En la primera dice qué produce el calor: gas, combustible o electricidad. En la segunda, qué parte necesita corriente: control, ventilador, bomba o resistencia. En la tercera, qué tipo de respaldo tiene sentido.",
    "nouns": [
      "tres columnas",
      "gas",
      "combustible",
      "electricidad",
      "control",
      "ventilador",
      "bomba",
      "resistencia",
      "respaldo"
    ],
    "sourceMoment": "cmec_b_007"
  },
  {
    "key": "cmec_m_118_still",
    "start": 20737,
    "dur": 187,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_118.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "En la segunda, qué parte necesita corriente: control, ventilador, bomba o resistencia.",
    "nouns": [
      "placa de control",
      "ventilador",
      "bomba",
      "resistencia"
    ],
    "sourceMoment": "cmec_m_118"
  },
  {
    "key": "cmec_v2_5_003_still",
    "start": 21035,
    "dur": 201,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_5_003.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si el calor viene del gas y la electricidad solo mueve control y ventilador, mide consumo y pico.",
    "nouns": [
      "gas",
      "electricidad",
      "control",
      "ventilador",
      "consumo",
      "pico"
    ],
    "sourceMoment": "cmec_v2_5_003"
  },
  {
    "key": "cmec_v2_5_004_still",
    "start": 21313,
    "dur": 190,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_5_004.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si el equipo funciona por milivoltios y no tiene alimentación de red, confirma el manual y no agregues nada.",
    "nouns": [
      "equipo de milivoltios",
      "alimentación de red",
      "manual"
    ],
    "sourceMoment": "cmec_v2_5_004"
  },
  {
    "key": "cmec_v2_5_004_clip",
    "start": 21313,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_5_004.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Si el equipo funciona por milivoltios y no tiene alimentación de red, confirma el manual y no agregues nada.",
    "nouns": [
      "equipo de milivoltios",
      "alimentación de red",
      "manual"
    ],
    "sourceMoment": "cmec_v2_5_004"
  },
  {
    "key": "cmec_v2_5_005_still",
    "start": 21503,
    "dur": 255,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_5_005.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si el calor viene de una resistencia o de un compresor grande, deja de mirar baterías pequeñas y calcula un sistema de otra categoría.",
    "nouns": [
      "resistencia",
      "compresor grande",
      "batería pequeña",
      "sistema"
    ],
    "sourceMoment": "cmec_v2_5_005"
  },
  {
    "key": "cmec_v2_5_005_clip",
    "start": 21503,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_5_005.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Si el calor viene de una resistencia o de un compresor grande, deja de mirar baterías pequeñas y calcula un sistema de otra categoría.",
    "nouns": [
      "resistencia",
      "compresor grande",
      "batería pequeña",
      "sistema"
    ],
    "sourceMoment": "cmec_v2_5_005"
  },
  {
    "key": "cmec_b_009_still",
    "start": 22126,
    "dur": 432,
    "type": "still",
    "src": "img/cmecalor/ig_dg_cmec_b_009.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Capacidad útil dividida por promedio real. A un lado está el control de arranque: potencia de pico disponible mayor que el pico medido. Y al otro, el control de conexión: red y respaldo físicamente aislados.",
    "nouns": [
      "capacidad útil",
      "promedio real",
      "potencia de pico",
      "pico medido",
      "red",
      "respaldo",
      "aislamiento"
    ],
    "sourceMoment": "cmec_b_009"
  },
  {
    "key": "cmec_b_010_still",
    "start": 22567,
    "dur": 234,
    "type": "still",
    "src": "img/cmecalor/ig_dg_cmec_b_010.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Son tres casillas. Autonomía. Arranque. Aislamiento. Si una falla, el sistema no está listo.",
    "nouns": [
      "tres casillas",
      "autonomía",
      "arranque",
      "aislamiento",
      "sistema"
    ],
    "sourceMoment": "cmec_b_010"
  },
  {
    "key": "cmec_m_127_still",
    "start": 22708,
    "dur": 93,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_127_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si una falla, el sistema no está listo.",
    "nouns": [
      "Claudio",
      "tres módulos",
      "un indicador fallido",
      "cable desconectado"
    ],
    "sourceMoment": "cmec_m_127"
  },
  {
    "key": "cta_microgeneradores_1_1",
    "start": 22837,
    "dur": 370,
    "type": "float",
    "src": "img/cmecalor/cmec_cta_microgeneradores.png",
    "clipDuration": null,
    "kicker": "Escanea con tu celular",
    "side": "right",
    "anchor": "esta hoja forma parte del capítulo sobre microgeneradores de la guía del canal",
    "nouns": [
      "guía",
      "código QR"
    ],
    "sourceMoment": "cta_microgeneradores_1"
  },
  {
    "key": "cta_microgeneradores_1_2",
    "start": 23207,
    "dur": 371,
    "type": "float",
    "src": "img/cmecalor/cmec_cta_pages.png",
    "clipDuration": null,
    "kicker": "Capítulo: microgeneradores",
    "side": "left",
    "anchor": "esta hoja forma parte del capítulo sobre microgeneradores de la guía del canal",
    "nouns": [
      "guía",
      "código QR"
    ],
    "sourceMoment": "cta_microgeneradores_1"
  },
  {
    "key": "cmec_v2_flow_005_still",
    "start": 23952,
    "dur": 125,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_flow_005.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Primero se prueba el sistema con la red normal y se anota el orden.",
    "nouns": [
      "sistema",
      "red normal",
      "orden",
      "cuaderno",
      "calefacción"
    ],
    "sourceMoment": "cmec_v2_flow_005"
  },
  {
    "key": "cmec_b_013_still",
    "start": 24091,
    "dur": 284,
    "type": "still",
    "src": "img/cmecalor/ig_dg_cmec_b_013.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "El termostato pide calor, arranca el extractor si existe, aparece la ignición, se confirma la llama y después entra el ventilador principal.",
    "nouns": [
      "termostato",
      "extractor",
      "ignición",
      "llama",
      "ventilador principal"
    ],
    "sourceMoment": "cmec_b_013"
  },
  {
    "key": "cmec_m_139_still",
    "start": 24393,
    "dur": 155,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_139.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Cada equipo tiene su propia secuencia. Si no la conoces, el manual la explica.",
    "nouns": [
      "equipo",
      "secuencia",
      "manual"
    ],
    "sourceMoment": "cmec_m_139"
  },
  {
    "key": "cmec_v2_5_006_still",
    "start": 24553,
    "dur": 147,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_5_006.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Después, con la instalación de transferencia terminada y revisada por un profesional,",
    "nouns": [
      "instalación de transferencia",
      "profesional"
    ],
    "sourceMoment": "cmec_v2_5_006"
  },
  {
    "key": "cmec_v2_5_006_clip",
    "start": 24553,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_5_006.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Después, con la instalación de transferencia terminada y revisada por un profesional,",
    "nouns": [
      "instalación de transferencia",
      "profesional"
    ],
    "sourceMoment": "cmec_v2_5_006"
  },
  {
    "key": "cmec_m_141_still",
    "start": 24716,
    "dur": 99,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_141_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "se corta la fuente normal mediante el sistema previsto.",
    "nouns": [
      "fuente normal",
      "sistema"
    ],
    "sourceMoment": "cmec_m_141"
  },
  {
    "key": "cmec_v2_root_004_still",
    "start": 24827,
    "dur": 94,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_root_004.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Se conecta el respaldo con la calefacción detenida.",
    "nouns": [
      "respaldo",
      "calefacción detenida",
      "conector"
    ],
    "sourceMoment": "cmec_v2_root_004"
  },
  {
    "key": "cmec_b_015_still",
    "start": 25112,
    "dur": 83,
    "type": "still",
    "src": "img/cmecalor/cmec_b_015.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Mira el ciclo completo, no solo la primera llama.",
    "nouns": [
      "ciclo completo",
      "primera llama",
      "calefacción"
    ],
    "sourceMoment": "cmec_b_015"
  },
  {
    "key": "cmec_b_015_clip",
    "start": 25112,
    "dur": 83,
    "type": "clip",
    "src": "broll/cmecalor_agnes/cmec_b_015.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Mira el ciclo completo, no solo la primera llama.",
    "nouns": [
      "ciclo completo",
      "primera llama",
      "calefacción"
    ],
    "sourceMoment": "cmec_b_015"
  },
  {
    "key": "cmec_v2_5_007_still",
    "start": 25385,
    "dur": 84,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_5_007.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "el ventilador alcanza su velocidad,",
    "nouns": [
      "ventilador",
      "velocidad"
    ],
    "sourceMoment": "cmec_v2_5_007"
  },
  {
    "key": "cmec_v2_5_008_still",
    "start": 25676,
    "dur": 193,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_5_008.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si se bloquea, no aumentes fusibles, no puentes sensores y no repítas el arranque 20 veces.",
    "nouns": [
      "bloqueo",
      "fusibles",
      "sensores",
      "arranque"
    ],
    "sourceMoment": "cmec_v2_5_008"
  },
  {
    "key": "cmec_v2_5_008_clip",
    "start": 25676,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_5_008.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Si se bloquea, no aumentes fusibles, no puentes sensores y no repítas el arranque 20 veces.",
    "nouns": [
      "bloqueo",
      "fusibles",
      "sensores",
      "arranque"
    ],
    "sourceMoment": "cmec_v2_5_008"
  },
  {
    "key": "cmec_b_016_still",
    "start": 25883,
    "dur": 58,
    "type": "still",
    "src": "img/cmecalor/cmec_b_016.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Lee el código y corta la prueba.",
    "nouns": [
      "código de falla",
      "panel de calefacción",
      "prueba"
    ],
    "sourceMoment": "cmec_b_016"
  },
  {
    "key": "cmec_m_153_still",
    "start": 25957,
    "dur": 184,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_153_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Los seguros de una calefacción existen para detener combustible o calor cuando algo no cuadra.",
    "nouns": [
      "seguros",
      "calefacción",
      "combustible",
      "calor"
    ],
    "sourceMoment": "cmec_m_153"
  },
  {
    "key": "cmec_b_017_still",
    "start": 26269,
    "dur": 275,
    "type": "still",
    "src": "img/cmecalor/cmec_b_017.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Algunos equipos modernos son sensibles a la calidad de la alimentación. Pueden esperar una onda senoidal limpia. Pueden verificar polaridad.",
    "nouns": [
      "equipo moderno",
      "calidad de alimentación",
      "onda senoidal",
      "polaridad",
      "osciloscopio"
    ],
    "sourceMoment": "cmec_b_017"
  },
  {
    "key": "cmec_m_158_still",
    "start": 26698,
    "dur": 142,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_158_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "algunos generadores o estaciones portátiles tienen una salida flotante",
    "nouns": [
      "generadores",
      "estaciones portátiles",
      "salida"
    ],
    "sourceMoment": "cmec_m_158"
  },
  {
    "key": "cmec_m_159_still",
    "start": 26840,
    "dur": 161,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_159_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "que la placa interpreta como una falla, aunque el medidor muestre la tensión correcta.",
    "nouns": [
      "placa",
      "falla",
      "medidor",
      "tensión"
    ],
    "sourceMoment": "cmec_m_159"
  },
  {
    "key": "cmec_b_018_still",
    "start": 27045,
    "dur": 342,
    "type": "still",
    "src": "img/cmecalor/ig_dg_cmec_b_018.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Dos fuentes con el mismo número de vatios no siempre se comportan igual. Una arranca la calefacción y la otra enciende la pantalla, intenta la secuencia y se bloquea.",
    "nouns": [
      "dos fuentes",
      "vatios",
      "calefacción",
      "pantalla",
      "bloqueo"
    ],
    "sourceMoment": "cmec_b_018"
  },
  {
    "key": "cmec_m_162_still",
    "start": 27397,
    "dur": 109,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_162_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "No se arregla improvisando un puente entre neutro y tierra.",
    "nouns": [
      "puente",
      "neutro",
      "tierra"
    ],
    "sourceMoment": "cmec_m_162"
  },
  {
    "key": "cmec_m_164_still",
    "start": 27778,
    "dur": 161,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_164_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "copiar un cable de un foro puede crear una corriente peligrosa sobre una carcasa metálica.",
    "nouns": [
      "cable",
      "foro",
      "corriente",
      "carcasa metálica"
    ],
    "sourceMoment": "cmec_m_164"
  },
  {
    "key": "cmec_m_165_still",
    "start": 28017,
    "dur": 79,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_165.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "compatibilidad declarada por el fabricante,",
    "nouns": [
      "compatibilidad",
      "fabricante"
    ],
    "sourceMoment": "cmec_m_165"
  },
  {
    "key": "cmec_m_167_still",
    "start": 28204,
    "dur": 113,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_167_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "revisión del esquema por el profesional que instala la transferencia.",
    "nouns": [
      "esquema",
      "profesional",
      "transferencia"
    ],
    "sourceMoment": "cmec_m_167"
  },
  {
    "key": "cmec_m_168_still",
    "start": 28333,
    "dur": 242,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_168_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si el equipo necesita una referencia específica, se resuelve en el diseño. No con un adaptador misterioso a las dos de la mañana.",
    "nouns": [
      "equipo",
      "referencia",
      "diseño",
      "adaptador"
    ],
    "sourceMoment": "cmec_m_168"
  },
  {
    "key": "cmec_m_169_still",
    "start": 28589,
    "dur": 54,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_169.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Hablemos de las fuentes de respaldo.",
    "nouns": [
      "fuentes de respaldo"
    ],
    "sourceMoment": "cmec_m_169"
  },
  {
    "key": "cmec_b_021_still",
    "start": 28657,
    "dur": 496,
    "type": "still",
    "src": "img/cmecalor/cmec_b_021.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Una estación de energía con batería puede trabajar dentro de la casa porque no quema gasolina ni produce gases de escape. Aun así, debe mantenerse seca, ventilada como indique su fabricante, lejos de fuentes de calor y con espacio para disipar temperatura.",
    "nouns": [
      "estación de energía",
      "batería",
      "interior de la casa",
      "ventilación",
      "espacio",
      "fuentes de calor"
    ],
    "sourceMoment": "cmec_b_021"
  },
  {
    "key": "cmec_m_174_still",
    "start": 29276,
    "dur": 155,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_174_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Su límite es la capacidad: cuando los vatios hora se terminan, se terminó el calor.",
    "nouns": [
      "capacidad",
      "vatios hora",
      "calor"
    ],
    "sourceMoment": "cmec_m_174"
  },
  {
    "key": "cmec_v2_5_009_still",
    "start": 29437,
    "dur": 276,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_5_009.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Un generador portátil puede dar muchas más horas mientras tengas combustible, pero introduce el riesgo más grave de todo este vídeo.",
    "nouns": [
      "generador portátil",
      "horas",
      "combustible",
      "riesgo"
    ],
    "sourceMoment": "cmec_v2_5_009"
  },
  {
    "key": "cmec_v2_5_009_clip",
    "start": 29437,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_5_009.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Un generador portátil puede dar muchas más horas mientras tengas combustible, pero introduce el riesgo más grave de todo este vídeo.",
    "nouns": [
      "generador portátil",
      "horas",
      "combustible",
      "riesgo"
    ],
    "sourceMoment": "cmec_v2_5_009"
  },
  {
    "key": "cmec_b_022_still",
    "start": 29726,
    "dur": 280,
    "type": "still",
    "src": "img/cmecalor/cmec_b_022_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Funciona siempre afuera, lejos de puertas, ventanas y respiraderos, con el escape apuntando en dirección contraria a la vivienda.",
    "nouns": [
      "generador portátil",
      "exterior",
      "puertas",
      "ventanas",
      "respiraderos",
      "escape",
      "vivienda"
    ],
    "sourceMoment": "cmec_b_022"
  },
  {
    "key": "cmec_m_177_still",
    "start": 30067,
    "dur": 100,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_177.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "mantenlo al menos a unos seis metros de la casa.",
    "nouns": [
      "generador",
      "metros",
      "casa"
    ],
    "sourceMoment": "cmec_m_177"
  },
  {
    "key": "cmec_m_178_still",
    "start": 30182,
    "dur": 174,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_178.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Nunca dentro del garaje, aunque la puerta esté abierta. Nunca en un cobertizo.",
    "nouns": [
      "garaje",
      "puerta",
      "cobertizo"
    ],
    "sourceMoment": "cmec_m_178"
  },
  {
    "key": "cmec_m_179_still",
    "start": 30368,
    "dur": 57,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_179.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Nunca debajo de una ventana.",
    "nouns": [
      "generador",
      "ventana"
    ],
    "sourceMoment": "cmec_m_179"
  },
  {
    "key": "cmec_c_001_still",
    "start": 30683,
    "dur": 224,
    "type": "still",
    "src": "img/cmecalor/cmec_c_001_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Instala alarmas de monóxido a pilas o con respaldo de batería en cada nivel y fuera de las zonas donde se duerme.",
    "nouns": [
      "alarma de monóxido de carbono",
      "baterías",
      "pasillo",
      "puertas de dormitorios"
    ],
    "sourceMoment": "cmec_c_001"
  },
  {
    "key": "cmec_m_181_still",
    "start": 30683,
    "dur": 224,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_181.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Instala alarmas de monóxido a pilas o con respaldo de batería en cada nivel y fuera de las zonas donde se duerme.",
    "nouns": [
      "alarmas de monóxido",
      "pilas",
      "batería",
      "nivel",
      "zonas donde se duerme"
    ],
    "sourceMoment": "cmec_m_181"
  },
  {
    "key": "cmec_m_182_still",
    "start": 30921,
    "dur": 212,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_182.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si suenan, o alguien siente dolor de cabeza, mareo, debilidad, náusea, sueño o confusión,",
    "nouns": [
      "alarmas",
      "cabeza",
      "mareo",
      "debilidad",
      "náusea",
      "sueño",
      "confusión"
    ],
    "sourceMoment": "cmec_m_182"
  },
  {
    "key": "cmec_m_183_still",
    "start": 31148,
    "dur": 107,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_183.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "todos salen al aire libre y se pide ayuda desde afuera.",
    "nouns": [
      "aire libre",
      "ayuda"
    ],
    "sourceMoment": "cmec_m_183"
  },
  {
    "key": "cmec_v2_10_001_still",
    "start": 31262,
    "dur": 81,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_10_001.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "La extensión también forma parte del sistema.",
    "nouns": [
      "extensión para exterior",
      "sistema de respaldo"
    ],
    "sourceMoment": "cmec_v2_10_001"
  },
  {
    "key": "cmec_v2_10_001_clip",
    "start": 31262,
    "dur": 81,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_10_001.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "La extensión también forma parte del sistema.",
    "nouns": [
      "extensión para exterior",
      "sistema de respaldo"
    ],
    "sourceMoment": "cmec_v2_10_001"
  },
  {
    "key": "cmec_c_002_still",
    "start": 31354,
    "dur": 271,
    "type": "still",
    "src": "img/cmecalor/cmec_c_002.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Debe ser para exterior, tener tierra, estar completa, sin empalmes ni aislamiento cortado, y soportar la corriente a la distancia utilizada.",
    "nouns": [
      "extensión para exterior",
      "clavija con tierra",
      "aislamiento",
      "conectores"
    ],
    "sourceMoment": "cmec_c_002"
  },
  {
    "key": "cmec_v2_home_001_still",
    "start": 31639,
    "dur": 189,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_home_001.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Un cable demasiado fino puede perder tensión, calentarse y hacer que el motor arranque mal.",
    "nouns": [
      "cable fino",
      "extensión exterior gruesa",
      "motor"
    ],
    "sourceMoment": "cmec_v2_home_001"
  },
  {
    "key": "cmec_v2_home_002_still",
    "start": 31839,
    "dur": 178,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_home_002.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "No te voy a leer una medida universal porque cambia con la tensión, la longitud y el consumo.",
    "nouns": [
      "medida",
      "tensión",
      "longitud",
      "consumo",
      "extensión",
      "cinta métrica",
      "medidor",
      "carga"
    ],
    "sourceMoment": "cmec_v2_home_002"
  },
  {
    "key": "cmec_v2_root_014_still",
    "start": 32032,
    "dur": 97,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_root_014.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Usa la tabla correspondiente a tu país y deja margen.",
    "nouns": [
      "tabla",
      "país",
      "margen",
      "cable"
    ],
    "sourceMoment": "cmec_v2_root_014"
  },
  {
    "key": "cmec_c_003_still",
    "start": 32143,
    "dur": 139,
    "type": "still",
    "src": "img/cmecalor/cmec_c_003.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si la extensión entra por una puerta o ventana, no la aplastes con el marco.",
    "nouns": [
      "extensión",
      "puerta",
      "marco",
      "protector de paso"
    ],
    "sourceMoment": "cmec_c_003"
  },
  {
    "key": "cmec_m_189_still",
    "start": 32294,
    "dur": 264,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_189_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si llueve, el generador y sus conexiones necesitan protección diseñada para mantener ventilación y evitar agua, sin encerrar el escape.",
    "nouns": [
      "lluvia",
      "generador",
      "conexiones",
      "protección",
      "ventilación",
      "agua",
      "escape"
    ],
    "sourceMoment": "cmec_m_189"
  },
  {
    "key": "cmec_v2_10_002_still",
    "start": 32572,
    "dur": 111,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_10_002.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Y antes de cargar combustible, se apaga y se deja enfriar.",
    "nouns": [
      "generador",
      "combustible",
      "motor"
    ],
    "sourceMoment": "cmec_v2_10_002"
  },
  {
    "key": "cmec_v2_10_002_clip",
    "start": 32572,
    "dur": 111,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_10_002.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Y antes de cargar combustible, se apaga y se deja enfriar.",
    "nouns": [
      "generador",
      "combustible",
      "motor"
    ],
    "sourceMoment": "cmec_v2_10_002"
  },
  {
    "key": "cmec_v2_fuel_001_still",
    "start": 32696,
    "dur": 201,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_fuel_001.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Derramar gasolina sobre un motor caliente es una forma muy rápida de convertir un apagón en un incendio.",
    "nouns": [
      "gasolina",
      "motor caliente",
      "apagón",
      "incendio"
    ],
    "sourceMoment": "cmec_v2_fuel_001"
  },
  {
    "key": "cmec_v2_fuel_001_clip",
    "start": 32696,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_fuel_001.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Derramar gasolina sobre un motor caliente es una forma muy rápida de convertir un apagón en un incendio.",
    "nouns": [
      "gasolina",
      "motor caliente",
      "apagón",
      "incendio"
    ],
    "sourceMoment": "cmec_v2_fuel_001"
  },
  {
    "key": "cmec_c_005_still",
    "start": 33515,
    "dur": 324,
    "type": "still",
    "src": "img/cmecalor/cmec_c_005.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Elige una habitación de reunión, de preferencia interior, pequeña y con pocas ventanas. Lleva allí mantas, agua, medicamentos, linternas y cargadores.",
    "nouns": [
      "habitación interior",
      "mantas",
      "agua",
      "medicamentos",
      "linternas",
      "cargadores"
    ],
    "sourceMoment": "cmec_c_005"
  },
  {
    "key": "cmec_m_195_still",
    "start": 33857,
    "dur": 381,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_195_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Cierra las puertas de habitaciones que no usan, pero no tapes al azar las rejillas de suministro o retorno de un sistema central: reducir demasiado el flujo puede recalentar el equipo o dañarlo.",
    "nouns": [
      "puertas",
      "habitaciones",
      "rejillas de suministro",
      "retorno",
      "sistema central",
      "flujo",
      "equipo"
    ],
    "sourceMoment": "cmec_m_195"
  },
  {
    "key": "cmec_c_006_still",
    "start": 34382,
    "dur": 234,
    "type": "still",
    "src": "img/cmecalor/cmec_c_006.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Bloquea corrientes de aire en puertas y ventanas con burletes, toallas o plástico instalado de manera segura.",
    "nouns": [
      "ventana",
      "burlete",
      "corriente de aire",
      "manos"
    ],
    "sourceMoment": "cmec_c_006"
  },
  {
    "key": "cmec_m_196_still",
    "start": 34382,
    "dur": 234,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_196_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Bloquea corrientes de aire en puertas y ventanas con burletes, toallas o plástico instalado de manera segura.",
    "nouns": [
      "puerta",
      "ventana",
      "burlete",
      "toalla",
      "plástico"
    ],
    "sourceMoment": "cmec_m_196"
  },
  {
    "key": "cmec_v2_10_003_still",
    "start": 34631,
    "dur": 56,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_10_003.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Cierra cortinas al caer el sol",
    "nouns": [
      "cortinas",
      "sol"
    ],
    "sourceMoment": "cmec_v2_10_003"
  },
  {
    "key": "cmec_v2_home_003_still",
    "start": 34700,
    "dur": 99,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_home_003.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "aprovecha la radiación solar durante el día si aparece.",
    "nouns": [
      "radiación solar",
      "día",
      "cortinas",
      "habitación"
    ],
    "sourceMoment": "cmec_v2_home_003"
  },
  {
    "key": "cmec_c_007_still",
    "start": 34817,
    "dur": 341,
    "type": "still",
    "src": "img/cmecalor/cmec_c_007.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Usa ropa seca por capas. Mantén a niños, personas mayores y quienes tengan problemas de salud en la zona más templada. Y controla la temperatura con un termómetro.",
    "nouns": [
      "ropa por capas",
      "niño",
      "persona mayor",
      "habitación templada",
      "termómetro"
    ],
    "sourceMoment": "cmec_c_007"
  },
  {
    "key": "cmec_m_198_still",
    "start": 34817,
    "dur": 54,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_198_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Usa ropa seca por capas.",
    "nouns": [
      "ropa seca",
      "capas"
    ],
    "sourceMoment": "cmec_m_198"
  },
  {
    "key": "cmec_m_199_still",
    "start": 34883,
    "dur": 187,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_199_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Mantén a niños, personas mayores y quienes tengan problemas de salud en la zona más templada.",
    "nouns": [
      "niños",
      "personas mayores",
      "zona templada"
    ],
    "sourceMoment": "cmec_m_199"
  },
  {
    "key": "cmec_c_008_still",
    "start": 35290,
    "dur": 137,
    "type": "still",
    "src": "img/cmecalor/cmec_c_008.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Bajar el termostato unos grados puede cambiar mucho el ciclo de trabajo.",
    "nouns": [
      "termostato",
      "mano",
      "temperatura"
    ],
    "sourceMoment": "cmec_c_008"
  },
  {
    "key": "cmec_v2_10_004_still",
    "start": 36183,
    "dur": 105,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_10_004.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "No uses la cocina ni el horno para calentar la vivienda.",
    "nouns": [
      "cocina",
      "horno",
      "vivienda"
    ],
    "sourceMoment": "cmec_v2_10_004"
  },
  {
    "key": "cmec_v2_10_004_clip",
    "start": 36183,
    "dur": 105,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_10_004.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "No uses la cocina ni el horno para calentar la vivienda.",
    "nouns": [
      "cocina",
      "horno",
      "vivienda"
    ],
    "sourceMoment": "cmec_v2_10_004"
  },
  {
    "key": "cmec_v2_10_005_still",
    "start": 36304,
    "dur": 131,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_10_005.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "No lleves una parrilla, bracero o carbón a un ambiente cerrado.",
    "nouns": [
      "parrilla",
      "bracero",
      "carbón",
      "ambiente cerrado"
    ],
    "sourceMoment": "cmec_v2_10_005"
  },
  {
    "key": "cmec_v2_10_006_still",
    "start": 36450,
    "dur": 76,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_10_006.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "No dejes velas encendidas mientras duermen",
    "nouns": [
      "velas encendidas",
      "sueño"
    ],
    "sourceMoment": "cmec_v2_10_006"
  },
  {
    "key": "cmec_v2_10_006_clip",
    "start": 36450,
    "dur": 76,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_10_006.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "No dejes velas encendidas mientras duermen",
    "nouns": [
      "velas encendidas",
      "sueño"
    ],
    "sourceMoment": "cmec_v2_10_006"
  },
  {
    "key": "cmec_v2_auto_001_still",
    "start": 36541,
    "dur": 108,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_auto_001.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "no conectes un calefactor electrico a una estacion pequena",
    "nouns": [
      "calefactor electrico",
      "estacion pequena",
      "clavijas"
    ],
    "sourceMoment": "cmec_v2_auto_001"
  },
  {
    "key": "cmec_v2_home_004_still",
    "start": 36766,
    "dur": 100,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_home_004.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "El tamaño físico no dice nada, mira los vatios",
    "nouns": [
      "tamaño físico",
      "vatios",
      "calefactor",
      "placa de potencia",
      "1500 W"
    ],
    "sourceMoment": "cmec_v2_home_004"
  },
  {
    "key": "cmec_v2_auto_002_still",
    "start": 36938,
    "dur": 142,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_auto_002.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si el apagon viene con frio extremo y la casa puede acercarse al congelamiento,",
    "nouns": [
      "apagon",
      "frio extremo",
      "casa",
      "congelamiento",
      "termometro"
    ],
    "sourceMoment": "cmec_v2_auto_002"
  },
  {
    "key": "cmec_v2_auto_002_clip",
    "start": 36938,
    "dur": 142,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_auto_002.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Si el apagon viene con frio extremo y la casa puede acercarse al congelamiento,",
    "nouns": [
      "apagon",
      "frio extremo",
      "casa",
      "congelamiento",
      "termometro"
    ],
    "sourceMoment": "cmec_v2_auto_002"
  },
  {
    "key": "cmec_c_010_still",
    "start": 37092,
    "dur": 158,
    "type": "still",
    "src": "img/cmecalor/cmec_c_010.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Localiza de antemano la llave general, identifica las tuberías más expuestas.",
    "nouns": [
      "llave general de agua",
      "tuberías expuestas",
      "sótano",
      "mano"
    ],
    "sourceMoment": "cmec_c_010"
  },
  {
    "key": "cmec_c_010_clip",
    "start": 37092,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_agnes/cmec_c_010.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Localiza de antemano la llave general, identifica las tuberías más expuestas.",
    "nouns": [
      "llave general de agua",
      "tuberías expuestas",
      "sótano",
      "mano"
    ],
    "sourceMoment": "cmec_c_010"
  },
  {
    "key": "cmec_v2_10_007_still",
    "start": 37388,
    "dur": 123,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_10_007.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "No espere a que una tubería reviente para aprender dónde se corta.",
    "nouns": [
      "tubería",
      "llave de corte"
    ],
    "sourceMoment": "cmec_v2_10_007"
  },
  {
    "key": "cmec_v2_10_007_clip",
    "start": 37388,
    "dur": 123,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_10_007.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "No espere a que una tubería reviente para aprender dónde se corta.",
    "nouns": [
      "tubería",
      "llave de corte"
    ],
    "sourceMoment": "cmec_v2_10_007"
  },
  {
    "key": "cmec_v2_auto_003_still",
    "start": 37520,
    "dur": 92,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_auto_003.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Antes de una tormenta, haz una prueba de autonomia real.",
    "nouns": [
      "tormenta",
      "prueba",
      "autonomia",
      "bateria",
      "cronometro"
    ],
    "sourceMoment": "cmec_v2_auto_003"
  },
  {
    "key": "cmec_v2_auto_003_clip",
    "start": 37520,
    "dur": 92,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_auto_003.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Antes de una tormenta, haz una prueba de autonomia real.",
    "nouns": [
      "tormenta",
      "prueba",
      "autonomia",
      "bateria",
      "cronometro"
    ],
    "sourceMoment": "cmec_v2_auto_003"
  },
  {
    "key": "cmec_c_011_still",
    "start": 37686,
    "dur": 370,
    "type": "still",
    "src": "img/cmecalor/cmec_c_011.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Carga la batería, desconecta otras cargas y deja que la calefacción complete varios ciclos mientras anotas consumo, porcentaje inicial, porcentaje final y temperatura exterior.",
    "nouns": [
      "estación de energía",
      "calefacción a gas",
      "cuaderno",
      "medidor de consumo",
      "termómetro exterior"
    ],
    "sourceMoment": "cmec_c_011"
  },
  {
    "key": "cmec_v2_auto_004_still",
    "start": 38072,
    "dur": 134,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_auto_004.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Con una hora de datos ya puedes estimar mucho mejor que con la etiqueta.",
    "nouns": [
      "hora",
      "datos",
      "etiqueta",
      "medidor",
      "cuaderno"
    ],
    "sourceMoment": "cmec_v2_auto_004"
  },
  {
    "key": "cmec_v2_auto_005_still",
    "start": 38212,
    "dur": 40,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_auto_005.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Haz la cuenta con margen.",
    "nouns": [
      "cuenta",
      "margen",
      "calculadora",
      "bateria",
      "reserva"
    ],
    "sourceMoment": "cmec_v2_auto_005"
  },
  {
    "key": "cmec_v2_heat_005_still",
    "start": 38586,
    "dur": 128,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_heat_005.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "cualquier teléfono que alguien conecte se comen esa precisión.",
    "nouns": [
      "dos teléfonos",
      "radio",
      "batería portátil",
      "consumos",
      "precisión"
    ],
    "sourceMoment": "cmec_v2_heat_005"
  },
  {
    "key": "cmec_v2_auto_006_still",
    "start": 38725,
    "dur": 59,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_auto_006.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Disena para llegar con reserva.",
    "nouns": [
      "reserva",
      "bateria",
      "calefaccion",
      "indicador de carga"
    ],
    "sourceMoment": "cmec_v2_auto_006"
  },
  {
    "key": "cmec_v2_heat_006_still",
    "start": 38793,
    "dur": 43,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_heat_006.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Y prepara un plan de salida.",
    "nouns": [
      "plan de salida",
      "llaves",
      "abrigo",
      "linterna",
      "ruta",
      "puerta"
    ],
    "sourceMoment": "cmec_v2_heat_006"
  },
  {
    "key": "cmec_v2_heat_006_clip",
    "start": 38793,
    "dur": 43,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_heat_006.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Y prepara un plan de salida.",
    "nouns": [
      "plan de salida",
      "llaves",
      "abrigo",
      "linterna",
      "ruta",
      "puerta"
    ],
    "sourceMoment": "cmec_v2_heat_006"
  },
  {
    "key": "cmec_v2_fuel_002_still",
    "start": 38848,
    "dur": 191,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_fuel_002.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si la temperatura sigue bajando, si la batería llega al límite que definiste, si el generador falla",
    "nouns": [
      "temperatura baja",
      "batería",
      "límite",
      "generador"
    ],
    "sourceMoment": "cmec_v2_fuel_002"
  },
  {
    "key": "cmec_c_013_still",
    "start": 39047,
    "dur": 372,
    "type": "still",
    "src": "img/cmecalor/cmec_c_013_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si una alarma de monóxido se activa, la respuesta no es improvisar otra conexión. Es ir a un refugio, a la casa de alguien con calefacción segura o al lugar indicado por las autoridades locales.",
    "nouns": [
      "alarma de monóxido",
      "familia",
      "puerta de salida",
      "abrigos",
      "bolso"
    ],
    "sourceMoment": "cmec_c_013"
  },
  {
    "key": "cmec_m_224_still",
    "start": 39212,
    "dur": 207,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_224_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Es ir a un refugio, a la casa de alguien con calefacción segura o al lugar indicado por las autoridades locales.",
    "nouns": [
      "familia",
      "refugio",
      "casa",
      "calefacción segura"
    ],
    "sourceMoment": "cmec_m_224"
  },
  {
    "key": "cmec_v2_home_005_still",
    "start": 39503,
    "dur": 50,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_home_005.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "No reemplaza un plan familiar.",
    "nouns": [
      "plan familiar",
      "bolso",
      "abrigo",
      "linterna",
      "ruta",
      "tomacorriente"
    ],
    "sourceMoment": "cmec_v2_home_005"
  },
  {
    "key": "cmec_v2_heat_001_still",
    "start": 39634,
    "dur": 303,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_heat_001.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si tu calefacción produce calor con gas y solo necesita electricidad para control, ventilador o bomba, puede ser una carga excelente para respaldo.",
    "nouns": [
      "calefacción a gas",
      "línea de gas",
      "control eléctrico",
      "ventilador",
      "bomba circuladora",
      "respaldo"
    ],
    "sourceMoment": "cmec_v2_heat_001"
  },
  {
    "key": "cmec_c_014_still",
    "start": 39955,
    "dur": 109,
    "type": "still",
    "src": "img/cmecalor/cmec_c_014.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Mide potencia activa, pico de arranque y ciclo de trabajo.",
    "nouns": [
      "calefacción a gas",
      "medidor eléctrico",
      "ventilador",
      "técnico"
    ],
    "sourceMoment": "cmec_c_014"
  },
  {
    "key": "cmec_v2_fuel_003_still",
    "start": 40079,
    "dur": 204,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_fuel_003.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Después instala una forma aprobada de aislarla de la red y alimentarla desde una fuente compatible.",
    "nouns": [
      "aislamiento de red",
      "conmutador de un circuito",
      "fuente compatible"
    ],
    "sourceMoment": "cmec_v2_fuel_003"
  },
  {
    "key": "cmec_v2_heat_002_still",
    "start": 40299,
    "dur": 183,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_heat_002.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si el equipo ya funciona sin electricidad, confirma el manual y no agregues piezas innecesarias.",
    "nouns": [
      "equipo sin electricidad",
      "manual",
      "estufa mural",
      "piezas innecesarias"
    ],
    "sourceMoment": "cmec_v2_heat_002"
  },
  {
    "key": "cmec_v2_heat_002_clip",
    "start": 40299,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_heat_002.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Si el equipo ya funciona sin electricidad, confirma el manual y no agregues piezas innecesarias.",
    "nouns": [
      "equipo sin electricidad",
      "manual",
      "estufa mural",
      "piezas innecesarias"
    ],
    "sourceMoment": "cmec_v2_heat_002"
  },
  {
    "key": "cmec_v2_heat_003_still",
    "start": 40496,
    "dur": 209,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_heat_003.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Si la calefacción es eléctrica o depende de un compresor grande, una estación pequeña no es la respuesta.",
    "nouns": [
      "calefacción eléctrica",
      "compresor grande",
      "estación pequeña"
    ],
    "sourceMoment": "cmec_v2_heat_003"
  },
  {
    "key": "cmec_v2_heat_004_still",
    "start": 40717,
    "dur": 90,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_heat_004.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Necesitas reducir el área que intentas calentar,",
    "nouns": [
      "área calentada",
      "puerta interior",
      "una habitación",
      "radiador mural"
    ],
    "sourceMoment": "cmec_v2_heat_004"
  },
  {
    "key": "cmec_v2_heat_004_clip",
    "start": 40717,
    "dur": 90,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_heat_004.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "Necesitas reducir el área que intentas calentar,",
    "nouns": [
      "área calentada",
      "puerta interior",
      "una habitación",
      "radiador mural"
    ],
    "sourceMoment": "cmec_v2_heat_004"
  },
  {
    "key": "cmec_c_015_still",
    "start": 40966,
    "dur": 332,
    "type": "still",
    "src": "img/cmecalor/cmec_c_015.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Y si alguien te propone conectar un generador a un enchufe de la casa, fabricar un cable de dos puntas macho o unir neutro y tierra sin plano ni medición, aléjate.",
    "nouns": [
      "cable con dos clavijas macho",
      "banco de trabajo"
    ],
    "sourceMoment": "cmec_c_015"
  },
  {
    "key": "cmec_v2_fuel_004_still",
    "start": 41298,
    "dur": 257,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_fuel_004.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "El problema no es que sea una solución poco elegante, es que puede dejar tensión en lugares donde una persona espera encontrar cero.",
    "nouns": [
      "tensión",
      "cero voltios",
      "probador sin contacto",
      "gabinete cerrado"
    ],
    "sourceMoment": "cmec_v2_fuel_004"
  },
  {
    "key": "cta_microgeneradores_2_1",
    "start": 41561,
    "dur": 518,
    "type": "float",
    "src": "img/cmecalor/cmec_cta_microgeneradores.png",
    "clipDuration": null,
    "kicker": "Escanea con tu celular",
    "side": "right",
    "anchor": "En el capítulo sobre microgeneradores, disponible con el código QR de la pantalla y en la descripción",
    "nouns": [
      "guía",
      "código QR"
    ],
    "sourceMoment": "cta_microgeneradores_2"
  },
  {
    "key": "cta_microgeneradores_2_2",
    "start": 42079,
    "dur": 518,
    "type": "float",
    "src": "img/cmecalor/cmec_cta_pages.png",
    "clipDuration": null,
    "kicker": "Capítulo: microgeneradores",
    "side": "left",
    "anchor": "En el capítulo sobre microgeneradores, disponible con el código QR de la pantalla y en la descripción",
    "nouns": [
      "guía",
      "código QR"
    ],
    "sourceMoment": "cta_microgeneradores_2"
  },
  {
    "key": "cmec_v2_fuel_005_still",
    "start": 42608,
    "dur": 110,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_fuel_005.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "La pieza del título no hace milagros, hace algo mejor.",
    "nouns": [
      "pieza del título",
      "tomacorriente con tierra",
      "calefacción"
    ],
    "sourceMoment": "cmec_v2_fuel_005"
  },
  {
    "key": "cmec_v2_fuel_005_clip",
    "start": 42608,
    "dur": 110,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_fuel_005.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "La pieza del título no hace milagros, hace algo mejor.",
    "nouns": [
      "pieza del título",
      "tomacorriente con tierra",
      "calefacción"
    ],
    "sourceMoment": "cmec_v2_fuel_005"
  },
  {
    "key": "cmec_c_016_still",
    "start": 42729,
    "dur": 234,
    "type": "still",
    "src": "img/cmecalor/cmec_c_016.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "Convierte una calefacción fija en una carga que puedes aislar, medir y respaldar sin intentar alimentar toda la casa.",
    "nouns": [
      "calefacción fija a gas",
      "conmutador de transferencia de un circuito",
      "estación de energía",
      "cable"
    ],
    "sourceMoment": "cmec_c_016"
  },
  {
    "key": "cmec_m_251_still",
    "start": 43510,
    "dur": 115,
    "type": "still",
    "src": "img/cmecalor/mass/cmec_m_251_v2.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "estufa de pared, bomba de calor o resistencia eléctrica.",
    "nouns": [
      "estufa de pared",
      "bomba de calor",
      "resistencia eléctrica"
    ],
    "sourceMoment": "cmec_m_251"
  },
  {
    "key": "cmec_v2_fuel_006_still",
    "start": 44063,
    "dur": 297,
    "type": "still",
    "src": "img/cmecalor_v2/cmec_v2_fuel_006.png",
    "clipDuration": null,
    "kicker": null,
    "side": null,
    "anchor": "En el próximo vídeo voy a medir cuánto dura una estación de energía con las cargas que de verdad importan durante un apagón, una por una hasta que se apague.",
    "nouns": [
      "estación de energía",
      "cargas importantes",
      "medición",
      "apagón",
      "una por una"
    ],
    "sourceMoment": "cmec_v2_fuel_006"
  },
  {
    "key": "cmec_v2_fuel_006_clip",
    "start": 44063,
    "dur": 147,
    "type": "clip",
    "src": "broll/cmecalor_v2_agnes/cmec_v2_fuel_006.mp4",
    "clipDuration": 5.042,
    "kicker": null,
    "side": null,
    "anchor": "En el próximo vídeo voy a medir cuánto dura una estación de energía con las cargas que de verdad importan durante un apagón, una por una hasta que se apague.",
    "nouns": [
      "estación de energía",
      "cargas importantes",
      "medición",
      "apagón",
      "una por una"
    ],
    "sourceMoment": "cmec_v2_fuel_006"
  }
] as const satisfies readonly CmecalorCue[];
