// GENERATED by build_cmecalor.mjs. No captions by design.
import React from "react";
import {Audio, Video} from "@remotion/media";
import {AbsoluteFill, OffthreadVideo, Sequence, staticFile, useCurrentFrame} from "remotion";
import {RawShot} from "../VideoEdit/scenes/RawShot";
import {FloatingInsert} from "../VideoEdit/scenes/FloatingInsert";
import {CUES_CMECALOR} from "./cues_cmecalor.gen";

export const TOTAL_FRAMES_CMECALOR = 44818;
export const AVATAR_FRAMES_CMECALOR = 44817;

const AvatarFloor: React.FC = () => {
  const frame = useCurrentFrame();
  const scale = 1.018 + Math.sin(frame / 1100) * 0.008;
  return <AbsoluteFill style={{backgroundColor:"#10100d",overflow:"hidden"}}>
    <Video src={staticFile("avatar_cmecalor.mp4")} muted style={{width:"100%",height:"100%",objectFit:"cover",transform: "scale(" + scale.toFixed(4) + ")"}} />
  </AbsoluteFill>;
};

export const MainCmecalor: React.FC = () => (
  <AbsoluteFill style={{backgroundColor:"#10100d"}}>
    <AvatarFloor />
    {CUES_CMECALOR.map((cue) => (
      <Sequence key={cue.key} from={cue.start} durationInFrames={cue.dur} premountFor={30}>
        {cue.type === "float" ? (
          <FloatingInsert durationInFrames={cue.dur} src={cue.src} side={cue.side ?? "right"} kicker={cue.kicker ?? undefined} hue="amber" />
        ) : cue.type === "clip" ? (
          <OffthreadVideo src={staticFile(cue.src)} muted playbackRate={1} style={{width:"100%",height:"100%",objectFit:"cover"}} />
        ) : (
          <RawShot durationInFrames={cue.dur} src={cue.src} darken={0} blur={0} kbBoost={0.55} />
        )}
      </Sequence>
    ))}
    <Audio src={staticFile("cmecalor_fish.wav")} />
  </AbsoluteFill>
);
