// DIRECTOR C — número 10 (la cómoda mid-century del garaje), la lección, lo que SÍ se vende, la culpa, dónde vender,
// fotos, empresas de remate, abrir cajones, el final, CTA (p28-44)
import { S, BI, HZP, HOUSE, SHOP, GARAGE, VELVET } from "./dir_lib.mjs";
import { DAUGHTER, CABINET } from "./dir_a.mjs";
const DRESSER = "a long low mid-century modern walnut dresser with skinny tapered legs and a matching pair of small side tables";
export const SHOTS = [
  // ── 10 MID-CENTURY
  S(28, "", "c", "HzLotCard", { props: { n: 10, of: 10, title: "the furniture nobody wanted", where: "out in the garage", bed: "b_dressergarage" } }),
  S(28, "out in the garage", "bi", "b_dressergarage", { p: BI(`In a dusty one-car garage of an older Ohio house: ${DRESSER}, scratched and dusty, half covered by an old bedsheet, a rake and paint cans beside them.`), anim: "dust drifts in the light from the garage door" }),
  S(28, "Her mother had bought them in the nineteen sixties", "av", "av"),
  S(28, "give them to the neighbor's son", "bi", "b_neighborson", { p: BI(`A young man in his twenties in a hoodie standing in the open door of a dusty garage, looking at ${DRESSER} with his hands in his pockets.`), anim: "he leans in to look at the dresser" }),
  S(29, "", "av", "av"),
  S(29, "Simple, clean lines, often made of teak or walnut", "st", "st_midcentury.1"),
  S(29, "Young people today love it", "bi", "b_apartment", { p: BI(`A bright small city apartment with white walls and plants: ${DRESSER.replace("and a matching pair of small side tables", "")} under a record player and a lamp, a young couple setting a plant on it.`), anim: "the young woman sets the plant down and steps back" }),
  S(29, "sell for hundreds, sometimes thousands of dollars", "c", "HzSoldListings", { props: { title: "mid-century · sold listings", rows: [{ item: "walnut lowboy dresser", price: "$1,200" }, { item: "pair of side tables", price: "$450" }, { item: "teak credenza", price: "$1,800" }, { item: "Danish chair", price: "$600" }], range: "hundreds to thousands", bed: "b_apartment" } }),
  S(30, "", "bi", "b_dresserclean", { p: BI(`${DRESSER}, cleaned and oiled, standing on a plain floor against a white wall in bright daylight from a window, photographed for a listing.`), anim: "the daylight brightens slightly on the walnut" }),
  S(30, "sold for more than everything in the china cabinet", "c", "HzCabinetScale", { props: { title: "the china cabinet vs. the garage", left: [{ label: "Hummels", price: "$10-50" }, { label: "Waterford", price: "$20-60" }, { label: "bone china", price: "$100-200" }, { label: "Beanie Babies", price: "$1-5" }], right: { label: "the dresser + 2 tables", price: "more than all of it" }, reveal: true, every: 18, bed: "b_dresserclean" } }),
  S(31, "", "av", "av"),
  S(31, "the thing they thought was ordinary", "hz", "h_dresser", { p: HZP(`She runs her hand along the top of ${DRESSER.replace("and a matching pair of small side tables", "")}, smiling at the camera like she knows a secret.`) }),
  // ── LO QUE SÍ SE VENDE
  S(32, "", "av", "av"),
  S(32, "Cast iron skillets", "st", "st_castiron.1"),
  S(32, "Sterling silver, which sells by weight", "st", "st_silver.1"),
  S(32, "Old video games and game systems", "c", "HzRecap", { props: { title: "what DOES sell", items: ["old cast iron with a name", "bright old Pyrex", "sterling + gold (by weight)", "old video games", "vintage denim + concert tees", "old hand planes + wrenches", "mid-century anything"], every: 22, start: 4, bed: "st_vintage.1" } }),
  S(32, "And mid-century modern anything", "st", "st_midcentury.2"),
  S(33, "", "av", "av"),
  S(33, "Look at the sold listings", "c", "HzRuleCard", { props: { eyebrow: "Hazel's rule", rule: "not how old · not what it cost · not how much she loved it", lines: ["look at the SOLD listings"], stamp: "the market decides", bed: "b_laptop" } }),
  // ── LA CULPA
  S(34, "", "av", "av"),
  S(35, "", "bi", "b_momshelf", { p: BI("An old woman's hands carefully dusting a porcelain figurine of a girl feeding geese on a sunny windowsill, a faded family photo beside it."), anim: "the hands set the figurine down gently" }),
  S(35, "a beautiful table for her family at Thanksgiving", "st", "st_family.1"),
  S(35, "It was the life she made with them", "av", "av"),
  S(36, "", "bi", "b_teacup", { p: BI("A single white bone china teacup with a gold rim and its saucer on a kitchen windowsill in morning light, a small plant beside it."), anim: "morning light grows on the teacup" }),
  S(36, "without guilt. That's what she'd want", "av", "av"),
  // ── DÓNDE VENDER
  S(37, "", "c", "HzWhereToSell", { props: { item: "where to sell what", routes: [{ name: "china + crystal", take: "replacement companies", note: "then local marketplaces" }, { name: "Hummels + figurines", take: "as a group", note: "online auction or consignment" }, { name: "books", take: "used book store", note: "only the good ones" }, { name: "mid-century furniture", take: "local marketplace", note: "daylight photos + sold prices" }], best: 3, stamp: "goes fast" } }),
  S(37, "You'll be surprised how fast the good stuff goes", "av", "av"),
  S(38, "", "bi", "b_photo", { p: BI("A cut crystal vase standing on a plain white bedsheet on a table by a bright window, an older woman's hands holding a phone up to photograph it."), anim: "the phone moves to a new angle" }),
  S(38, "Be honest about the damage", "av", "av"),
  S(38, "Write down the measurements", "bi", "b_measure", { p: BI("An older woman's hands holding a yellow tape measure across the top of a walnut side table, a notepad with numbers written on it beside it."), anim: "the tape measure extends across the table" }),
  S(38, "A good listing with clear photos", "c", "HzRuleCard", { props: { eyebrow: "a good listing", rule: "daylight · plain sheet · every side + the marks", lines: ["say the chips", "write the size", "maker + pattern in the title"], stamp: "up to 2x the price", bed: "b_photo" } }),
  S(39, "", "hz", "h_walkthrough", { p: HZP("She walks through a living room full of household things with a clipboard, a middle-aged couple following her, pointing at a lamp and making a note.", HOUSE) }),
  S(39, "ask what happens to the things that don't sell", "av", "av"),
  S(40, "", "bi", "b_drawers", { p: BI("An older woman's hands pulling open the bottom drawer of a china cabinet in an old dining room, finding an envelope tucked under folded tablecloths."), anim: "the hand lifts the envelope out" }),
  S(40, "jewelry in candy tins, and savings bonds", "st", "st_jewelry.1"),
  S(40, "Look before you let it go", "av", "av"),
  // ── EL FINAL
  S(41, "", "av", "av"),
  S(41, "I kept one Hummel", "bi", "b_windowsill", { p: BI("A small porcelain figurine of a girl feeding geese on a kitchen windowsill in early morning light, a coffee mug beside it, a backyard visible through the window."), anim: "the morning light slowly brightens" }),
  S(41, "I gave the rest of the china cabinet to the church rummage sale", "bi", "b_rummage", { p: BI(`${DAUGHTER.replace("tired red eyes", "a relieved smile")} carrying a cardboard box of china and figurines into a church fellowship hall set up for a rummage sale, long tables of donated things.`), anim: "she sets the box down on a table and smiles" }),
  S(42, "", "c", "HzRecap", { props: { title: "the right way", items: ["know what it's worth", "sell what's worth selling", "keep what you love", "let the rest go"], every: 20, start: 4, bed: "b_windowsill" } }),
  S(43, "", "av", "av", { ov: { c: "HzSubscribe", props: { line: "next: a stranger's 1800s jewelry box" } } }),
  S(44, "", "av", "av2", { ov: { c: "HzAsk", props: { question: "What does YOUR family swear is valuable?" } } }),
  // AUTO cortes
  S(0, "figurines a Waterford", "st", "st_oldhouse.1"),
  S(0, "of fine bone", "st", "st_attic.3"),
  S(0, "in plastic cases", "st", "st_oldhouse.2"),
  S(1, "the hardest thing", "av", "av"),
  S(3, "things families are", "st", "st_attic.4"),
  S(3, "The things everybody's", "st", "st_oldhouse.3"),
  S(3, "sell I'll tell", "st", "st_attic.5"),
  S(3, "prices and which", "av", "av"),
  S(5, "paid Anybody can", "st", "st_garagesale.1"),
  S(6, "had a shelf", "st", "st_antique.1"),
  S(8, "marks from before", "st", "st_figurine.2"),
  S(8, "The newer ones", "av", "av"),
  S(9, "story even more", "st", "st_antique.2"),
  S(10, "and sometimes much", "st", "st_dishes.3"),
  S(12, "But today a", "st", "st_crystal.1"),
  S(13, "acid-etched mark on", "av", "av"),
  S(13, "and turn it", "st", "st_dishes.4"),
  S(14, "tag errors that", "st", "st_attic.6"),
  S(15, "sorry Give them", "st", "st_plush.1"),
  S(16, "condensed books the", "av", "av"),
  S(16, "lettering I watch", "st", "st_books.3"),
  S(17, "books and some", "st", "st_books.4"),
  S(18, "it's made of", "st", "st_piano.2"),
  S(19, "have a piano", "av", "av"),
  S(20, "People keep them", "st", "st_magazines.1"),
  S(20, "them away But", "st", "st_vintage.2"),
  S(20, "few very early", "st", "st_magazines.2"),
  S(21, "certificate saying it", "av", "av"),
  S(23, "often given away", "st", "st_glass.1"),
  S(23, "can bring more", "st", "st_jewelry.2"),
  S(24, "box Most of", "st", "st_quilt.1"),
  S(24, "with a maker's", "av", "av"),
  S(24, "or silver Look", "st", "st_glass.2"),
  S(25, "a store in", "st", "st_jewelry.3"),
  S(25, "But an old", "st", "st_quilt.2"),
  S(25, "condition made by", "av", "av"),
  S(25, "somebody's winter of", "st", "st_glass.3"),
  S(26, "for forty to", "st", "st_sewing.2"),
  S(28, "with skinny tapered", "st", "st_oldhouse.4"),
  S(29, "some of it", "av", "av"),
  S(32, "bottom Old Pyrex", "st", "st_vintage.3"),
  S(32, "Gold jewelry even", "st", "st_castiron.2"),
  S(34, "donate the Hummels", "st", "st_family.2"),
  S(35, "them because they", "av", "av"),
  S(36, "teacup one figurine", "st", "st_oldhouse.5"),
  S(36, "you'll see it", "st", "st_family.3"),
  S(37, "online marketplaces Hummels", "st", "st_vintage.4"),
  S(37, "shop Books a", "av", "av"),
  S(37, "it on a", "st", "st_garagesale.2"),
  S(38, "Take your pictures", "st", "st_moving.1"),
  S(38, "the piece on", "st", "st_vintage.5"),
  S(38, "side the bottom", "av", "av"),
  S(38, "type like the", "st", "st_garagesale.3"),
  S(39, "A good one", "st", "st_moving.2"),
  S(39, "of the money", "st", "st_vintage.6"),
  S(40, "every box every", "av", "av"),
  S(41, "and it's on", "st", "st_oldhouse.6"),
  S(43, "stranger's eighteen hundreds", "st", "st_family.4"),
];
export const BEDS = [];
