// tfbinodoro — PLAN DE RODAJE (inglés). Por escena: SETS[S].k0 = foto base (desde ref_tfbinodoro.png reubicado).
// Por línea (ACTS[id]):  a = qué pasa en el clip · e = estado FINAL (= ancla siguiente; "S:" = mismo lugar/encuadre/luz)
//   cut = el clip ARRANCA en un ancla nueva (otro ángulo/encuadre = corte en el montaje), sale de K0 limpio (+W si está el vecino)
//   d: da/db = primer y último cuadro del detalle (keyframe, sin habla) · e = cómo queda al volver al plano abierto
// Placeholders: {G} garaje · {B} baño · {ME} vestuario fijo · {CUT} inodoro cortado · {W} el vecino · {LOOKG}/{LOOKB} luz del lugar
export const G = "The place is a real, messy home garage-workshop of a working-class house in Latin America: concrete floor with old stains and cement dust, a wooden workbench covered in tools, tins, rags and offcuts, a pegboard with hanging tools, stacked plastic buckets, a bicycle leaning on the wall, bare painted brick walls with damp patches, the wide garage door on the left open to the street.";
export const LOOKG = " Light: flat overcast daylight coming in through the open garage door on the left, plus one plain fluorescent tube on the ceiling; the side near the door a little brighter and cooler, the back corners dimmer.";
export const B = "The place is the small real bathroom of a modest family house in Latin America: white wall tiles up to shoulder height with greyish grout, pale green painted wall above, an ordinary white ceramic toilet with its tank against the wall and the seat and lid up, a toilet brush in a plastic holder beside it, a small white sink with a chrome tap and a bar of soap, a plastic shower curtain on the right, a towel on a hook, a small bathroom rug; the toilet bowl has a thick yellow-brown ring of limescale at the water line and brownish streaks under the rim.";
export const LOOKB = " Light: daylight from a frosted window on the left above the toilet, plus a ceiling lamp with a plain warm bulb; the tiles near the window brighter and cooler, the corner by the door dimmer.";
export const ME = "the man of the reference photo — same face, same dark curly hair, same short salt-and-pepper beard — wearing a faded olive-green work shirt with the sleeves rolled up to the elbows, stained with paint and dust, and a worn brown leather apron over it";
export const CUT = "an old white porcelain toilet sawn in half lengthwise: the flat cut face shows the inside of the curved trap channel lined with a thick, rough, layered crust of yellow-brown and grey limescale, like stone, narrowing the passage to less than half";
export const W = "the neighbour of the fourth/last-but-one input image: a heavy-set man around 65, bald on top with grey hair on the sides, a thick grey moustache, a faded light-blue checked short-sleeve shirt with a pen in the breast pocket, reading glasses hanging on a cord around his neck";
const CLOSE = " EXTREME CLOSE-UP of the HANDS and the object ONLY, the detail fills the whole frame; the wrists and forearms enter from the bottom edge; ignore the last input image (no face in this frame).";

export const SETS = {
 S1: { k0: `Place this same man in a new place. ${G} He is ${ME}. He is crouching on the concrete floor beside the two halves of ${CUT}, lying on a folded dirty blanket. An angle grinder lies on the floor beside them with its cable across the frame. A dust mask hangs around his neck, clear safety glasses pushed up on his forehead, white dust on his shoulders and in his hair. He looks up at the camera, mouth caught mid-word. Medium shot from about one and a half metres, the camera at the height of a crouching person.${LOOKG}` },
 S2: { k0: `Place this same man in a completely new place: nothing from the workshop of the first image remains. ${B} He is ${ME}, with yellow rubber gloves on. He kneels on the rug beside the toilet, turned three-quarters to the camera, one gloved hand on the small chrome quarter-turn valve on the wall under the tank. On the tiled floor beside him: a red plastic bucket, a plastic cup, an old yellow sponge, a glass jug of clear vinegar, a grey pumice stone, a short piece of thin wire and a roll of toilet paper. Medium shot from the bathroom doorway, at the eye level of a kneeling man.${LOOKB}` },
 S3: { k0: `Place this same man in a new place. ${G} He is ${ME}. The two halves of ${CUT} now stand upright on the wooden workbench, their cut faces toward the camera. He stands behind the workbench, waist-up, one hand resting on a toilet half, talking to the camera; the open garage door on the left edge.${LOOKG}` },
 S4: { k0: `Place this same man in a new place. ${G} He is ${ME}. One half of ${CUT} lies on the workbench on its back, the cut face up and toward the camera; the other half stands beside it. He leans over the bench with a small flashlight in one hand, looking at the camera, a pencil behind his ear. Medium shot, slightly from the side, waist-up.${LOOKG}` },
 S6: { k0: `Place this same man in a new place. ${G} He is ${ME}. He stands beside the workbench, the two halves of ${CUT} on the bench beside him, and he holds a single sheet of cream-coloured printed paper in one hand, lowered at his side, looking at the camera with a serious face. Medium shot, waist-up.${LOOKG}` },
 SC: { k0: `Place this same man in a new place. ${G} He is ${ME}. On the floor in front of him lies a whole old white porcelain toilet on its side on a folded dirty blanket, uncut. He stands beside it wearing clear safety glasses and a white dust mask pulled down under his chin, holding an angle grinder with a grey diamond cutting disc, switched off, pointing down; a bucket of water beside the blanket. Medium-wide shot, full body, from about two and a half metres.${LOOKG}` },
 S5: { k0: `Place this same man in a new place. ${G} He is ${ME}. At the workbench: one half of ${CUT}, two clear drinking glasses side by side, a small saucepan, a bottle of clear white vinegar without label, a grey pumice stone, a small cup of water and a clean white offcut of porcelain. He stands behind the bench, waist-up, holding a small chunk of yellow-brown limescale crust between two gloved fingers, showing it to the camera.${LOOKG}` },
 S8: { k0: `Place this same man in a completely new place: nothing from the workshop of the first image remains. ${B} He is ${ME}. The lid of the toilet tank is off, leaning against the wall; he stands beside the toilet, one hand on the edge of the open tank, looking at the camera. A thin vertical brownish streak of limescale runs down the inside of the bowl from under the rim to the water. Medium shot from the doorway, waist-up.${LOOKB}` },
 S7: { k0: `Place this same man in a completely new place: nothing from the workshop of the first image remains. ${B} He is ${ME}, with yellow rubber gloves on. He kneels beside the toilet with the seat and lid up; on the floor beside him: a red plastic bucket full of water, a plastic cup, an old yellow sponge, a glass jug, a grey pumice stone, a thin wire, a small round hand mirror and a roll of toilet paper. He looks at the camera, mid-sentence. Medium shot from the other side of the bathroom, near the sink, at the eye level of a kneeling man.${LOOKB}` },
 S7b: { k0: `Place this same man in a completely new place: nothing from the workshop of the first image remains. ${B} He is ${ME}. The frosted window on the left is open a little; he stands in the bathroom between the sink and the toilet, taking off one yellow rubber glove, looking at the camera. A red plastic bucket with some water stands beside the toilet. Medium shot, waist-up, from the doorway.${LOOKB}` },
 S9: { k0: `Place this same man in a new place. ${G} He is ${ME}. The two halves of ${CUT} lie on the workbench under the fluorescent tube; he stands behind the bench, both hands resting on the edge, looking at the camera, relaxed, late afternoon. Medium shot, waist-up.${LOOKG}` },
};

const S_ = "S: ";
export const ACTS = {
 // ---------------- S1 garaje, gancho
 s1_01: { a: "He points with a dusty finger at the yellow-brown crust inside the cut trap, then looks back at the camera and talks.", e: S_ + "he holds one half of the toilet tilted toward the camera with one hand, pointing at the crust with the other, looking at the camera." },
 s1_w1: { cut: `The camera now looks toward the open garage door: the neighbour, ${W}, stands in the doorway with a folded newspaper in one hand, staring down at the cut toilet halves on the floor with a frown of disbelief; the presenter is crouched at the right edge of the frame, seen from the side, looking up at him.`, a: "The neighbour in the doorway frowns, points down at the cut toilet with his newspaper and speaks to the presenter in disbelief; the presenter only listens, looking up at him.", e: S_ + "the neighbour has put his hands on his hips, shaking his head slightly; the presenter at the right edge looks up at him." },
 s1_02: { cut: "The camera is back on the presenter: he crouches beside the cut toilet halves on the blanket, turned toward the garage door on the left (the neighbour is out of the frame), with a half grin, one hand resting on top of a toilet half.", a: "He answers toward the neighbour off-frame on the left with a half grin and taps the cut toilet with his hand.", e: S_ + "he looks back at the camera, one hand flat on top of the cut toilet half, eyebrows raised." },
 s1_03: { a: "He talks to the camera with conviction, brushing white dust off his hands, counting on his fingers.", e: S_ + "still crouched, he holds up his index finger toward the camera, a determined look." },
 // ---------------- S2 baño, el arreglo base completo
 s2_01: { a: "He turns the small chrome valve on the wall under the tank closed with his gloved hand, then reaches up and presses the flush button on top of the tank, talking to the camera.", e: S_ + "he kneels beside the toilet, one gloved hand resting on the flush button on the tank, the water in the bowl settling, looking at the camera." },
 s2_02: { da: "A gloved hand scoops water out of the toilet bowl with a plastic cup; the thick yellow-brown ring of limescale at the water line is right there." + CLOSE, db: "Same close-up, a moment later: the bowl is almost empty, a yellow sponge in the gloved hand soaks up the last water at the bottom; the yellow-brown ring and the brown crust at the bottom now fully exposed." + CLOSE, a: "The gloved hand scoops water out of the bowl with the cup, then presses the sponge into the bottom; the water level drops.", e: S_ + "he kneels beside the toilet, the bowl empty, the red bucket beside him half full of water, looking at the camera." },
 s2_03: { da: "A gloved hand tilts a glass jug of steaming clear vinegar over the rim of the empty toilet bowl, the first thin stream starting to pour." + CLOSE, db: "Same close-up, a moment later: the vinegar runs down the inside of the bowl over the yellow limescale ring, a shallow steaming pool of vinegar at the bottom, the jug lifted away." + CLOSE, a: "The steaming vinegar is poured slowly around the inside of the bowl, running down over the yellow ring.", e: S_ + "he holds the empty glass jug, kneeling beside the toilet, a little steam rising from the bowl, looking at the camera." },
 s2_04: { a: "He sets the jug down, lowers the toilet lid and taps it twice with his gloved hand, then holds up one finger while explaining to the camera.", e: S_ + "the seat and lid are down; he sits back on his heels beside the toilet, one hand resting on the closed lid, looking at the camera." },
 s2_05: { da: "A gloved hand holds a dripping-wet grey pumice stone against the thick yellow-brown ring inside the toilet bowl." + CLOSE, db: "Same close-up, a moment later: the wet pumice has rubbed a clean white strip through the ring, grey muddy residue on the stone and running down the white porcelain." + CLOSE, a: "The wet pumice stone rubs gently back and forth along the ring; the crust comes off as grey mud and clean white porcelain appears.", e: S_ + "the lid is up again; he holds up the wet grey pumice stone toward the camera, kneeling beside the toilet." },
 s2_06: { da: "Seen from below the rim of the toilet bowl: the row of small holes under the rim, several blocked with white-brown crust, a gloved hand pushing a thin wire into one hole." + CLOSE, db: "Same close-up under the rim, a moment later: strips of wet toilet paper soaked in vinegar pressed flat along the underside of the rim, covering the holes." + CLOSE, a: "The gloved hand pushes the thin wire in and out of a blocked rim hole, then presses a wet strip of toilet paper under the rim.", e: S_ + "he looks at the camera holding the thin wire up in one gloved hand, kneeling beside the toilet." },
 s2_07: { a: "He reaches down and opens the chrome valve under the tank, presses the flush button, watches the clean water rush around the bowl and looks back at the camera, satisfied.", e: S_ + "the bowl is now clean and white with clear water, the yellow ring gone; he kneels beside it, one gloved hand on the tank, a small satisfied smile at the camera." },
 // ---------------- S3 garaje, las objeciones del vecino
 s3_01: { a: "He wipes his hands on his apron and talks to the camera, glancing once toward the open garage door on the left.", e: S_ + "he looks toward the garage door on the left with a half smile and raised eyebrows." },
 s3_w1: { cut: `Same garage, the camera turned a little to the left: the neighbour, ${W}, leans on the end of the workbench with his arms crossed, looking at the toilet halves and then at the presenter; the presenter stands at the right edge of the frame, partly visible, listening.`, a: "The neighbour, arms crossed, shakes his head and speaks to the presenter with a smirk; the presenter listens.", e: S_ + "the neighbour lifts both hands in a shrug; the presenter at the right edge listens." },
 s3_02: { cut: "The camera is back on the presenter behind the workbench with the toilet halves, turned slightly toward the neighbour off-frame on the left, answering him calmly with one open hand raised.", a: "He answers the neighbour off-frame on the left calmly, then runs a finger along the cut edge of the porcelain.", e: S_ + "he looks at the camera, one hand on the cut toilet half." },
 s3_03: { a: "He taps the thick crust inside the cut trap with his knuckle, then picks up a clear glass of tap water from the bench and holds it up, talking to the camera.", e: S_ + "he holds the clear glass of tap water up beside the toilet halves, looking at the camera." },
 s3_w2: { cut: `Same garage, closer on the neighbour, ${W}, standing by the workbench, waist-up, index finger raised, a knowing grin; a toilet half at the edge of the frame; the presenter is not in this frame.`, a: "The neighbour lifts his index finger and says his line with a knowing grin, nodding.", e: S_ + "the neighbour nods to himself, arms crossed again, pleased with himself." },
 s3_04: { cut: "The camera is back on the presenter behind the workbench, nodding with a half grin toward the left; a plain white plastic bottle without any label stands on the bench beside the toilet halves.", a: "He nods toward the neighbour off-frame, then picks up the plain white plastic bottle and holds it up to the camera.", e: S_ + "he holds the plain white plastic bottle up toward the camera, serious." },
 s3_05: { da: "Hands in thick orange rubber gloves pour a little clear liquid from a plain white plastic bottle into a red bucket that is already half full of water; clear safety glasses lie on the bench beside it." + CLOSE, db: "Same close-up, a moment later: the gloved hands set the plain white bottle down beside the red bucket; clear safety glasses and a folded dust mask on the bench." + CLOSE, a: "The gloved hands pour a small amount of the clear liquid slowly into the bucket of water, then set the bottle down.", e: S_ + "he now wears clear safety glasses and orange rubber gloves, standing behind the workbench beside the red bucket, looking at the camera." },
 s3_06: { a: "He picks up an old chrome toilet flush lever from the bench, dull and spotted, turns it in his gloved fingers and talks to the camera.", e: S_ + "he holds up the dull, spotted chrome flush lever toward the camera." },
 s3_07: { a: "He sets the lever down and picks up a plastic bottle of descaler with a blank white label, turns it as if reading the back, then looks at the camera.", e: S_ + "he holds the blank-labelled plastic bottle, looking at the camera." },
 s3_08: { a: "He raises both hands in orange rubber gloves, turning them to show them, with a grin, talking to the camera.", e: S_ + "both gloved hands raised at shoulder height, looking at the camera with a grin." },
 s3_09: { a: "He points at a small white plastic tub of caustic soda granules on the bench and shakes his head, talking to the camera.", e: S_ + "he wags his index finger 'no' at the camera, the white tub on the bench beside him." },
 s3_10: { a: "He tips a spoonful of white baking soda into a glass jar of vinegar on the bench; it fizzes up with white foam; he looks at the camera.", e: S_ + "the glass jar on the bench overflows a little with white foam; he looks at the camera with raised eyebrows." },
 s3_11: { a: "He wipes the foam off the bench with a rag while talking to the camera.", e: S_ + "he holds the rag, looking at the camera, the jar beside him with flat liquid." },
 s3_12: { a: "He picks up a plastic bottle of dark cola soda from the bench, shows it to the camera and puts it aside with a small shrug.", e: S_ + "the cola bottle stands aside on the bench; he looks at the camera with a small shrug." },
 // ---------------- S4 garaje, el descubrimiento
 s4_01: { a: "He switches on the small flashlight and points it at the cut face of the toilet half on the bench, looking at the camera.", e: S_ + "he leans over the cut toilet half, lighting the curved channel with the flashlight, looking at the camera." },
 s4_02: { da: "Macro view of the layered limescale crust on the cut face of the porcelain: thin stacked layers of white, grey, yellow and brown mineral, like the rings of a tree, a flashlight beam across it." + CLOSE, db: "Same macro view, a moment later: a gloved fingertip enters from the right edge and traces along the layers of the crust." + CLOSE, a: "The flashlight beam slides slowly across the layered crust; a gloved fingertip traces the layers.", e: S_ + "he stands behind the bench beside the cut toilet half, looking at the camera, the flashlight pointed down." },
 s4_03: { a: "He traces with his finger the horizontal line where the crust starts on the inside of the bowl, at the old water level, talking to the camera.", e: S_ + "his finger rests on the line of the old water level inside the cut bowl; he looks at the camera." },
 s4_04: { a: "He scrapes a little of the yellow-brown crust with his fingernail onto the bench, looks at the colour and talks to the camera.", e: S_ + "a little yellow-brown powder on the bench in front of him; he looks at the camera." },
 s4_05: { da: "Close view along the cut rim of the toilet: the hollow channel inside the rim is visible in cross-section, and below it a row of small holes, most of them blocked with white-brown crust." + CLOSE, db: "Same close view, a moment later: the beam of a small flashlight shines into the channel inside the rim, showing crust inside it." + CLOSE, a: "The flashlight beam moves slowly along the hollow channel inside the rim and the blocked holes below it.", e: S_ + "he holds the flashlight near the rim of the cut toilet half, looking at the camera." },
 s4_06: { a: "He pokes the blocked holes under the rim one after another with the tip of a pencil, talking to the camera.", e: S_ + "he holds the pencil up, looking at the camera, a little white dust on the bench." },
 s4_07: { a: "He runs his finger along the curved trap channel of the cut toilet from top to bottom, following the curve, talking to the camera.", e: S_ + "his finger rests inside the narrowest part of the curved channel, he looks at the camera." },
 s4_08: { da: "Macro view inside the curved trap channel of the cut toilet: the passage is lined with rough, bumpy yellow-brown stone-like crust, leaving only a narrow gap." + CLOSE, db: "Same macro view, a moment later: a small wad of white toilet paper is caught on the rough crust inside the narrow channel." + CLOSE, a: "The camera stays on the rough narrow channel; a small wad of toilet paper slides down and snags on the crust.", e: S_ + "he stands behind the bench looking at the camera, holding the flashlight." },
 s4_08b: { da: "Macro view of the thick crust on the cut face at the top of the curve: a gloved fingertip placed flat beside it for scale; the crust is about as thick as the finger." + CLOSE, db: "Same macro view lower down, at the bottom bend of the curve: the crust there is even thicker, the fingertip beside it." + CLOSE, a: "The gloved fingertip moves from the crust at the top of the curve down to the thicker crust at the bottom bend.", e: S_ + "he looks at the camera, one hand on the cut toilet half, eyebrows raised." },
 s4_09: { a: "He shakes his head slowly and talks to the camera, tapping the crust with the flashlight.", e: S_ + "he looks at the camera with a skeptical half smile." },
 s4_10: { a: "He pats the toilet half like an old car and talks to the camera, then glances at the top edge of the bowl.", e: S_ + "his hand rests on the top edge of the cut bowl; he looks at the camera." },
 // ---------------- S6 garaje, el error y la hoja
 s6_01: { a: "He puts the sheet of paper down on the bench, face down, and talks to the camera seriously, holding up one finger.", e: S_ + "he holds up one finger, the sheet face down on the bench." },
 s6_02: { a: "He mimes pouring from a bottle into the full toilet bowl of the cut half, shaking his head, talking to the camera.", e: S_ + "his open hand is held over the cut toilet half, he shakes his head at the camera." },
 s6_02b: { a: "He shrugs reassuringly and talks to the camera with a calm hand gesture.", e: S_ + "a calm, reassuring expression, one hand open toward the camera." },
 s6_03: { a: "He mimes scrubbing hard with his fist, then stops and taps his wrist as if pointing at a watch, talking to the camera.", e: S_ + "he taps his wrist, looking at the camera." },
 s6_04: { a: "He picks up a dry grey pumice stone from the bench and holds it up, rubbing it with his thumb, talking to the camera.", e: S_ + "he holds the dry pumice stone up toward the camera." },
 s6_04b: { a: "He puts the pumice down and counts three fingers to the camera.", e: S_ + "he holds up three fingers, looking at the camera." },
 s6_05: { a: "He picks up the sheet of cream paper from the bench and slowly raises it toward the camera, serious.", e: S_ + "he holds the sheet of cream paper up at chest height, facing the camera, printed side toward the camera but too far to read, looking at the camera seriously." },
 s6_06: { a: "He lowers the sheet, taps it with his finger and talks to the camera, calm.", e: S_ + "he holds the sheet at his side, looking at the camera with a friendly face." },
 s6_06b: { a: "He mimes holding up a phone toward the camera with one hand, then points down, talking to the camera.", e: S_ + "he points down with his index finger, looking at the camera." },
 s6_07: { a: "He puts the sheet down on the bench and turns toward the floor on the right, where the grinder is, talking to the camera.", e: S_ + "he looks at the camera with a small grin, turned half toward the right." },
 // ---------------- SC garaje, cómo lo cortó
 sc_01: { a: "He stands beside the uncut toilet holding the switched-off grinder pointed down, talking to the camera, shaking his head once.", e: S_ + "he lifts the switched-off grinder a little toward the camera." },
 sc_02: { a: "He crouches and pats the side of the old toilet lying on the blanket, then straightens the blanket under it, talking to the camera.", e: S_ + "he crouches beside the toilet on the blanket, one hand on it, looking at the camera." },
 sc_03: { da: "The grinder's grey diamond cutting disc seen close, with its segmented rim, the grinder held in gloved hands, switched off." + CLOSE, db: "Same close-up, a moment later: a gloved hand pours a little water from a cup over the side of the porcelain toilet where the cut will start." + CLOSE, a: "The gloved hands turn the grinder to show the diamond disc, then water is poured over the porcelain where the cut will go.", e: S_ + "he crouches beside the toilet holding the grinder, wet porcelain in front of him, looking at the camera." },
 sc_04: { a: "He pulls the white dust mask up over his nose and mouth and pulls the safety glasses down over his eyes, then gives a thumbs up to the camera.", e: S_ + "mask on his face and glasses on, he gives a thumbs up to the camera." },
 sc_05: { da: "The spinning diamond disc of the grinder cuts slowly into the side of the white porcelain toilet along a straight line, throwing a fan of fine white dust and a few orange sparks." + CLOSE, db: "Same close-up, a moment later: the disc has cut deeper along the curve, a long clean cut line in the porcelain, white dust hanging in the air and settling on the blanket." + CLOSE, a: "The spinning disc advances slowly along the cut line, white dust flying and settling, a few sparks.", e: S_ + "he kneels beside the toilet with the grinder switched off, dust on his shoulders, mask down under his chin, looking at the camera." },
 sc_06: { a: "He carefully lifts one freshly cut edge of porcelain with his gloved hand and runs a gloved finger near the sharp edge, talking to the camera.", e: S_ + "he holds the gloved hand near the sharp cut edge, looking at the camera." },
 sc_07: { a: "He pulls the two halves slightly apart on the blanket and looks inside, then back at the camera with raised eyebrows.", e: S_ + "the two halves lie slightly apart on the blanket, the yellow-brown crust visible inside; he looks at the camera, amazed." },
 // ---------------- S5 garaje, pruebas
 s5_01: { a: "He turns the chunk of crust in his gloved fingers and talks to the camera, then puts it down on the bench.", e: S_ + "the chunk of crust lies on the bench; he looks at the camera, both hands on the bench." },
 s5_w1: { cut: `Same garage, the camera turned toward the end of the workbench: the neighbour, ${W}, leans with one elbow on the bench, looking at the two glasses with a skeptical face; the presenter is at the right edge, partly visible.`, a: "The neighbour looks at the glasses, waves his hand dismissively and says his line with a skeptical grin; the presenter listens.", e: S_ + "the neighbour crosses his arms, skeptical; the presenter at the right edge." },
 s5_02: { cut: "The camera is back on the presenter behind the workbench: in front of him the two clear drinking glasses with clear liquid, a small saucepan with steaming vinegar, the chunk of crust split in two pieces beside the glasses.", a: "He pours cold vinegar from the bottle into the left glass and hot vinegar from the small saucepan into the right glass, then drops one piece of crust into each, talking to the camera.", e: S_ + "the two glasses of vinegar stand side by side, each with a piece of crust at the bottom, steam over the right one; he looks at the camera." },
 s5_03: { da: "Two clear glasses of vinegar side by side, each with a piece of yellow-brown crust at the bottom; a few tiny bubbles rise from the piece in the left glass." + CLOSE.replace("the HANDS and the object ONLY", "the two glasses ONLY").replace(" the wrists and forearms enter from the bottom edge;", ""), db: "Same close-up of the two glasses, a moment later: many more tiny bubbles stream up from the crust in the right glass, the steaming one, than in the left one." + CLOSE.replace("the HANDS and the object ONLY", "the two glasses ONLY").replace(" the wrists and forearms enter from the bottom edge;", ""), a: "Tiny bubbles rise from the pieces of crust, many more from the hot glass on the right.", e: S_ + "he leans over the two glasses, pointing at the right one, looking at the camera." },
 s5_04: { a: "He points at the steaming glass, then raises a warning finger to the camera.", e: S_ + "warning finger raised, looking at the camera." },
 s5_05: { a: "He picks up the clean white offcut of porcelain and the dry grey pumice stone and shows both to the camera.", e: S_ + "he holds the white porcelain offcut in one hand and the dry pumice stone in the other, looking at the camera." },
 s5_06: { da: "A gloved hand rubs a DRY grey pumice stone on a clean glossy white piece of porcelain on the workbench." + CLOSE, db: "Same close-up, a moment later: the pumice is lifted away; the glossy white surface now shows dull grey scratch marks where it was rubbed." + CLOSE, a: "The dry pumice rubs a few times on the glossy porcelain and is lifted away, leaving dull grey scratches.", e: S_ + "he holds up the porcelain offcut toward the camera, showing the grey scratches." },
 s5_07: { da: "A gloved hand dips the grey pumice stone into a cup of water and rubs it, dripping wet, on a patch of yellow-brown crust on the white porcelain." + CLOSE, db: "Same close-up, a moment later: where the wet pumice rubbed, the crust is gone and the white porcelain underneath is smooth and glossy, wet." + CLOSE, a: "The wet pumice rubs gently; the crust dissolves into grey mud and smooth glossy porcelain appears.", e: S_ + "he holds up the wet pumice stone, looking at the camera, satisfied." },
 s5_08: { a: "He lifts a piece of crust out of the vinegar glass with his gloved fingers, presses it — the outside is soft and crumbles a little — and talks to the camera.", e: S_ + "he holds the half-softened piece of crust up to the camera between two fingers." },
 s5_09: { a: "He shows a small clear bag of white citric acid powder, then a glass with cloudy water beside it, talking to the camera.", e: S_ + "he holds the small bag of white powder, looking at the camera." },
 s5_10: { a: "He puts everything down and talks to the camera, counting three things on his fingers.", e: S_ + "three fingers up, looking at the camera." },
 s5_11: { a: "He picks up an old kitchen knife from the bench, shakes his head, puts it down far away, talking to the camera.", e: S_ + "he looks at the camera with a firm face, hands resting on the bench." },
 s5_w2: { cut: `Same garage, closer on the neighbour, ${W}, leaning over the two glasses of vinegar on the workbench, peering at the bubbles through his reading glasses now on his nose; the presenter is not in the frame.`, a: "The neighbour peers at the bubbling glass, purses his lips and admits his line reluctantly, nodding a little.", e: S_ + "the neighbour straightens up with a reluctant half smile, taking off his reading glasses." },
 // ---------------- S8 baño, la mochila y Rosa
 s8_01: { a: "He points at the thin brownish streak running down inside the bowl from under the rim, talking to the camera.", e: S_ + "his finger points at the streak inside the bowl; he looks at the camera." },
 s8_02: { da: "Close view inside the open toilet tank: water, the flush valve and the float, a tiny steady ripple at the flush valve seal where water keeps leaking." + CLOSE, db: "Close view inside the toilet bowl under the rim: a thin trickle of water running down the white porcelain along a brownish streak into the water." + CLOSE, a: "The camera goes from the leaking valve in the tank to the thin trickle running down the bowl along the streak.", e: S_ + "he looks at the camera, one hand on the open tank." },
 s8_03: { a: "He taps the edge of the open tank and talks to the camera, shaking his head.", e: S_ + "he holds a small bottle of blue food colouring, looking at the camera." },
 s8_04: { da: "A hand squeezes a few drops of blue food colouring into the clear water of the open toilet tank; blue swirls spread in the water." + CLOSE, db: "Close view of the toilet bowl water, a moment later: a faint blue tint has appeared in the water of the bowl." + CLOSE, a: "Blue drops fall into the tank water and spread; then the water in the bowl turns faintly blue.", e: S_ + "he points at the faintly blue water in the bowl, looking at the camera." },
 s8_05: { a: "He lifts the float arm inside the tank slightly and lets it go, then presses on the flush valve with a finger, talking to the camera.", e: S_ + "he looks at the camera, one hand inside the open tank." },
 s8_05b: { a: "He picks up a round white chlorine tablet from the edge of the tank, shows it to the camera and drops it into a small plastic bag.", e: S_ + "he holds the small plastic bag with the tablet, looking at the camera, serious." },
 s8_05c: { a: "He points at the open window, then waves his hand in front of his nose, serious, talking to the camera.", e: S_ + "he looks at the camera, serious, one hand on the tank." },
 s8_06: { cut: "Same bathroom, closer: he sits on the edge of the bathtub side (by the shower curtain) holding a phone in his hand, screen dark, turned toward the camera, the toilet beside him. Medium close shot.", a: "He sits holding the phone with its screen dark, glances at it and tells the story to the camera.", e: S_ + "he looks at the camera, the phone lowered in his hand." },
 s8_07: { a: "He shrugs with a small laugh, telling the story, then mimes lowering a level with his flat hand.", e: S_ + "his flat hand held low, looking at the camera." },
 s8_08: { a: "He holds up two fingers, then nods, telling the story to the camera.", e: S_ + "two fingers up, a small smile." },
 s8_09: { a: "He stands up and gestures around the bathroom with an open hand, talking to the camera.", e: S_ + "standing beside the toilet, looking at the camera." },
 s8_10: { a: "He points down at the bottom of the frame with his index finger, friendly, talking to the camera.", e: S_ + "he points down, smiling at the camera." },
 // ---------------- S7 baño, los detalles
 s7_01: { a: "He holds up a plastic cup and a sponge, talking to the camera.", e: S_ + "he holds the red bucket of water by the handle, looking at the camera." },
 s7_02: { da: "The red bucket tilted by gloved hands pours a big splash of water into the toilet bowl all at once." + CLOSE, db: "Close view of the toilet bowl a moment later: the water swirls down the drain and the level in the bowl is left very low." + CLOSE, a: "A bucket of water is dumped into the bowl in one go; it swirls and the water level drops very low.", e: S_ + "he sets the empty bucket down beside the toilet, looking at the camera." },
 s7_03: { da: "A gloved hand scoops the last water from the bottom of the toilet bowl with a plastic cup." + CLOSE, db: "Same close-up, a moment later: an old yellow sponge in the gloved hand pressed into the bottom of the dry bowl." + CLOSE, a: "The cup scoops out the remaining water, then the sponge soaks up the bottom.", e: S_ + "he wrings the sponge into the bucket, looking at the camera." },
 s7_04: { cut: "Same house, the small kitchen next to the bathroom: he stands at the stove, a steel pot of vinegar on the gas burner, a little steam rising, one gloved hand on the pot handle, looking at the camera. Daylight from a kitchen window. Medium shot, waist-up.", a: "He looks at the steam rising from the pot, then turns off the burner knob, talking to the camera.", e: S_ + "the burner is off; he holds the pot handle, steam rising, looking at the camera." },
 s7_05: { k0: true, da: "A gloved hand pours steaming vinegar from a glass jug slowly around the rim of the empty toilet bowl, the liquid running down the white porcelain." + CLOSE, db: "Same close-up, a moment later: the jug moves along the far side of the rim, the vinegar sheet covering the yellow ring and pooling in the bottom curve." + CLOSE, a: "The jug pours slowly all the way around the rim, the vinegar running down over the ring into the bottom.", e: S_ + "back in the bathroom, he kneels beside the toilet with the empty jug, looking at the camera." },
 s7_06: { a: "He holds up a small clear bag of white citric acid powder, then pours a little into the jug of hot water and stirs it with a spoon, talking to the camera.", e: S_ + "he holds the jug with the spoon in it, looking at the camera." },
 s7_07: { a: "He closes the lid and sticks a handwritten paper note on it with tape, the writing turned away from the camera, talking to the camera with a grin.", e: S_ + "a paper note is taped on the closed lid; he looks at the camera with a grin." },
 s7_08: { da: "A gloved hand dips a grey pumice stone into the water at the bottom of the bowl, the stone dripping." + CLOSE, db: "Same close-up, a moment later: the wet pumice glides lightly along the yellow ring, a clean white line opening behind it, grey mud running down." + CLOSE, a: "The pumice is wetted and then glides lightly along the ring like an eraser; a clean white line appears behind it.", e: S_ + "the lid is up; he holds the wet pumice, looking at the camera." },
 s7_09: { a: "He points at a part of the ring that is still yellow and holds up one finger, then two, talking to the camera.", e: S_ + "two fingers up, looking at the camera." },
 s7_10: { da: "A small round hand mirror held under the rim of the toilet bowl by a gloved hand reflects the row of rim holes, several blocked with crust." + CLOSE, db: "Same close-up, a moment later: a thin wire pokes into one of the holes seen in the mirror, a little white crust crumbling out." + CLOSE, a: "The mirror shows the blocked holes under the rim; the thin wire goes in and out of one, crust crumbling out.", e: S_ + "he holds the mirror and the wire, kneeling beside the toilet, looking at the camera." },
 s7_11: { da: "Gloved fingers press long strips of toilet paper soaked in vinegar flat against the yellow ring inside the bowl." + CLOSE, db: "Same close-up, a moment later: the wet paper strips cover the whole ring and the underside of the rim, stuck flat to the porcelain." + CLOSE, a: "Wet strips of toilet paper are pressed flat one after another along the ring and under the rim.", e: S_ + "he looks at the camera, the paper strips stuck inside the bowl behind him." },
 s7_12: { a: "He leans over the bowl and points down into the bottom front of the bowl, where there is a larger hole, talking to the camera.", e: S_ + "he points into the bottom of the bowl, looking at the camera." },
 s7_13: { da: "Looking down into the drained toilet bowl: at the bottom front, a larger round hole partly blocked with yellow-brown crust; a narrow bottle brush held in a gloved hand enters from the bottom edge." + CLOSE, db: "Same view, a moment later: the narrow brush scrubs at the rim of the larger hole, flakes of crust coming loose." + CLOSE, a: "The narrow brush scrubs gently at the edge of the larger hole; flakes of crust come loose.", e: S_ + "he holds the narrow brush up, looking at the camera." },
 s7_14: { a: "He leans toward the camera and lowers his voice a little, pointing down toward the bottom of the frame, with a knowing look.", e: S_ + "he points down with a knowing look at the camera." },
 // ---------------- S7b baño, cuidados y límites
 s7b_01: { a: "He pushes the frosted window open a bit more and switches on a small wall extractor fan, talking to the camera.", e: S_ + "the window is open wider; he looks at the camera." },
 s7b_02: { a: "He covers the chrome hinges of the toilet seat with a small plastic bag, talking to the camera.", e: S_ + "the seat hinges are covered by a plastic bag; he looks at the camera." },
 s7b_03: { da: "Gloved hands lift the red plastic bucket of cloudy water beside the toilet." + CLOSE, db: "Same close-up, a moment later: the gloved hands pour the bucket of water slowly into the toilet bowl." + CLOSE, a: "The bucket is lifted and its water poured slowly into the toilet bowl.", e: S_ + "he sets the empty bucket down, looking at the camera." },
 s7b_04: { a: "He presses the flush, watches the water rise slowly in the bowl and then drop, and talks to the camera with a doubtful face.", e: S_ + "he looks at the camera with a doubtful face, one hand on the tank." },
 s7b_05: { a: "He runs a gloved finger along the porcelain as if searching for a crack, then raises a warning finger, talking to the camera.", e: S_ + "warning finger raised, looking at the camera." },
 s7b_06: { a: "He crouches and points at the base of the toilet where it meets the floor tiles, talking to the camera.", e: S_ + "crouched, pointing at the base of the toilet, looking at the camera." },
 // ---------------- S9 garaje, cierre
 s9_01: { a: "He holds up a plain glass of vinegar, then mimes pouring it and sleeping with his hands against his cheek, talking to the camera.", e: S_ + "he holds the glass of vinegar, looking at the camera, smiling." },
 s9_02: { a: "He takes a toilet brush from the bench and mimes brushing under the rim of the cut toilet half, talking to the camera.", e: S_ + "he holds the toilet brush under the rim of the cut half, looking at the camera." },
 s9_03: { a: "He puts the brush down and talks to the camera, gesturing toward the house behind the garage.", e: S_ + "he looks at the camera, hands on the bench." },
 s9_03b: { a: "He holds up a small piece of glass with white water spots on it, turning it to the light, talking to the camera.", e: S_ + "he holds the spotted piece of glass up, looking at the camera." },
 s9_03c: { a: "He puts the glass down, pulls the cut toilet half toward him on the bench and looks at the camera with a small smile.", e: S_ + "he leans over the cut toilet half, one hand on it, looking at the camera." },
 s9_04: { a: "He points the flashlight into the lowest bend of the cut trap channel, talking to the camera.", e: S_ + "the flashlight beam lights the lowest bend of the channel; he looks at the camera." },
 s9_05: { da: "Macro view of the lowest bend inside the cut trap: the crust there forms a hard, sharp-edged ridge sticking out into the passage, lit by a flashlight beam." + CLOSE, db: "Same macro view, a moment later: a wad of toilet paper and dark debris caught behind the sharp crust ridge in the bend." + CLOSE, a: "The flashlight beam moves over the sharp crust ridge in the bottom bend and reveals paper caught behind it.", e: S_ + "he looks at the camera, serious, the flashlight in his hand." },
 s9_06: { a: "He runs his finger along the ridge in the bend and shakes his head, talking to the camera.", e: S_ + "his finger on the ridge, he looks at the camera." },
 s9_07: { a: "He taps the bench with his finger three times as he talks to the camera, firm.", e: S_ + "he looks at the camera, firm, index finger on the bench." },
 s9_07b: { a: "He mimes lifting a tank lid and adding drops with his fingers, then nods to the camera.", e: S_ + "he looks at the camera, nodding, hands on the bench." },
 s9_w1: { cut: `Same garage, the camera toward the open garage door: the neighbour, ${W}, stands in the doorway with his hands in his pockets and a resigned half smile, looking at the presenter; the presenter is at the right edge of the frame, partly visible.`, a: "The neighbour raises his hands in surrender with a half smile and says his line, then points a finger jokingly; the presenter listens.", e: S_ + "the neighbour points his finger jokingly at the presenter, smiling." },
 s9_08: { cut: "The camera is back on the presenter behind the workbench with the cut toilet halves, laughing toward the left, then turning to the camera.", a: "He laughs toward the neighbour off-frame on the left, then turns to the camera and talks, friendly.", e: S_ + "he looks at the camera with a friendly smile." },
 s9_09: { a: "He points down toward the bottom of the frame, then gives a small wave to the camera.", e: S_ + "he gives a small wave, smiling at the camera." },
};

// T = planos de detalle del TRÁILER (keyframe, sin habla, con foley). base: "S1" o "S2" (el ancla sale de su K0).
export const T = {
 t01: { base: "S1", da: "An old white porcelain toilet lying on its side on a folded dirty blanket; gloved hands press the spinning disc of an angle grinder against the porcelain, the disc just touching, the first orange sparks and a puff of white dust." + CLOSE, db: "Same close-up, a moment later: the disc is halfway into the bowl, throwing a wide fan of orange sparks and a cloud of white dust drifting toward the open door." + CLOSE, a: "The spinning grinder disc bites into the porcelain; sparks and white dust burst out." },
 t02: { base: "S1", da: "The old white toilet just sawn in half lengthwise lies on the blanket, the two halves still pressed together, a thin cut line all around, white dust everywhere; gloved hands grip both halves." + CLOSE, db: "Same close-up, a moment later: the gloved hands have pulled the two halves apart, the cut face revealing the curved channel lined with thick yellow-brown and grey limescale crust." + CLOSE, a: "The gloved hands pull the two halves apart and the crusted inside is revealed; dust falls." },
 t03: { base: "S1", da: "Macro view of the cut face of the toilet trap: thick rough yellow-brown limescale crust with a dark narrow hole through the middle, like stone." + CLOSE.replace("the HANDS and the object ONLY", "the crust ONLY").replace(" the wrists and forearms enter from the bottom edge;", ""), db: "Same macro view, a moment later, slightly closer: the rough texture and layers of the crust, fine white dust settling on it." + CLOSE.replace("the HANDS and the object ONLY", "the crust ONLY").replace(" the wrists and forearms enter from the bottom edge;", ""), a: "The view slowly pushes in on the crust; fine dust settles." },
 t04: { base: "S1", da: "Macro view: a man's bare fingernail pressed against the yellow-brown limescale crust inside the cut toilet trap." + CLOSE, db: "Same macro view, a moment later: the fingernail has scratched a short groove in the crust, yellow-brown powder crumbling off." + CLOSE, a: "The fingernail scratches along the crust; powder crumbles off." },
 t05: { base: "S1", da: "The cut toilet half lifted a little by gloved hands, seen from the side, white dust sliding off the cut face." + CLOSE, db: "Same close-up, a moment later: the half is tilted toward the camera, showing the whole crusted curve inside." + CLOSE, a: "The gloved hands tilt the cut half toward the camera; dust slides off." },
 t06: { base: "S2", da: "Looking down into the bowl of a toilet right after flushing: the water level is high, swirling slowly, a little toilet paper floating." + CLOSE.replace("the HANDS and the object ONLY", "the toilet bowl ONLY").replace(" the wrists and forearms enter from the bottom edge;", ""), db: "Same view, a moment later: the water is still high and swirling slowly, only slightly lower, the paper still there." + CLOSE.replace("the HANDS and the object ONLY", "the toilet bowl ONLY").replace(" the wrists and forearms enter from the bottom edge;", ""), a: "The water in the bowl swirls slowly and drains very slowly." },
 t07: { base: "S2", da: "Close view of the inside of the toilet bowl at the water line: a thick yellow-brown ring of limescale just above the still water." + CLOSE.replace("the HANDS and the object ONLY", "the toilet bowl ONLY").replace(" the wrists and forearms enter from the bottom edge;", ""), db: "Same close view, a moment later, slightly further along the ring, the still water reflecting the window light." + CLOSE.replace("the HANDS and the object ONLY", "the toilet bowl ONLY").replace(" the wrists and forearms enter from the bottom edge;", ""), a: "The view glides slowly along the yellow ring at the water line." },
 t08: { base: "S2", da: "Seen from inside the bowl looking up under the rim: the row of small rim holes, most blocked with white-brown crust, dry." + CLOSE.replace("the HANDS and the object ONLY", "the toilet rim ONLY").replace(" the wrists and forearms enter from the bottom edge;", ""), db: "Same view under the rim, a moment later: water trickles out of only two of the holes, the others stay dry and blocked." + CLOSE.replace("the HANDS and the object ONLY", "the toilet rim ONLY").replace(" the wrists and forearms enter from the bottom edge;", ""), a: "The flush starts: water trickles from only two holes under the rim, the rest stay blocked." },
 t09: { base: "S2", da: "A toilet brush held in a hand scrubbing hard inside the bowl above the yellow ring, foam." + CLOSE, db: "Same close-up, a moment later: the brush lifted out, the yellow ring still exactly there under the foam." + CLOSE, a: "The brush scrubs hard and is lifted away; the yellow ring is still there." },
 t10: { base: "S2", da: "Looking down into the toilet bowl as it is flushed: the water rises slowly with a wad of toilet paper turning in it." + CLOSE.replace("the HANDS and the object ONLY", "the toilet bowl ONLY").replace(" the wrists and forearms enter from the bottom edge;", ""), db: "Same view, a moment later: the water has risen higher, the paper still turning, not going down." + CLOSE.replace("the HANDS and the object ONLY", "the toilet bowl ONLY").replace(" the wrists and forearms enter from the bottom edge;", ""), a: "The water rises slowly, the paper turns and does not go down." },
 t11: { base: "S1", da: "Macro view of the lowest bend inside the cut toilet trap, in deep shadow, only the edge of rough crust visible." + CLOSE.replace("the HANDS and the object ONLY", "the crust ONLY").replace(" the wrists and forearms enter from the bottom edge;", ""), db: "Same macro view, a moment later: a flashlight beam from the side catches the edge of a hard crust ridge in the bend, the rest still in shadow." + CLOSE.replace("the HANDS and the object ONLY", "the crust ONLY").replace(" the wrists and forearms enter from the bottom edge;", ""), a: "A flashlight beam slowly sweeps into the dark bend and catches the edge of a hard ridge." },
 t12: { base: "S1", da: "Low view at floor level: the angle grinder cutting into the toilet on the blanket, a man's knee and gloved hands, sparks and dust flying toward the camera." + CLOSE, db: "Same low view, a moment later: a thick cloud of white dust fills half the frame, sparks still flying." + CLOSE, a: "Sparks and white dust fly toward the camera from the grinder cutting the porcelain." },
 t13: { base: "S1", da: "A gloved hand lays one cut half of the toilet down on the blanket, cut face up." + CLOSE, db: "Same close-up, a moment later: the half lies still, cut face up, the crusted curve fully visible, dust settling." + CLOSE, a: "The half is laid down cut face up; dust settles over the crusted curve." },
 t14: { base: "S2", da: "A gloved hand tilts a glass jug of steaming vinegar over the yellow ring inside a toilet bowl, the stream starting." + CLOSE, db: "Same close-up, a moment later: the steaming vinegar runs down over the ring into the bowl." + CLOSE, a: "Steaming vinegar pours over the yellow ring." },
 t15: { base: "S2", da: "A gloved hand holds a dripping-wet pumice stone against the yellow ring inside the bowl." + CLOSE, db: "Same close-up, a moment later: a clean white stripe rubbed through the ring, grey mud running down." + CLOSE, a: "The wet pumice rubs a clean white stripe through the ring." },
 t16: { base: "S2", da: "Under the toilet rim, a gloved hand pushes a thin wire into a blocked rim hole." + CLOSE, db: "Same close-up, a moment later: white crust crumbles out of the hole around the wire, and water trickles out of it." + CLOSE, a: "The wire pushes into the rim hole and crust crumbles out; water starts to trickle." },
};
