// DIRECTOR — segunda pasada: cortes para que cada clip agnes quede ≤12 s, avatar hacia ~25 % y planos fijos ≤12 s.
import { S, BI, LORP, EI } from "./dir_lib.mjs";
export const SHOTS = [
  S(11, "Down there they'll", "av", ""),
  S(25, "And here's the trick", "bi", "b_icewater", { p: BI("A tall glass of ice water with ice cubes sweating on a floury counter beside a bowl of crumbly pie dough, a tablespoon resting on the bowl rim, daylight from the window."), anim: "an ice cube shifts and water beads run down the glass" }),
  S(32, "and I made her write", "av", ""),
  S(47, "If you just dump", "c", "LorTrick", { props: { title: "Esther's trick", text: "Dissolve the soda in the hot water first", bed: "img/lorpies/b_molasses.jpg" } }),
  S(53, "And nobody said", "av", ""),
  S(60, "That's the difference", "bi", "b_darker", { p: BI("Close view of a black cast iron skillet on a white enamel stove with butter and brown sugar cooked to a deep dark mahogany syrup, small bubbles, a wooden spoon resting across the rim."), anim: "the dark syrup bubbles slowly" }),
  S(65, "I do the meringue", "av", ""),
  S(68, "And I'd say", "av", ""),
  S(71, "there'd be two", "av", ""),
  S(72, "and she learned it", "av", ""),
  S(75, "Then back into", "bi", "b_backpan", { p: BI("Close view of warmed egg yolk mixture being poured from a small bowl back into a saucepan of thick yellow filling on a white enamel stove, a wooden spoon stirring."), anim: "the yolks pour in and the spoon stirs" }),
  S(76, "and I have never", "av", ""),
  S(77, "", "c", "LorMeasure", { props: { title: "The meringue", items: [{ amt: "4", what: "egg whites" }, { amt: "¼ tsp", what: "cream of tartar" }, { amt: "½ cup", what: "sugar, a spoon at a time" }] } }),
  S(78, "", "av", ""),
  S(78, "You pour your filling", "bi", "b_hotfill", { p: BI("Hot bright yellow lemon filling being poured from a saucepan into a baked golden pie crust in a glass plate, steam rising, a bowl of white meringue waiting beside it."), anim: "the hot filling pours and steams" }),
  S(83, "So you could make", "av", ""),
  S(85, "That's what most", "av", ""),
  S(95, "Well, you make it", "av", ""),
  S(96, "and she kept making", "av", ""),
  S(99, "", "av", ""),
  S(99, "If you crush", "c", "LorTwoCards", { props: { a: { title: "Crushed", lines: ["you get paste"], mark: "✗" }, b: { title: "Broken by hand", lines: ["bites like an apple"], mark: "✓" }, bed: "img/lorpies/b_crackersapples.jpg" } }),
  S(102, "And we believed", "av", ""),
  S(104, "And nobody needs", "av", ""),
  S(19, "Three hours", "av", ""),
  S(31, "And that's the whole pie", "av", ""),
  S(42, "And honestly", "av", ""),
  S(49, "Still a little warm", "av", ""),
  S(62, "Warm, not boiling", "av", ""),
  S(66, "Same as the lemon", "av", ""),
  S(88, "Then off the heat", "av", ""),
  S(77, "Turn the bowl", "av", ""),
  S(87, "If you put dry", "bi", "b_dryraisins", { p: BI("Close view of a slice of raisin custard pie with hard shriveled dry raisins and a dry cracked filling on a plate beside a small bowl of plump soaked raisins for comparison, on a kitchen table.") }),
  S(38, "You'll think", "av", ""),
  S(51, "and not one", "av", ""),
  S(54, "And I'm not going", "av", ""),
  S(69, "so sour it makes", "av", ""),
  S(107, "That's for Sunday", "av", ""),
  S(16, "Like the top", "av", ""),
  // v3 (voz nueva, más lenta): planos fijos que pasaron de 12 s → cierre a cámara
  S(51, "was standing closest", "av", ""),
  S(66, "tablespoons of sugar", "av", ""),
  S(68, "anniversary he'd say", "av", ""),
  S(79, "Take", "av", ""),
  S(102, "When this is in", "av", ""),
];
