// Plan de clips del jamón (anclas gpt-image-2 + clips LTX-2.5): 9 hablados (voz exacta de `loretta`) + 17 detalles con foley.
// node vlog/lorham/mkplan.mjs   → vlog/lorham/M1/plan.json (anclas con `scripts/agnes_vlog.mjs … anclas`, clips con ltx/mk_ltx.mjs)
import fs from "node:fs";
import { R, WHO, KIT, A, act, plan } from "./lib.mjs";
const M = JSON.parse(fs.readFileSync(R + "_v3/lorham_m1.json", "utf8")); // {m1:{text,s,e}, ...}
const HAM = "a whole spiral-sliced ham with a glossy amber glaze on a platter";
const T = (id) => R + `vlog/lorham/ltx/aud/${id}.wav`;
const FACE = "Medium shot from her grandson's handheld camera at eye level, she looks at the camera and talks.";
const anchors = [
  A("K0", ["k0"], `Same kitchen, same moment of the day. ${WHO} sits at the floury wooden table of ${KIT}. In front of her on the table sits ${HAM}, steam still rising from it, and she rests one hand beside it, looking at the camera and talking, delighted. ${FACE}`),
  A("K1", ["k0"], `Same kitchen, same light. ${WHO} sits at the floury wooden table and looks straight at the camera with a skeptical little smile, eyebrows raised, both hands flat on the table, ${HAM} on the table beside her, mid-sentence. ${FACE}`),
  A("K2", ["k0"], `Same kitchen, same light. ${WHO} sits at the floury wooden table and holds up four fingers of one hand toward the camera, the other hand on the table beside ${HAM}, mouth open mid-sentence, eyebrows lifted. ${FACE}`),
  A("K3", ["k0"], `Same kitchen, same light. ${WHO} leans toward the camera and lowers her head a little as if telling a secret, holding up between two fingers a small faded, yellowed, stained index card written in pencil, the worn spiral recipe book open on the floury table, ${HAM} behind it. ${FACE}`),
  A("K4", ["k0"], `Same kitchen, same light. ${WHO} stands at the white enamel stove side counter, both old hands on a spiral ham she is turning over in a big dented aluminum roasting pan so the flat cut side faces down, looking up at the camera with a focused little smile, a measuring cup of golden juice on the counter. ${FACE}`),
  A("K5", ["k0"], `Same kitchen, same light. ${WHO} sits at the floury table and holds up a white handwritten recipe card to the camera with both hands, the card close in front of her chest while her warm eyes look over the top of it, ${HAM} and the spiral recipe book on the table behind it. ${FACE}`),
  A("K6", ["k0"], `Same kitchen, same light. ${WHO} stands at the counter brushing brown glaze over a spiral ham in a roasting pan with a pastry brush, glancing up at the camera with a gentle smile, a saucepan of glaze on the counter beside the pan. ${FACE}`),
  A("K7", ["k0"], `Same kitchen, same light. ${WHO} sits at the floury table covering her mouth with one hand as she laughs, eyes crinkled, looking at the camera, in front of her a ham with a little white plastic disk still on its bone end. ${FACE}`),
  A("K8", ["k0"], `Same kitchen, same light. ${WHO} stands at the white enamel stove stirring a small saucepan of warm brown pan juices with a wooden spoon, looking up at the camera with a thoughtful warm face, the yellow checked curtains beside the stove. ${FACE}`),
];
const D = (id, scene) => anchors.push(A(id, ["k0"], `Tight close-up of only hands and food, her face is NOT in the frame at all (cropped out above the top edge): on the floury wooden table of her kitchen, ${scene}`));
const clips = [];
const talk = (id, a, action) => clips.push({ id, a, audio: T(id), text: M[id].text, action: act(action) });
talk("m1", "K0", "She talks to her grandson behind the camera, delighted, gesturing toward the glazed ham in front of her.");
talk("m2", "K1", "She looks at the camera with a skeptical smile and talks, counting the old way off on her hand.");
talk("m3", "K2", "She holds up four fingers toward the camera, talking, then wags one finger firmly.");
talk("m4", "K3", "She leans toward the camera holding the small faded card, speaking lower as if telling a secret.");
talk("v_flip", "K4", "She turns the ham over in the pan with both hands while she talks to the camera.");
talk("v_card", "K5", "She holds up the recipe card to the camera lens and talks warmly, inviting him to take a picture.");
talk("v_glaze", "K6", "She brushes the glaze over the ham while she talks, glancing up at the camera.");
talk("v_dottie", "K7", "She laughs behind her hand while telling the story, then shakes her head.");
talk("v_juice", "K8", "She stirs the small saucepan of warm pan juices while she talks to the camera.");
const det = (id, scene, d1, d2, sound) => { D("K" + id, scene); clips.push({ id, a: "K" + id, detail: true, d1, d2, sound }); };
det("d_slice", `a long carving knife cutting a thick slice from a glazed spiral ham on a wooden board and the slice tipping over, an old hand with a lilac sleeve holding the ham steady, clear pink juice beginning to run onto the board.`, "a carving knife glides through a glazed ham and a thick slice tips over", "juice runs out of the slice and pools on the board", "the soft slice of a knife through ham and a wet drip of juice on wood");
det("d_dry", `a plate with a dry gray slice of ham with curled cracked edges, an old hand with a lilac sleeve lifting one corner of it with a fork.`, "a fork lifts the curled edge of a dry gray ham slice", "the dry slice cracks a little as it lifts", "a small dry crackle of a fork on dry meat");
det("d_thermowait", `an old oven thermometer dial on a ham in a roasting pan seen through the open oven door, the dial reading low, an old hand in a quilted oven mitt tapping the pan edge.`, "the mitted hand taps the pan while the thermometer dial sits low", "the hand pulls back as steam drifts up from the ham", "a metal tap on a pan and a low oven hum");
det("d_cutdown", `an old hand with a lilac sleeve flipping a spiral ham in a big dented aluminum roasting pan so its flat cut side lands face down on the pan, a measuring cup of golden juice beside the pan.`, "both old hands tip a spiral ham over in the roasting pan", "the ham settles cut side down in the pan", "the heavy soft thud of a ham settling in a metal pan");
det("d_foil", `old hands crimping a long sheet of aluminum foil tightly around the rim of a roasting pan holding a ham, pinching the foil edge down with the fingers.`, "old fingers pinch the foil down around the rim of the pan", "the foil edge is sealed tight all around", "the crinkle of aluminum foil being pinched and folded");
det("d_glazepot", `a small saucepan on a white enamel stove with a thick brown glaze bubbling gently, an old hand with a lilac sleeve stirring it with a wooden spoon, steam rising.`, "a wooden spoon stirs the bubbling brown glaze", "a thread of glaze drips off the spoon back into the pan", "a gentle bubbling and the scrape of a spoon in a pan");
det("d_probe", `an old hand pushing the metal probe of a dial meat thermometer into the thickest part of a ham in a roasting pan, the dial held up at the side.`, "the metal probe slides into the thickest part of the ham", "the hand lets go and the dial needle settles", "a soft push of a metal probe into meat");
det("d_foilpeel", `an old hand in a thick quilted oven mitt peeling back the foil from a roasting pan with a ham, a cloud of steam rolling up from the pan.`, "the mitted hand peels the foil back from the pan", "steam billows up over the pink wet ham", "the crinkle of foil and a hiss of escaping steam");
det("d_brush", `an old hand with a lilac sleeve painting brown glaze over a spiral ham with a pastry brush, working it down between the slices, the glaze dripping into the cuts.`, "a pastry brush paints glaze across the top of the ham", "the brush works the glaze down between the slices", "the soft wet sweep of a pastry brush and dripping glaze");
det("d_dial140", `a dial meat thermometer stuck in a ham reading one hundred forty degrees, an old hand with a lilac sleeve pointing at the dial with one finger.`, "a finger taps the glass of the dial that reads one hundred forty", "the hand lifts the thermometer out of the ham", "a small tap on glass and the hiss of steam");
det("d_spiralcarve", `a thin knife running along the bone of a spiral ham as the slices fall away, an old hand with a lilac sleeve steadying the ham, slices stacking on a white platter.`, "the knife runs along the bone and the thin slices fall away", "the slices land in a neat stack on the platter", "the soft papery fall of thin ham slices onto a platter");
det("d_stirglaze", `an old hand with a lilac sleeve stirring a saucepan of brown sugar glaze with a wooden spoon, brown sugar and a honey jar and a mustard bottle beside the stove.`, "a wooden spoon stirs the brown sugar glaze as it melts", "the glaze turns glossy and thick", "a slow bubbling and the scrape of a spoon");
det("d_score", `a sharp knife cutting diamond lines into the layer of fat on top of a ham, an old hand with a lilac sleeve holding the ham steady.`, "a sharp knife cuts a line across the fat of the ham", "a second line crosses the first making a diamond", "the dry scratch of a knife through fat");
det("d_hamsalad", `an old hand with a lilac sleeve mixing chopped ham with mayonnaise and sweet pickle relish in a glass bowl with a wooden spoon.`, "a wooden spoon folds mayonnaise into the chopped ham", "the ham salad becomes creamy and pink in the bowl", "a soft wet folding of mayonnaise in a glass bowl");
det("d_hambone", `an old hand with a lilac sleeve lowering a ham bone into a big pot with navy beans, onions and carrots, water rippling around it, steam rising.`, "the ham bone is lowered into the pot of beans", "water ripples and settles around the bone", "a low splash and the hum of a simmering pot");
det("d_strain", `an old hand with a lilac sleeve pouring brown ham pan juices through a metal strainer into a small saucepan, a pat of butter beside it.`, "brown juices pour through the strainer into the saucepan", "the stream thins to drips as the pan empties", "the trickle of liquid through a metal strainer");
det("d_spoonjuice", `an old hand with a lilac sleeve spooning glossy brown juice over a row of overlapping ham slices on a white platter, the juice running between the slices.`, "a spoon drizzles glossy juice along a row of ham slices", "the juice runs between the slices and shines", "the soft drizzle of juice on meat");
fs.mkdirSync(R + "vlog/lorham/M1", { recursive: true });
fs.writeFileSync(R + "vlog/lorham/M1/plan.json", JSON.stringify(plan("vlog/lorham/M1", anchors, clips), null, 1));
console.log("plan:", anchors.length, "anclas,", clips.length, "clips");
