// Constantes y helpers del DIRECTOR de Loretta (vestuario FIJO, cocina, luz y look del creador). Cada toma: S(p, frase, kind, name, opts)
//   kind: av · vl (LTX a2v hablado, opts.a=escena del ancla, opts.act=acción) · kf (LTX i2v detalle con foley: opts.a, d1, d2, sound)
//         lor (foto gpt con Loretta) · bi (foto gpt / stock si opts.q) · ei (snapshot de época) · c (componente Lor*, opts.props)
export const LIGHT = "This is one ordinary frame pulled from a normal handheld home video shot by her grandson with a consumer camera at eye level, simply recording what happens, not composing a photo. The framing is casual and a little off: something is cut by the edge of the frame. Almost everything in the frame is in focus, nothing blurred out: the cluttered kitchen background stays fully readable. The only light is what the place really has, and each person and object gets light according to where it stands; correctly exposed, the side near the window a little brighter and cooler, the far corners dimmer. Colours of an ordinary video with automatic white balance and almost no correction: moderate contrast, soft highlights, mild sensor noise and light compression, faint motion blur on anything moving. Skin with pores, age spots and uneven tone; hair with stray strands; clothes and apron with real creases and flour dust. People are caught mid-action, unposed. Daylight from the window on the left plus the ceiling lamp.";
export const LOOK = "Ordinary handheld home video filmed by her grandson with a consumer camera at eye level, small natural shakes and casual slightly imperfect framing, everything in the kitchen in focus, only the light the place really has, correctly exposed, automatic white balance, mild sensor noise; real skin and natural old hands; she moves naturally and unposed, nothing staged; no music.";
export const WHO = "Loretta, an 81-year-old woman with short curly white hair, light-framed glasses, a pearl necklace, a lilac cardigan over a lilac blouse and a floral apron with a green trim, old hands with age spots and veins";
export const KIT = "her 1950s white farmhouse kitchen: a white enamel stove, yellow checked curtains on the window at the left, a ceramic rooster on the wooden dresser, a small wooden cross on the wall, a paper church calendar, a floury wooden table with a worn spiral recipe book";
export const S = (p, at, kind, name, o = {}) => ({ ...o, prompt: o.p, p, at, kind, name });
const TAIL = " One ordinary frame from a normal home video shot at eye level with a consumer camera, casual slightly imperfect framing, something cut by the edge of the frame. Almost everything in focus, nothing blurred out: the background stays readable with ordinary everyday objects. Only the light the place really has, correctly exposed, automatic white balance, moderate contrast, mild sensor noise, true-to-life colors. Real materials with wear and use. No text, no letters, no labels, no logos.";
export const BI = (scene) => scene + TAIL;
export const LORP = (scene) => `${WHO}, in ${KIT}. ${scene} Her face is the face of the reference image: same face, same age, same glasses, not younger, not prettier.` + TAIL;
export const EI = (year, scene) => `A faded color snapshot photograph taken around ${year} in small-town rural Iowa with an ordinary family snapshot camera: ${scene} Faded warm colors of old print film, slightly soft print, casual family snapshot of ordinary Midwestern people caught mid-action, nobody posing for a professional, someone cut by the edge of the frame, the room around them readable, nothing blurred out. No text, no letters, no signs, no logos.`;
export const BSMT = "a church basement fellowship hall with long folding tables covered in red checked paper tablecloths, gray metal folding chairs, a kitchen pass-through window with a roll-up shutter, a big steel coffee urn, painted cinder-block walls and humming fluorescent ceiling lights";
