// DIRECTOR B — el método paso a paso: los ocho pasos + azúcar/Miracle Whip (párrafos 22-52)
import { S, BI, LORP, EI } from "./dir_lib.mjs";
const STEP = (p, n, name, sub) => S(p, "", "c", "LorStepCount", { props: { n, total: 8, name, sub } });
export const SHOTS = [
  // ── PASO 1: los huevos
  STEP(22, 1, "The eggs", "a week or two old"),
  S(22, "A dozen large", "bi", "b_dozeneggs", { q: "carton of white eggs on kitchen table", p: BI("A carton of one dozen large white eggs open on a floury wooden kitchen table with a date written in pencil on the lid, a glass bowl, a wooden spoon, a bag of flour and a pitcher of tea beside it, yellow checked curtain and morning window light."), anim: "light slides across the eggs in the carton" }),
  S(22, "Now, I know", "av", ""),
  S(22, "And honey", "lor", "l_shrug", { p: LORP("She holds out a fresh egg in her palm toward the camera with a shrug and a pained, humorous grimace, as if saying that is the problem, the carton and a dish towel on the floury table.") }),
  S(23, "", "av", ""),
  S(23, "it loses a little", "c", "LorYolkCrossSection", { props: { stage: "perfect", title: "Why an older egg peels", sub: "the air pocket grows at the fat end", callouts: [{ at: 36, text: "the air pocket grows", x: 0.5, y: 0.9 }, { at: 70, text: "the white lets go of the shell", x: 0.2, y: 0.4, color: "#4C7440" }] } }),
  S(23, "A fresh egg clings", "bi", "b_clinging", { p: BI("A close view of a fresh peeled egg with bits of thin shell skin still clinging in tiny flecks and a torn piece of white, an old woman's thumbnail working at it, a bowl of cold water and shell fragments on a metal drain board, window light."), anim: "the thumbnail picks at a flake that will not come off" }),
  S(23, "An older egg lets go", "bi", "b_oldegg", { q: "peeling boiled egg shell comes off", p: BI("An old woman's hands lifting off one big smooth curved piece of eggshell from a hard boiled egg in a single piece, the egg underneath perfectly smooth and white, a bowl of shells and a dish towel on a floury table."), anim: "the whole shell lifts away in one piece" }),
  S(23, "That's all", "av", ""),
  S(24, "", "av", ""),
  S(24, "You buy them on Monday", "bi", "b_buymonday", { q: "buying eggs grocery store", p: BI("An old woman in a lilac cardigan setting a carton of eggs into a wire shopping cart in a small-town grocery store aisle, a calendar on her wrist-watch strap, cans and boxes on the shelves, a store clerk far off down the aisle, ordinary store lighting."), anim: "she sets the carton down in the cart" }),
  S(24, "you put them", "bi", "b_fridgedoor", { p: BI("The door shelf of an old white refrigerator with a carton of eggs on the egg rack, a jar of pickles, a bottle of ketchup, a butter dish and a jug of milk on the other shelves, a hand closing the carton, a masking tape label with a Monday date written in pencil."), anim: "the refrigerator door swings a little" }),
  S(24, "I write the date", "lor", "l_pencil", { p: LORP("She writes the date with a stubby pencil on the lid of an egg carton, tongue slightly out in concentration, reading glasses low on her nose, the carton and a dish towel on the floury table.") }),
  S(24, "Mrs. Halvorsen used", "ei", "e_halvfinger", { p: EI("1968", "a stout church lady in a flowered apron and cat-eye glasses wagging one finger at a younger woman across a church kitchen counter, a carton of eggs and a bowl on the counter between them, the younger woman nodding, a steel coffee urn behind.") }),
  S(24, "She was right", "av", ""),
  // ── PASO 2: la cocción
  STEP(25, 2, "The cooking", "cold water, hard boil, lid on"),
  S(25, "Put the eggs", "bi", "b_onelayer", { q: "eggs in pot of cold water", p: BI("A heavy aluminum pot on a white enamel stove with a dozen white eggs in a single layer on the bottom, an old woman's hand arranging the last egg, a measuring cup, the yellow checked curtain and a kitchen timer on the counter."), anim: "the hand nudges the last egg into place" }),
  S(25, "Cover them", "bi", "b_coldwater", { p: BI("Cold water pouring from a kitchen faucet into a pot of white eggs until it covers them by an inch, an old woman's finger measuring the depth of the water above the eggs, a stainless sink, a dish towel on the faucet."), anim: "water pours and rises over the eggs" }),
  S(25, "Now, cold water", "av", ""),
  S(26, "", "bi", "b_rollingboil", { q: "pot of water at a rolling boil", p: BI("A heavy pot of water at a hard rolling boil with big bubbles bursting all over the surface and steam rising on a white enamel stove, the burner glowing orange, a wooden spoon resting on the edge, a yellow checked curtain at the window."), anim: "big bubbles burst across the surface" }),
  S(26, "Not a little simmer", "bi", "b_simmer", { p: BI("A pot of water with only a few lazy small bubbles at the edge, barely simmering, on a white enamel stove, an old woman's finger pointing at it with disapproval, a kitchen timer and a dish towel beside the stove."), anim: "a few small bubbles drift up" }),
  S(27, "", "vl", "v_cook"),
  S(27, "you put the lid", "bi", "b_lidon", { p: BI("An old woman's hand lowering a heavy aluminum lid onto a pot of eggs on a white enamel stove with the burner turned off, steam escaping around the edge of the lid, an old white wind-up kitchen timer being turned with the other hand, the yellow checked curtain behind."), anim: "the lid settles and steam puffs out" }),
  S(27, "Thirteen I'm not", "c", "LorEggTimer", { props: { steps: [{ kind: "pot", minutes: 13, label: "Lid on. Heat off.", sub: "large eggs: thirteen minutes" }], stepFrames: 240 } }),
  S(27, "If yours are medium", "c", "LorTwoCards", { props: { a: { title: "Medium eggs", lines: ["take off a minute"], mark: "−1" }, b: { title: "Extra large eggs", lines: ["give them a minute more"], mark: "+1" }, bed: "img/lordeviled/b_dozeneggs.jpg" } }),
  S(28, "", "lor", "l_timer", { p: LORP("She stands at the white enamel stove with her arms folded, watching a covered pot, an old white kitchen timer ticking on the counter beside it, a patient but stern look, the yellow checked curtain behind her.") }),
  S(28, "That's how I ended", "ei", "e_dottie79", { p: EI("1979", "two church ladies in polyester blouses and aprons in a farmhouse kitchen, one holding up a halved egg with a gray-green ring around the yolk and laughing, the other covering her face in embarrassment, a pot on the stove, avocado-green wall clock.") }),
  S(28, "Thirteen minutes, and", "bi", "b_timerring", { p: BI("An old white wind-up kitchen timer on a counter with its hand at zero, a small bell mid-ring and a pot with a lid on a white enamel stove behind it, an old woman's hand reaching in from the edge to stop the timer, a dish towel."), anim: "the timer bell shakes as it rings" }),
  // ── el hielo
  S(29, "", "vl", "v_ice"),
  S(29, "Now why", "c", "LorEggTimer", { props: { steps: [{ kind: "ice", minutes: 15, label: "Into the ice water", sub: "fifteen minutes" }], stepFrames: 240 } }),
  S(29, "If it goes on", "bi", "b_keepcooking", { p: BI("A slotted spoon lifting a hot white egg out of a steaming pot and holding it in the air above the pot, steam curling from the shell, a bowl of ice water ready on the floury table beside the stove, an old woman's hand and lilac sleeve."), anim: "steam curls off the egg" }),
  S(29, "The ice stops", "kf", "d_ice"),
  S(29, "So that's two things", "av", ""),
  S(30, "", "bi", "b_washpot", { p: BI("An old woman's hands scrubbing a heavy aluminum pot in a deep white farmhouse sink with soap suds, a dish brush, a window above the sink with yellow checked curtains, a bowl of ice water with eggs on the counter beside the sink."), anim: "soap bubbles slide and the brush scrubs" }),
  S(30, "you set out", "bi", "b_setout", { p: BI("A floury wooden table laid out ready for cooking: a glass mixing bowl, a fine metal sieve, a big metal spoon, a fork, a paring knife, a jar of mustard, a jar of pickles, a jar of mayonnaise, a dish towel folded, the spiral recipe book open."), anim: "a hand sets down one more spoon" }),
  S(30, "A good cook", "av", ""),
  S(30, "We called it", "lor", "l_getout", { p: LORP("She laughs warmly with her head tilted back, a wooden spoon in one hand and a dish towel over her shoulder, the bowls and jars of her ingredients laid out on the floury table before her.") }),
  // ── PASO 3: pelar
  STEP(31, 3, "The peeling", "tap, roll, peel under water"),
  S(31, "you take an egg", "bi", "b_tapegg", { q: "cracking hard boiled egg shell on counter", p: BI("An old woman's hand tapping a cold hard-boiled egg against a floury wooden counter, the first hairline cracks spreading on the white shell, a bowl of ice water with more eggs and a few shell flakes beside it."), anim: "the egg taps and cracks spread" }),
  S(31, "and you roll it", "bi", "b_rollegg", { q: "rolling egg to crack shell", p: BI("An old woman's flat palm rolling a cracked hard boiled egg back and forth on the counter, the shell crackled all over like a map, bits of shell lifting, a bowl of eggs and a dish towel at the edge of the frame."), anim: "the palm rolls the egg and the shell crackles" }),
  S(32, "", "vl", "v_peel"),
  S(32, "You get your thumbnail", "bi", "b_bigpieces", { q: "peeling boiled egg under running water", p: BI("A close view of an old woman's thumbs peeling a smooth hard-boiled egg under a thin stream of running water over a sink, the shell sliding off in big curved pieces, a bowl of shell pieces and a white sink, window light."), anim: "the shell slides off in a big piece under the water" }),
  S(32, "See that", "lor", "l_showingoff", { p: LORP("She holds up a perfectly smooth peeled egg between her thumb and finger toward the camera with a playful, mock-modest look, the sink and a bowl of eggshell pieces behind her.") }),
  S(33, "", "bi", "b_torn1", { p: BI("A cold hard-boiled egg with a torn, pitted white lying on a saucer next to three perfect peeled eggs on a floury table, an old woman's finger pushing the torn one aside, a bowl of shell fragments and a yellow bowl for the yolks."), anim: "the finger slides the ugly egg aside" }),
  S(33, "That one goes", "lor", "l_eating", { p: LORP("She stands at the counter eating a torn peeled egg with her hand cupped under it, glancing sideways at the camera with a guilty, mischievous look, the pot and bowl of shells on the counter.") }),
  S(33, "She eats them", "av", ""),
  // ── PASO 4: cortar
  STEP(34, 4, "The cutting", "a thin sharp knife, a damp towel"),
  S(34, "A thin sharp knife", "kf", "d_cut"),
  S(34, "Cut lengthwise", "c", "LorEgg3D", { props: { mode: "halve", ring: false, cutAt: 28, title: "A golden yolk", sub: "all the way through" } }),
  S(34, "That is a beautiful", "lor", "l_beautiful", { p: LORP("She holds one halved egg up close to her face and admires the perfect shiny golden yolk with a soft, proud smile, a knife and a damp towel on the floury cutting board in front of her.") }),
  S(35, "", "bi", "b_popyolks", { p: BI("An old woman's thumb popping golden yolks out of halved eggs into a glass bowl, the egg whites lined up in a row on a wooden board, a paper-towel-lined baking tray waiting beside them, a dish towel and a paring knife."), anim: "a yolk drops into the bowl" }),
  S(35, "set the whites", "bi", "b_whitesdry", { q: "egg whites on paper towel", p: BI("A baking tray lined with paper towels with two neat rows of egg white halves set cut side down, an old woman's hand setting the last one, a bowl of golden yolks beside the tray on a floury table, the paper towel slightly damp near the whites."), anim: "the hand sets a white half down on the towel" }),
  S(35, "This is the cure", "lor", "l_cure", { p: LORP("She taps a finger on a baking tray of egg white halves drying on paper towels and nods with satisfied authority toward the camera, the bowl of golden yolks and a dish towel on the floury table beside the tray.") }),
  S(35, "Wet whites make", "av", ""),
  S(35, "So we let", "bi", "b_towelwater", { p: BI("An old woman's hand turning over an egg white half to show the paper towel beneath it now soaked with a damp ring of water, the rest of the white halves still on the tray, a bowl of golden yolks and a tin of paprika beside the tray."), anim: "the hand turns the white over and the wet ring shows" }),
  S(36, "", "ei", "e_bernice", { p: EI("1966", "a thin elderly church lady with a gray bun and wire glasses in a church kitchen holding a paring knife and a halved egg, patiently demonstrating to a younger woman beside her, a calendar and a steel counter behind them.") }),
  S(36, "Take a very thin", "bi", "b_slicebottom", { p: BI("An old woman's hand holding a halved egg white while a paring knife shaves a very thin slice off its rounded bottom, a dime lying on the floury cutting board next to it for scale, other white halves lined up beside the board."), anim: "the knife shaves a thin sliver" }),
  S(36, "Now it sits flat", "bi", "b_sitsflat", { p: BI("A glass Pyrex dish with a neat grid of egg white halves sitting perfectly flat and level, one being tilted by a finger to show it does not tip, a few thin shaved slivers of white on the floury table beside the dish."), anim: "the finger rocks one egg and it settles flat" }),
  S(36, "Because a deviled", "bi", "b_rolledover", { p: BI("The back seat floor of an old sedan where a glass dish of deviled eggs has tilted, several eggs rolled over upside down with the filling smeared on the dish, an old woman's hand lifting the dish with a wince, a purse and a folded blanket on the seat."), anim: "the dish tips and an egg rolls over" }),
  // ── PASO 5: el colador
  STEP(37, 5, "The sieve", "forty cents at a rummage sale"),
  S(37, "Here's my sieve", "bi", "b_mysieve", { p: BI("An old woman holding up her worn fine-mesh metal sieve with a little wooden handle toward the camera with obvious pride, the dented rim catching the window light, a glass bowl of golden yolks on the floury table below it, the spiral recipe book beside the bowl."), anim: "the sieve tilts and catches the light" }),
  S(37, "You put your yolks", "vl", "v_sieve"),
  S(38, "", "kf", "d_sieve"),
  S(38, "No lumps", "c", "LorSieve", { props: { title: "Sieve it. Don't mash it.", smooth: "smooth as sand", lumpy: "a fork leaves lumps", note: "and no seasoning yet" } }),
  S(38, "I haven't added", "av", ""),
  S(39, "", "bi", "b_scrapesieve", { p: BI("An old woman's spoon scraping the underside of a fine metal sieve held over a glass bowl, a smear of golden sieved yolk on the mesh, the bowl heaped with fluffy fine yellow yolk, a floury table and a dish towel."), anim: "the spoon scrapes yolk off the mesh" }),
  S(39, "And if you've got a ricer", "bi", "b_ricer", { q: "potato ricer", p: BI("An old metal potato ricer with long handles pressing a golden egg yolk into thin strands over a glass bowl, an old woman's hands on the handles, a few strands on the floury table, the spiral recipe book beside the bowl."), anim: "the handles close and strands of yolk emerge" }),
  S(39, "And if you've got neither", "bi", "b_strainer", { p: BI("A small round flour strainer with a wooden handle held over a glass bowl, an old woman's spoon pressing yellow yolk through its fine mesh, a cheese grater and a big metal sieve lying on the floury table beside it for comparison."), anim: "the spoon presses yolk through the strainer" }),
  S(39, "You can even", "av", ""),
  S(40, "", "lor", "l_reader", { p: LORP("She reads from a smartphone held at arm's length with her glasses pushed up on her head, her lips moving, then nodding approvingly, a bowl of sieved yolks and a cutting board of white halves on the floury table in front of her.") }),
  S(40, "takes the little trimmings", "bi", "b_choptrim", { p: BI("A paring knife chopping tiny shavings and trimmings of egg white very fine on a wooden cutting board, an old woman's hand steadying them, a glass bowl of golden sieved yolks waiting at the edge, flour dust on the table."), anim: "the knife chops the white trimmings finely" }),
  S(40, "Well, I tried it", "lor", "l_tried", { p: LORP("She stirs the finely chopped egg white into the golden sieved yolks in a glass bowl with a fork, her eyebrows raised in pleasant surprise, glancing up toward the camera, the spiral recipe book beside the bowl.") }),
  S(40, "So you don't waste", "bi", "b_crumb", { p: BI("A neat bowl of fluffy golden filling with a few flecks of chopped white, a tidy cutting board with no scraps left on it, an old woman's finger pressing the last crumb of white from the board into the bowl, a dish towel."), anim: "the finger sweeps the last crumb into the bowl" }),
  // ── PASO 6: sazonar primero
  STEP(41, 6, "Season first", "the yolks drink it up"),
  S(41, "Two teaspoons", "c", "LorMeasure", { props: { title: "Season the yolks first", items: [{ amt: "2 tsp", what: "yellow mustard" }, { amt: "1 Tbsp", what: "dill pickle juice" }, { amt: "1 tsp", what: "sugar" }, { amt: "½ tsp", what: "salt" }] } }),
  S(42, "", "vl", "v_season"),
  S(42, "And then and this is", "lor", "l_window", { p: LORP("She stands at the kitchen window with her arms folded looking out at a green yard, a kitchen timer on the sill, waiting patiently with a small smile, the bowl of seasoned yolks resting on the floury table behind her.") }),
  S(43, "", "av", ""),
  S(43, "Because a cooked yolk", "bi", "b_yolkdrink", { p: BI("A glass bowl of thick golden yolk paste being stirred with a fork, pickle juice from a jar soaking visibly into the dry crumbs, a yellow stain spreading on a spoon, an old woman's hand and a jar of dill pickles with its lid off on the floury table."), anim: "the fork stirs and the juice soaks in" }),
  S(43, "If you put", "c", "LorTwoCards", { props: { a: { title: "Mayonnaise first", lines: ["fat coats the dry crumbs", "the flavor stays outside"], mark: "✗" }, b: { title: "Seasoning first", lines: ["the yolk drinks it up", "flavor goes to the middle"], mark: "✓" }, bed: "img/lordeviled/b_yolkdrink.jpg" } }),
  S(43, "Then the mayonnaise", "av", ""),
  // ── PASO 7: la mayonesa al final
  STEP(44, 7, "Mayonnaise last", "a little at a time"),
  S(44, "Half a cup", "vl", "v_mayo"),
  S(45, "", "bi", "b_softpeak", { p: BI("A big spoon lifted out of a glass bowl of golden filling holding a soft peak that slumps just slightly at the tip, an old woman's hand tilting the spoon toward the camera, the rest of the filling smooth in the bowl, a jar of mayonnaise and flour on the table."), anim: "the spoon lifts and the peak slumps at the tip" }),
  S(45, "If it runs off", "c", "LorTwoCards", { props: { a: { title: "Too loose", lines: ["boil one more yolk", "that is why I cook two extra"], mark: "✗" }, b: { title: "Too stiff", lines: ["one teaspoon of pickle juice", "a little at a time"], mark: "✗" }, bed: "img/lordeviled/b_softpeak.jpg" } }),
  S(45, "If it's stiff", "av", ""),
  S(46, "", "lor", "l_taste", { p: LORP("She tastes a little of the golden filling off a clean spoon, eyes closed in concentration, then opens them with a considering look toward the camera, a salt cellar and the jar of mustard at hand on the floury table.") }),
  S(46, "Cold food tastes", "c", "LorTrick", { props: { title: "Nobody says this", text: "Cold dulls flavor. Season it brighter.", stamp: "Taste it", bed: "img/lordeviled/l_taste.jpg" } }),
  S(46, "So make it", "av", ""),
  // ── PASO 8: rellenar
  STEP(47, 8, "The filling", "spoon or bag, both are right"),
  S(47, "Now, the spoon", "av", ""),
  S(47, "Both are right", "bi", "b_bothright", { p: BI("An old woman's two hands held side by side over a floury table, one holding a plain tablespoon heaped with golden filling and the other holding a zip-top bag of the same filling with a snipped corner, a glass dish of white egg halves in the middle waiting, a dish towel."), anim: "the two hands hold steady and the filling glistens" }),
  S(47, "You take one spoon", "vl", "v_fill"),
  S(48, "", "kf", "d_pipe"),
  S(48, "A star tip", "bi", "b_startip", { p: BI("A zip-top bag of golden filling with a snipped corner piping a neat star-shaped swirl into a white egg half, the row of other white halves waiting on a glass dish, an old woman's hands squeezing the bag, a dish towel and flour on the table."), anim: "the bag squeezes and a swirl forms" }),
  S(48, "I do it when", "lor", "l_joke", { p: LORP("She laughs and waves her hand dismissively at the camera, a zip-top bag of filling in the other hand, a dish of half-filled deviled eggs on the floury table in front of her.") }),
  S(49, "", "kf", "d_pap"),
  S(49, "Not a big pile", "bi", "b_papdust", { q: "paprika dusting on deviled eggs", p: BI("Red paprika falling in a fine even dusting through a small sieve over a glass dish of deviled eggs with smooth mounded filling, an old woman's hand tapping the sieve, the red tin of paprika open beside the dish, floury table."), anim: "paprika dusts down like soft red snow" }),
  S(49, "And tap the jar", "bi", "b_tapjar", { p: BI("An old woman tapping the side of a jar of paprika against her finger so that only a little falls onto a plate of deviled eggs, her glasses low on her nose as she concentrates, the dish towel and spiral recipe book beside the tray."), anim: "a few red specks fall from the jar" }),
  S(49, "I learned that", "lor", "l_darned", { p: LORP("She looks down at her tin of paprika then up at the camera with a humble, amused shake of her head, as if conceding a point to a stranger, a tray of finished deviled eggs on the floury table.") }),
  S(50, "", "c", "LorDevilTray3D", { props: { count: 24, label: "deviled egg halves", title: "One dozen eggs", sub: "sieve · season · mayonnaise last" } }),
  // ── el azúcar y la Miracle Whip
  S(51, "", "av", ""),
  S(51, "A teaspoon of sugar", "bi", "b_tspsugar", { p: BI("A level metal teaspoon of white sugar held over a glass bowl of golden filling, a few grains falling, a jar of dill pickle juice and a yellow mustard jar beside the bowl, the old woman's hand and lilac sleeve, floury table."), anim: "sugar grains fall from the spoon" }),
  S(51, "But if you don't", "av", ""),
  S(52, "", "bi", "b_mw", { p: BI("A white jar of Miracle Whip with its lid off on a floury kitchen table beside a half cup measure, a bowl of golden filling and a spoon, an old woman's hand pointing at the jar, the yellow checked curtain behind."), anim: "a spoon lifts a glossy ribbon of the dressing" }),
  S(52, "I've watched", "ei", "e_swear", { p: EI("1972", "three church ladies in aprons around a long church kitchen counter, one holding up a jar of salad dressing and arguing happily with the others, a bowl of egg filling on the counter, a steel coffee urn and stacked Pyrex dishes behind them.") }),
  S(52, "Use the one", "av", ""),
];
