// DIRECTOR C — rhmoldbleach: 5 errores (paga el loop 1) + 4 rincones + puerta + la familia del ventilador + techo + preguntas
// + la pintura de juntas + cuándo llamar a un profesional + la rutina de 30 s (paga el loop 3) + resumen + nunca mezclar + CTA 3 (p36-74).
import { S, BI, RHP, BOTTLE } from "../rhonda/lib.mjs";
import { SHOWER, CORNER } from "./dir_a.mjs";
const C = (p, at, name, props = {}, o = {}) => S(p, at, "c", name, { props, ...o });
const DOTS = "clusters of small black mold dots spotting the grout lines and the caulk bead";
const I = (n) => `img/rhmoldbleach/${n}.jpg`;
export const SHOTS = [
  // ── 7:55 · los 5 errores
  C(36, "", "RhChapter", { n: 5, title: "5 mistakes", sub: "that make it do nothing" }),
  S(36, "every one of them makes this fix not work", "av", ""),
  C(37, "", "RhChapter", { n: 1, title: "Watering it down", mistake: true }),
  S(37, "People pour it into a spray bottle", "kf", "k_dilute", { p: BI(`Close view at a white bathroom counter: a hand pours ${BOTTLE.replace("a brown", "a brown")} into a clear plastic spray bottle that is already half full of tap water.`), d1: "the brown bottle pours into the half-full clear spray bottle", d2: "the clear bottle fills up to the top", sound: "liquid glugging into a plastic bottle" }),
  S(37, "Three percent is already mostly water", "bi", "b_mostlywater", { q: "glass of water table", p: BI(`${BOTTLE} standing next to a tall clear glass of water on a white bathroom counter, side by side, daylight from the window.`), anim: "the daylight shimmers slowly in the glass of water; nothing else moves" }),
  C(37, "Cut it in half", "RhStrengthMeter", { full: "Full strength", half: "Half and half" }),
  S(37, "Full strength, straight from the bottle", "rh", "r_fullstrength", { p: RHP(`She holds ${BOTTLE} with a white trigger sprayer up to the camera in ${SHOWER}, tapping it firmly with a gloved finger, dead serious.`) }),
  C(38, "", "RhChapter", { n: 2, title: "Scrubbing right away", mistake: true }),
  S(38, "you're just moving wet black around", "bi", "b_smear", { p: BI(`Close view of ${CORNER}: a toothbrush smearing wet black streaks across white grout, gray dirty water spreading over the tile.`), anim: "the toothbrush smears the black across the grout; nothing else moves" }),
  S(38, "Set a timer and walk away", "bi", "st_phonetimer", { q: "setting timer on phone", q2: "phone timer", p: BI("A hand setting a countdown timer on a smartphone.") }),
  C(39, "", "RhChapter", { n: 3, title: "An old bottle", mistake: true }),
  S(39, "poured it into a clear spray bottle", "bi", "b_clearsill", { q: "spray bottle windowsill", p: BI(`A clear plastic spray bottle of liquid sitting in bright sun on a bathroom windowsill next to a potted plant, dust on the sill.`), anim: "the sunlight sparkles slowly in the clear bottle; nothing else moves" }),
  C(39, "Spray a dirty spot", "RhBottle3D", { compare: { clear: "Goes flat", brown: "Stays strong" } }),
  S(39, "If nothing fizzes at all", "bi", "b_flatspray", { p: BI(`Extreme close view of one wet gray grout line between white subway tiles with small black mold dots, glistening wet from a spray, completely still and flat with not a single bubble. Nothing else in the frame.`), anim: "a single drop slides down; nothing else moves" }),
  S(39, "Get a fresh one", "bi", "st_pharmacyshelf", { q: "pharmacy shelf aisle", q2: "drugstore aisle", p: BI("Shelves of a drugstore aisle with bottles.") }),
  C(40, "", "RhChapter", { n: 4, title: "Metal on the grout", mistake: true }),
  S(40, "A wire brush or a screwdriver", "bi", "b_wirebrush", { p: BI(`A rusty wire brush and a flathead screwdriver lying on the white edge of a tub next to a grout line that has fresh pale scratches gouged into it.`), anim: "the light glints slowly on the metal; nothing else moves" }),
  C(40, "every scratch is a brand new pore", "RhGroutPore3D", { mode: "scratch", labels: { pore: "A new home" } }),
  C(40, "A soft grout brush", "RhDoDont", { yes: { label: "Soft grout brush", img: I("b_softbrush") }, no: { label: "Wire brush", img: I("b_wirebrush") } }),
  S(40, "", "bi", "b_softbrush", { p: BI("A narrow grout brush with soft white nylon bristles and an old toothbrush lying on a white towel on the edge of a white tub."), skip: true }),
  C(41, "", "RhChapter", { n: 5, title: "Not drying it", mistake: true }),
  S(41, "you leave it dripping for the night", "bi", "b_dripnight", { q: "bathroom at night", p: BI(`A dark small bathroom at night, the bottom corner of the white tub still dripping wet and beaded with water, faint light from the hallway.`), anim: "a drop falls from the tile into the little puddle; nothing else moves" }),
  S(41, "Towel it dry, every time", "rh", "r_towel", { p: RHP(`She kneels beside the tub drying the bottom row of grout with an old striped towel, firm and quick.`) }),
  // ── 9:26 · los 4 rincones
  C(42, "", "RhChapter", { n: 6, title: "4 spots nobody cleans", sub: "they send it right back" }),
  S(42, "where the same mold lives", "av", ""),
  S(43, "", "kf", "k_liner", { p: BI(`Close view of a yellow-gloved hand lifting the bottom hem of a clear shower curtain liner out of a white tub: the hem is spotted with pink and black mildew.`), d1: "the gloved hand lifts the liner hem out of the tub", d2: "the hand turns the hem to show the pink and black spots", sound: "a crinkly plastic shower curtain" }),
  S(43, "Pink and black, right", "bi", "b_linermacro", { p: BI("Extreme close view of the folded hem of a clear plastic shower curtain liner with pink slime and black mildew spots along the seam."), anim: "the view creeps slowly along the hem; nothing else moves" }),
  S(43, "Or toss the liner in the washer", "bi", "st_washerload", { q: "loading washing machine", p: BI("Loading laundry into a washing machine.") }),
  S(44, "", "kf", "k_bottlelift", { p: BI(`Close view of a white shower caddy shelf: a yellow-gloved hand lifts a plain shampoo bottle with a blank label, revealing a black slimy ring where it stood.`), d1: "the gloved hand lifts the shampoo bottle off the shelf", d2: "a black slimy ring shows on the shelf where it stood", sound: "a plastic bottle lifted off a wet shelf" }),
  S(44, "Spray the shelf", "bi", "b_shelfspray", { p: BI(`Close view of ${BOTTLE} with a trigger sprayer misting a white corner shower shelf where black rings are, plain shampoo bottles with blank labels set aside on the tub edge.`), anim: "the mist drifts down onto the shelf; nothing else moves" }),
  S(45, "", "bi", "b_fancover", { p: BI("Looking straight up at a bathroom ceiling exhaust fan cover with its white plastic grille clogged with gray fuzzy dust."), anim: "a strand of gray fuzz trembles slightly on the grille; nothing else moves" }),
  C(45, "that fan can't pull the wet air out", "RhFogMirror", { img: I("b_fogmirror"), lines: ["Fan clogged", "= wet for hours"] }),
  S(45, "", "bi", "b_fogmirror", { p: BI(`A bathroom mirror above a white sink completely fogged with steam, water droplets running down the glass, the room behind reflected only as a blur of white light.`), skip: true }),
  S(45, "Turn off the power", "bi", "b_fanwash", { q: "washing vent cover", p: BI("A gray plastic exhaust fan grille being washed under a running kitchen faucet by yellow-gloved hands, gray dust rinsing off."), anim: "the gray dust rinses off under the water; nothing else moves" }),
  S(46, "", "bi", "b_windowtrack", { q: "cleaning window track", p: BI("Close view of the bottom track of a small white vinyl window inside a tiled shower, standing water and black gunk in the track corners."), anim: "a drop of water runs into the track; nothing else moves" }),
  S(46, "clean it out with a cotton swab", "bi", "b_trackswab", { p: BI("A yellow-gloved hand running a white cotton swab along a wet window track, the swab tip turning black."), anim: "the swab slides along the track; nothing else moves" }),
  S(47, "", "bi", "st_glassdoor", { q: "glass shower door bathroom", q2: "glass shower", p: BI("A glass shower door in an ordinary home bathroom.") }),
  S(47, "The rubber strip at the bottom of the door", "kf", "k_doorsweep", { p: BI(`Extreme close view of a yellow-gloved finger running along the clear rubber strip at the bottom of a glass shower door, the finger coming away slimy and gray.`), d1: "the gloved finger runs along the rubber strip", d2: "the finger lifts showing gray slime on the glove", sound: "a wet rubbery squeak" }),
  S(47, "Then wipe the track dry", "bi", "b_trackdry", { q: "cleaning shower door", p: BI("A yellow-gloved hand wiping the metal bottom track of a glass shower door dry with a white cloth."), anim: "the cloth wipes along the track; nothing else moves" }),
  // ── la familia del ventilador
  S(48, "", "rh", "r_family", { p: RHP(`She stands in a family bathroom with three kids' toothbrushes in a cup and rubber ducks on the tub edge, sniffing the air with a puzzled face next to a mom holding a laundry basket.`) }),
  S(48, "like a wet basement", "bi", "st_basement", { q: "old basement interior", q2: "damp basement", p: BI("An old damp basement with concrete walls.") }),
  S(48, "It was the fan cover", "kf", "k_fanfuzz", { p: BI(`Looking up at a yellow-gloved hand pulling a white plastic exhaust fan cover down from a bathroom ceiling, thick gray fuzz packed in its grille.`), d1: "the gloved hand pulls the fan cover down from the ceiling", d2: "gray fuzz drifts down from the grille", sound: "a plastic cover popping off a ceiling" }),
  S(48, "We washed that cover", "rh", "r_fanclean", { p: RHP(`She holds up a clean bright white exhaust fan cover in a family bathroom, smiling at a relieved mom.`) }),
  // ── 11:07 · el techo
  C(49, "", "RhChapter", { n: 7, title: "The ceiling", sub: "never spray straight up" }),
  S(49, "spraying straight up", "bi", "b_sprayup", { p: BI(`A man standing in a white tub spraying a plain white spray bottle with a blank label straight up at black dots on the bathroom ceiling, squinting, drops falling.`), anim: "drops fall from the ceiling toward his face; nothing else moves" }),
  S(49, "It drips right back in your eyes", "av", ""),
  S(50, "", "rh", "r_glasses", { p: RHP(`She puts on a pair of plain safety glasses in ${SHOWER}, giving the camera a little nod.`) }),
  S(50, "Spray the peroxide onto a cloth", "kf", "k_spraycloth", { p: BI(`Close view of a yellow-gloved hand spraying ${BOTTLE} onto a folded white cloth held over the bathroom sink.`), d1: "the brown bottle sprays onto the folded cloth", d2: "the cloth turns damp", sound: "two squirts onto fabric" }),
  S(50, "wipe the spots with that", "bi", "b_ceilwipe", { q: "cleaning ceiling", p: BI(`A yellow-gloved hand reaching up with a damp white cloth on a sponge mop head, wiping small black dots off a white bathroom ceiling above a shower.`), anim: "the mop head wipes slowly across the ceiling; nothing else moves" }),
  S(50, "Leave it fifteen minutes", "bi", "b_ceilclean", { p: BI("A white bathroom ceiling corner above a shower, clean and white, a ceiling exhaust fan grille nearby."), anim: "a faint wisp of steam drifts up into the fan; nothing else moves" }),
  S(50, "if the paint is bubbling or peeling", "bi", "b_peeling", { q: "peeling paint ceiling", p: BI("Close view of a bathroom ceiling with paint bubbling and peeling in curls around a brownish water stain."), anim: "a curl of paint trembles slightly; nothing else moves" }),
  S(50, "that's a job for somebody with a ladder", "bi", "st_ladder", { q: "plumber ladder bathroom", p: BI("A repairman on a ladder in a bathroom.") }),
  // ── 11:45 · preguntas
  C(51, "", "RhChapter", { n: 8, title: "Questions I always get" }),
  S(52, "", "av", "", { ov: { c: "RhAsk", props: { q: "Will it bleach colored grout?" } } }),
  S(52, "test a little spot low in the corner first", "bi", "b_testspot", { p: BI("Close view of a yellow-gloved hand dabbing a cotton swab of clear liquid on a small spot of dark charcoal grout low in a bathroom corner, a piece of tape marking it."), anim: "the swab dabs the spot; nothing else moves" }),
  S(52, "Keep it off the fabric", "bi", "st_bathmat", { q: "bath mat towels bathroom", q2: "bath towels folded", p: BI("A soft bath mat and folded towels in a bathroom.") }),
  S(53, "", "av", "", { ov: { c: "RhAsk", props: { q: "Marble or natural stone?" } } }),
  S(53, "Stone is touchy", "bi", "st_marble", { q: "marble bathroom", p: BI("A marble bathroom counter and wall.") }),
  S(54, "", "av", "", { ov: { c: "RhAsk", props: { q: "Can I use vinegar instead?" } } }),
  S(54, "it's no friend to some grout", "bi", "b_vinegar", { p: BI("A plain glass bottle of white vinegar with a blank label on a white bathroom counter next to a grout brush, daylight."), anim: "the light shimmers slowly in the bottle; nothing else moves" }),
  S(55, "", "av", "", { ov: { c: "RhAsk", props: { q: "The stronger stuff?" } } }),
  S(55, "The regular three percent from the drugstore", "rh", "r_regular", { p: RHP(`She holds ${BOTTLE} up in one hand in a drugstore aisle, nodding firmly at the camera.`) }),
  S(56, "", "av", "", { ov: { c: "RhAsk", props: { q: "Does it stink like bleach?" } } }),
  S(56, "after thirty four years of bleach headaches", "rh", "r_headache", { p: RHP(`She sits on the edge of a tub rubbing her temple with a yellow-gloved hand next to a plain white bleach jug, then laughing at herself.`) }),
  S(57, "", "av", "", { ov: { c: "RhAsk", props: { q: "How often?" } } }),
  C(57, "Then once a week", "RhMoldCalendar", { mode: "weekly", img: I("b_whiteafter") }),
  S(58, "", "bi", "b_highshelf", { q: "linen closet towels", p: BI(`${BOTTLE} on a high shelf of a bathroom linen closet above folded towels, out of reach.`), anim: "the closet door swings open a little; nothing else moves" }),
  S(58, "there's nothing left on the grout but water", "av", ""),
  S(59, "", "bi", "b_newcaulk", { q: "applying caulk bathtub", p: BI(`Close view of a fresh smooth white bead of new silicone caulk along a white tub edge, glossy and clean, a caulk gun lying on a towel beside it.`), anim: "the light glints slowly along the wet new caulk; nothing else moves" }),
  C(59, "It needs to cure", "RhTimer30", { minutes: 24, unit: "hours", label: "New caulk: hands off" }),
  // ── 13:21 · la pintura de juntas
  C(60, "", "RhChapter", { n: 9, title: "When to call a pro", sub: "I'll be honest" }),
  S(61, "", "rh", "r_seller", { p: RHP(`She stands in a staged house for sale with a for-sale sign visible through the window, raising one eyebrow at the camera.`) }),
  S(61, "painted every black line", "kf", "k_groutpen", { p: BI(`Extreme close view of a white grout pen marker being drawn along a grout line with black dots between white tiles, the line turning bright white behind the tip.`), d1: "the white pen tip draws along the dotted grout line", d2: "the line behind the tip turns bright white", sound: "a felt marker squeaking on grout" }),
  S(61, "It looked brand new", "bi", "b_painted", { p: BI(`Straight-on view of a shower corner where every grout line is painted unnaturally bright white, too perfect, shining.`), anim: "the light glints slowly on the painted lines; nothing else moves" }),
  S(61, "Two weeks later", "bi", "b_inspector", { q: "home inspector flashlight", p: BI("A home inspector in a polo shirt crouched in a bathroom shining a flashlight at the shower grout, a clipboard on his knee."), anim: "the flashlight beam moves slowly along the grout; nothing else moves" }),
  C(61, "wearing a white coat", "RhGroutPore3D", { mode: "paint", labels: { top: "Paint", roots: "Roots: still there" } }),
  S(61, "over a two dollar pen", "rh", "r_pen", { p: RHP(`She holds up a white grout pen between two gloved fingers like something distasteful, shaking her head at the camera.`) }),
  // ── cuándo llamar a un profesional
  S(62, "", "av", ""),
  C(62, "bigger than about three feet by three feet", "RhPatchMeter", { img: I("b_bigpatch") }),
  S(62, "", "bi", "b_bigpatch", { p: BI("Straight-on view of a bathroom wall next to a tub with a large spread of black mold over the painted drywall, wider than a bath mat, a towel bar above it."), skip: true }),
  S(62, "the wall feels soft", "kf", "k_softwall", { p: BI(`Close view of a yellow-gloved thumb pressing into a stained, bubbling patch of painted bathroom drywall near a tub, the wall giving in.`), d1: "the gloved thumb presses on the stained wall", d2: "the wall dents softly under the thumb", sound: "a soft damp crunch of drywall" }),
  S(62, "coming out from behind the tile", "bi", "b_behindtile", { p: BI("Close view of black mold creeping out from behind the edge of a cracked white wall tile next to a tub, the grout around it crumbling."), anim: "the view creeps slowly along the cracked tile; nothing else moves" }),
  S(62, "a musty smell", "rh", "r_musty", { p: RHP(`She stands in a bathroom doorway wrinkling her nose and waving one gloved hand in front of her face.`) }),
  S(63, "", "bi", "st_leak", { q: "water leak pipe drip", q2: "leaking pipe", p: BI("Water dripping from a leaking pipe.") }),
  S(63, "No brown bottle in the world fixes a leak", "av", ""),
  S(63, "You fix the water first", "bi", "st_plumber", { q: "plumber fixing pipe", p: BI("A plumber fixing a pipe with a wrench.") }),
  // ── 14:24 · la rutina de 30 s (loop 3)
  C(64, "", "RhChapter", { n: 10, title: "The 30-second habit", sub: "11 years, not one black dot" }),
  S(64, "it's the reason I haven't seen a black dot", "rh", "r_myshower", { p: RHP(`She stands in her own small cozy bathroom next to a spotless white tub and shower, a squeegee hanging from the shower head, smiling warmly at the camera.`) }),
  S(65, "", "kf", "k_squeegee2", { p: BI(`Close view of a yellow-gloved hand pulling a rubber squeegee across a glass shower door beaded with water, a clean streak behind the blade.`), d1: "the squeegee pulls across the wet glass", d2: "the glass behind the blade is left clear", sound: "a rubber squeegee pulling across wet glass" }),
  S(65, "Then a quick wipe", "bi", "st_wipegrout", { q: "wiping shower tiles towel", q2: "cleaning bathroom tiles cloth", p: BI("A towel wiping the bottom row of shower tiles.") }),
  C(65, "Thirty seconds", "RhFogMirror", { img: I("b_fogmirror"), lines: ["Squeegee", "Wipe the corners", "30 seconds"] }),
  S(66, "", "bi", "b_fanon", { q: "bathroom ceiling fan steam", p: BI("A white bathroom ceiling exhaust fan with a wisp of steam being drawn into it after a shower, the shower curtain pulled open below."), anim: "the steam drifts up into the fan; nothing else moves" }),
  S(66, "and leave the shower curtain pulled open", "bi", "b_curtainopen", { q: "shower curtain bathroom", p: BI(`A clear shower curtain liner spread out open along the rod to dry in ${SHOWER}, not bunched.`), anim: "the curtain sways very slightly; nothing else moves" }),
  S(66, "A wet bunched up curtain is a mold hotel", "bi", "b_bunched", { p: BI("A wet shower curtain liner bunched up in a tight wad at one end of the rod, dripping, black spots in its folds."), anim: "a drop falls from the wad; nothing else moves" }),
  S(67, "", "rh", "r_weekly", { p: RHP(`She lightly sprays ${BOTTLE} along the bottom row of grout in a clean white shower, casual, on cleaning day.`) }),
  C(67, "light spray of peroxide on the corners", "RhMoldCalendar", { mode: "weekly", img: I("b_day9clean") }),
  S(67, "You don't even have to scrub", "av", ""),
  S(68, "", "bi", "b_squeegeehook", { q: "shower squeegee", p: BI(`A rubber squeegee hanging from a little hook on a chrome shower head in ${SHOWER}, an old hand towel on a hook just outside the curtain.`), anim: "the squeegee swings gently on its hook; nothing else moves" }),
  S(68, "Nobody will", "av", ""),
  // ── resumen
  C(69, "", "RhCheck", { title: "The whole thing", items: ["Gloves on, fan on", "Rinse the corner", "Spray full strength, soaking", "15 minutes, hands off", "Brush, rinse, dry", "Swab test · strips overnight", "Squeegee after every shower"], fast: true }),
  S(69, "Squeegee after every shower", "av", ""),
  // ── nunca mezclar + cierre
  C(70, "", "RhNeverMix", { chart: true }),
  S(70, "And peroxide and vinegar", "av", ""),
  S(71, "", "bi", "b_brownbottle", { p: BI(`${BOTTLE} standing alone on a white bathroom shelf in soft window light.`), anim: "the window light shifts slowly over the bottle; nothing else moves" }),
  S(71, "That's why it comes in brown", "av", ""),
  C(72, "", "RhBookPage", { page: I("book_p10"), stamp: "Page 10 · Rhonda's book" }),
  C(72, "and Fix number one is free on the page", "RhQRCard", { qr: I("qr"), cover: I("book_cover") }),
  S(73, "", "av", "", { ov: { c: "RhAsk", props: { q: "How many days did YOUR bleach last?" } } }),
  S(74, "", "vl", "m7", { a: `stands in ${SHOWER} peeling off one yellow rubber glove, smiling warmly at the camera.`, act: "She peels off her glove, smiles warmly and says goodbye to the camera with a little wave.", b: "she waves goodbye to the camera with her bare hand, smiling, the yellow glove in her other hand." }),
];
