// cues_cultivosep.gen.tsx — GENERADO por beatsheet.mjs desde cultivosep.json.
// NO editar a mano: cambiá el beatsheet y re-corré  node beatsheet.mjs beatsheet/cultivosep.json
import { ReactNode } from "react";
import { RawShot } from "./scenes/RawShot";
import { CropShowcase } from "./scenes/CropShowcase";
import { SeasonDial } from "./scenes/CropMechanisms";
import { StarchToSugar } from "./scenes/CropMechanisms";
import { VernalizationClock } from "./scenes/CropMechanisms";
import { SoilFridge } from "./scenes/CropMechanisms";
import { PremiumOverlay } from "./scenes/PremiumOverlay";
import { HighlightSweep, BigStatReveal, DuelColumns, PullQuote, ChecklistReveal, NumberedSteps, CtaCard, THEME_EARTH } from "./kit/premium";

export type Cue = { key: string; start: number; dur: number; kind: string; el: (d: number) => ReactNode };

export const CUES: Cue[] = [
  { key: "cultivosep_s_01", start: 0, dur: 5.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_01.mp4" hue="amber" darken={0} clipDur={10.01} /> },
  { key: "cultivosep_s_02", start: 5.44, dur: 5.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_02.mp4" hue="amber" darken={0} clipDur={116.44} /> },
  { key: "cultivosep_s_03", start: 10.74, dur: 5.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_03.mp4" hue="amber" darken={0} clipDur={9.88} /> },
  { key: "cultivosep_s_04", start: 15.96, dur: 4.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_04.mp4" hue="amber" darken={0} clipDur={21.39} /> },
  { key: "cultivosep_s_05", start: 20.48, dur: 7.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_05.mp4" hue="amber" darken={0} clipDur={9.21} /> },
  { key: "cultivosep_s_06", start: 27.8, dur: 5.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_06.mp4" hue="amber" darken={0} clipDur={19.74} /> },
  { key: "cultivosep_s_07", start: 33.2, dur: 4.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_07.mp4" hue="amber" darken={0} clipDur={31.05} /> },
  { key: "cultivosep_s_08", start: 37.1, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_08.mp4" hue="amber" darken={0} clipDur={8.23} /> },
  { key: "cultivosep_s_09", start: 44.96, dur: 3.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_09.mp4" hue="amber" darken={0} clipDur={10.3} /> },
  { key: "cultivosep_s_10", start: 47.88, dur: 3.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_10.mp4" hue="amber" darken={0} clipDur={16.2} /> },
  { key: "cultivosep_s_11", start: 51.22, dur: 7.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_11.mp4" hue="amber" darken={0} clipDur={11.51} /> },
  { key: "cultivosep_s_12", start: 58.12, dur: 4.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_12.mp4" hue="amber" darken={0} clipDur={20.64} /> },
  { key: "cultivosep_s_13", start: 62.56, dur: 3.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_13.mp4" hue="amber" darken={0} clipDur={10.6} /> },
  { key: "cultivosep_s_14", start: 66.18, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_14.mp4" hue="amber" darken={0} clipDur={9.56} /> },
  { key: "cultivosep_s_15", start: 69.16, dur: 4.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_15.mp4" hue="amber" darken={0} clipDur={13.48} /> },
  { key: "cultivosep_s_16", start: 73.7, dur: 4.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_16.mp4" hue="amber" darken={0} clipDur={58} /> },
  { key: "cultivosep_s_17", start: 78.28, dur: 4.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_17.mp4" hue="amber" darken={0} clipDur={9.18} /> },
  { key: "cultivosep_s_18", start: 82.2, dur: 5.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_18.mp4" hue="amber" darken={0} clipDur={12.9} /> },
  { key: "cultivosep_s_19", start: 87.42, dur: 4.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_19.mp4" hue="amber" darken={0} clipDur={6.36} /> },
  { key: "cultivosep_s_20", start: 91.56, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_20.mp4" hue="amber" darken={0} clipDur={44} /> },
  { key: "cultivosep_s_21", start: 94.76, dur: 4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_21.mp4" hue="amber" darken={0} clipDur={8} /> },
  { key: "cultivosep_s_22", start: 98.46, dur: 4.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_22.mp4" hue="amber" darken={0} clipDur={37.07} /> },
  { key: "cultivosep_s_23", start: 102.72, dur: 4.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_23.mp4" hue="amber" darken={0} clipDur={22.42} /> },
  { key: "cultivosep_s_24", start: 107.08, dur: 4.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_24.mp4" hue="amber" darken={0} clipDur={28.88} /> },
  { key: "cultivosep_s_25", start: 111.6, dur: 6.22, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_25.mp4" hue="amber" darken={0} clipDur={28.38} /> },
  { key: "cultivosep_s_26", start: 117.52, dur: 3.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_26.mp4" hue="amber" darken={0} clipDur={14.11} /> },
  { key: "cultivosep_s_27", start: 121.14, dur: 7.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_27.mp4" hue="amber" darken={0} clipDur={11.36} /> },
  { key: "cultivosep_s_28", start: 128.66, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_28.mp4" hue="amber" darken={0} clipDur={16} /> },
  { key: "cultivosep_s_29", start: 132.12, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_29.mp4" hue="amber" darken={0} clipDur={12.08} /> },
  { key: "cultivosep_s_30", start: 139.9, dur: 4.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_30.mp4" hue="amber" darken={0} clipDur={24.42} /> },
  { key: "cultivosep_s_31", start: 144.32, dur: 4.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_31.mp4" hue="amber" darken={0} clipDur={18.67} /> },
  { key: "cultivosep_s_32", start: 148.34, dur: 3.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_32.mp4" hue="amber" darken={0} clipDur={28.72} /> },
  { key: "cultivosep_s_33", start: 151.56, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_33.mp4" hue="amber" darken={0} clipDur={5.67} /> },
  { key: "cultivosep_s_34", start: 155.96, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_34.mp4" hue="amber" darken={0} clipDur={26.49} /> },
  { key: "cultivosep_s_35", start: 158.86, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_35.mp4" hue="amber" darken={0} clipDur={10.54} /> },
  { key: "cultivosep_s_36", start: 162, dur: 3.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_36.mp4" hue="amber" darken={0} clipDur={11} /> },
  { key: "cultivosep_s_37", start: 165.08, dur: 6.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_37.mp4" hue="amber" darken={0} clipDur={27.96} /> },
  { key: "cultivosep_s_38", start: 170.8, dur: 3.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_38.mp4" hue="amber" darken={0} clipDur={50.02} /> },
  { key: "cultivosep_s_39", start: 174.02, dur: 5.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_39.mp4" hue="amber" darken={0} clipDur={25} /> },
  { key: "cultivosep_s_40", start: 178.92, dur: 6.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_40.mp4" hue="amber" darken={0} clipDur={7.5} /> },
  { key: "cultivosep_s_41", start: 185.02, dur: 4.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_41.mp4" hue="amber" darken={0} clipDur={28.21} /> },
  { key: "show_0", start: 189.54, dur: 18, kind: "showcase", el: (d) => <CropShowcase durationInFrames={d} focus={0} number={"1"} name={"Col rizada"} description={"Con la primera helada convierte su almidón en azúcar: se vuelve más tierna y dulce."} tip={"Cosecha de abajo hacia arriba y te da hojas nuevas todo el invierno."} images={["broll/cultivosep/reel_kale.jpg","broll/cultivosep/reel_acelga.jpg","broll/cultivosep/reel_zanahoria.jpg","broll/cultivosep/reel_puerro.jpg","broll/cultivosep/reel_ajo.jpg"]} months={[7,8,9]} /> },
  { key: "cultivosep_s_47", start: 208.44, dur: 5.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_47.mp4" hue="amber" darken={0} clipDur={9.87} /> },
  { key: "cultivosep_s_48", start: 213.26, dur: 4.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_48.mp4" hue="amber" darken={0} clipDur={10.6} /> },
  { key: "cultivosep_s_49", start: 217.86, dur: 4.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_49.mp4" hue="amber" darken={0} clipDur={31.63} /> },
  { key: "cultivosep_s_50", start: 222.08, dur: 5.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_50.mp4" hue="amber" darken={0} clipDur={7.3} /> },
  { key: "cultivosep_s_51", start: 226.84, dur: 3.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_51.mp4" hue="amber" darken={0} clipDur={17.58} /> },
  { key: "cultivosep_s_52", start: 230.18, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_52.mp4" hue="amber" darken={0} clipDur={21.48} /> },
  { key: "cultivosep_s_53", start: 232.72, dur: 2.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_53.mp4" hue="amber" darken={0} clipDur={5.51} /> },
  { key: "mech_starchsugar", start: 235.18, dur: 8, kind: "starchsugar", el: (d) => <StarchToSugar durationInFrames={d} /> },
  { key: "cultivosep_s_55", start: 243.82, dur: 5.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_55.mp4" hue="amber" darken={0} clipDur={10.4} /> },
  { key: "cultivosep_s_56", start: 249.06, dur: 3.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_56.mp4" hue="amber" darken={0} clipDur={12.71} /> },
  { key: "cultivosep_s_57", start: 252.14, dur: 7.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_57.mp4" hue="amber" darken={0} clipDur={12.51} /> },
  { key: "cultivosep_s_58", start: 259.3, dur: 5.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_58.mp4" hue="amber" darken={0} clipDur={14.64} /> },
  { key: "cultivosep_s_59", start: 264.04, dur: 7.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_59.mp4" hue="amber" darken={0} clipDur={12.28} /> },
  { key: "cultivosep_s_60", start: 271.28, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_60.mp4" hue="amber" darken={0} clipDur={27.03} /> },
  { key: "cultivosep_s_61", start: 274.1, dur: 7.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_61.mp4" hue="amber" darken={0} clipDur={7.46} /> },
  { key: "cultivosep_s_62", start: 281.3, dur: 6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_62.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_63", start: 287, dur: 6.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_63.mp4" hue="amber" darken={0} clipDur={8.11} /> },
  { key: "cultivosep_s_64", start: 293.22, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_64.mp4" hue="amber" darken={0} clipDur={31.95} /> },
  { key: "cultivosep_s_65", start: 298.42, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_65.mp4" hue="amber" darken={0} clipDur={10.44} /> },
  { key: "cultivosep_s_66", start: 301.36, dur: 5.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_66.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_67", start: 306.36, dur: 4.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_67.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_68", start: 310.42, dur: 5.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_68.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_69", start: 316.02, dur: 5.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_69.mp4" hue="amber" darken={0} clipDur={31.16} /> },
  { key: "cultivosep_s_70", start: 321.36, dur: 4.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_70.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_71", start: 325.6, dur: 5.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_71.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_72", start: 330.54, dur: 4.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_72.mp4" hue="amber" darken={0} clipDur={11.47} /> },
  { key: "cultivosep_s_73", start: 334.48, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_73.mp4" hue="amber" darken={0} clipDur={9.88} /> },
  { key: "cultivosep_s_74", start: 337.68, dur: 3.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_74.mp4" hue="amber" darken={0} clipDur={26.73} /> },
  { key: "show_1", start: 341.3, dur: 13, kind: "showcase", el: (d) => <CropShowcase durationInFrames={d} focus={1} number={"2"} name={"Acelga"} description={"La de cortar y volver: le sacas las hojas de afuera y rebrota durante meses."} tip={"Cuanto más la cortas, más te da. Castiga al vago."} images={["broll/cultivosep/reel_kale.jpg","broll/cultivosep/reel_acelga.jpg","broll/cultivosep/reel_zanahoria.jpg","broll/cultivosep/reel_puerro.jpg","broll/cultivosep/reel_ajo.jpg"]} months={[8,9,10]} assemble={false} /> },
  { key: "cultivosep_s_78", start: 358.12, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_78.mp4" hue="amber" darken={0} clipDur={52.96} /> },
  { key: "cultivosep_s_79", start: 360.98, dur: 3.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_79.mp4" hue="amber" darken={0} clipDur={9.14} /> },
  { key: "cultivosep_s_80", start: 364.54, dur: 5.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_80.mp4" hue="amber" darken={0} clipDur={15.5} /> },
  { key: "cultivosep_s_81", start: 369.82, dur: 6.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_81.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_82", start: 376.48, dur: 3.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_82.mp4" hue="amber" darken={0} clipDur={41.08} /> },
  { key: "cultivosep_s_83", start: 380.04, dur: 7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_83.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_84", start: 386.74, dur: 3.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_84.mp4" hue="amber" darken={0} clipDur={15.08} /> },
  { key: "cultivosep_s_85", start: 390.38, dur: 7.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_85.mp4" hue="amber" darken={0} clipDur={17.52} /> },
  { key: "cultivosep_s_86", start: 397.56, dur: 5.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_86.mp4" hue="amber" darken={0} clipDur={9.03} /> },
  { key: "cultivosep_s_87", start: 402.56, dur: 3.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_87.mp4" hue="amber" darken={0} clipDur={15.43} /> },
  { key: "cultivosep_s_88", start: 406, dur: 6.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_88.mp4" hue="amber" darken={0} clipDur={12.88} /> },
  { key: "cultivosep_s_89", start: 412.2, dur: 5.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_89.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_91", start: 423.76, dur: 3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_91.mp4" hue="amber" darken={0} clipDur={53.48} /> },
  { key: "cultivosep_s_92", start: 426.46, dur: 4.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_92.mp4" hue="amber" darken={0} clipDur={35.68} /> },
  { key: "cultivosep_s_95", start: 443.02, dur: 7.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_95.mp4" hue="amber" darken={0} clipDur={44.64} /> },
  { key: "cultivosep_s_96", start: 450.38, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_96.mp4" hue="amber" darken={0} clipDur={7.67} /> },
  { key: "cultivosep_s_97", start: 453.1, dur: 5.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_97.mp4" hue="amber" darken={0} clipDur={11.01} /> },
  { key: "cultivosep_s_98", start: 457.88, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_98.mp4" hue="amber" darken={0} clipDur={15.64} /> },
  { key: "show_2", start: 464.52, dur: 13, kind: "showcase", el: (d) => <CropShowcase durationInFrames={d} focus={2} number={"3"} name={"Zanahoria"} description={"Se endulza con la helada y la dejas en la tierra: la tierra es tu heladera."} tip={"Tapala con paja y sacala fresca todo el invierno."} images={["broll/cultivosep/reel_kale.jpg","broll/cultivosep/reel_acelga.jpg","broll/cultivosep/reel_zanahoria.jpg","broll/cultivosep/reel_puerro.jpg","broll/cultivosep/reel_ajo.jpg"]} months={[7,8]} assemble={false} /> },
  { key: "cultivosep_s_104", start: 480.16, dur: 6.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_104.mp4" hue="amber" darken={0} clipDur={9.51} /> },
  { key: "cultivosep_s_105", start: 486.84, dur: 3.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_105.mp4" hue="amber" darken={0} clipDur={11.09} /> },
  { key: "cultivosep_s_106", start: 490.28, dur: 4.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_106.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_107", start: 494.58, dur: 4.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_107.mp4" hue="amber" darken={0} clipDur={30.53} /> },
  { key: "cultivosep_s_108", start: 499.04, dur: 7.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_108.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_109", start: 506.28, dur: 4.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_109.mp4" hue="amber" darken={0} clipDur={36.87} /> },
  { key: "cultivosep_s_110", start: 510.84, dur: 2.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_110.jpg" hue="amber" darken={0} /> },
  { key: "mech_soilfridge", start: 513.28, dur: 9, kind: "soilfridge", el: (d) => <SoilFridge durationInFrames={d} /> },
  { key: "cultivosep_s_113", start: 526.52, dur: 5.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_113.mp4" hue="amber" darken={0} clipDur={13.16} /> },
  { key: "cultivosep_s_114", start: 531.72, dur: 6.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_114.mp4" hue="amber" darken={0} clipDur={16.8} /> },
  { key: "cultivosep_s_115", start: 538.26, dur: 6.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_115.mp4" hue="amber" darken={0} clipDur={18.64} /> },
  { key: "cultivosep_s_116", start: 544.34, dur: 7.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_116.mp4" hue="amber" darken={0} clipDur={23.97} /> },
  { key: "cultivosep_s_117", start: 551.72, dur: 4.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_117.mp4" hue="amber" darken={0} clipDur={4.37} /> },
  { key: "cultivosep_s_118", start: 556, dur: 8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_118.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_119", start: 563.86, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_119.mp4" hue="amber" darken={0} clipDur={14.04} /> },
  { key: "cultivosep_s_120", start: 566.9, dur: 3.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_120.mp4" hue="amber" darken={0} clipDur={28.7} /> },
  { key: "cultivosep_s_121", start: 569.8, dur: 6.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_121.mp4" hue="amber" darken={0} clipDur={60.17} /> },
  { key: "cultivosep_s_122", start: 576.14, dur: 5.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_122.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_123", start: 581.42, dur: 5.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_123.mp4" hue="amber" darken={0} clipDur={9.76} /> },
  { key: "cultivosep_s_124", start: 586.98, dur: 5.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_124.mp4" hue="amber" darken={0} clipDur={10.04} /> },
  { key: "cultivosep_s_125", start: 591.84, dur: 4.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_125.mp4" hue="amber" darken={0} clipDur={19.24} /> },
  { key: "cultivosep_s_126", start: 596.46, dur: 3.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_126.mp4" hue="amber" darken={0} clipDur={7.67} /> },
  { key: "cultivosep_s_127", start: 599.42, dur: 5.6, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_127.mp4" hue="amber" darken={0} clipDur={46.96} /> },
  { key: "show_3", start: 605.02, dur: 13, kind: "showcase", el: (d) => <CropShowcase durationInFrames={d} focus={3} number={"4"} name={"Puerro"} description={"El soldado: se queda en pie en la nieve hasta que lo vas a buscar."} tip={"Aporca el tallo para que la parte blanca sea larga y tierna."} images={["broll/cultivosep/reel_kale.jpg","broll/cultivosep/reel_acelga.jpg","broll/cultivosep/reel_zanahoria.jpg","broll/cultivosep/reel_puerro.jpg","broll/cultivosep/reel_ajo.jpg"]} months={[3,4,8]} assemble={false} /> },
  { key: "cultivosep_s_131", start: 619.82, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_131.mp4" hue="amber" darken={0} clipDur={9.52} /> },
  { key: "cultivosep_s_132", start: 623.02, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_132.mp4" hue="amber" darken={0} clipDur={75.23} /> },
  { key: "cultivosep_s_133", start: 626.42, dur: 3.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_133.mp4" hue="amber" darken={0} clipDur={10.32} /> },
  { key: "cultivosep_s_134", start: 629.82, dur: 5.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_134.mp4" hue="amber" darken={0} clipDur={8.51} /> },
  { key: "cultivosep_s_136", start: 639.64, dur: 7.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_136.mp4" hue="amber" darken={0} clipDur={11.08} /> },
  { key: "cultivosep_s_137", start: 647.02, dur: 5.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_137.mp4" hue="amber" darken={0} clipDur={18.68} /> },
  { key: "cultivosep_s_138", start: 651.76, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_138.mp4" hue="amber" darken={0} clipDur={10.01} /> },
  { key: "cultivosep_s_139", start: 654.6, dur: 2.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_139.mp4" hue="amber" darken={0} clipDur={9.11} /> },
  { key: "cultivosep_s_140", start: 657.12, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_140.mp4" hue="amber" darken={0} clipDur={47.6} /> },
  { key: "cultivosep_s_141", start: 659.84, dur: 2.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_141.mp4" hue="amber" darken={0} clipDur={13.56} /> },
  { key: "cultivosep_s_142", start: 662.38, dur: 2.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_142.mp4" hue="amber" darken={0} clipDur={15.6} /> },
  { key: "cultivosep_s_143", start: 665.04, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_143.mp4" hue="amber" darken={0} clipDur={16.96} /> },
  { key: "cultivosep_s_144", start: 668.18, dur: 5.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_144.mp4" hue="amber" darken={0} clipDur={19.88} /> },
  { key: "cultivosep_s_145", start: 673.06, dur: 6.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_145.mp4" hue="amber" darken={0} clipDur={10.16} /> },
  { key: "cultivosep_s_146", start: 679.24, dur: 5.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_146.mp4" hue="amber" darken={0} clipDur={20.72} /> },
  { key: "cultivosep_s_147", start: 684.36, dur: 3.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_147.mp4" hue="amber" darken={0} clipDur={10.84} /> },
  { key: "cultivosep_s_148", start: 687.52, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_148.mp4" hue="amber" darken={0} clipDur={5.18} /> },
  { key: "cultivosep_s_149", start: 690.36, dur: 6.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_149.mp4" hue="amber" darken={0} clipDur={8.51} /> },
  { key: "cultivosep_s_150", start: 696.46, dur: 6.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_150.mp4" hue="amber" darken={0} clipDur={23.97} /> },
  { key: "cultivosep_s_151", start: 703.12, dur: 4.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_151.mp4" hue="amber" darken={0} clipDur={6.71} /> },
  { key: "cultivosep_s_152", start: 707.22, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_152.mp4" hue="amber" darken={0} clipDur={29.53} /> },
  { key: "show_4", start: 710.58, dur: 14, kind: "showcase", el: (d) => <CropShowcase durationInFrames={d} focus={4} number={"5"} name={"Ajo"} description={"El único que no perdona: plántalo en otoño o pierdes el año entero."} tip={"Un solo diente se convierte en una cabeza entera de ocho a doce dientes."} images={["broll/cultivosep/reel_kale.jpg","broll/cultivosep/reel_acelga.jpg","broll/cultivosep/reel_zanahoria.jpg","broll/cultivosep/reel_puerro.jpg","broll/cultivosep/reel_ajo.jpg"]} months={[9,10,11]} assemble={false} /> },
  { key: "cultivosep_s_157", start: 729.04, dur: 6.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_157.mp4" hue="amber" darken={0} clipDur={9.88} /> },
  { key: "cultivosep_s_158", start: 735.1, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_158.mp4" hue="amber" darken={0} clipDur={13.12} /> },
  { key: "cultivosep_s_159", start: 737.82, dur: 4.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_159.mp4" hue="amber" darken={0} clipDur={9.6} /> },
  { key: "cultivosep_s_160", start: 742.06, dur: 5.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_160.mp4" hue="amber" darken={0} clipDur={2.62} /> },
  { key: "cultivosep_s_162", start: 750.72, dur: 5.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_162.mp4" hue="amber" darken={0} clipDur={12.8} /> },
  { key: "cultivosep_s_163", start: 756.14, dur: 3.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_163.mp4" hue="amber" darken={0} clipDur={35.58} /> },
  { key: "cultivosep_s_164", start: 759.62, dur: 5.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_164.mp4" hue="amber" darken={0} clipDur={12.72} /> },
  { key: "cultivosep_s_165", start: 764.46, dur: 4.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_165.mp4" hue="amber" darken={0} clipDur={16.02} /> },
  { key: "cultivosep_s_166", start: 768.18, dur: 3.46, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_166.mp4" hue="amber" darken={0} clipDur={21.86} /> },
  { key: "cultivosep_s_167", start: 771.34, dur: 5.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_167.mp4" hue="amber" darken={0} clipDur={13.97} /> },
  { key: "cultivosep_s_168", start: 776.38, dur: 2.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_168.mp4" hue="amber" darken={0} clipDur={14.24} /> },
  { key: "mech_vernalize", start: 778.7, dur: 8, kind: "vernalize", el: (d) => <VernalizationClock durationInFrames={d} /> },
  { key: "cultivosep_s_171", start: 793.76, dur: 3.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_171.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_174", start: 806.14, dur: 6.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_174.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_175", start: 812.24, dur: 3.1, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_175.mp4" hue="amber" darken={0} clipDur={2.62} /> },
  { key: "cultivosep_s_178", start: 826.66, dur: 5.82, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_178.mp4" hue="amber" darken={0} clipDur={9.34} /> },
  { key: "cultivosep_s_179", start: 832.18, dur: 3.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_179.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_180", start: 835.82, dur: 6.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_180.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_181", start: 841.76, dur: 5.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_181.mp4" hue="amber" darken={0} clipDur={9.63} /> },
  { key: "cultivosep_s_183", start: 857.84, dur: 5.68, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_183.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_184", start: 863.22, dur: 5.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_184.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_185", start: 868.08, dur: 4.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_185.mp4" hue="amber" darken={0} clipDur={15.78} /> },
  { key: "cultivosep_s_186", start: 872.2, dur: 5.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_186.mp4" hue="amber" darken={0} clipDur={15.84} /> },
  { key: "cultivosep_s_187", start: 877.28, dur: 7.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_187.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_188", start: 884.52, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_188.mp4" hue="amber" darken={0} clipDur={7.92} /> },
  { key: "cultivosep_s_189", start: 888.02, dur: 3.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_189.mp4" hue="amber" darken={0} clipDur={12.72} /> },
  { key: "cultivosep_s_190", start: 891.04, dur: 6.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_190.mp4" hue="amber" darken={0} clipDur={16.02} /> },
  { key: "cultivosep_s_191", start: 897.64, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_191.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_192", start: 900.36, dur: 3.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_192.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_193", start: 904.04, dur: 6.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_193.mp4" hue="amber" darken={0} clipDur={12.35} /> },
  { key: "cultivosep_s_194", start: 909.82, dur: 4.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_194.mp4" hue="amber" darken={0} clipDur={99.29} /> },
  { key: "cultivosep_s_195", start: 914.38, dur: 4.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_195.mp4" hue="amber" darken={0} clipDur={7.51} /> },
  { key: "cultivosep_s_196", start: 918.5, dur: 4.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_196.mp4" hue="amber" darken={0} clipDur={8.44} /> },
  { key: "cultivosep_s_197", start: 922.68, dur: 3.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_197.mp4" hue="amber" darken={0} clipDur={13.9} /> },
  { key: "cultivosep_s_199", start: 932.3, dur: 5.96, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_199.mp4" hue="amber" darken={0} clipDur={20.2} /> },
  { key: "cultivosep_s_200", start: 937.96, dur: 6.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_200.mp4" hue="amber" darken={0} clipDur={13} /> },
  { key: "cultivosep_s_201", start: 943.84, dur: 3.4, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_201.mp4" hue="amber" darken={0} clipDur={9.01} /> },
  { key: "cultivosep_s_202", start: 946.94, dur: 2.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_202.mp4" hue="amber" darken={0} clipDur={12.21} /> },
  { key: "cultivosep_s_203", start: 949.54, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_203.mp4" hue="amber" darken={0} clipDur={15} /> },
  { key: "cultivosep_s_205", start: 960.36, dur: 3.72, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_205.mp4" hue="amber" darken={0} clipDur={11.47} /> },
  { key: "cultivosep_s_206", start: 963.78, dur: 4.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_206.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_207", start: 967.8, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_207.mp4" hue="amber" darken={0} clipDur={15.83} /> },
  { key: "cultivosep_s_208", start: 970.58, dur: 4.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_208.mp4" hue="amber" darken={0} clipDur={18.1} /> },
  { key: "cultivosep_s_210", start: 978.38, dur: 2.98, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_210.mp4" hue="amber" darken={0} clipDur={38.2} /> },
  { key: "mech_seasondial", start: 981.36, dur: 11, kind: "seasondial", el: (d) => <SeasonDial durationInFrames={d} /> },
  { key: "cultivosep_s_214", start: 993.74, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_214.mp4" hue="amber" darken={0} clipDur={7.1} /> },
  { key: "cultivosep_s_215", start: 997.02, dur: 5.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_215.mp4" hue="amber" darken={0} clipDur={27.53} /> },
  { key: "cultivosep_s_216", start: 1001.92, dur: 5.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_216.mp4" hue="amber" darken={0} clipDur={10.73} /> },
  { key: "cultivosep_s_217", start: 1007.52, dur: 7.52, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_217.mp4" hue="amber" darken={0} clipDur={20.59} /> },
  { key: "cultivosep_s_218", start: 1014.74, dur: 4.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_218.mp4" hue="amber" darken={0} clipDur={30.03} /> },
  { key: "cultivosep_s_219", start: 1019.32, dur: 3.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_219.mp4" hue="amber" darken={0} clipDur={11.72} /> },
  { key: "cultivosep_s_220", start: 1022.46, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_220.mp4" hue="amber" darken={0} clipDur={15.18} /> },
  { key: "cultivosep_s_221", start: 1026.86, dur: 4.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_221.mp4" hue="amber" darken={0} clipDur={15.1} /> },
  { key: "cultivosep_s_223", start: 1038.44, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_223.mp4" hue="amber" darken={0} clipDur={23.71} /> },
  { key: "cultivosep_s_224", start: 1041.5, dur: 4.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_224.mp4" hue="amber" darken={0} clipDur={6.46} /> },
  { key: "cultivosep_s_226", start: 1053.02, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_226.mp4" hue="amber" darken={0} clipDur={24.61} /> },
  { key: "cultivosep_s_228", start: 1060.12, dur: 6.86, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_228.mp4" hue="amber" darken={0} clipDur={28.13} /> },
  { key: "cultivosep_s_230", start: 1069.74, dur: 2.88, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_230.mp4" hue="amber" darken={0} clipDur={44.38} /> },
  { key: "cultivosep_s_231", start: 1072.32, dur: 3.3, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_231.mp4" hue="amber" darken={0} clipDur={31.53} /> },
  { key: "cultivosep_s_234", start: 1088.18, dur: 5.64, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_234.mp4" hue="amber" darken={0} clipDur={10.44} /> },
  { key: "cultivosep_s_235", start: 1093.52, dur: 3.58, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_235.mp4" hue="amber" darken={0} clipDur={10.16} /> },
  { key: "cultivosep_s_237", start: 1103.28, dur: 3.12, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_237.mp4" hue="amber" darken={0} clipDur={10.16} /> },
  { key: "cultivosep_s_238", start: 1106.1, dur: 3.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_238.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_239", start: 1108.82, dur: 2.92, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_239.mp4" hue="amber" darken={0} clipDur={13.08} /> },
  { key: "cultivosep_s_240", start: 1111.44, dur: 3.5, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_240.mp4" hue="amber" darken={0} clipDur={30.42} /> },
  { key: "cultivosep_s_241", start: 1114.64, dur: 6.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_241.mp4" hue="amber" darken={0} clipDur={8.27} /> },
  { key: "cultivosep_s_242", start: 1120.52, dur: 4.32, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_242.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_243", start: 1124.54, dur: 3.36, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_243.mp4" hue="amber" darken={0} clipDur={2.67} /> },
  { key: "cultivosep_s_244", start: 1127.6, dur: 4.7, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_244.mp4" hue="amber" darken={0} clipDur={16.77} /> },
  { key: "cultivosep_s_246", start: 1139.36, dur: 6.56, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_246.mp4" hue="amber" darken={0} clipDur={13.01} /> },
  { key: "cultivosep_s_247", start: 1145.62, dur: 6.18, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_247.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_249", start: 1155.22, dur: 5.06, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_249.mp4" hue="amber" darken={0} clipDur={14} /> },
  { key: "cultivosep_s_250", start: 1159.98, dur: 5.02, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_250.mp4" hue="amber" darken={0} clipDur={10.88} /> },
  { key: "cultivosep_s_251", start: 1164.7, dur: 4.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_251.mp4" hue="amber" darken={0} clipDur={18.48} /> },
  { key: "cultivosep_s_252", start: 1168.68, dur: 4.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_252.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_253", start: 1172.82, dur: 5.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_253.mp4" hue="amber" darken={0} clipDur={26.63} /> },
  { key: "cultivosep_s_255", start: 1181.36, dur: 4.2, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_255.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_256", start: 1185.26, dur: 3.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_256.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_257", start: 1188.34, dur: 3.84, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_257.mp4" hue="amber" darken={0} clipDur={7.46} /> },
  { key: "cultivosep_s_258", start: 1191.88, dur: 5.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_258.mp4" hue="amber" darken={0} clipDur={8.04} /> },
  { key: "cultivosep_s_260", start: 1199.54, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_260.mp4" hue="amber" darken={0} clipDur={12.72} /> },
  { key: "cultivosep_s_261", start: 1203.28, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_261.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_262", start: 1207.02, dur: 5.44, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_262.mp4" hue="amber" darken={0} clipDur={13.77} /> },
  { key: "cultivosep_s_263", start: 1212.16, dur: 3.76, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_263.mp4" hue="amber" darken={0} clipDur={7.28} /> },
  { key: "cultivosep_s_264", start: 1215.62, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_264.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_268", start: 1229.52, dur: 5.66, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_268.mp4" hue="amber" darken={0} clipDur={14.21} /> },
  { key: "cultivosep_s_269", start: 1234.88, dur: 4.48, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_269.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_270", start: 1239.06, dur: 4.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_270.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_271", start: 1243.18, dur: 4.94, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_271.mp4" hue="amber" darken={0} clipDur={24.84} /> },
  { key: "cultivosep_s_272", start: 1247.82, dur: 6.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_272.mp4" hue="amber" darken={0} clipDur={15.28} /> },
  { key: "cultivosep_s_273", start: 1253.68, dur: 3.08, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_273.mp4" hue="amber" darken={0} clipDur={9.3} /> },
  { key: "cultivosep_s_274", start: 1256.46, dur: 6.42, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_274.mp4" hue="amber" darken={0} clipDur={15.72} /> },
  { key: "cultivosep_s_275", start: 1262.58, dur: 4.04, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_275.mp4" hue="amber" darken={0} clipDur={21.88} /> },
  { key: "cultivosep_s_276", start: 1266.32, dur: 3.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_276.mp4" hue="amber" darken={0} clipDur={13.01} /> },
  { key: "cultivosep_s_278", start: 1273.04, dur: 5.9, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_278.mp4" hue="amber" darken={0} clipDur={7.92} /> },
  { key: "cultivosep_s_279", start: 1278.64, dur: 3.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_279.mp4" hue="amber" darken={0} clipDur={12.08} /> },
  { key: "cultivosep_s_280", start: 1282.08, dur: 4.38, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_280.mp4" hue="amber" darken={0} clipDur={18.96} /> },
  { key: "cultivosep_s_281", start: 1286.16, dur: 2.78, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_281.mp4" hue="amber" darken={0} clipDur={16.92} /> },
  { key: "cultivosep_s_283", start: 1294.18, dur: 3.34, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_283.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_284", start: 1297.22, dur: 3.24, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_284.mp4" hue="amber" darken={0} clipDur={14.96} /> },
  { key: "cultivosep_s_285", start: 1300.16, dur: 3.28, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_285.mp4" hue="amber" darken={0} clipDur={22.92} /> },
  { key: "cultivosep_s_286", start: 1303.14, dur: 5.62, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_286.jpg" hue="amber" darken={0} /> },
  { key: "cultivosep_s_287", start: 1308.46, dur: 4.26, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_287.mp4" hue="amber" darken={0} clipDur={12.25} /> },
  { key: "cultivosep_s_288", start: 1312.42, dur: 4.14, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_288.mp4" hue="amber" darken={0} clipDur={22.53} /> },
  { key: "cultivosep_s_289", start: 1316.26, dur: 3.8, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_289.mp4" hue="amber" darken={0} clipDur={7.44} /> },
  { key: "cultivosep_s_290", start: 1319.76, dur: 4.74, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_290.mp4" hue="amber" darken={0} clipDur={5.28} /> },
  { key: "cultivosep_s_291", start: 1324.2, dur: 3.16, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_291.mp4" hue="amber" darken={0} clipDur={8.96} /> },
  { key: "cultivosep_s_292", start: 1327.06, dur: 1.54, kind: "raw", el: (d) => <RawShot durationInFrames={d} src="broll/cultivosep/s_292.mp4" hue="amber" darken={0} clipDur={15.28} /> },
];

export const REFRAME: { start: number; end: number }[] = [];

export const OVERLAYS: Cue[] = [
  { key: "ov_highlightsweep_13", start: 13.36, dur: 4.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><HighlightSweep durationInFrames={d} theme={THEME_EARTH} {...({"pre":"Comés de tu huerta hasta marzo,","highlight":"sin invernadero","post":".","note":"con la tierra dura de frío"} as any)} /></PremiumOverlay> },
  { key: "ov_highlightsweep_31", start: 30.7, dur: 4.6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="top" theme={THEME_EARTH}><HighlightSweep durationInFrames={d} theme={THEME_EARTH} {...({"pre":"Para estos cinco cultivos,","highlight":"el frío los hace mejores","post":".","note":""} as any)} /></PremiumOverlay> },
  { key: "ov_bigstatreveal_40", start: 40.44, dur: 5.2, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><BigStatReveal durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El error que casi nadie evita","value":90,"suffix":" %","support":"hacen todo bien y no cosechan casi nada — y no es por el frío"} as any)} /></PremiumOverlay> },
  { key: "ov_duelcolumns_892", start: 891.94, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><DuelColumns durationInFrames={d} theme={THEME_EARTH} {...({"title":"Quién gana con que te olvides","leftName":"La góndola en invierno","rightName":"Tu huerta viva","rows":[{"attr":"Verdura de miles de km","leftWins":true},{"attr":"En plástico, medio mustia","leftWins":true},{"attr":"Pagás cada semana","leftWins":true},{"attr":"Gratis, en tu patio","leftWins":false}]} as any)} /></PremiumOverlay> },
  { key: "ov_pullquote_938", start: 938.44, dur: 5.4, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><PullQuote durationInFrames={d} theme={THEME_EARTH} {...({"quote":"Cuando algo que la naturaleza hace gratis te lo venden en veinticinco productos, ahí hay gato encerrado."} as any)} /></PremiumOverlay> },
  { key: "ov_checklistreveal_1111", start: 1111.44, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><ChecklistReveal durationInFrames={d} theme={THEME_EARTH} {...({"title":"Lo que esto NO hace","items":["No da tomates ni pimientos en invierno","En el frío profundo casi no crece: cosechás","En zonas muy duras: una manta de vellón"],"stamp":"SIN MENTIRAS"} as any)} /></PremiumOverlay> },
  { key: "ov_numberedsteps_1173", start: 1173.4, dur: 7, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="left" theme={THEME_EARTH}><NumberedSteps durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"Esta semana de septiembre","title":"Los cinco, a la tierra","steps":[{"title":"Col rizada y acelga","sub":"hoja todo el invierno, cortá de afuera"},{"title":"Zanahoria bajo paja","sub":"la tierra es la heladera"},{"title":"Puerro en pie","sub":"aporcá el tallo"},{"title":"Ajo: un diente → una cabeza","sub":"el único que no podés plantar más tarde"}]} as any)} /></PremiumOverlay> },
  { key: "ov_ctacard_1263", start: 1262.58, dur: 6, kind: "premium", el: (d) => <PremiumOverlay durationInFrames={d} zone="topLeft" theme={THEME_EARTH}><CtaCard durationInFrames={d} theme={THEME_EARTH} {...({"eyebrow":"El suelo es la mitad de la batalla","title":"La guía del abono de $3","bullet":"cómo preparo el bancal antes de sembrar esto — link en la descripción","price":0,"cta":"LINK EN LA DESCRIPCIÓN"} as any)} /></PremiumOverlay> },
];

// cama de música (AudioBed) — null si el beatsheet no define "music"
export const AUDIO_BED: { src: string; activity: [number, number][]; base: number; duck: number; totalSec: number; loop: boolean } | null = null;

// riel de SFX suaves (SfxRail) — [] si "sfx": false
export const SFX_CUES: { at: number; role: string; vol?: number }[] = [{"at":13.36,"role":"popUp","vol":0.32},{"at":30.7,"role":"popUp","vol":0.32},{"at":40.44,"role":"popUp","vol":0.32},{"at":189.54,"role":"popUp","vol":0.32},{"at":235.18,"role":"popUp","vol":0.32},{"at":341.3,"role":"popUp","vol":0.32},{"at":464.52,"role":"popUp","vol":0.32},{"at":513.28,"role":"popUp","vol":0.32},{"at":605.02,"role":"popUp","vol":0.32},{"at":710.58,"role":"popUp","vol":0.32},{"at":778.7,"role":"popUp","vol":0.32},{"at":891.94,"role":"popUp","vol":0.32},{"at":938.44,"role":"popUp","vol":0.32},{"at":981.36,"role":"popUp","vol":0.32},{"at":1111.44,"role":"popUp","vol":0.32},{"at":1173.4,"role":"popUp","vol":0.32},{"at":1262.58,"role":"popUp","vol":0.32}];
