// DIRECTOR B — extras, luz, lo de una sola vez, la cinta del año, los huevos mes a mes, la división, por gallina, las 3 viejas (p17-36)
import { S, BI, HZP, COOP, YARD, BARN, KITCHEN, STORE, HENS, PULLETS } from "./dir_lib.mjs";
const TABLE = "a worn wooden farmhouse kitchen table with a checked oilcloth";
export const YEAR = [{ item: "layer feed x22", amt: "420.00" }, { item: "shavings & straw", amt: "132.00" }, { item: "shell, scratch, meds", amt: "66.00" }, { item: "heated base + power", amt: "80.00" }, { item: "wire + camera", amt: "100.00" }, { item: "4 pullets", amt: "80.00" }];
export const SHOTS = [
  S(17, "", "bi", "b_oyster", { p: BI(`Inside ${COOP.split(":")[0]}: a small paper sack of crushed white oyster shell and a paper sack of scratch grains standing on a wooden shelf, a small plain white medicine bottle beside them.`), anim: "a little shell grit trickles from the sack" }),
  S(17, "Scratch grains, which are a treat", "st", "st_scratch.1"),
  S(17, "And a bottle of amprolium", "c", "OpLedger", { props: { title: "the extras", rows: [{ item: "oyster shell", price: "$16" }, { item: "scratch grains", price: "$30" }, { item: "amprolium", price: "$20" }], total: "$66", totalLabel: "Extras", every: 30, bed: "st_feed.4" } }),
  S(18, "", "bi", "b_heatedbase", { p: BI(`${COOP} in winter: a galvanized chicken waterer sitting on a round metal heated base with its electric cord running to an outlet, the water open and steaming slightly while frost covers the window.`), anim: "a thin wisp of steam rises from the water" }),
  S(18, "Mine finally quit in December", "bi", "b_deadbase", { p: BI(`${COOP} on a frozen December morning: a galvanized waterer on an old rusty heated base, the water inside frozen solid into a thick ice disk, a hen pecking at the ice.`), anim: "the hen pecks at the frozen water" }),
  S(18, "and a new one was fifty-five dollars", "c", "OpLedger", { props: { title: "keeping the water open", rows: [{ item: "new heated base", price: "$55" }, { item: "electricity, winter", price: "$25" }], total: "$80", totalLabel: "Winter water", every: 40, bed: "st_snow.2" } }),
  S(19, "", "av", "av"),
  S(19, "I bought a roll of hardware cloth", "bi", "b_hardware", { p: BI("The side of a red wooden chicken coop with white trim: a vent freshly covered with half inch galvanized hardware cloth screwed on with screws and washers, the roll of wire on the ground below.") , anim: "light moves across the shiny new wire" }),
  S(19, "and a trail camera, forty", "bi", "b_trailcam", { p: BI("A small camouflage trail camera strapped to a wooden fence post with a nylon strap, pointed at the side of a red chicken coop, autumn leaves on the ground.") , anim: "the little red light on the camera blinks" }),
  S(19, "And the four buff pullets", "st", "st_buff.1"),
  S(19, "Eighty dollars", "av", "av"),
  // ── EL AÑO ENTERO
  S(20, "", "c", "OpTape", { props: { rows: YEAR, total: "$878.00", totalLabel: "TOTAL", every: 72, title: "one year, every receipt", bed: "b_tablebed2" } }),
  S(21, "", "hz", "h_calendar", { p: HZP("She runs her pencil down the day squares of a paper wall calendar by the back door, counting, reading glasses on her nose.", KITCHEN) }),
  S(21, "Two thousand four hundred and twelve eggs", "bi", "b_eggbaskets", { p: BI(`On ${TABLE}: many wire baskets and bowls piled high with brown and speckled eggs, egg cartons stacked beside them, window light.`), anim: "an egg rolls slightly in the full basket" }),
  S(21, "That's two hundred and one dozen", "st", "st_cartons.1"),
  S(22, "", "av", "av"),
  S(22, "A dozen a week goes to my sister", "st", "st_cartons.2"),
  S(22, "for the funeral dinners", "bi", "b_church", { p: BI("A small country church fellowship hall kitchen with long counters, a few cartons of brown eggs set on the counter next to big casserole dishes and a coffee urn.") , anim: "steam rises slowly from the coffee urn" }),
  S(22, "Cracked eggs, the ones the hens stepped on", "bi", "b_cracked", { p: BI(`Close view in a straw nest box: two brown eggs with cracked shells, one a little crushed, next to whole eggs, a hen's foot at the edge of the frame.`), anim: "the hen's foot shifts in the straw" }),
  S(22, "because I fed them back to the girls scrambled", "bi", "b_scrambled", { p: BI(`${YARD}: a shallow pan of cooked scrambled eggs set on the ground, ${HENS} crowding around it pecking eagerly.`), anim: "the hens peck at the scrambled eggs" }),
  S(22, "An egg is an egg", "av", "av"),
  S(23, "", "av", "av"),
  S(23, "I didn't know", "bi", "b_shoebox2", { p: BI(`On ${TABLE}: an old empty shoebox with its lid off, a neat stack of smoothed receipts beside it held with a clothespin, a pencilled page of sums.`), anim: "the edge of the top receipt lifts in a draft" }),
  // ── MES A MES
  S(24, "", "av", "av"),
  S(24, "October, a hundred and thirty-nine", "c", "OpCaseLog", { props: { title: "eggs · Oct to Feb", rows: [{ day: "Oct", n: 139 }, { day: "Nov", n: 96 }, { day: "Dec", n: 74, note: "the low" }, { day: "Jan", n: 88 }, { day: "Feb", n: 152 }], every: 70, max: 316, drop: 2, bed: "b_calendar2" } }),
  S(24, "Then March, two hundred and forty-seven", "c", "OpCaseLog", { props: { title: "eggs · Mar to Sep", rows: [{ day: "Mar", n: 247 }, { day: "Apr", n: 301 }, { day: "May", n: 316, note: "my best" }, { day: "Jun", n: 309 }, { day: "Jul", n: 281 }, { day: "Aug", n: 236 }, { day: "Sep", n: 173 }], every: 70, max: 316, bed: "b_calendar3" } }),
  S(25, "", "av", "av"),
  S(25, "A hen needs about fourteen hours", "c", "OpDaylight", { props: { points: [{ m: "Jun", h: 15.2 }, { m: "Aug", h: 14.1 }, { m: "Oct", h: 11.5 }, { m: "Dec", h: 9.4 }], steady: 14, slow: 12, mark: 3, title: "Indiana daylight" } }),
  S(25, "I don't put a light in my coop", "st", "st_coop.2"),
  S(25, "I let them rest", "st", "st_roost.1"),
  S(25, "But it means my December eggs", "av", "av"),
  S(25, "December, with all that winter feed", "c", "OpSignCard", { props: { bed: "st_snow.3", see: "a December dozen", means: "almost $12", ok: false } }),
  S(25, "And May, with the girls out on the grass", "c", "OpSignCard", { props: { bed: "st_grass.3", see: "a May dozen", means: "about $1.35", ok: true } }),
  S(26, "", "av", "av"),
  S(26, "A spring number and a winter number", "st", "st_eggs.4"),
  // ── LA DIVISIÓN
  S(27, "", "c", "OpTape", { props: { rows: [{ item: "the whole year", amt: "878.00" }], total: "$878.00", totalLabel: "TOTAL", divide: { by: "201 dozen", result: "$4.37" }, every: 22, bed: "b_tablebed3" } }),
  S(28, "", "av", "av"),
  S(28, "The wire, the camera, the new waterer base", "bi", "b_onetime", { p: BI(`On a barn workbench: a roll of hardware cloth, a small camouflage trail camera, a boxed heated waterer base and an empty cardboard pullet box, laid out together.`), anim: "light through the barn boards slides across the workbench" }),
  S(28, "the pullets", "st", "st_buff.2"),
  S(28, "it comes down to six hundred and forty-three dollars", "c", "OpTape", { props: { rows: [{ item: "all of it", amt: "878.00" }, { item: "wire + camera", amt: "-100.00" }, { item: "heated base", amt: "-55.00" }, { item: "4 pullets", amt: "-80.00" }], total: "$643.00", totalLabel: "REAL COST", divide: { by: "201 dozen", result: "$3.20" }, every: 20, bed: "b_tablebed4" } }),
  S(28, "Still not cheap", "av", "av"),
  S(29, "", "av", "av"),
  S(29, "is about seventy-three dollars a hen", "c", "OpLedger", { props: { title: "per hen, per year", rows: [{ item: "with everything", price: "$73" }, { item: "without one-time things", price: "$54" }], total: "about $1 a week", totalLabel: "Each hen", every: 70, bed: "st_hens.4" } }),
  S(29, "If you're thinking about getting chickens", "st", "st_chicks.1"),
  S(29, "About a dollar a week, each", "av", "av"),
  // ── QUIÉN PONE
  S(30, "", "av", "av"),
  S(30, "The buff girls lay a light brown one", "bi", "b_threeeggs", { p: BI(`Three eggs side by side on ${TABLE}: a light tan brown egg, a big dark chocolate brown egg, and a small speckled brown egg, an older woman's finger pointing at the speckled one.`), anim: "her finger taps the speckled egg" }),
  S(30, "and Clover's are a little speckled", "bi", "b_speckled", { p: BI("Close view of a single brown egg covered in small dark speckles held up between an older woman's fingers in the light of a coop door.") , anim: "she turns the speckled egg slowly" }),
  S(31, "", "bi", "b_dottiemolt", { p: BI(`${YARD}: a reddish-brown hen in heavy molt, patchy and ragged with bare spots on her neck and back, loose feathers on the ground around her, pecking calmly.`), anim: "a loose feather falls from the molting hen as she pecks" }),
  S(31, "She started her molt", "av", "av"),
  S(31, "From the middle of September", "st", "st_feathers.1"),
  S(31, "She's putting everything she eats", "bi", "b_pinfeathers", { p: BI("Close view of the neck of a molting reddish-brown hen with new pin feathers coming in like little quills, an older woman's fingers parting the feathers gently.") , anim: "the hen shifts as the fingers part her feathers" }),
  S(31, "But for those weeks", "st", "st_hens.10"),
  S(31, "and that's part of the price too", "av", "av"),
  // ── LAS TRES VIEJAS
  S(32, "", "bi", "b_oldhens", { p: BI(`${COOP}: three old hens with faded feathers and pale combs sitting together on the lowest roost, one reddish-brown, one black, one speckled, late afternoon light.`), anim: "the three old hens settle closer together on the roost" }),
  S(32, "Between the three of them", "c", "OpLedger", { props: { title: "Mabel, Rosie & Pansy", rows: [{ item: "eggs, all year", price: "41" }, { item: "feed, 1/4 lb a day each", price: "~$105" }], total: "$30 a dozen", totalLabel: "That's", every: 80, bed: "b_oldhensbed" } }),
  S(32, "A quarter pound a day each", "bi", "b_quarterpound", { p: BI("A kitchen scale on a feed bin lid with a small metal cup holding a quarter pound of layer feed pellets, the paper feed sack behind it in a barn.") , anim: "a few pellets settle in the cup on the scale" }),
  S(33, "", "c", "OpSignCard", { props: { bed: "st_feed.5", see: "41 eggs for $105 of feed", means: "a $30 dozen", ok: false } }),
  S(34, "And I know a lot of folks do that", "av", "av"),
  S(34, "But Mabel was the first hen", "hz", "h_mabel", { p: HZP("She sits on the coop step holding an old faded reddish-brown hen in her lap, stroking its back, a soft sad smile.", COOP) }),
  S(34, "Rosie is the one who follows me", "bi", "b_clothesline", { p: BI(`A farmyard clothesline with white sheets hanging in the sun, an older woman's legs and apron hem at the basket, an old black hen standing right at her feet following her.`), anim: "the sheets sway in the breeze and the hen steps closer" }),
  S(34, "And Pansy will sit in my lap", "hz", "h_lap", { p: HZP("She sits in an old wooden porch chair with a speckled old hen settled calmly in her lap like a cat, her hand resting on it, smiling.", YARD) }),
  S(34, "They're staying", "av", "av"),
  S(35, "", "av", "av"),
  S(35, "I fried it for my breakfast", "bi", "b_friedegg", { p: BI("A single small fried egg with a bright orange yolk in an old black cast iron skillet on a farmhouse stove, a cup of coffee beside it, morning window light.") , anim: "the egg white sizzles at the edges" }),
  S(35, "it was the best thirty dollar egg", "av", "av"),
  S(36, "", "st", "st_sunrise.1"),
];
