// DIRECTOR C — lo que intentan (caza, carne, cosecha nocturna, cercos), la Big Island, Molokai/Lanai, el mundo,
// consejos al visitante, el cierre con el ranchero, CTA (p29-46)
import { S, BI, HZP, ROAD, RANCH, FARM, COAST, FOREST, AXIS } from "./dir_lib.mjs";
export const SHOTS = [
  S(29, "", "av", "av"),
  S(30, "", "st", "st_hunter.1"),
  S(30, "Some ranches hire professional shooters at night", "bi", "b_nightcrew", { p: BI(`${RANCH.split(":")[0]} at night: a pickup truck with a small trailer parked in a dark pasture, two men in dark jackets with headlamps and thermal scopes standing by it.`), anim: "the headlamps sweep across the pasture" }),
  S(31, "", "av", "av"),
  S(31, "process the meat properly, and sell the venison", "bi", "b_market", { p: BI("A small Maui farmers market stall under a white tent with a cooler of wrapped venison packages, a handwritten sign, a customer paying, palm trees behind."), anim: "the customer takes a package and smiles" }),
  S(31, "some of it goes to food banks", "st", "st_foodbank.1"),
  S(31, "we'd call that good common sense", "av", "av"),
  S(32, "", "bi", "b_trailer", { p: BI("The open back of a refrigerated trailer at night on a Maui ranch, white interior lights, stainless steel racks, a worker in a white coat and gloves checking a clipboard."), anim: "the worker checks the clipboard" }),
  S(32, "By sunrise, the crew was gone", "st", "st_sunrise.1"),
  S(33, "", "av", "av"),
  S(33, "Inside the fence, the plants can grow back", "c", "HkFenceSplit", { props: { inside: "inside the fence", outside: "outside", title: "same mountain, one fence", bgIn: "img/hankaxis/b_inside.jpg", bgOut: "img/hankaxis/b_outside.jpg" } }),
  S(33, "If you fly over some of these places", "bi", "b_aerialfence", { p: BI("An aerial drone view of a mountainside in Maui with a straight fence line running through it: dense green native forest on one side, brown bare grazed slope on the other."), anim: "the drone glides along the fence line" }),
  S(34, "", "hz", "h_fence", { p: HZP("He walks along a tall wire fence through a misty native forest next to a woman in a field shirt and boots carrying fencing pliers, both talking.", FOREST) }),
  S(34, "there were little native trees coming back", "bi", "b_seedlings", { p: BI(`${FOREST.split(":")[0]}: small native tree seedlings and ferns sprouting thickly on the ground inside a wire fence, misty light, a small wooden marker.`), anim: "mist drifts over the seedlings" }),
  S(34, "It's finding the one spot where a tree fell on it", "bi", "b_brokenfence", { p: BI("A tall wire fence in a misty Maui forest crushed flat by a fallen tree trunk, a gap in the wire, deer tracks in the mud going through it."), anim: "a drop of water falls from the bent wire" }),
  S(34, "So she walks it, mile after mile", "st", "st_forest.2"),
  S(35, "", "av", "av"),
  S(35, "everybody down there drinks the water", "st", "st_waterfall.1"),
  S(35, "So yes, Hank. It's worth it", "av", "av"),
  // ── BIG ISLAND
  S(36, "", "av", "av"),
  S(36, "somebody snuck axis deer onto the Big Island", "bi", "b_helicopter", { p: BI("A small helicopter flying low over green ranch land on the Big Island of Hawaii at dusk, the Mauna Kea slope behind."), anim: "the helicopter flies across the frame" }),
  S(37, "", "c", "DocHighlighter", { props: { source: "Hawaii state law · moving deer between islands", lines: ["~", "No person shall transport, release, or", "possess axis deer on any island", "where they are not established,", "~", "without permission of the state.", "~"], highlight: "transport, release", kicker: "a serious crime" } }),
  S(37, "put out cameras, and asked people to report", "c", "TrailCam", { props: { src: "img/hankaxis/b_trailcam.jpg", stamp: "02:47 AM", temp: "61°F", night: true } }),
  S(37, "it's Maui all over again, only bigger", "av", "av"),
  S(38, "", "st", "st_island.2"),
  S(38, "On Lanai, hunting the deer has become a big part", "bi", "b_lanai", { p: BI("A dry red-dirt landscape on Lanai, Hawaii, with a hunter in an orange cap and his young son looking through binoculars from the back of an old pickup truck, spotted deer far away."), anim: "the boy lowers the binoculars and points" }),
  S(38, "you can see it on the hillsides", "av", "av"),
  S(39, "", "av", "av"),
  S(39, "Some in Texas, some in Australia", "st", "st_deer.4"),
  S(39, "the animal didn't stop where they wanted it to", "av", "av"),
  S(40, "", "av", "av"),
  S(40, "Drive slow at dusk and at night", "st", "st_road.3"),
  S(40, "if you're on the Big Island and you see a spotted deer", "bi", "b_phonephoto", { p: BI("A person's hand holding a smartphone up to take a picture of a single spotted deer standing at the edge of a pasture on the Big Island of Hawaii, the phone screen showing the deer."), anim: "the phone screen flashes as the photo is taken" }),
  // ── CIERRE
  S(41, "", "av", "av"),
  S(41, "The trouble is, people put them somewhere", "st", "st_deer.5"),
  S(42, "", "bi", "b_trucknight", { p: BI(`${RANCH.split(":")[0]} at night: an old pickup truck parked at the edge of a dark pasture with its lights off, the faint shapes of many deer grazing beyond the fence under the stars.`), anim: "a deer's eyes catch faint light in the dark" }),
  S(42, "I just wish somebody a long time ago had thought it through", "av", "av"),
  S(43, "", "bi", "b_doe", { p: BI("A doe axis deer standing frozen in the middle of a dark two-lane mountain road in Maui, lit by car headlights, three more deer and a fawn stepping out of the brush behind her."), anim: "the doe stares and the fawn steps out behind her" }),
  S(43, "If I'd been going any faster", "av", "av"),
  S(44, "", "av", "av"),
  S(44, "swamp rats in Louisiana, iguanas in Florida", "c", "FieldNote", { props: { lines: ["nutria · Louisiana", "iguanas · Florida", "urchins · California", "axis deer · Maui"], bed: "st_ocean.3" } }),
  S(44, "it never stays the size of the idea", "av", "av"),
  S(45, "", "av", "av", { ov: { c: "ElAsk", props: { question: "What animal took over where you live?" } } }),
  S(45, "And if you want to come along, subscribe", "av", "av2", { ov: { c: "ElSubscribe", props: { line: "next: Colorado's wolves" } } }),
  S(46, "", "av", "av"),
  // AUTO cortes
  S(0, "Maui Hawaii it's", "st", "st_deer.6"),
  S(0, "and I want", "st", "st_ranch.1"),
  S(0, "are axis deer", "av", "av"),
  S(0, "animals reddish brown", "st", "st_deer.7"),
  S(0, "a fawn that", "st", "st_ranch.2"),
  S(0, "nobody knows exactly", "av", "av"),
  S(0, "say tens of", "st", "st_deer.8"),
  S(0, "at night with", "st", "st_ranch.3"),
  S(1, "deer we have", "av", "av"),
  S(1, "side and they", "st", "st_deer.9"),
  S(1, "bed Kind of", "st", "st_ranch.4"),
  S(2, "a couple of", "av", "av"),
  S(4, "every direction For", "st", "st_ocean.4"),
  S(5, "plants don't have", "st", "st_forest.3"),
  S(11, "back home in", "av", "av"),
  S(11, "And there's no", "st", "st_deer.10"),
  S(11, "here say happened", "st", "st_road.4"),
  S(12, "in the brush", "av", "av"),
  S(12, "in the dark", "st", "st_ranch.5"),
  S(14, "fence like it's", "st", "st_deer.11"),
  S(15, "you Car crashes", "av", "av"),
  S(16, "In fields on", "st", "st_drought.2"),
  S(17, "size in the", "st", "st_ranch.6"),
  S(18, "this story so", "av", "av"),
  S(19, "back home He", "st", "st_drought.3"),
  S(22, "So a deer", "st", "st_forest.4"),
  S(23, "so clear you", "av", "av"),
  S(24, "some of them", "st", "st_reef.3"),
  S(24, "from somewhere else", "st", "st_forest.5"),
  S(25, "hunting grounds Hunters", "av", "av"),
  S(27, "His grandfather hunted", "st", "st_hunter.2"),
  S(27, "a good deer", "st", "st_deer.12"),
  S(27, "the mainland think", "av", "av"),
  S(31, "of it goes", "st", "st_ranch.7"),
  S(32, "It's quiet it's", "st", "st_sunrise.2"),
  S(32, "truck and a", "av", "av"),
  S(32, "cold and inspected", "av", "av"),
  S(32, "few hours do", "st", "st_sunrise.3"),
  S(34, "She's been building", "av", "av"),
  S(34, "names some of", "st", "st_forest.6"),
  S(34, "deer tracks everywhere", "st", "st_waterfall.2"),
  S(34, "because one gap", "av", "av"),
  S(35, "is what catches", "st", "st_forest.7"),
  S(36, "Hawaii didn't have", "st", "st_road.5"),
  S(36, "were flown over", "av", "av"),
  S(38, "were let loose", "st", "st_island.3"),
  S(38, "identity So on", "st", "st_road.6"),
  S(38, "more or less", "av", "av"),
  S(39, "idea A pretty", "st", "st_island.4"),
  S(40, "ranch land If", "st", "st_road.7"),
  S(40, "almost always more", "av", "av"),
  S(40, "That one phone", "st", "st_island.5"),
  S(41, "One gift to", "st", "st_sunrise.4"),
  S(41, "an island is", "av", "av"),
  S(41, "scientists the people", "av", "av"),
  S(42, "in his truck", "st", "st_sunrise.5"),
  S(42, "the dark Hundreds", "av", "av"),
  S(42, "anything for a", "av", "av"),
  S(43, "My second night", "av", "av"),
  S(43, "stepped right out", "av", "av"),
  S(43, "slid a little", "av", "av"),
  S(43, "and a fawn", "av", "av"),
];
export const BEDS = [
  { name: "b_inside", p: BI(`${FOREST.split(":")[0]}: thick green native undergrowth, ferns and young ohia trees inside a fenced area, morning mist.`) },
  { name: "b_outside", p: BI("A bare brown grazed hillside in Maui with patches of dirt, a few dry grass tufts and deer tracks, under the same misty morning light.") },
  { name: "b_trailcam", p: BI("A black and white night trail camera photo of a single spotted deer walking through grass on a ranch on the Big Island of Hawaii, the deer's eyes glowing.") },
];
