// DIRECTOR de olcast — «NEVER Season Cast Iron the Store Way Again — The Old Camp Cook's Trick»
// S(p, frase, kind, name, opts): p = párrafo del guion filmado · frase = palabras donde CORTA (contiguas, dentro del párrafo)
// kind: av (avatar InfiniteTalk) · vl (hablado agnes 2.5) · st (stock Pexels REAL: name = s_* → stock_pick.json)
//       ar (archivo REAL dominio público: name = a_* → ar_pick.json) · ole (foto gpt con Ole, /edits) · bi (foto gpt sin Ole)
//       c (componente) · opts: { p: prompt, anim: movimiento agnes v2 (mano/objeto SIN cara), props, ov: overlay {c, props} }
import { S, BI, CAMP, OLEP } from "./dir_lib.mjs";
const CI = "a heavy black cast iron skillet"; // el objeto firma
export const SHOTS = [
  // ══ MINUTO 1 (≥20 cortes, ninguna toma >4 s, Ole HABLANDO desde el cuadro 0) ══
  S(0, "", "vl", "m1"),
  S(0, "an old gate", "bi", "b_rustmacro", { p: BI(`Extreme close view of the orange rust flecks and dull brown crust along the rim of an old cast iron skillet on a rough plank table, an old man's thumb dragging across the rust, the log wall behind. Old hands only, no face.`), anim: "the thumb slowly drags across the rusty rim" }),
  S(0, "in a cupboard", "st", "s_cupboard"),
  S(0, "Give", "vl", "m2"),
  S(0, "and this pan goes from", "c", "OlcPanRescue3D", { props: { teaser: true } }),
  S(0, "No kit", "bi", "b_kitjunk", { p: BI(`A kitchen counter with a store-bought cast iron seasoning kit: a small plain tin of seasoning wax paste, a spray can with a blank label, a bottle of flaxseed-looking oil and a box, all with blank packaging, next to a dull gray skillet, a dish towel, nobody in frame.`), anim: "the camera hardly moves, a dish towel corner flutters" }),
  S(0, "no fancy oil", "vl", "m2"),
  S(0, "Just one wipe", "vl", "m3"),
  S(0, "and most folks", "bi", "b_wipeback", { p: BI(`Close view of an old hand smearing a big shiny wet layer of oil over the inside of a cast iron skillet with a wadded paper towel, the pan glistening with a thick oily sheen, oil dripping down the edge onto the counter. Hand and sleeve only, no face.`), anim: "the paper towel smears the oil around the pan" }),
  S(1, "", "vl", "m3"),
  S(1, "why your eggs stick", "bi", "b_eggstuck", { p: BI(`Close view of two fried eggs stuck to the bottom of a cast iron skillet, torn ragged with brown crust left behind, a metal spatula stuck under one egg, on a wood stove top, nobody in frame.`), anim: "the spatula pushes and the egg stays stuck and tears" }),
  S(1, "why your pan turns gummy", "bi", "b_gummy", { p: BI(`Close view into a black cast iron skillet whose surface is sticky and blotchy, brown tacky patches with fingerprints pressed into them, shiny wet gummy spots catching the window light, on a plank table.`), anim: "a fingertip presses into the gummy surface and lifts" }),
  S(1, "and the little step", "ar", "a_cooks"),
  S(1, "Well now", "vl", "m4"),
  S(2, "The store way", "vl", "m4"),
  S(2, "Rub a good coat", "bi", "b_oilpour", { p: BI(`Close view of golden cooking oil being poured from a plain glass bottle into the middle of a black cast iron skillet, a thick pool spreading, on a wooden table. Old hand holding the bottle only.`), anim: "the oil pours in a steady glossy stream into the pan" }),
  S(2, "nice and shiny", "bi", "b_shiny", { p: BI(`A black cast iron skillet shining wet and glossy all over with a thick coat of oil, the window reflected in it, drips running down the outside walls, on a rack ready to go in the oven.`), anim: "an oil drip slowly runs down the outside of the pan" }),
  S(2, "stick it in the oven", "st", "s_ovendoor"),
  S(2, "and call it seasoned", "vl", "m5"),
  S(2, "Then it goes tacky", "bi", "b_tacky", { p: BI(`Close view of a fingertip pressing on a cast iron skillet's cooking surface and lifting off with a sticky, tacky pull, the surface a dull blotchy brown, a dish towel beside it.`), anim: "the finger lifts and pulls a little sticky thread" }),
  S(2, "Then it flakes off", "bi", "b_flakes", { p: BI(`Close view of a golden cornbread slice on a plate with little black flakes of burnt seasoning scattered over its crumb and a black flake stuck on the fork, a black cast iron skillet behind it on the table.`), anim: "a black flake drops from the fork onto the cornbread" }),
  S(2, "You scrub it", "vl", "m5"),
  S(2, "and you get the same mess", "bi", "b_thickmess", { p: BI(`Close view of a scrubbing brush and a steel scrubber on a cast iron skillet in a sink, black sticky gunk and flakes coming off, dirty gray water, the surface still blotchy and thick and uneven.`), anim: "the brush scrubs and gray gunk swirls in the water" }),
  // ══ CTA (una vez) ══
  S(3, "", "av", ""),
  S(3, "It's a cookbook now", "c", "OleCTA", { props: { cover: "img/ole/portada.png", qr: "qr_ole_olcast.png", kicker: "THE WHOLE METHOD, WRITTEN DOWN", point: "Point your phone here", line: "50 old camp recipes" } }),
  // ══ CIENCIA ══
  S(4, "", "av", ""),
  S(4, "It's oil that got cooked", "st", "s_oilpan"),
  S(4, "The fancy word", "bi", "b_blackglass", { p: BI(`Close view of the cooking surface of a well-seasoned black cast iron skillet: smooth, deep black and satin, a window reflected softly in it, a single drop of water beading on it, on a plank table, no hands.`), anim: "the drop of water slowly rolls across the black surface" }),
  S(5, "", "c", "OlcPanCross3D", { props: { mode: "seasoning", events: { pits: 3.2, layers: [8.4, 10.4, 12.4, 14.1], thick: 16.2 } } }),
  S(6, "", "av", ""),
  S(6, "It puts on one thick coat", "c", "OlcPanCross3D", { props: { mode: "thick", events: { thick: 0.4, soft: 4.0 } } }),
  S(6, "like a puddle", "c", "OlcStoreVsCamp", { props: { flipAt: 3.2 } }),
  S(6, "And I'll tell you", "av", ""),
  // ══ EL TRUCO: UNA PASADA Y LIMPIAR ══
  S(7, "", "vl", "m6"),
  S(7, "Step two", "bi", "b_dropsoil", { p: BI(`Close view of a few drops of oil being dripped from a plain bottle onto a folded white paper towel held in an old hand over a cast iron skillet, only a few drops, the towel barely damp.`), anim: "three drops of oil fall onto the paper towel" }),
  S(7, "and rub it over", "st", "s_rubpan"),
  S(7, "Step three", "vl", "m7"),
  S(7, "like you made a mistake", "bi", "b_wipeoff", { p: BI(`Close view of a clean dry paper towel wiping firmly across the inside of a cast iron skillet, taking almost all the oil off, the towel darkened with oil, the pan surface turning matte and nearly dry.`), anim: "the towel wipes hard across the pan, sheen disappears" }),
  S(7, "and you're hiding the evidence", "ole", "o_hiding", { p: OLEP(`He glances sideways over his shoulder toward the door with a sly little grin, holding a crumpled oily paper towel behind his back in one hand and a black cast iron skillet in the other, as if hiding evidence.`) }),
  S(7, "When you're done", "bi", "b_drypan", { p: BI(`A black cast iron skillet on a wooden table looking nearly dry and matte, only a faint even satin sheen, no puddles, a crumpled oily paper towel beside it, window light.`), anim: "hardly any movement, a faint shift of window light across the pan" }),
  S(7, "If you can see shine", "bi", "b_shine", { p: BI(`Close view of an old hand tilting a cast iron skillet toward the window so a bright streak of shine shows on the surface and a folded paper towel is about to wipe it again.`), anim: "the pan tilts and the streak of shine slides across it" }),
  // ══ ACEITE / PUNTO DE HUMO ══
  S(8, "", "st", "s_oilbottle"),
  S(8, "Canola or ordinary", "bi", "b_canola", { p: BI(`Two plain cheap bottles of canola oil and vegetable oil with blank labels on an ordinary kitchen shelf beside a cast iron skillet and a paper towel roll, a hand taking one down.`), anim: "the hand lifts a bottle off the shelf" }),
  S(8, "What matters is", "st", "s_smokepan"),
  S(8, "Butter for instance", "c", "OlcSmokeLadder", { props: { at: [0.3, 4.3, 5.9, 8.9], ovenAt: 11.5 } }),
  // ══ HORNO ══
  S(9, "", "c", "OlcOvenStack", { props: { tUp: 1.5, tFoil: 4.4, tDial: 8.4, tHour: 11.0, tOff: 12.7 } }),
  S(9, "And if your smoke alarm", "bi", "b_smokealarm", { p: BI(`A white ceiling smoke alarm with its red light on and a thin wisp of gray smoke drifting under it in an ordinary kitchen, an open window and a small fan turning nearby, a skillet on the oven rack visible below.`), anim: "the wisp of smoke drifts along the ceiling" }),
  S(10, "", "c", "OlcLayerCount", { props: { } }),
  // ══ SE TERMINA EN LA COCINA ══
  S(11, "", "av", ""),
  S(11, "Fry bacon in it", "st", "s_bacon"),
  S(11, "Fry sausage", "st", "s_sausage"),
  S(11, "Fry a mess of potatoes", "st", "s_hashbrowns"),
  S(11, "Every time fat", "bi", "b_layerbuild", { p: BI(`Close view of hot bacon fat pooling shiny and clear in a black cast iron skillet on a wood stove, a little smoke, bacon strips at the edge, the fat forming a glossy thin film as the pan tilts, old hand on the handle.`), anim: "the fat shimmers and a wisp of smoke rises" }),
  S(11, "A camp cook never", "ar", "a_kitchen"),
  S(11, "the pan seasoned itself", "st", "s_potatocamp"),
  S(12, "", "c", "OleBookPage", { props: { src: "img/olcast/addon_p3.png", aspect: 1469 / 1901, label: "A PAGE FROM THE BOOK'S CAST IRON ADD-ON", keys: [[0, 0.5, 0.5, 1], [1.4, 0.34, 0.2, 2.2], [4.4, 0.55, 0.27, 2.5], [6.7, 0.55, 0.27, 2.5], [7.5, 0.5, 0.345, 2.6], [8.4, 0.4, 0.385, 2.7], [10.0, 0.5, 0.45, 1.1]], marks: [{ t: 1.8, x0: 0.076, y0: 0.192, x1: 0.565, y1: 0.192 }, { t: 6.8, x0: 0.4, y0: 0.282, x1: 0.84, y1: 0.282 }, { t: 7.6, x0: 0.1, y0: 0.338, x1: 0.62, y1: 0.338 }, { t: 8.5, x0: 0.07, y0: 0.396, x1: 0.62, y1: 0.396 }] } }),
  // ══ LA SEGUNDA RAZÓN: EL FUEGO ══
  S(13, "", "av", ""),
  S(13, "Most folks crank", "st", "s_highburner"),
  S(13, "That sound is not a sear", "bi", "b_stucksupper", { p: BI(`Close view of a pork chop welded to the bottom of a very hot cast iron skillet on a gas burner on high, smoke curling, a metal spatula bent under it and the crust torn off in the pan, kitchen dim behind.`), anim: "smoke curls up while the spatula digs at the stuck chop" }),
  S(14, "", "st", "s_griddle"),
  S(14, "Crank it to high", "c", "OlcHeatMap", { props: { tHigh: 0.1, tMed: 7.1, tWait: 9.2, tFat: 13.0, tShimmer: 15.7 } }),
  S(15, "", "vl", "m8"),
  S(15, "If they gather into", "c", "OlcFlick", { props: { readyAt: 0.6 } }),
  S(16, "", "bi", "b_nonstick", { p: BI(`A scratched worn-out nonstick frying pan with a peeling gray coating on a kitchen counter next to a black cast iron skillet, an old hand holding a small dab of butter on a knife over the nonstick.`), anim: "the knife lowers a bit of butter toward the pan" }),
  S(16, "in iron than you think", "st", "s_oilpour"),
  S(16, "And there's one mistake", "av", ""),
  // ══ EL MERCADO DE PULGAS ══
  S(17, "", "st", "s_fleamarket"),
  S(17, "Everybody's walked past one", "ar", "a_flea"),
  S(17, "thought that's garbage", "bi", "b_rustpanmarket", { p: BI(`A rusty cast iron skillet lying among mismatched dishes, old tools and jars on a folding table at an outdoor flea market on a sunny morning, a handwritten paper price tag tied to the handle, a browsing man's arm at the edge of the frame.`), anim: "the browsing man's hand reaches in and lifts the rusty pan" }),
  S(17, "best deal", "bi", "b_bargain", { p: BI(`An old hand holding up a rusty but thick, sound cast iron skillet toward the light between the stalls of a flea market, checking it, the orange rust obvious on the cooking surface.`), anim: "the hand turns the pan in the light" }),
  S(18, "", "bi", "b_checkbuy", { p: BI(`Close view of a man's hand turning a rusty cast iron skillet over to inspect its underside at a flea market stall, other rusty tools and enamel pots on the folding table behind, bright morning daylight, checking the pan carefully. Hand and sleeve only, no face.`), anim: "the hand turns the pan over slowly to look at its bottom" }),
  S(18, "Set it on a flat", "c", "OlcRustCheck", { props: { tStamp: 5.2 } }),
  S(18, "Tap the rim", "bi", "b_knuckle", { p: BI(`Extreme close view of a knuckle tapping the rim of a cast iron skillet held up by the handle in a flea market stall, the pan hanging free, an old hand only.`), anim: "the knuckle taps the rim and the pan swings slightly" }),
  S(18, "Run your finger", "st", "s_rustclose"),
  S(18, "But if you can feel real holes", "bi", "b_pitted", { p: BI(`Extreme close view of deeply pitted rusty cast iron with small craters and holes in the cooking surface, a fingertip resting at the edge of a crater, harsh light.`), anim: "the fingertip slides slowly over the pitted surface" }),
  S(18, "There's always another pan", "av", ""),
  // ══ RESCATE ══
  S(19, "", "st", "s_scrub"),
  S(19, "Start gentle", "c", "OlcPanRescue3D", { props: { tScrub: 1.0, tGray: 7.2, tBlack: 999 } }),
  S(19, "soak the pan in half white vinegar", "bi", "b_vinegar", { p: BI(`A rusty cast iron skillet lying submerged in a plastic wash tub of clear liquid, a bottle of white vinegar and a measuring cup beside it on a garage workbench, a kitchen timer set on the bench.`), anim: "small bubbles rise slowly from the submerged pan" }),
  S(19, "Vinegar is an acid", "st", "s_vinegar"),
  S(19, "Wear gloves", "bi", "b_gloves", { p: BI(`Close view of hands in yellow rubber gloves lifting a gray-orange cast iron skillet out of a tub of vinegar water and setting it on a towel, drips falling.`), anim: "the gloved hands lift the pan and drips fall" }),
  S(20, "", "st", "s_dryburner"),
  S(20, "because bare iron", "bi", "b_rustagain", { p: BI(`Extreme close view of bare gray cast iron with fresh orange flash-rust spots blooming on its surface, a drop of water beside them, dish towel edge, harsh window light, no hands.`), anim: "hardly any movement, a faint shift of window light" }),
  S(20, "Once it's bare", "c", "OlcPanRescue3D", { props: { startGray: true, tBlack: 3.0 } }),
  // ══ EL ERROR DE DIEZ SEGUNDOS ══
  S(21, "", "bi", "b_shockcrack", { p: BI(`Steam exploding upward as cold water is poured from a pitcher into a very hot cast iron skillet on a wood stove, a hairline crack visible on the pan's wall, the pitcher and a hand at the top edge of the frame.`), anim: "the water hits the pan and steam bursts up" }),
  S(21, "Pour cold water", "ole", "o_shock", { p: OLEP(`He winces and pulls back with his hand raised, looking at a steaming black cast iron skillet on the wood stove in front of him, a small pitcher of water beside it on the stove shelf, concerned expression.`), ov: { c: "OleStamp", props: { text: "NEVER", sub: "cold water on a hot pan", at: 0.6 } } }),
  S(21, "And don't ever put one", "bi", "b_selfclean", { p: BI(`The front of a modern wall oven with its digital display glowing and a heavy black cast iron skillet visible through the dark glass door, the door latch locked, kitchen counter in front, nobody in frame.`), anim: "the oven's display light blinks once" }),
  S(21, "That cycle gets hot", "st", "s_hotoven"),
  // ══ LIMPIEZA ══
  S(22, "", "st", "s_cleanintro"),
  S(22, "While the pan's still warm", "st", "s_washpan"),
  S(22, "A little mild dish soap", "bi", "b_soap", { p: BI(`Close view of a sponge with a drop of dish soap scrubbing the inside of a black seasoned cast iron skillet in a sink under running warm water, soapy bubbles, the seasoning staying deep black and intact.`), anim: "the sponge scrubs and bubbles form" }),
  S(22, "For stuck food", "bi", "b_simmer", { p: BI(`A cast iron skillet on a stove burner with half an inch of gently simmering water in it, bits of stuck food loosening from the bottom, a flat metal scraper resting on the rim.`), anim: "the water simmers with small bubbles" }),
  S(23, "", "av", ""),
  S(23, "Dry it completely", "st", "s_dryburner2"),
  S(23, "Rub in a thin film", "bi", "b_thinoil", { p: BI(`Close view of an old hand rubbing a thin film of oil into a warm just-dried black cast iron skillet with a paper towel, the surface turning satin, faint wisps of warmth.`), anim: "the paper towel rubs a thin film across the warm pan" }),
  S(23, "Never let it soak", "bi", "b_sinksoak", { p: BI(`A black cast iron skillet sitting in a sink full of gray dishwater with soapy dishes around it, the pan half submerged, rust-orange streaks beginning at the rim, nobody in frame.`), anim: "the dishwater ripples slightly", ov: { c: "OleStamp", props: { text: "NEVER", sub: "soak it", at: 0.4, x: 0.24, y: 0.26 } } }),
  S(23, "Never put it in the dishwasher", "bi", "b_dishwasher", { p: BI(`The open door of a dishwasher with a cast iron skillet on the lower rack among plates, with rusty orange marks on it, steam rising from the machine, kitchen counter beside it.`), anim: "steam drifts up out of the dishwasher", ov: { c: "OleStamp", props: { text: "NEVER", sub: "the dishwasher", at: 0.4, x: 0.24, y: 0.26 } } }),
  // ══ DUTCH OVEN Y BRASAS ══
  S(24, "", "c", "OleDutchOven3D", { props: { on: "coals", states: [{ at: 0, mode: "still" }], lidCracked: false, label: "A CAMP DUTCH OVEN" } }),
  S(24, "If you've got", "ar", "a_stove"),
  S(24, "Store it with", "bi", "b_papertowel", { p: CAMP(`A black cast iron Dutch oven on the plank table with a folded paper towel sticking out between the pot and its lid, a hand about to set the lid down on it.`), anim: "the lid settles down on the paper towel" }),
  S(25, "", "c", "OlcBriquette", { props: { tMeasure: 1.6, tDouble: 4.3, tLid: 9.1, tUnder: 11.1, tHeat: 13.6, tTurn: 99 } }),
  S(25, "It's a starting point", "ar", "a_crew1"),
  S(25, "Wind cold", "av", ""),
  S(25, "old coals", "st", "s_oldcoals"),
  S(25, "so check your food", "av", ""),
  S(25, "Lift the lid", "st", "s_dutchfire"),
  S(26, "", "av", "", { ov: { c: "OleStamp", props: { text: "OUTDOORS ONLY", sub: "coals make carbon monoxide", at: 1.2 } } }),
  S(26, "Coals and camp fires", "st", "s_campskillet"),
  S(26, "Cook outside", "ar", "a_campfire"),
  S(26, "Charcoal makes", "st", "s_charcoalsmoke"),
  S(26, "keep a bucket of water", "bi", "b_bucketwater", { p: BI(`Outdoors at a fire ring: a galvanized metal bucket of water and a shovel leaning beside a cast iron Dutch oven on coals, dirt ground, grass well away from the fire, dusk light.`), anim: "the bucket water ripples and the coals glow" }),
  S(26, "spread the coals", "st", "s_embers"),
  // ══ PRIMERAS SEMANAS / ARREGLOS ══
  S(27, "", "av", ""),
  S(27, "A new coat is tender", "ar", "a_kitchen75"),
  S(27, "Cook fatty", "st", "s_cornbread"),
  S(27, "Hold off on long", "c", "OlcFirstWeeks", { props: { okAt: 8.4 } }),
  S(28, "", "c", "OlcFixTable", { props: { rows: [{ problem: "STICKY OR GUMMY", cause: "too much oil", fix: "bake upside down, 450–500°F, 1 hr · still tacky? scrub it back and go thinner", at: 0.4 }, { problem: "FLAKING BLACK BITS", cause: "thick coat baked on", fix: "scrape it off · re-season in thin coats", at: 13.0 }, { problem: "FOOD STICKS", cause: "pan too cold going in", fix: "preheat longer · add a little fat", at: 21.2 }] } }),
  // ══ TAREA PARA ESTA NOCHE ══
  S(29, "", "vl", "m9"),
  S(29, "Starting cold", "st", "s_baconcold"),
  S(29, "Fry your eggs", "st", "s_eggs"),
  S(29, "If they slide", "ar", "a_cookmess"),
  S(29, "If they grab", "av", ""),
  S(29, "Either way", "c", "OlcHomework", { props: { } }),
  // ══ CIERRE ══
  S(30, "", "av", ""),
  S(30, "Thin coats", "c", "OlcRecap", { props: { } }),
  S(30, "That's the whole thing", "ar", "a_cookwait"),
  S(30, "A pan you treat like that", "ar", "a_skillets"),
  S(31, "", "av", "", { ov: { c: "OleCTA", props: { compact: true, cover: "img/ole/portada.png", qr: "qr_ole_olcast.png", text: "The cookbook's link is in the description" } } }),
  S(31, "Now tell me", "av", "", { ov: { c: "OleAsk", props: { text: "What's the oldest pan in your kitchen?", sub: "and who did it come from? tell me in the comments" } } }),
];
