// S3 (226–326s) — LA REGLA DE LOS 500 DALTON. Objetivo: derribar el mito de la crema con un número.
export default [
  ["y ahora te voy a dar el numero", "a plain pen resting on a page of handwritten figures on a desk"],
  ["que es el unico numero aburrido", "an open notebook with a single number written large on the page, plain desk"],
  ["que te va a ahorrar miles de pesos", "a small pile of mexican peso notes held together with an elastic band on a table"],
  ["en dermatologia hay una regla", "a thick medical textbook lying open on a desk under a plain lamp"],
  ["que se publico formalmente en el ano 2000", "a stack of old scientific journals with faded spines on a shelf"],
  ["por dos investigadores holandeses", "two lab coats hanging on hooks beside a plain office door"],
  ["se le llama la regla de los 500 dalton", "a small kitchen scale with nothing on the tray, standing on a counter"],
  ["el dalton es simplemente la unidad", "a set of small brass weights lined up beside a balance scale on a table"],
  ["como los gramos pero para cosas diminutas", "the tiny numbers on the dial of an old weighing scale, extreme close view"],
  ["para que una molecula pueda atravesar", "a narrow gap under a closed door with light coming through"],
  ["la piel sana y llegar hasta abajo", "extreme close view of the surface of skin, tight and unbroken"],
  ["tiene que pesar menos de 500 dalton", "a doorway with a low measuring bar across it, like a fairground height limit"],
  ["mas pesada que eso no pasa", "a heavy wooden crate standing in front of a narrow doorway, blocked"],
  ["se queda arriba punto", "a small object resting on top of a closed flat surface, going no further"],
  ["por eso los parches de nicotina si funcionan", "a small beige adhesive patch stuck on the upper arm of a person, plain background"],
  ["la nicotina pesa como 160", "a single small weight sitting on the tray of a balance scale"],
  ["pasa facil se cuela", "a thin coin slipping through a narrow slot"],
  ["cuanto pesa una molecula de colageno", "a large heavy iron weight standing alone on a plain concrete floor"],
  ["300 mil dalton", "an enormous iron weight sitting on a bent balance scale on a plain floor"],
  ["o sea 600 veces mas pesada", "a huge stone block beside a tiny pebble on flat bare ground"],
  ["es como querer meter un refrigerador", "a large white refrigerator standing on a pavement in front of a plain wall"],
  ["por la ranura de un buzon", "a small metal letterbox slot set into a plain painted wall, close view"],
  ["y no es que lo empujes con mas ganas", "two hands pushing hard against the side of a large refrigerator on a pavement"],
  ["es que no cabe", "a refrigerator standing beside a narrow letterbox slot, both in the same frame"],
  ["la ranura mide lo que mide", "extreme close view of a narrow letterbox slot, the metal flap slightly open"],
  ["entonces cuando tu te pones esa crema", "a woman's fingers scooping white cream from an open jar on a bathroom shelf"],
  ["el colageno se queda arriba", "a thick layer of white cream sitting on the surface of skin, not absorbed, close view"],
  ["encima de la capa de celulas muertas", "extreme close view of white cream resting on dry flaky skin"],
  ["forma una pelicula que retiene agua", "a thin film of water beading on a smooth surface, close view"],
  ["y una piel hidratada se ve mejor", "close view of a woman's cheek looking smooth and slightly damp, plain daylight"],
  ["pero es maquillaje humedo", "a smear of white cream wiped across a bathroom mirror"],
  ["te lavas la cara y se fue", "water running over a pair of hands in a plain bathroom sink"],
  ["ese colageno no bajo a la dermis", "a closed cosmetic jar standing on a bathroom shelf, plain tile behind"],
  ["estaba impedido por el tamano", "a refrigerator on the pavement beside a narrow wall slot, seen from further back"],
];
