// cues_cmesodimac.gen.tsx — GENERADO por build_cmesodimac.mjs. NO editar a mano.
import React from "react";
import { Clip, Foto, IconoNum } from "./Piezas";
import { MovAdentro } from "./MovAdentro";
import { MovAngulo } from "./MovAngulo";
import { MovBateria } from "./MovBateria";
import { MovCaja } from "./MovCaja";
import { MovCalor } from "./MovCalor";
import { MovCierre } from "./MovCierre";
import { MovDia } from "./MovDia";
import { MovEntra } from "./MovEntra";
import { MovEscalones } from "./MovEscalones";
import { MovFactura } from "./MovFactura";
import { MovGiro } from "./MovGiro";
import { MovGuia } from "./MovGuia";
import { MovHeladera } from "./MovHeladera";
import { MovInversor } from "./MovInversor";
import { MovPeligro } from "./MovPeligro";
import { MovRegulador } from "./MovRegulador";
import { MovTrato } from "./MovTrato";

export type Cue = { key: string; start: number; dur: number; capa: "base" | "over"; el: (frame: number) => React.ReactNode };

export const CUES_CMESODIMAC: Cue[] = [
  { key: "mv_MovCaja", start: 95, dur: 1560, capa: "base", el: (frame: number) => <MovCaja acto={0} gFrame={frame - 95} /> },
  { key: "m000", start: 1658, dur: 135, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s1_letra_chica.jpg" seed={1658} /> },
  { key: "m001", start: 1825, dur: 107, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s1_pinza_cerca.mp4" /> },
  { key: "m002", start: 1932, dur: 90, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_pinza.png" texto={"47 VATIOS"} /> },
  { key: "m003", start: 2014, dur: 135, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s1_dos_maderas.mp4" /> },
  { key: "m005", start: 2378, dur: 150, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s1_panel_techo.mp4" /> },
  { key: "mv_MovTrato", start: 2645, dur: 1322, capa: "base", el: (frame: number) => <MovTrato acto={0} gFrame={frame - 2645} /> },
  { key: "m007", start: 3967, dur: 68, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s2_boleta_mano.jpg" seed={3967} /> },
  { key: "m008", start: 4034, dur: 117, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_reloj.png" texto={"MINUTO 3"} /> },
  { key: "mv_MovAdentro", start: 4202, dur: 1740, capa: "base", el: (frame: number) => <MovAdentro acto={0} gFrame={frame - 4202} /> },
  { key: "m009", start: 6010, dur: 150, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s3_manual_abierto.jpg" seed={6010} /> },
  { key: "m010", start: 6164, dur: 117, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s3_manual_flecha.jpg" seed={6164} /> },
  { key: "m011", start: 6281, dur: 62, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s3_caja_vacia.mp4" /> },
  { key: "m012", start: 6343, dur: 90, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_bateria.png" texto={"NO VIENE"} /> },
  { key: "m013", start: 6398, dur: 90, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_inversor.png" texto={"NO VIENE"} /> },
  { key: "m014", start: 6452, dur: 90, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_regla.png" texto={"NO VIENE"} /> },
  { key: "m015", start: 6562, dur: 105, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_breaker.png" texto={"NI UN FUSIBLE"} /> },
  { key: "m016", start: 6683, dur: 150, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s3_claudio_senala.mp4" /> },
  { key: "m018", start: 6976, dur: 84, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s3_panel_solo.mp4" /> },
  { key: "m019", start: 7060, dur: 135, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s3_sol_en_vidrio.mp4" /> },
  { key: "m020", start: 7214, dur: 80, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s3_panel_noche.mp4" /> },
  { key: "m022", start: 7354, dur: 126, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s3_lampara_enciende.mp4" /> },
  { key: "m023", start: 7480, dur: 180, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s3_hueco_bateria.jpg" seed={7480} /> },
  { key: "m024", start: 7792, dur: 150, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s3_bateria_muerta.jpg" seed={7792} /> },
  { key: "m025", start: 7990, dur: 120, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s3_cuaderno_lapiz.mp4" /> },
  { key: "m026", start: 8122, dur: 150, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s3_panel_plano.mp4" /> },
  { key: "m027", start: 8302, dur: 135, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s3_techo_arriba.jpg" seed={8302} /> },
  { key: "m028", start: 8473, dur: 85, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s3_pinza_41.mp4" /> },
  { key: "m029", start: 8558, dur: 150, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s3_tester_174.mp4" /> },
  { key: "m030", start: 8837, dur: 120, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_calculadora.png" texto={"71 VATIOS"} /> },
  { key: "m031", start: 8897, dur: 135, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s3_resta.jpg" seed={8897} /> },
  { key: "mv_MovAngulo", start: 9115, dur: 925, capa: "base", el: (frame: number) => <MovAngulo acto={0} gFrame={frame - 9115} /> },
  { key: "mv_MovCalor", start: 10040, dur: 1440, capa: "base", el: (frame: number) => <MovCalor acto={0} gFrame={frame - 10040} /> },
  { key: "m032", start: 11516, dur: 69, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s4_53_cuaderno.jpg" seed={11516} /> },
  { key: "mv_MovRegulador", start: 11585, dur: 1860, capa: "base", el: (frame: number) => <MovRegulador acto={0} gFrame={frame - 11585} /> },
  { key: "m034", start: 13540, dur: 80, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s5_polvo_vidrio.mp4" /> },
  { key: "m035", start: 13620, dur: 135, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s5_etiqueta_panel.jpg" seed={13620} /> },
  { key: "m036", start: 13820, dur: 141, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s5_cuatro_numeros.jpg" seed={13820} /> },
  { key: "m037", start: 13961, dur: 108, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s5_manual_letra.mp4" /> },
  { key: "m038", start: 14069, dur: 150, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s5_tapa_otra_vez.jpg" seed={14069} /> },
  { key: "m039", start: 14408, dur: 87, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s5_sol_recorre.mp4" /> },
  { key: "m040", start: 14495, dur: 74, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s5_noche_casa.jpg" seed={14495} /> },
  { key: "mv_MovDia", start: 14569, dur: 1253, capa: "base", el: (frame: number) => <MovDia acto={0} gFrame={frame - 14569} /> },
  { key: "mv_MovHeladera", start: 15822, dur: 1680, capa: "base", el: (frame: number) => <MovHeladera acto={0} gFrame={frame - 15822} /> },
  { key: "m041", start: 17561, dur: 150, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s6_refri_cerrado.mp4" /> },
  { key: "m042", start: 17770, dur: 93, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s6_vendedor.jpg" seed={17770} /> },
  { key: "m043", start: 17863, dur: 141, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s6_panel_galpon.mp4" /> },
  { key: "mv_MovEntra", start: 18077, dur: 1740, capa: "base", el: (frame: number) => <MovEntra acto={0} gFrame={frame - 18077} /> },
  { key: "m045", start: 19880, dur: 105, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_pava.png" texto={"1.500 W"} /> },
  { key: "m046", start: 19954, dur: 105, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_calentador.png" texto={"1.000 W"} /> },
  { key: "m047", start: 20011, dur: 105, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_aire.png" texto={"AFUERA"} /> },
  { key: "m048", start: 20316, dur: 68, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s7_router_foco.mp4" /> },
  { key: "mv_MovFactura", start: 20460, dur: 1620, capa: "base", el: (frame: number) => <MovFactura acto={0} gFrame={frame - 20460} /> },
  { key: "m050", start: 22086, dur: 135, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s8_mppt_caja.jpg" seed={22086} /> },
  { key: "m051", start: 22333, dur: 81, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s8_billetes_bolsillo.mp4" /> },
  { key: "m052", start: 22414, dur: 72, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s8_cambiar_foco.mp4" /> },
  { key: "m053", start: 22486, dur: 120, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_calendario.png" texto={"5 MESES"} /> },
  { key: "m054", start: 22576, dur: 150, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s8_giro_luz.mp4" /> },
  { key: "mv_MovGiro", start: 22826, dur: 1680, capa: "base", el: (frame: number) => <MovGiro acto={0} gFrame={frame - 22826} /> },
  { key: "m055", start: 24526, dur: 78, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s9_bateria_polvo.jpg" seed={24526} /> },
  { key: "m056", start: 24604, dur: 75, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s9_camioneta_lona.mp4" /> },
  { key: "m057", start: 24679, dur: 154, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s9_moto_galpon.jpg" seed={24679} /> },
  { key: "m058", start: 24833, dur: 152, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s9_bornes_sulfatados.mp4" /> },
  { key: "m059", start: 24985, dur: 137, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s9_sulfato.jpg" seed={24985} /> },
  { key: "m060", start: 25119, dur: 120, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_billete.png" texto={"$120 A $180"} /> },
  { key: "r00", start: 25122, dur: 135, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s9_bornes_sulfatados.mp4" /> },
  { key: "m061", start: 25240, dur: 120, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_calendario.png" texto={"CADA 2-3 AÑOS"} /> },
  { key: "r01", start: 25257, dur: 129, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s9_sulfato.jpg" seed={25257} /> },
  { key: "r02", start: 25386, dur: 131, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s9_panel_a_bateria.mp4" /> },
  { key: "m063", start: 25517, dur: 326, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s9_cable_capot.jpg" seed={25517} /> },
  { key: "m064", start: 25731, dur: 120, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_pinza.png" texto={"53 W ALCANZAN"} /> },
  { key: "m065", start: 25843, dur: 150, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s9_bateria_nueva.jpg" seed={25843} /> },
  { key: "mv_MovEscalones", start: 25993, dur: 1982, capa: "base", el: (frame: number) => <MovEscalones acto={0} gFrame={frame - 25993} /> },
  { key: "m066", start: 27975, dur: 145, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s10_panel_plano_feo.jpg" seed={27975} /> },
  { key: "m067", start: 28036, dur: 120, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_moneda.png" texto={"ESCALÓN 2 · $34"} /> },
  { key: "m068", start: 28120, dur: 93, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s10_mano_regulador.mp4" /> },
  { key: "m069", start: 28213, dur: 75, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s10_cajita_negra.jpg" seed={28213} /> },
  { key: "m070", start: 28288, dur: 206, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s10_mppt_aletas.mp4" /> },
  { key: "m071", start: 28494, dur: 153, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s10_tester_mppt.mp4" /> },
  { key: "r10", start: 28647, dur: 120, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s10_tester_mppt.mp4" /> },
  { key: "m073", start: 28723, dur: 105, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_rayo.png" texto={"LO TRANSFORMA"} /> },
  { key: "r11", start: 28767, dur: 106, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s10_esquema_mppt.jpg" seed={28767} /> },
  { key: "m074", start: 28873, dur: 152, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s10_mismo_panel.mp4" /> },
  { key: "r20", start: 29025, dur: 138, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s10_dos_paneles.jpg" seed={29025} /> },
  { key: "m075", start: 29037, dur: 135, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_calculadora.png" texto={"68 → 84"} /> },
  { key: "r21", start: 29163, dur: 147, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s10_dos_paneles_techo.mp4" /> },
  { key: "m076", start: 29310, dur: 172, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s10_claudio_serio.jpg" seed={29310} /> },
  { key: "m077", start: 29403, dur: 120, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_billete.png" texto={"$34 = 16 W"} /> },
  { key: "m078", start: 29482, dur: 204, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s10_dos_paneles.jpg" seed={29482} /> },
  { key: "m079", start: 29686, dur: 101, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s10_dos_paneles_techo.mp4" /> },
  { key: "m080", start: 29787, dur: 72, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s10_caja_mppt.jpg" seed={29787} /> },
  { key: "m081", start: 29859, dur: 81, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s10_techo_chico.mp4" /> },
  { key: "m082", start: 29940, dur: 277, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s10_nublado.mp4" /> },
  { key: "m083", start: 30217, dur: 219, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s10_gris_julio.jpg" seed={30217} /> },
  { key: "m084", start: 30436, dur: 178, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s10_bateria_tablon.mp4" /> },
  { key: "mv_MovBateria", start: 30614, dur: 1902, capa: "base", el: (frame: number) => <MovBateria acto={0} gFrame={frame - 30614} /> },
  { key: "m085", start: 32516, dur: 214, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s11_litio_plomo.jpg" seed={32516} /> },
  { key: "m086", start: 32730, dur: 160, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s11_burbujas.mp4" /> },
  { key: "m087", start: 32834, dur: 105, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_billete.png" texto={"$100"} /> },
  { key: "m088", start: 32890, dur: 238, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s11_panel_apoyado.mp4" /> },
  { key: "m091", start: 33128, dur: 88, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s11_inversor_sombra.mp4" /> },
  { key: "m092", start: 33216, dur: 248, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s11_inversor_frente.jpg" seed={33216} /> },
  { key: "m093", start: 33464, dur: 207, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s11_inversor_enchufe.mp4" /> },
  { key: "m094", start: 33671, dur: 186, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s11_inversor_caja.jpg" seed={33671} /> },
  { key: "m095", start: 33857, dur: 73, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s11_pinza_inversor.mp4" /> },
  { key: "mv_MovInversor", start: 33930, dur: 1886, capa: "base", el: (frame: number) => <MovInversor acto={0} gFrame={frame - 33930} /> },
  { key: "m096", start: 35691, dur: 105, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_enchufe.png" texto={"APÁGALO"} /> },
  { key: "m097", start: 35816, dur: 72, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s12_interruptor_off.mp4" /> },
  { key: "m098", start: 35888, dur: 150, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s12_borne_cable.mp4" /> },
  { key: "m099", start: 35962, dur: 105, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_bateria.png" texto={"12 V"} /> },
  { key: "m100", start: 36038, dur: 80, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s12_tira_led.mp4" /> },
  { key: "m101", start: 36118, dur: 142, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s12_cargador_auto.jpg" seed={36118} /> },
  { key: "m102", start: 36260, dur: 246, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s12_etiqueta_router.mp4" /> },
  { key: "m103", start: 36506, dur: 208, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s12_fusible_linea.jpg" seed={36506} /> },
  { key: "m104", start: 36574, dur: 105, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_flecha.png" texto={"−15%"} /> },
  { key: "r31", start: 36714, dur: 129, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s12_fusible_linea.jpg" seed={36714} /> },
  { key: "r32", start: 36843, dur: 149, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s12_casa_luces.mp4" /> },
  { key: "m105", start: 36992, dur: 131, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s12_casa_luces.mp4" /> },
  { key: "mv_MovPeligro", start: 37123, dur: 1981, capa: "base", el: (frame: number) => <MovPeligro acto={0} gFrame={frame - 37123} /> },
  { key: "m107", start: 39104, dur: 144, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s13_tapas_abombadas.jpg" seed={39104} /> },
  { key: "m108", start: 39248, dur: 105, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s13_bateria_cajon.mp4" /> },
  { key: "m109", start: 39353, dur: 141, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s13_burbujas_celda.mp4" /> },
  { key: "m111", start: 39494, dur: 88, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s13_bateria_afuera.mp4" /> },
  { key: "m112", start: 39579, dur: 120, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_casa.png" texto={"NUNCA ADENTRO"} /> },
  { key: "r40", start: 39582, dur: 132, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s13_portafusible.mp4" /> },
  { key: "m113", start: 39636, dur: 120, capa: "over", el: (frame: number) => <IconoNum src="img/cmesodimac/cmes_ic_breaker.png" texto={"4 · EL FUSIBLE"} /> },
  { key: "r41", start: 39714, dur: 130, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s13_llave_inglesa.jpg" seed={39714} /> },
  { key: "m114", start: 39844, dur: 269, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s13_portafusible.mp4" /> },
  { key: "m115", start: 40113, dur: 77, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_s13_llave_inglesa.jpg" seed={40113} /> },
  { key: "m116", start: 40190, dur: 243, capa: "base", el: (frame: number) => <Clip src="broll/cmesodimac/cmes_s13_cable_humo.mp4" /> },
  { key: "m117", start: 40433, dur: 66, capa: "base", el: (frame: number) => <Foto src="img/cmesodimac/cmes_lam_cablefusible.jpg" seed={40433} /> },
  { key: "mv_MovCierre", start: 40499, dur: 2289, capa: "base", el: (frame: number) => <MovCierre acto={0} gFrame={frame - 40499} /> },
  { key: "mv_MovGuia", start: 42788, dur: 1493, capa: "base", el: (frame: number) => <MovGuia acto={0} gFrame={frame - 42788} /> },
];
