// author_p2_vki4.mjs — autora los beats de la SEGUNDA MITAD de vki4lqtcboy0
// (platos 16-25 + revelación + recap + carnada + teaser), anclados a las frases
// reales de captions_p2only.json y desplazados por la duración de la parte 1.
//
// Salida: _v3/vki4lqtcboy0_beats_p2.json  (mismo formato que _v3/vki4lqtcboy0_beats.json)
import fs from "fs";

const P1_MS = Math.round(Number(process.argv[2] || 1110480)); // duración exacta de la parte 1
const SLUG = "vki4lqtcboy0";
const START_IDX = 317; // los beats de la parte 1 llegan hasta s_316

// OJO: leemos las captions del audio COMPLETO (parte1+parte2) y nos quedamos con la
// segunda mitad. Así las `phrase` son literalmente las que el build va a buscar —
// si autoráramos sobre captions_p2only.json, la segmentación de whisper podría diferir
// unas palabras y los anclajes fallarían.
const ALL = JSON.parse(fs.readFileSync("public/captions_vki4lqtcboy0.json", "utf8").replace(/^﻿/, ""));
const caps = ALL.filter((c) => c.startMs >= P1_MS).map((c) => ({ ...c, startMs: c.startMs - P1_MS, endMs: c.endMs - P1_MS }));

// ── pools de visuales por sección (t en segundos, relativos a la parte 2) ──
// i = imagen IA (escena de época / gente) · s = stock (comida, objetos, manos)
const S = (desc, q1, q2) => ({ desc, queries: [q1, q2], src: "stock" });
const I = (desc, q1, q2) => ({ desc, queries: [q1, q2], src: "image" });

const SECTIONS = [
  { t: 0, name: "carbonada", pool: [
    I("rustic clay bowl of carbonada stew with beef, pumpkin, corn and peach pieces on a worn wooden table", "carbonada criolla guiso", "beef stew with corn and pumpkin"),
    S("close-up of a thick beef and vegetable stew bubbling slowly in a heavy pot", "guiso de carne hirviendo", "beef stew bubbling in pot"),
    S("hands cutting orange pumpkin into big chunks on a wooden board", "cortar zapallo en trozos", "cutting pumpkin chunks board"),
    S("fresh corn cobs being cut into thick rounds with a knife", "choclo cortado en rodajas", "corn cob cut into rounds"),
    S("sweet potatoes being peeled, orange flesh showing under the skin", "pelar batata", "peeling sweet potato"),
    S("ripe peaches and pears in a bowl, one cut open showing the flesh", "duraznos y peras frescos", "fresh peaches and pears bowl"),
    I("whole hollowed-out pumpkin used as a serving pot, steaming stew inside, on a family table", "zapallo entero relleno de guiso", "hollowed pumpkin filled with stew"),
    I("1950s rural Argentine family table seen from above with a huge steaming pumpkin in the centre", "mesa familiar antigua con zapallo", "vintage family table steaming dish"),
    S("steam rising in the light above a hot dish on a table", "vapor sobre plato caliente", "steam rising over hot dish"),
    S("wooden spoon lifting stew, letting it fall back into the pot", "cuchara de madera revolviendo guiso", "wooden spoon stirring stew"),
    I("close-up of peach slices half-submerged in savoury stew, an unexpected mix", "fruta dentro del guiso", "fruit inside savoury stew"),
    I("grandmother ladling stew from a hollowed pumpkin into a child's bowl in a warm old kitchen", "abuela sirviendo guiso a nieto", "grandmother serving stew to child"),
    S("cast iron pot with a dented lid sitting on glowing embers", "olla de hierro sobre brasas", "cast iron pot on embers"),
    I("humble home-cooked platter that still looks more beautiful than any restaurant dish", "plato casero humilde y hermoso", "rustic homemade dish presentation"),
    S("family hands reaching in over a shared table of food", "manos compartiendo la mesa", "hands sharing food at table"),
    S("simple earthenware plates stacked beside a steaming pot", "platos de barro apilados", "earthenware plates beside pot"),
  ]},
  { t: 49.5, name: "honestidad", pool: [
    I("tired woman in an apron sitting alone for a moment beside a stove that has been on for hours", "mujer cansada en la cocina antigua", "tired woman sitting by old stove"),
    I("worn hands with cracked knuckles resting on a floured kitchen table", "manos gastadas de trabajo", "worn working hands on table"),
    S("clock on a kitchen wall showing hours passing", "reloj de pared de cocina", "kitchen wall clock time passing"),
    I("woman stirring an enormous pot for hours, steam covering her face, 1950s kitchen", "mujer revolviendo olla enorme", "woman stirring huge pot steam"),
    I("empty pantry shelf with only a couple of jars left on it", "despensa casi vacia", "nearly empty pantry shelf"),
    S("a few bones and scraps on a cutting board — everything the family had", "huesos y sobras en la tabla", "bones and scraps cutting board"),
    I("mother serving her children first and keeping the smallest portion for herself", "madre sirviendo a sus hijos primero", "mother serving children first"),
    I("hands washing dishes in a metal basin late at night by lamp light", "lavar platos de noche palangana", "washing dishes basin lamplight"),
    S("kitchen fire burning low, someone feeding it another log", "alimentar el fuego con leña", "feeding wood into kitchen fire"),
    I("black and white style portrait of a hard-working rural housewife of the 1950s", "ama de casa rural antigua retrato", "vintage rural housewife portrait"),
    I("child watching from a doorway while the mother cooks, quiet and patient", "nino mirando a la madre cocinar", "child watching mother cook doorway"),
    S("steam and sweat on a window above a busy stove", "vidrio empanado sobre la cocina", "steamed window above stove"),
    I("plate of humble food placed on the table with real care", "plato humilde servido con carino", "humble plate served with care"),
    I("family sitting down together to eat, everyone quiet and grateful", "familia sentada a comer junta", "family sitting to eat together"),
    S("hands slowly stirring, close-up, the motion of patience", "revolver despacio con paciencia", "hands slowly stirring pot"),
    I("worn wedding ring on a hand that has cooked for decades", "anillo gastado mano trabajadora", "worn ring on working hand"),
    S("last of the daylight going out over a simple kitchen table", "ultima luz sobre mesa de cocina", "last daylight over kitchen table"),
    I("woman untying her apron at the end of a very long day", "mujer sacandose el delantal cansada", "woman untying apron long day"),
    S("cup of tea gone cold and forgotten on the kitchen counter", "taza de te olvidada y fria", "forgotten cold tea cup counter"),
    I("plate kept warm under another plate for someone arriving late", "plato tapado esperando al que llega tarde", "plate kept warm covered late"),
  ]},
  { t: 106.7, name: "chicharrones", pool: [
    S("golden crispy pork cracklings piled in a bowl", "chicharrones dorados crujientes", "crispy pork cracklings bowl"),
    I("rural neighbours gathering in a yard for the day of the pig, everyone helping", "carneada del chancho vecinos", "rural neighbours pig butchering day"),
    S("large iron cauldron over a wood fire outdoors with fat slowly melting", "fuenton de hierro con grasa", "iron cauldron melting fat fire"),
    I("man stirring a huge outdoor cauldron with a long wooden pole", "revolver con vara larga fuenton", "man stirring cauldron long pole"),
    S("pork fat bubbling and rendering in a big pot, close-up", "grasa de cerdo derritiendose", "pork fat rendering close up"),
    S("white rendered lard being poured into a tin can to set", "grasa blanca en lata", "white lard poured into tin"),
    S("skimmer lifting crisp golden pieces out of hot fat", "espumadera sacando chicharrones", "skimmer lifting cracklings from fat"),
    S("cracklings draining on paper, still steaming", "chicharrones escurriendo", "cracklings draining steaming"),
    I("children hovering around the cauldron like puppies waiting for a scrap", "ninos esperando alrededor del fuego", "children waiting around cooking fire"),
    S("coarse salt being sprinkled over hot cracklings by hand", "sal gruesa sobre chicharrones", "salt sprinkled on cracklings"),
    S("thick slice of homemade bread topped with hot cracklings", "pan casero con chicharrones", "homemade bread with cracklings"),
    I("child biting into bread with cracklings, burning their mouth and smiling anyway", "nino comiendo pan con chicharron", "child eating bread cracklings"),
    S("shelf of tin cans full of white lard stored for the year", "latas de grasa guardadas", "tins of lard stored shelf"),
    I("nothing wasted — every part of the animal laid out on a wooden table", "aprovechar todo del animal", "whole animal parts wooden table"),
    S("outdoor wood fire burning strong under a black pot", "fuego de lena bajo la olla", "outdoor wood fire under pot"),
    S("hot fat splattering, tiny droplets in the light", "salpicaduras de grasa caliente", "hot fat splattering droplets"),
    I("neighbours dividing up the meat to take home at the end of the day", "repartir la carne entre vecinos", "neighbours dividing meat portions"),
    S("hands working over a rough outdoor wooden table covered in food", "manos trabajando mesa exterior", "hands working outdoor table food"),
    I("a whole community day of work ending with everyone eating together outdoors", "jornada comunitaria comiendo afuera", "community workday eating outdoors"),
    S("close-up of the crunch — a crackling breaking between fingers", "chicharron crujiente en la mano", "crackling breaking in fingers"),
    I("old tin can of lard sitting on a 1950s kitchen shelf", "lata de grasa en la alacena", "vintage lard tin kitchen shelf"),
    I("smoke from the outdoor fire drifting across a rural yard at midday", "humo del fuego en el patio rural", "smoke drifting rural yard fire"),
  ]},
  { t: 173.8, name: "miedo-grasa", pool: [
    I("modern supermarket shelf lined with identical plastic bottles of refined oil", "gondola de aceites en el super", "supermarket shelf refined oil bottles"),
    S("industrial factory drum of processed cooking oil", "bidon industrial de aceite", "industrial drum cooking oil"),
    I("scary red health warning graphics about fat from an old magazine", "advertencia sobre las grasas", "vintage health warning about fat"),
    S("clear refined oil being poured from a plastic bottle into a pan", "aceite de botella en la sarten", "refined oil poured into pan"),
    I("side by side: a tin of home-rendered lard and a factory bottle of oil", "grasa casera contra aceite de fabrica", "lard tin versus factory oil bottle"),
    S("factory conveyor belt of identical bottles", "linea de produccion botellas", "factory conveyor identical bottles"),
  ]},
  { t: 190.4, name: "cuajada", pool: [
    S("fresh raw milk being poured from a metal pail into a bowl", "leche recien ordenada en balde", "fresh milk poured from pail"),
    S("soft white curds forming and separating in a bowl of milk", "leche cuajando cuajada", "milk curds forming bowl"),
    I("bowl of fresh curd covered with a cloth on a 1950s kitchen shelf", "cuajada tapada con repasador", "curd bowl covered cloth shelf"),
    S("fresh white cheese draining in a cloth, whey dripping", "queso fresco escurriendo en tela", "fresh cheese draining cloth whey"),
    S("soft fresh cheese cut with a knife, crumbling slightly", "queso fresco cortado cuchillo", "soft fresh cheese cut knife"),
    I("plate of fresh curd with sugar sprinkled on top, ready as dessert", "cuajada con azucar de postre", "fresh curd with sugar dessert"),
    S("honey being drizzled over a piece of fresh white cheese", "miel sobre queso fresco", "honey drizzled fresh cheese"),
    I("breakfast table with fresh cheese, salt and bread in an old rural house", "desayuno con quesillo y pan", "rural breakfast fresh cheese bread"),
    S("cheesecloth tied and hanging, dripping slowly into a bowl", "tela colgada goteando suero", "cheesecloth hanging dripping whey"),
    I("only two ingredients on a table: a jug of milk and a clock", "solo leche y tiempo", "jug of milk and clock table"),
    S("modern supermarket yoghurt pots with long ingredient labels", "yogures con etiquetas largas", "supermarket yoghurt long labels"),
    I("hands lifting the cloth off a bowl to reveal set curd", "destapar la cuajada lista", "lifting cloth from set curd"),
    S("close-up of creamy fresh cheese texture", "textura queso fresco cremoso", "creamy fresh cheese texture"),
    I("old enamel jug of milk on a windowsill in the morning light", "jarra de leche en la ventana", "enamel milk jug morning window"),
    I("metal milk pail and a wooden stool in a barn doorway", "balde de leche y banquito en el establo", "milk pail stool barn doorway"),
  ]},
  { t: 235.3, name: "flan", pool: [
    S("classic homemade flan on a plate with dark caramel running down the sides", "flan casero con caramelo", "homemade flan caramel dripping"),
    S("white sugar melting in a metal mould over a flame, turning amber", "azucar derritiendose caramelo", "sugar melting into amber caramel"),
    I("woman swirling a flan mould in the air over the fire to spread the caramel", "mover la flanera sobre el fuego", "woman swirling caramel mould fire"),
    S("dark amber caramel coating the inside of a round mould", "caramelo cubriendo la flanera", "amber caramel coating mould"),
    S("eggs being cracked into a bowl one after another", "romper huevos en un bol", "eggs cracked into bowl"),
    S("milk being poured into beaten eggs and whisked", "batir huevos con leche", "milk poured into beaten eggs"),
    I("flan mould sitting in a tray of hot water inside an old oven", "flan a bano maria en el horno", "flan mould bain marie old oven"),
    S("close-up of caramel bubbling and darkening in the pan", "caramelo burbujeando oscuro", "caramel bubbling darkening"),
    I("family watching as the flan is turned out onto a plate", "familia mirando desmoldar el flan", "family watching flan unmoulded"),
    S("flan being unmoulded with a sharp knock, caramel cascading down", "desmoldar flan cascada caramelo", "flan unmoulded caramel cascade"),
    I("children with huge eyes staring at the dessert arriving at the table", "ninos con ojos enormes ante el postre", "children wide eyes dessert table"),
    S("spoon cutting through a wobbling flan, showing the smooth texture", "cuchara cortando flan tembloroso", "spoon cutting wobbling flan"),
    S("caramel pooling on the plate around the dessert", "caramelo alrededor del flan", "caramel pooling around dessert"),
    I("hands applauding around a family table", "aplausos en la mesa familiar", "hands applauding family table"),
    S("modern instant dessert powder sachet next to a bowl", "sobre de flan instantaneo", "instant dessert powder sachet"),
    I("old metal flan mould, scratched and used for decades", "flanera de metal vieja", "old scratched metal flan mould"),
    S("burnt sugar smoke rising from a pan", "humo del azucar quemada", "burnt sugar smoke rising pan"),
    S("close-up of the glossy top of a finished flan", "superficie brillante del flan", "glossy flan surface close up"),
    I("grandmother proudly carrying the flan to the table with both hands", "abuela llevando el flan a la mesa", "grandmother carrying flan table"),
    I("empty plate with only caramel left, scraped clean", "plato vacio solo caramelo", "empty plate caramel scraped"),
    S("fresh eggs, a jug of milk and sugar lined up before baking", "huevos leche y azucar sobre la mesa", "eggs milk sugar before baking"),
  ]},
  { t: 300.6, name: "torrejas", pool: [
    S("stale bread slices soaking in a bowl of milk", "pan duro remojado en leche", "stale bread soaking milk bowl"),
    S("cinnamon and sugar being stirred into warm milk", "canela y azucar en la leche", "cinnamon sugar stirred milk"),
    S("soaked bread being dipped into beaten egg", "pan pasado por huevo batido", "bread dipped beaten egg"),
    S("bread slices frying golden in a hot pan", "torrejas friendose doradas", "bread slices frying golden pan"),
    S("sugar being sprinkled over hot fried bread", "azucar sobre torrejas calientes", "sugar sprinkled fried bread"),
    I("plate of golden torrijas dusted with cinnamon on a rustic cloth", "plato de torrejas con canela", "plate golden torrijas cinnamon"),
    I("basket of hard leftover bread that would be thrown away today", "canasto de pan duro viejo", "basket of hard stale bread"),
    S("hands squeezing milk out of soaked bread", "escurrir el pan remojado", "hands squeezing soaked bread"),
    I("old cinnamon tin and sugar jar on a wooden shelf", "lata de canela y azucarera", "vintage cinnamon tin sugar jar"),
    S("golden crust close-up with sugar crystals catching the light", "costra dorada con azucar", "golden crust sugar crystals"),
    I("humble dessert made of nothing but yesterday's bread, served with pride", "postre humilde de pan de ayer", "humble dessert yesterday bread"),
    S("frying pan with hot fat and bubbles around the bread", "sarten con grasa caliente pan", "frying pan hot fat bread"),
    I("children queueing with small plates waiting for fried bread", "ninos en fila esperando con el plato", "children queueing plates fried bread"),
  ]},
  { t: 337.1, name: "budin", pool: [
    S("dark moist bread pudding sliced on a plate", "budin de pan en rodajas", "dark bread pudding sliced plate"),
    I("wicker basket of dry bread kept on top of an old refrigerator", "canasto de pan arriba de la heladera", "basket dry bread on old fridge"),
    S("stale bread breaking apart into a bowl of milk", "pan viejo desarmandose en leche", "stale bread breaking into milk"),
    S("hands mashing soaked bread in a large bowl", "aplastar el pan con las manos", "hands mashing soaked bread"),
    S("eggs and sugar being beaten into the bread mixture", "huevo y azucar en la mezcla", "eggs sugar beaten into mixture"),
    S("raisins soaking in a small bowl of liquid", "pasas de uva en remojo", "raisins soaking small bowl"),
    S("lemon zest being grated over a mixing bowl", "ralladura de limon sobre el bol", "lemon zest grated over bowl"),
    S("caramel being swirled to coat the inside of a loaf tin", "caramelo forrando el molde", "caramel coating loaf tin"),
    I("loaf tin of bread pudding going into a hot wood oven", "budin entrando al horno", "bread pudding into hot oven"),
    I("child circling the kitchen asking how much longer", "nino dando vueltas en la cocina", "child circling kitchen waiting"),
    S("dark caramel top of a baked pudding just out of the oven", "budin recien salido del horno", "baked pudding caramel top oven"),
    S("thick slice of bread pudding with raisins visible inside", "tajada de budin con pasas", "bread pudding slice raisins"),
    I("pudding stored in a wooden pantry cupboard, covered with a cloth", "budin guardado en la alacena", "pudding stored pantry cupboard"),
    I("afternoon mate gourd beside a slice of bread pudding", "mate con una tajada de budin", "mate gourd beside pudding slice"),
    S("knife cutting a clean slice from a dense loaf", "cuchillo cortando el budin", "knife cutting dense loaf"),
    S("close-up of moist crumb texture with raisins", "miga humeda con pasas", "moist crumb texture raisins"),
    I("basket of dry bread transformed into a whole week of dessert", "pan seco convertido en postre", "dry bread turned into dessert"),
    S("modern kitchen bin with bread thrown on top of it", "pan tirado a la basura", "bread thrown into kitchen bin"),
    I("1950s kitchen filled with the smell of caramel and baking bread", "cocina antigua con olor a caramelo", "vintage kitchen caramel baking smell"),
    S("hands covering a dish with a cloth to store it", "tapar el budin con un repasador", "hands covering dish with cloth"),
    S("sugar being weighed on an old kitchen scale", "azucar en balanza antigua", "sugar on vintage kitchen scale"),
    I("pattern emerging: three desserts on a table all made from old bread", "tres postres hechos de pan viejo", "three desserts made stale bread"),
    S("steam escaping as a pudding is uncovered", "vapor al destapar el budin", "steam escaping uncovered pudding"),
    S("close-up of raisins plump after soaking", "pasas hinchadas despues del remojo", "plump soaked raisins close up"),
    I("wooden pantry shelf with the week's food carefully stored", "alacena con la comida de la semana", "pantry shelf week food stored"),
    S("a slice of dark pudding lifted onto a small plate", "servir una tajada de budin", "slice of pudding onto plate"),
    S("ladle of milk being poured over a bowl of torn bread", "cucharon de leche sobre el pan roto", "ladle milk over torn bread"),
    I("older woman writing a recipe by hand in a worn notebook", "abuela anotando la receta a mano", "woman writing recipe notebook"),
  ]},
  { t: 421.1, name: "mate-cocido", pool: [
    S("small pot of dark herbal tea boiling on a stove", "mate cocido hirviendo en la olla", "herbal tea boiling small pot"),
    I("glowing ember dropped into a pot of mate cocido to settle it", "brasa dentro del mate cocido", "ember dropped into tea pot"),
    S("loose yerba mate leaves being poured into boiling water", "yerba mate en agua hirviendo", "yerba mate leaves boiling water"),
    S("milk being poured into a dark hot drink, swirling", "chorro de leche en el mate cocido", "milk poured into dark hot drink"),
    S("thick slice of homemade bread spread with lard", "pan casero untado con grasa", "homemade bread spread lard"),
    S("sugar sprinkled over bread with lard", "azucar sobre pan con grasa", "sugar sprinkled bread lard"),
    I("winter morning window covered in frost in an old rural house", "escarcha en la ventana invierno", "frost covered window rural house"),
    I("child holding a hot bowl with both cold hands before school", "nino sosteniendo tazon caliente", "child holding hot bowl cold hands"),
    S("steam rising from a large enamel bowl of hot drink", "vapor de un tazon enlozado", "steam rising enamel bowl drink"),
    I("family breakfast before dawn in a 1950s kitchen, everyone bundled up", "desayuno antes del amanecer familia", "predawn family breakfast vintage"),
    S("homemade jam being spread thickly on bread", "dulce untado en el pan", "jam spread thick on bread"),
    I("worker leaving the house at dawn with a full stomach", "hombre saliendo a trabajar temprano", "worker leaving house at dawn"),
    S("modern coffee machine dispensing into a paper cup", "cafetera moderna vaso de carton", "coffee machine paper cup"),
    I("colourful modern cereal box with an english name on a shelf", "caja de cereal moderna", "modern cereal box shelf"),
    S("empty stomach feeling — a small breakfast box barely touched", "desayuno de caja sin terminar", "small breakfast box untouched"),
    S("old kettle whistling on a wood stove", "pava silbando en la cocina de lena", "kettle whistling wood stove"),
    I("enamel mug of mate cocido on a rough wooden table with bread", "tazon de mate cocido con pan", "enamel mug tea bread table"),
    S("hands warming around a hot cup", "manos calentandose con la taza", "hands warming around hot cup"),
    I("school children walking a dirt road in the cold morning", "ninos yendo a la escuela camino", "children walking dirt road morning"),
    S("close-up of hot liquid poured into a bowl", "servir el liquido caliente", "hot liquid poured into bowl"),
    I("old wood stove with the fire going and a pot on top at dawn", "cocina de lena encendida al alba", "wood stove fire pot dawn"),
    S("thick slice of bread toasting directly on the hot stove top", "tostar el pan sobre la chapa", "bread toasting on stove top"),
    I("frozen dirt road at dawn seen through a kitchen window", "camino helado visto desde la cocina", "frozen road dawn kitchen window"),
  ]},
  { t: 490.4, name: "zapallo", pool: [
    S("big whole pumpkin sitting in a cool dark storage corner", "zapallo guardado en un rincon", "whole pumpkin dark storage corner"),
    S("pumpkin halves roasting in an oven, edges caramelised", "zapallo asado al horno", "roasted pumpkin halves oven"),
    S("roasted pumpkin opening up, sweet and soft inside", "zapallo asado abierto dulce", "roasted pumpkin opening soft"),
    S("sugar sprinkled over hot roasted pumpkin", "azucar sobre zapallo asado", "sugar sprinkled roasted pumpkin"),
    S("cubes of pumpkin candying in thick syrup", "zapallo en almibar en cubos", "pumpkin cubes candying syrup"),
    S("glass jar of pumpkin preserve in syrup on a shelf", "frasco de dulce de zapallo", "jar pumpkin preserve syrup"),
    I("cheap pumpkins piled high at an old street market stall", "zapallos en la feria del pueblo", "pumpkins piled market stall"),
    S("pumpkin being split open with a heavy knife", "partir el zapallo con cuchillo", "pumpkin split heavy knife"),
    I("pantry corner where a pumpkin has been stored for months", "zapallo guardado meses despensa", "pumpkin stored months pantry"),
    S("empanadas being filled with sweet pumpkin mixture", "empanadas rellenas de zapallo", "empanadas filled pumpkin mixture"),
    S("pumpkin seeds and flesh scooped out onto a board", "semillas y pulpa de zapallo", "pumpkin seeds flesh board"),
    I("one humble vegetable turned into three different dishes on a table", "un zapallo tres recetas distintas", "one vegetable three dishes table"),
    S("coins being counted out on a kitchen table", "contar monedas en la mesa", "coins counted kitchen table"),
    S("close-up of bright orange pumpkin flesh texture", "textura naranja del zapallo", "orange pumpkin flesh texture"),
    S("wheelbarrow full of pumpkins brought in from the garden", "carretilla con zapallos de la huerta", "wheelbarrow pumpkins from garden"),
  ]},
  { t: 535.4, name: "pan-casero", pool: [
    S("round loaf of homemade bread with a golden crust on a wooden table", "pan casero redondo dorado", "round homemade bread golden crust"),
    S("flour poured into a volcano shape on a wooden table", "harina en volcan sobre la mesa", "flour volcano wooden table"),
    S("warm water being poured into the well of flour", "agua tibia en el volcan de harina", "warm water poured flour well"),
    S("yeast being dissolved and starting to foam", "levadura despertando espuma", "yeast dissolving foaming"),
    I("hands kneading dough on a table dusted white with flour", "manos amasando en mesa enharinada", "hands kneading floured table"),
    S("dough being folded and pushed, over and over", "amasar la masa una y otra vez", "dough folded pushed kneading"),
    S("smooth elastic dough no longer sticking to the fingers", "masa lisa que no se pega", "smooth elastic dough fingers"),
    I("ball of dough covered with a cloth and a blanket near the stove", "bocha tapada con repasador y manta", "dough covered cloth blanket stove"),
    I("children walking on tiptoe past the rising dough, told to stay quiet", "ninos en puntas de pie por el pan", "children tiptoe quiet rising dough"),
    S("dough visibly rising and doubling in a bowl", "masa leudando y creciendo", "dough rising doubling bowl"),
    I("loaves going into a hot brick oven on a wooden peel", "pan entrando al horno de ladrillo", "loaves into brick oven peel"),
    S("bread baking, crust turning deep golden through the oven door", "pan dorandose en el horno", "bread baking golden oven door"),
    I("whole house filled with the smell of fresh bread, family drawn to the kitchen", "olor a pan recien horneado en la casa", "house smell fresh bread family"),
    S("steaming loaf torn open by hand, never with a knife", "partir el pan con las manos", "loaf torn open by hand steaming"),
    S("close-up of the crackling crust of a fresh loaf", "corteza crujiente del pan", "crackling crust fresh loaf"),
    I("family fighting over the end piece of the loaf", "pelearse por la punta del pan", "family fighting bread end piece"),
    S("bread placed at the centre of a set family table", "pan en el centro de la mesa", "bread centre family table"),
    I("every meal on the table accompanied by homemade bread", "toda comida con pan casero", "every meal with homemade bread"),
    S("hands dusting flour off a wooden board at the end", "sacudir la harina de la tabla", "hands dusting flour board"),
    I("empty floured table where bread used to be made every week", "mesa vacia donde se amasaba", "empty floured table no bread"),
    S("plastic bag of factory sliced bread on a counter", "pan de molde en bolsa plastica", "plastic bag sliced bread counter"),
    I("supermarket bread aisle with identical packaged loaves", "gondola de pan envasado", "supermarket packaged bread aisle"),
    S("old bread tin and rolling pin put away in a cupboard", "utensilios de panaderia guardados", "old bread tin rolling pin cupboard"),
    I("silent kitchen where the weekly bread ritual simply stopped", "cocina donde se dejo de amasar", "silent kitchen bread ritual stopped"),
    S("close-up of soft white crumb inside a torn loaf", "miga blanca del pan casero", "soft white crumb torn loaf"),
    I("grandmother's hands shaping a loaf with practised movements", "manos de abuela formando el pan", "grandmother hands shaping loaf"),
    S("flour floating in a beam of kitchen light", "harina flotando en la luz", "flour floating in light beam"),
    S("dough being punched down after rising", "desinflar la masa leudada", "dough punched down after rising"),
    I("wood-fired brick oven glowing with heat, ready for bread", "horno de ladrillo listo caliente", "brick oven glowing ready bread"),
    S("bread cooling on a rack covered with a cloth", "pan enfriandose tapado", "bread cooling rack cloth"),
    I("weekly ritual: the whole family around the kneading table", "ritual semanal familia amasando", "family around kneading table ritual"),
    S("crumbs left on a wooden board after the loaf is gone", "migas sobre la tabla vacia", "crumbs on empty wooden board"),
    S("hands breaking bread and passing it around", "partir y repartir el pan", "hands breaking passing bread"),
    I("bread as the heart of the table, everything else around it", "el pan corazon de la mesa", "bread heart of the table"),
    S("last slice of homemade bread on a plate", "ultima rodaja de pan casero", "last slice homemade bread"),
    S("blade scoring a cross on top of a risen loaf before baking", "marcar una cruz en el pan", "blade scoring cross on loaf"),
    I("paper bakery bag beside a cloth-wrapped homemade loaf", "bolsa de panaderia junto al pan casero", "bakery bag versus homemade loaf"),
    S("hands sprinkling more flour over dough before kneading again", "espolvorear harina sobre la masa", "sprinkling flour over dough"),
  ]},
  { t: 646.7, name: "atencion", pool: [
    I("close-up of a woman's serious face about to reveal something important", "mujer seria a punto de revelar", "serious woman about to reveal"),
    S("all the dishes of the video laid out together on one long table", "todos los platos juntos en la mesa", "all dishes together long table"),
    I("question mark formed by kitchen ingredients on a dark table", "signo de pregunta con ingredientes", "question mark kitchen ingredients"),
    S("hands stopping, resting on the table before speaking", "manos quietas sobre la mesa", "hands resting still on table"),
    I("old family photograph of a full table being held up", "foto antigua de la mesa familiar", "old family table photograph held"),
    S("empty modern plate next to a full traditional one", "plato moderno vacio junto al antiguo", "empty modern plate versus traditional"),
    I("dark kitchen with one light over the table, everything else in shadow", "cocina oscura con una sola luz", "dark kitchen single light table"),
    S("close-up of eyes looking straight ahead, serious", "mirada seria de frente", "serious eyes looking ahead"),
  ]},
  { t: 671.5, name: "revelacion", pool: [
    I("bones, stale bread and bruised fruit laid out together as the real ingredients", "huesos pan duro y fruta golpeada", "bones stale bread bruised fruit"),
    S("beef bones on a butcher block, the cheapest cut there is", "huesos de carne en la tabla", "beef bones butcher block"),
    S("hard stale bread in a basket", "pan duro en un canasto", "hard stale bread basket"),
    S("bruised fruit fallen under a tree in the grass", "fruta caida bajo el arbol", "bruised fallen fruit grass"),
    S("cheap lentils and beans in an open sack", "lentejas y porotos en bolsa", "lentils beans open sack"),
    S("pork fat trimmings on a board — what we throw away today", "recortes de grasa en la tabla", "pork fat trimmings board"),
    I("split screen feel: a rich stew on one side, a rubbish bin on the other", "guiso rico y tacho de basura", "rich stew versus rubbish bin"),
    S("food scraps being scraped off a plate into a bin", "restos de comida al tacho", "food scraps scraped into bin"),
    I("supermarket packaging of boneless meat wrapped in plastic", "carne sin hueso envasada plastico", "boneless meat plastic packaging"),
    S("perfect shiny supermarket fruit under bright lights", "fruta perfecta del supermercado", "perfect supermarket fruit lights"),
    I("advertising-style image selling convenience food in a box", "publicidad de comida en caja", "advertising boxed convenience food"),
    S("cardboard boxes and plastic packaging piling up", "cajas y plasticos amontonados", "cardboard plastic packaging pile"),
    I("the word progress written over a supermarket trolley of packaged food", "carrito lleno de comida envasada", "trolley full packaged food"),
    S("bones going straight into a bin in a modern kitchen", "tirar los huesos a la basura", "bones thrown into bin"),
    I("the same soup made from what someone else threw away", "sopa hecha con lo que se tira", "soup made from discarded food"),
    S("old pot of stock simmering with bones and vegetables", "caldo de huesos hirviendo", "bone stock simmering pot"),
    I("two shopping baskets compared: cheap scraps versus expensive packets", "dos canastas comparadas", "two shopping baskets compared"),
    S("money being handed over at a modern checkout", "pagar en la caja del super", "money handed at checkout"),
    I("factory production line making packaged food", "linea de produccion de alimentos", "factory food production line"),
    S("a pot of patience — long slow simmer, nothing else", "olla de paciencia a fuego lento", "slow simmering pot patience"),
    I("nobody profits from a woman who can cook a feast out of bones", "banquete hecho con huesos", "feast made from bones"),
    S("close-up of hands protecting a piece of stale bread", "manos guardando el pan de ayer", "hands saving stale bread"),
    I("generations of the same family eating from the same humble pot", "generaciones comiendo de la misma olla", "generations same humble pot"),
    S("empty rubbish bin bag being opened, ready to waste food", "bolsa de basura abierta", "empty bin bag opened"),
    S("humble ingredients arranged beautifully on a dark table", "ingredientes humildes bien puestos", "humble ingredients dark table"),
    S("stale bread and bones lit like treasure on dark wood", "pan duro y huesos como un tesoro", "stale bread bones dark wood"),
    I("long expensive supermarket receipt beside a cheap pot of bones", "ticket largo junto a la olla de huesos", "long receipt beside bone pot"),
  ]},
  { t: 752.1, name: "no-casualidad", pool: [
    I("boardroom-style shot of packaged food products lined up for sale", "productos envasados en fila", "packaged food products lined up"),
    S("plastic sachets and boxes of instant food on a shelf", "sobres y cajas de comida instantanea", "instant food sachets boxes shelf"),
    I("a bowl of bones and water — something nobody can sell you", "huesos y agua en una olla", "bones and water in pot"),
    S("cash register receipt printing out", "ticket de caja saliendo", "cash register receipt printing"),
    I("bright advertising colours of a processed food package", "envase colorido de comida procesada", "bright processed food package"),
    S("hands putting a packaged product into a trolley", "poner un producto en el carrito", "hands placing product trolley"),
    I("quiet kitchen pot that costs almost nothing to fill", "olla humilde que cuesta poco", "humble cheap cooking pot"),
    S("hands tearing open a plastic food wrapper", "abrir un envoltorio de plastico", "hands tearing plastic wrapper"),
  ]},
  { t: 775.8, name: "pedido", pool: [
    I("modern busy woman looking at the clock, no time to cook for hours", "mujer moderna mirando el reloj", "busy modern woman clock"),
    S("hand hovering over a bin holding yesterday's bread", "mano con pan de ayer sobre el tacho", "hand holding bread over bin"),
    S("chicken bones on a plate about to be thrown away", "huesos de pollo en el plato", "chicken bones plate discarded"),
    I("fruit going soft in a bowl on a modern kitchen counter", "fruta pasada en la cocina moderna", "soft fruit modern kitchen bowl"),
    S("someone stopping and putting the bread back on the counter instead", "guardar el pan en vez de tirarlo", "putting bread back counter"),
    I("simple pot of stock started with the bones that were going to be wasted", "caldo hecho con huesos rescatados", "stock made rescued bones"),
    S("modern kitchen with a small pot quietly simmering", "cocina moderna con una olla al fuego", "modern kitchen small simmering pot"),
    I("grandmother's photo on a modern fridge door", "foto de la abuela en la heladera", "grandmother photo fridge door"),
    S("hands closing a container of leftovers to save them", "guardar las sobras en un tupper", "hands saving leftovers container"),
    I("present-day kitchen, one small old habit brought back", "una costumbre vieja recuperada", "old habit brought back kitchen"),
    I("young woman phoning her grandmother to ask for a recipe", "joven llamando a su abuela por la receta", "young woman phoning grandmother recipe"),
    S("bag of bones and vegetable scraps saved in the freezer", "huesos y restos guardados en el freezer", "bones scraps saved freezer bag"),
  ]},
  { t: 807.8, name: "recap", pool: [
    S("big pot of puchero boiling with meat and vegetables", "puchero hirviendo con verduras", "puchero boiling meat vegetables"),
    S("bowl of bread soup, humble and steaming", "sopa de pan humeante", "bread soup steaming bowl"),
    S("pot of locro thick with corn and beans", "locro espeso con maiz", "locro thick corn beans"),
    S("small mug of mazamorra with white corn", "mazamorra en jarrito", "mazamorra white corn mug"),
    S("rice pudding with a browned skin on top", "arroz con leche con costrita", "rice pudding browned skin"),
    S("wooden spoon covered in thick dulce de leche", "cuchara con dulce de leche", "wooden spoon dulce de leche"),
    S("fried dough cakes piled on a plate on a rainy day", "tortas fritas dia de lluvia", "fried dough cakes rainy day"),
    S("fresh pasta being cut into long strands", "fideos caseros cortados", "fresh pasta cut strands"),
    S("empanadas baking in a clay oven", "empanadas en horno de barro", "empanadas baking clay oven"),
    S("cracklings served on top of homemade bread", "chicharrones sobre pan casero", "cracklings on homemade bread"),
    S("flan with hand-burnt caramel on a plate", "flan con caramelo quemado", "flan hand burnt caramel"),
    S("homemade loaf being broken with two hands", "pan casero partido a mano", "homemade loaf broken hands"),
    I("all twenty five dishes remembered, a long table full of food", "mesa larga con todos los platos", "long table all dishes remembered"),
    I("memories coming back like old photographs on a table", "recuerdos como fotos viejas", "memories like old photographs"),
    S("steam rising from several dishes at once", "vapor de varios platos juntos", "steam several dishes together"),
    I("someone remembering, eyes closed, at a kitchen table", "recordar con los ojos cerrados", "remembering eyes closed kitchen"),
    S("close-up of a full family table seen from above", "mesa familiar llena desde arriba", "full family table from above"),
    S("bowl of lentil stew with a bone resting in it", "lentejas con hueso en el plato", "lentil stew with bone bowl"),
  ]},
  { t: 863.1, name: "carnada", pool: [
    I("woman speaking warmly and directly, inviting an answer", "mujer hablando calidamente", "woman speaking warmly inviting"),
    S("hand writing in an old notebook at a kitchen table", "escribir en un cuaderno viejo", "hand writing notebook kitchen"),
    I("world map with pins marking many small towns", "mapa con alfileres de pueblos", "map pins marking towns"),
    S("old letters and postcards spread on a table", "cartas y postales viejas", "old letters postcards table"),
    I("many different kitchens around the world with the same pot", "cocinas distintas con la misma olla", "different kitchens same pot"),
    S("a pot shared between distant hands, symbolic", "olla compartida entre manos", "pot shared between hands"),
    I("faces of grandmothers from different countries side by side", "abuelas de distintos paises", "grandmothers different countries"),
    S("close-up of someone smiling while reading something", "sonreir mientras se lee", "smiling while reading"),
    I("neighbourhood street of a small town at dusk", "calle de pueblo al atardecer", "small town street dusk"),
    S("hands typing a short message", "manos escribiendo un mensaje", "hands typing short message"),
    I("kitchen table with a cup of tea and time to talk", "mesa con te y tiempo para charlar", "table tea time to talk"),
  ]},
  { t: 897.6, name: "teaser", pool: [
    I("mysterious dish covered with a cloth on a table, not yet revealed", "plato tapado sin revelar", "covered mysterious dish table"),
    S("old wall calendar with one date circled in pen", "calendario con una fecha marcada", "calendar one date circled"),
    I("secret ingredient in a small jar, unlabelled", "ingrediente secreto en un frasco", "secret ingredient small jar"),
    S("candle lit on a festive table once a year", "vela encendida mesa de fiesta", "candle lit festive table"),
    I("family celebrating a special date around a full table", "familia celebrando fecha especial", "family celebrating special date"),
    S("hands hiding something small inside a dish", "esconder algo dentro del plato", "hiding something inside dish"),
    I("old recipe written by hand on a yellowed page", "receta escrita a mano papel viejo", "handwritten recipe yellowed page"),
    S("a coin or charm hidden in food, tradition of luck", "moneda escondida en la comida", "coin hidden in food luck"),
    I("young family members who have never heard of the tradition", "jovenes que no conocen la tradicion", "young family unaware tradition"),
    S("close-up of steam rising from a covered pot, mystery", "vapor saliendo de una olla tapada", "steam covered pot mystery"),
    I("grandmother smiling knowingly, keeping the secret for next time", "abuela sonriendo guardando el secreto", "grandmother smiling keeping secret"),
    S("twelve months of a calendar flipping past", "calendario pasando los meses", "calendar months flipping"),
    I("cooking with the hands, with patience, with what little there was", "cocinar con las manos y paciencia", "cooking hands patience little"),
    S("old pot still warm on the stove, not fully out", "olla todavia tibia en la cocina", "pot still warm on stove"),
    I("someone telling the story and someone else listening carefully", "alguien contando y alguien escuchando", "someone telling someone listening"),
    S("embers still glowing in a stove at night", "brasas encendidas de noche", "embers glowing stove night"),
    I("warm kitchen light staying on, the pot never fully going out", "luz calida de la cocina encendida", "warm kitchen light staying on"),
    I("family gathered at night for a meal that happens once a year", "familia reunida de noche una vez al ano", "family night meal once a year"),
  ]},
  { t: 950.9, name: "cierre", pool: [
    I("the same kitchen from the beginning, warm and lived in", "la misma cocina del principio", "same warm lived kitchen"),
    S("pot simmering gently, steam rising, end of the story", "olla al fuego humeando suave", "pot simmering gentle steam"),
  ]},
];

// ── ventanas: recorre las captions y corta cada ~3.2s en frontera de palabra ──
const TARGET = 3.2, MIN = 2.4, MAX = 3.9;
const sectionAt = (sec) => { let cur = SECTIONS[0]; for (const s of SECTIONS) if (sec >= s.t) cur = s; return cur; };
const cursor = new Map(); // sección → índice del pool

const beats = [];
let i = 0, idx = START_IDX;
while (i < caps.length) {
  const startMs = caps[i].startMs;
  let j = i, endMs = caps[i].endMs;
  while (j + 1 < caps.length && (caps[j + 1].endMs - startMs) / 1000 <= TARGET) { j++; endMs = caps[j].endMs; }
  if ((endMs - startMs) / 1000 < MIN && j + 1 < caps.length) { j++; endMs = caps[j].endMs; }
  let dur = +((endMs - startMs) / 1000).toFixed(2);
  if (dur > MAX) dur = MAX;
  const phrase = caps.slice(i, j + 1).map((c) => c.text).join(" ").replace(/\s+/g, " ").trim();
  const sec = startMs / 1000;
  const S0 = sectionAt(sec);
  const k = cursor.get(S0.name) || 0;
  const v = S0.pool[k % S0.pool.length];
  cursor.set(S0.name, k + 1);
  const name = `${SLUG}_s_${String(idx).padStart(3, "0")}`;
  beats.push({ name, old: name, ms: P1_MS + startMs, dur, phrase, desc: v.desc, queries: v.queries, src: v.src, section: S0.name });
  idx++;
  i = j + 1;
}

fs.writeFileSync(`_v3/${SLUG}_beats_p2.json`, JSON.stringify(beats, null, 1));
const bySec = {};
for (const b of beats) bySec[b.section] = (bySec[b.section] || 0) + 1;
const reused = Object.entries(bySec).filter(([n, c]) => c > (SECTIONS.find((s) => s.name === n).pool.length));
console.log(`beats p2: ${beats.length}  ·  ${beats.filter((b) => b.src === "stock").length} stock / ${beats.filter((b) => b.src === "image").length} imagen`);
console.log("por sección:", JSON.stringify(bySec));
if (reused.length) console.log("⚠ secciones que reciclan visual (pool corto):", reused.map(([n, c]) => `${n} ${c}>${SECTIONS.find((s) => s.name === n).pool.length}`).join(", "));
