// DIRECTOR olcabin — parte C: #12 mojakka .. #1 lefse, cierre (9:10-19:20)
import { X, V, AVA, ST, AR, H, B, BC, O, C } from "./dir_lib.mjs";
const BOOK = "img/ole/portada.png", QR = "qr_ole_olcabin.png";
const PG = (n, extra = {}) => ({ src: `img/olcabin/book/p${n}.png`, aspect: 1700 / 2200, label: "A PAGE FROM THE BOOK", ...extra });
export const C_ = [
  // ── #12 MOJAKKA (551.6)
  B("Number twelve", "mojakka", "A steaming bowl of Finnish-American beef and potato stew, mojakka, with allspice berries visible, rye bread beside it, on a plank table.", "steam rises from the bowl"),
  AR("beef and potatoes, or fish and potatoes", "ar_finnish_miners"),
  B("and up on the Iron Range they'll fight you", "ironrange", "In a rustic cabin kitchen two older men in wool caps argue over two black pots on a wood stove, one pointing at a pot of beef stew and the other at a pot of fish stew, everyone good-humored.", "the two men gesture at the pots"),
  C("One story says the word comes from", "GrandmaCard", { title: "Mo-Jacob", lines: ["'more Jacob's stew,", "more Jacob, mo-Jacob'"], rot: -3, x: 50, y: 50 }),

  AVA("I can't prove it"),

  ST("Potatoes, onion, a hot bowl", "st_stew_steam"),
  // ── #11 WILD RICE HOTDISH (584.1)
  B("Number eleven", "hotdish", "A glass baking dish of wild rice hotdish with a crusty golden top and a serving spoon lifting a scoop, on a plank table with a potholder.", "steam rises from the scoop"),
  AR("Wild rice is manoomin to the Ojibwe", "ar_wildrice_harvest"),
  ST("who harvested it for centuries", "st_wild_rice_lake"),
  C("and in nineteen seventy-seven Minnesota made it the state grain", "OleCounter", { mode: "number", from: 1970, to: 1977, label: "State grain of Minnesota", start: 0.2, end: 1.6, x: 0.5, y: 0.5, bed: "img/olcabin/ar/ar_wildrice_harvest.jpg" }),
  C("Hotdish itself was first printed", "CabinRecipeBook3D", { pages: [{ title: "Church Supper", lines: ["hamburger", "macaroni", "canned peas", "bake till bubbly"], note: "1930" }, { title: "Hot Dish", lines: ["hamburger, macaroni,", "canned peas, soup"], note: "Ladies Aid" }], flips: 1, flipStart: 10, flipEvery: 14, cover: "Ladies Aid Cookbook" }),
  AVA("Nowadays plenty of folks make it with wild rice"),
  H("Brown some meat, fold in cooked wild rice", "hotdishmix", "An old hand folding cooked wild rice, browned ground beef, celery and a can of soup together in a big enamel bowl with a wooden spoon.", "the spoon folds the mixture"),
  ST("bake it until the top goes crusty", "st_casserole_bake"),
  AVA("It tastes like a Sunday after church"),
  // ── #10 SWEDISH MEATBALLS (622.0)
  B("Number ten", "meatballs", "A skillet of browned Swedish meatballs in cream gravy on the wood stove, lingonberry jar and potatoes beside, steam rising.", "the gravy bubbles"),
  AR("Sweden's own official account said the recipe came from King Charles", "ar_charles_xii"),
  C("who brought it home from Turkey", "OriginMap", { origins: [{ id: "sweden", label: "SWEDEN", dishes: ["meatballs"], at: 0.2 }], dest: "Turkey (1700s)", focus: "sweden" }),
  AVA("Plenty of folks argue about that"),
  AVA("I don't care"),
  H("Ground beef and pork, a little onion", "meatballmix", "Two old hands rolling small round meatballs from a bowl of ground meat and breadcrumbs soaked in milk onto a floured board.", "the hands roll a meatball"),
  ST("browned slow in butter", "st_meatballs_pan"),
  H("then a cream gravy scraped up", "gravy", "An old hand stirring cream into the brown bits in a cast iron skillet with a wooden spoon, gravy thickening.", "the spoon scrapes up the brown bits"),
  B("Serve them with potatoes and lingonberries", "meatplate", "A plate of Swedish meatballs with cream gravy, boiled potatoes and a spoon of red lingonberry sauce on a blue enamel plate.", "steam rises"),
  AR("a whole dinner that miners carried", "ar_miners_lunch"),
  // ── #9 LANTTULAATIKKO (660.4)
  B("Number nine", "lanttu", "A baking dish of golden-brown Finnish rutabaga casserole, lanttulaatikko, with a spoon scooping out orange mash, Christmas candle beside it.", "steam rises from the scoop"),
  ST("Boil the rutabaga soft", "st_rutabaga"),
  H("mash it with a little cream", "mash", "An old hand mashing soft orange rutabaga with a wooden masher in a big pot, cream being poured in.", "the masher presses the rutabaga"),
  ST("then bake it about an hour", "st_mash_veg"),
  AVA("Now most of you are making a face"),
  AVA("I get it"),
  BC("A rutabaga isn't a pretty vegetable", "ugly", "A lumpy waxy purple-yellow rutabaga on a plank table beside a knife, a bit of dirt still on its skin, harsh window light.", "slow push in"),
  B("Try it once before you decide", "christmasfin", "A Finnish Christmas table in a cabin with a casserole of orange rutabaga mash, candles, a loaf of bread and pine branches, snowy window.", "candles flicker"),
  // ── #8 PANNUKAKKU (690.0)
  B("Number eight", "pannu", "A thick golden puffed baked pancake, pannukakku, in a black cast iron skillet with raised edges and a sunken middle, cut in squares with a berry on top.", "steam rises from the pancake"),
  H("Melt butter in a cast-iron skillet", "pannubutter", "A pat of butter melting and sizzling in a black cast iron skillet inside a hot open oven, an old hand with a mitt holding the skillet.", "the butter melts and sizzles"),
  ST("and watch it puff up at the edges", "st_pancake_puff_oven"),
  BC("It sinks in the middle", "sinks", "A puffed golden pancake in an iron skillet on a plank table, its middle slowly sinking, steam curling up, the log cabin window behind.", "the middle sinks a little"),
  AVA("That's how you know it's right"),
  B("put a berry on the top", "berrysquare", "Squares of pannukakku with a berry on each on a blue enamel plate, four forks, a family's hands reaching in from the edges, everyone silent and eating.", "the hands take squares"),
  // ── POR QUÉ SE DEJARON DE HACER (719.5)
  AVA("Now why did all this fade"),
  C("These dishes took a whole day", "WhyTheyStopped", { title: "Why they faded", items: [{ kind: "iron", caption: "a special iron", offAt: 5.2 }, { kind: "kettle", caption: "a big kettle", offAt: 7.2 }, { kind: "table", caption: "a crew", offAt: 9.0 }] }),
  ST("Supper turned into something one person does alone", "st_lone_dinner"),
  AR("The ones that lived, lived because a church kitchen", "ar_church_women_cooking"),
  AVA("So if you take one thing from my box"),
  // ── #7 LUTEFISK (743.2)
  B("Number seven", "lutefisk", "A plate of jiggly white boiled lutefisk with melted butter poured over it, boiled potatoes and a piece of lefse beside, blue mug of coffee.", "melted butter runs down"),
  AVA("Here we go"),
  H("Dried cod, soaked in a lye solution", "lutesoak", "A big wooden trough of cloudy water with a stiff dried cod slab swelling in it, an old hand in a rubber glove pressing on the fish.", "the fish slab swells slowly"),
  C("Some folks say the Vikings invented it", "GrandmaCard", { title: "The Viking legend", lines: ["a fire, a rainstorm,", "and somebody very hungry"], rot: 2, x: 50, y: 50, from: "right" }),
  ST("It comes out white and jiggly", "st_fish_steamed"),
  ST("pour melted butter all over", "st_melted_butter"),
  AVA("Now, I'll be honest, friend"),
  AVA("But look at this"),
  AR("Lutheran churches across Minnesota still put on a lutefisk dinner", "ar_lutefisk_dinner"),
  B("Somebody loves it", "lutefans", "A church basement long table with paper plates of lutefisk and people of all ages eating happily, an older man giving a thumbs up, no readable signs.", "the older man raises his thumb"),
  AVA("The rest of us eat the potatoes and lefse"),
  // ── #6 LIMPA (783.2)
  B("Number six", "limpa", "A round loaf of dark limpa Swedish rye bread with a shiny crust, sliced thin, with butter, cheese and a blue mug on a wooden board.", "steam rises from the fresh loaf"),
  H("sweetened with brown sugar and molasses", "molasses", "Dark black molasses pouring slowly from a spoon into a big bowl of rye dough with brown sugar.", "the molasses pours"),
  H("and spiced with anise, caraway and fennel", "limpaspice", "Four tin spoons on a plank table each holding a different spice: star anise, caraway seeds, fennel seeds and orange peel.", "slow push in on the spoons"),
  ST("It's baked mostly at Christmas", "st_dark_bread_oven"),
  BC("and the smell in a cabin kitchen", "cabinbaking", "The cabin kitchen at Christmas: a loaf of dark bread cooling on the sill beside the snowy window, steam curling, a hand-drawn paper star, wood stove glow.", "the steam curls from the loaf"),
  H("Slice it thin", "limpaslice", "An old hand slicing a thin slice off a dark rye loaf with a long bread knife.", "the knife slices"),
  ST("Butter it thick", "st_butter_toast"),
  B("Top it with cheese or a piece of that pickled herring", "limpaherring", "A slice of dark limpa bread topped with cheese and another with a piece of pickled herring and onion on a wooden board, a pickle jar behind.", "slow push in"),
  // ── #5 FISH CHOWDER (810.4) — libro p.34

  B("Number five", "chowder", "A tin bowl of creamy salt-pork fish chowder with chunks of white fish and potato, black pepper on top, steam rising, oyster crackers beside.", "steam rises"),
  AVA("Not Scandinavian, friend"),
  AR("Every cabin on a cold lake had a pot for it", "ar_lake_cabin"),
  ST("Render four ounces of diced salt pork", "st_salt_pork_render"),
  H("Cook a chopped onion in the fat", "chowderonion", "An old hand stirring chopped onion in rendered pork fat in a black pot, cubes of potato in a tin cup beside.", "the onion sizzles in the fat"),
  H("Nestle a pound and a half of firm white fish", "chowderfish", "An old hand laying thick white fish fillets on top of potatoes in a black pot, water steaming.", "the fish settles on the potatoes"),
  ST("then pour in three cups of milk and a cup of cream", "st_cream_pour"),
  ST("Do not boil it", "st_chowder_soup"),
  C("That one's in the book, page thirty-four", "OleBookPage", PG(34, { keys: [[0.2, 0.5, 0.5, 1], [0.9, 0.27, 0.53, 2.3]], sub: "Salt-pork fish chowder · page 34" })),
  // ── #4 RØMMEGRØT (848.1) HÉROE
  C("Number four", "PorridgeBowl3D", { stages: [{ at: 0, stage: "cream" }, { at: 8.5, stage: "butter" }, { at: 12.0, stage: "cinnamon" }] }),
  H("it was too rich to eat any old Tuesday", "rommerich", "A heavy black pot on the wood stove filled with thick white sour cream porridge, a wooden whisk standing in it.", "slow push in on the pot"),
  B("It was for weddings", "weddingtable", "A long rustic table set for a cabin celebration: a big bowl of sour-cream porridge, three candles, pine sprigs, a bowl of cinnamon sugar and rows of tin spoons.", "candles flicker"),
  ST("Here's how it's done", "st_candles_table"),

  H("Two cups of full-fat sour cream in a heavy pot", "rommesimmer", "Thick white sour cream simmering in a heavy black pot on the wood stove, small bubbles and a wooden spoon.", "the cream bubbles"),
  H("Sift in three-quarters of a cup of flour", "rommeflour", "Flour sifted through a tin sieve into a pot of hot sour cream while an old hand whisks hard.", "the flour sifts into the pot"),
  ST("Keep cooking, and the butterfat rises", "st_sour_cream_stir"),
  H("Skim it off and save it", "rommeskim", "A spoon skimming yellow butterfat from the surface of thick white porridge into a small tin cup.", "the spoon skims the butter"),
  H("Now whisk in two cups of hot milk", "rommemilk", "Hot milk being poured into the pot while a wooden whisk stirs the thick porridge, steam rising.", "the milk pours into the pot"),
  C("Pour it in a bowl, make a well in the middle", "PorridgeBowl3D", { stages: [{ at: 0, stage: "well" }, { at: 2.5, stage: "butter" }, { at: 4.8, stage: "cinnamon" }] }),
  AVA("Now that's a bowl worth waiting for"),
  AVA("My whole cabin used to go quiet"),
  AVA("I say it's the butter"),
  // ── #3 PASTY (905.8) HÉROE
  C("Number three", "TinRecipeBox3D", { cards: [["The pasty", "beef, potato", "rutabaga, onion"]], openAt: 0.0, liftAt: 0.5 }),
  AR("Cornish miners brought it to the Iron Range", "ar_cornish_miners"),
  AR("Michigan", "ar_iron_mine_mn"),
  B("a whole dinner in a crust you could carry", "pastydown", "A miner's hands holding a golden D-shaped pasty wrapped in a cloth, a dark mine shaft entrance and lantern light behind, dinner pail on the ground.", "the lantern light flickers"),
  C("Then the Finns showed up", "OriginMap", { origins: [{ id: "cornwall", label: "CORNWALL", dishes: ["pasty"], at: 0.2 }, { id: "finland", label: "FINLAND", dishes: ["+ rutabaga"], at: 2.0 }], dest: "The Iron Range" }),

  AVA("and that's the version I love"),
  ST("The filling is beef in small chunks", "st_chop_veggies"),
  B("with salt and pepper and nothing else", "pastyfill", "A wooden bowl of raw pasty filling: small cubes of beef, diced potato, diced rutabaga and chopped onion, salt and pepper on top, on the plank table.", "slow push in"),
  H("Cornwall's rule says skirt steak", "pastysteak", "An old hand cutting raw beef skirt steak into small chunks on a wooden board beside diced potato and rutabaga.", "the knife cuts a chunk"),
  B("Up here plenty of folks grind the beef", "twotrays", "Two enamel trays on a plank table: one with small cubes of raw beef and one with ground beef, both next to diced potato and rutabaga.", "slow push in"),
  H("For the crust, two and a half cups of flour", "pastycrust", "An old hand cutting cold lard into flour with two knives in a wooden bowl, ice water in a tin cup beside.", "the knives cut the lard"),
  C("a teaspoon of salt, a cup of cold lard", "OleRuleCard", { n: 4, title: "Pasty crust", line: "2 1/2 cups flour · 1 tsp salt · 1 cup lard · 6-8 Tbsp ice water", placement: "center" }),
  H("pile the filling on half, fold it over", "pastyfold", "Two old hands folding a dinner-plate round of dough over a heap of raw filling.", "the dough folds over the filling"),
  ST("crimp the edge along the side", "st_pastry_crimp"),
  ST("Bake it in a hot oven", "st_oven_dial"),
  AVA("Eat it with your hands"),
  AVA("Ketchup, or gravy"),
  // ── #2 BOOYAH (973.8) HÉROE
  C("Number two", "BooyahKettle3D", { pours: [{ at: 4.0 }] }),
  AR("Belgian immigrants who settled around Green Bay", "ar_belgian_doorcounty"),
  C("and the name is probably how somebody spelled", "OriginMap", { origins: [{ id: "belgium", label: "BELGIUM", dishes: ["booyah"], at: 0.2 }], dest: "Green Bay & Door County" }),
  H("with the spices tied up in a cheesecloth bag", "spicebag", "An old hand tying a small cheesecloth bag of whole spices and herbs with kitchen twine on the plank table.", "the hand ties the twine"),
  ST("In a church parking lot they cook it in a kettle", "st_big_kettle_outdoor"),
  AR("and it can take two days and a crew of cooks", "ar_church_picnic_kitchen"),
  AVA("At your house, do it like this"),
  ST("A whole stewing chicken", "st_chicken_pot"),
  H("covered with cold water", "boopot", "A whole stewing chicken and a beef shank lowered into a big black iron pot of cold water on the wood stove by an old hand.", "the chicken sinks into the water"),
  H("Pull the meat, chop it", "boochop", "An old hand pulling meat from a boiled chicken and chopping it on a wooden board beside a pot.", "the knife chops the meat"),
  H("Nobody eats one bowl", "boobowl", "A ladle pouring thick steaming booyah stew with carrots and potatoes into a tin bowl.", "the ladle pours the stew"),
  ST("Booyah is the reason a whole town shows up", "st_picnic_table_crowd"),
  ST("also the reason there are leftovers", "st_church_potluck"),
  // ── #1 LEFSE (1036.4) — PAGO GRANDE
  C("And now, number one", "RecipeCountdown", { n: 1, name: "Lefse", word: "NUMBER", placement: "center", hero: true }),
  B("Lefse. Norwegian potato flatbread", "lefse", "A stack of soft thin round lefse potato flatbread folded in a cloth on a plank table, one rolled with butter and sugar, a blue mug of coffee.", "steam rises from the stack"),
  AR("It goes back to medieval Norway", "ar_potato_field"),
  C("When the potato arrived", "OriginMap", { origins: [{ id: "norway", label: "NORWAY", dishes: ["lefse"], at: 0.2 }], dest: "The north woods", focus: "norway" }),
  AVA("Here's how it goes"),
  H("Boil about one and three-quarter pounds", "ricer", "An old hand pushing hot boiled russet potatoes through a metal ricer into a bowl, fluffy strands falling, steam rising.", "the potato strands fall from the ricer"),
  C("Stir in five tablespoons of butter", "OleRuleCard", { n: 5, title: "Lefse dough", line: "1 3/4 lb russets · 5 Tbsp butter · 1/4 cup cream · 2 tsp sugar · 1 1/2 tsp salt", placement: "center" }),
  H("Now here's the one way to ruin it", "warm", "Warm sticky potato dough clinging to a rolling pin and torn on a floured board, an old hand pulling the ragged sheet away.", "the dough sticks and tears"),
  ST("So chill it overnight", "st_kneading_dough"),
  BC("cold all the way through", "cold", "A covered bowl of potato dough on a cold pantry shelf under a frosty window, a thermometer hanging beside it, night, lantern glow.", "frost creeps on the glass"),
  H("The next day, work in a cup and a half of flour", "lefseflour", "An old hand working flour into cold potato dough in a wooden bowl, then rolling it into balls.", "the hand works the flour in"),
  H("Roll each ball paper thin", "lefsepin", "A grooved wooden rolling pin rolling a ball of potato dough paper thin on a floured cloth-covered board.", "the pin rolls the dough thin"),
  ST("lay it on a hot dry griddle", "st_griddle_flatbread"),
  H("Little brown freckles", "lefsestick", "A long flat wooden lefse stick sliding under a thin round of lefse with brown freckles on a hot griddle.", "the stick lifts and flips the lefse"),
  H("and stack it between clean towels", "lefsestack", "An old hand stacking hot soft lefse rounds between clean folded tea towels.", "the hand lays a lefse on the stack"),
  AVA("Butter and sugar, roll it up"),
  AR("Two weekends before Christmas", "ar_lefse_women"),
  AR("The bread itself is just potato and flour", "ar_immigrant_table"),
  AVA("The rest is everyone standing at the table together"),
  // ── CIERRE (1128.3)
  AVA("That's the whole box, friend"),
  C("Twenty-five dishes from a cabin kitchen", "CabinCutaway3D", { fill: [{ at: 0.0, n: 25 }, { at: 9, n: 25 }], startAngle: 0.2, orbit: 0.4 }),
  C("The dishes from my own kitchen", "OleCTA", { cover: BOOK, qr: QR, point: "Point your phone at this code", line: "Rice porridge · Dried-apple pie · Bannock · Sausage & sauerkraut · Fish chowder", kicker: "ON THE LIST, IN THE COOKBOOK" }),
  AVA("Now tell me"),
  AVA("Which of these did your family make"),
  B("I read every one", "coffeeon", "The plank table in the log cabin at dusk with the green tin recipe box closed, a blue enamel coffee pot steaming on the wood stove behind and a fresh blue mug of coffee poured in the foreground, warm lantern glow, snow at the window.", "steam curls from the mug, very slow push in"),
];
