// DIRECTOR A — minuto 1 (la caja del contenedor en Columbus) + Hazel + el contenedor + ítems 1-4 (p0-15)
import { S, BI, HZP, HOUSE, SHOP, GARAGE, VELVET } from "./dir_lib.mjs";
export const ITEMS10 = ["The button tin", "The mixing bowls", "The recipe box", "The war box", "Christmas boxes", "The quilts", "The records", "The toys", "The silverware", "The paper"];
const DRIVE = "the driveway of a modest two-story house in Columbus, Ohio, on a cleanout weekend: a big green rented dumpster with bags and broken furniture in it, cardboard boxes on the lawn, a minivan with its hatch open";
export const SHOTS = [
  // ── MINUTO 1
  S(0, "", "vl", "m1"),
  S(0, "That's what I said to a man in Columbus", "bi", "b_dumpsterman", { p: BI(`In ${DRIVE}: a man in his forties in a grey t-shirt with one foot up on the edge of the green dumpster, lifting a cardboard box of old dishes and a small wooden case to throw it in.`), anim: "the man lifts the box up toward the dumpster" }),
  S(0, "with one foot already up on the dumpster", "st", "st_dumpster.1"),
  S(0, "He was helping his wife clean out", "st", "st_clearing.1"),
  S(0, "and that box was going straight in the trash", "bi", "b_boxtrash", { p: BI(`Close view of a cardboard box tilted over the open green dumpster in ${DRIVE.split(":")[0]}: inside it an old cookie tin, three nested milk glass mixing bowls with colored bands, and a small dark velvet case.`), anim: "the box tilts further over the dumpster edge" }),
  S(0, "In that box was a button tin", "bi", "b_buttontin", { p: BI("An old round cookie tin opened on a kitchen table spilling hundreds of mixed vintage buttons, some heavy butterscotch, cherry red and dark green carved ones among plain white shirt buttons, an older woman's hand stirring them."), anim: "the hand stirs through the buttons in the tin" }),
  S(0, "three old mixing bowls", "st", "st_baking.1"),
  S(0, "and a little velvet case", "bi", "b_medalcase", { p: BI(`A small worn dark blue velvet case opened on ${VELVET.split(" on ")[0]} on a kitchen table showing old military medals with faded ribbons and a few cloth patches, an old black-and-white photo of a young soldier tucked in the lid.`), anim: "an older woman's fingers lift the lid of the velvet case wider" }),
  S(1, "", "av", "av"),
  S(1, "And I'm going to tell you how that box turned out", "vl", "m2"),
  S(2, "", "st", "st_attic.1"),
  S(2, "I'm going to give you ten things", "c", "HzRecap", { props: { items: ITEMS10, every: 3, start: 2, title: "check these first", bed: "st_antiqueshop.1" } }),
  S(2, "what it really sells for", "c", "HzPriceTag", { props: { bed: "b_buttontin", front: "$0", frontNote: "into the dumpster", sold: "sold prices", soldLabel: "not wishful thinking", item: "check the sold listings", flipAt: 30, stamp: "check" } }),
  S(2, "and where to sell it", "st", "st_laptop.1"),
  S(2, "or you know you will be someday", "av", "av"),
  S(2, "How to recognize each one", "st", "st_buttons.2"),
  S(3, "", "c", "HzWorthNothing", { props: { bed: "b_china", img: "b_china", title: "what isn't worth your time", price: "", note: "so you don't spend six months on it", stamp: "skip it", bed: "st_thrift.1" } }),
  // ── HAZEL
  S(4, "", "av", "av", { ov: { c: "HzNameTag", props: { name: "Hazel", line: "40 years of estate sales · Ohio" } } }),
  S(4, "I've helped hundreds of families", "st", "st_family.1"),
  S(4, "and I've watched more good things go in a dumpster", "vl", "m3"),
  // ── EL CONTENEDOR
  S(5, "", "c", "HzRuleCard", { props: { eyebrow: "Hazel's rule", rule: "Rent the dumpster last.", lines: ["Go room by room first."], every: 40, bed: "st_dumpster.2" } }),
  S(5, "I know, you're tired", "st", "st_boxes.2"),
  S(5, "Go through the house first", "hz", "h_roombyroom", { p: HZP("She walks slowly through an emptying living room of an older house with a clipboard, cardboard boxes labeled in marker stacked by the walls, looking into an open closet.", HOUSE) }),
  S(5, "and nothing leaves until somebody", "av", "av"),
  // ── 1 · BOTONES
  S(6, "", "c", "HzLotCard", { props: { n: 1, of: 10, title: "The button tin", where: "the sewing basket", bed: "st_buttonjar.1" } }),
  S(6, "Most of them are worth very little", "av", "av"),
  S(7, "", "bi", "b_bakelite", { p: BI("Close view of a few heavy vintage Bakelite buttons in an older woman's palm: butterscotch, cherry red and dark green, some deeply carved with flowers, beside plain white plastic buttons for comparison, on a kitchen table."), anim: "the palm tilts and the heavy buttons roll slightly" }),
  S(7, "Run one under hot tap water and smell it", "hz", "h_sniff", { p: HZP("She holds a wet red button she just ran under the hot tap close to her nose and sniffs it with a skeptical, focused squint over her glasses, at a kitchen sink.", "an older family kitchen") }),
  S(7, "Old Bakelite gives off a sharp chemical smell", "c", "HzMagnetTest", { props: { title: "the hot water test", left: { label: "Bakelite", sticks: true, verdict: "sharp chemical smell" }, right: { label: "plastic", sticks: false, verdict: "no smell" }, bed: "b_bakelite" } }),
  S(7, "Here's the test", "av", "av"),
  S(8, "", "c", "HzSoldListings", { props: { title: "Sold — Bakelite buttons", rows: [{ item: "Single plain Bakelite button", price: "$3–25" }, { item: "Carved, big, unusual colors", price: "$50–100+" }, { item: "A tin with a good mix", price: "a nice sum" }], every: 60, range: "sold, not asking", bed: "st_sewingmachine.1" } }),
  S(8, "Sell them as a lot online", "av", "av"),
  S(8, "and those ladies know their stuff", "av", "av"),
  S(8, "Carved ones, big ones", "av", "av"),
  S(8, "A tin with a good mix", "av", "av"),
  // ── 2 · PYREX
  S(9, "", "c", "HzLotCard", { props: { n: 2, of: 10, title: "The mixing bowls", where: "the top shelf", bed: "st_vintagekitchen.1" } }),
  S(9, "The milk glass bowls with the colored patterns", "bi", "b_pyrexshelf", { p: BI(`The top shelf of an old kitchen cabinet in ${HOUSE.split(":")[0]}: a nested set of four vintage opaque white milk glass mixing bowls with bright colored bands and dots, blue, yellow, red and green, a stack of old cake pans beside them.`), anim: "an older woman's hand reaches up and lifts the top bowl" }),
  S(9, "Common patterns usually sell for ten to forty dollars", "c", "HzSoldListings", { props: { title: "Sold — vintage mixing bowls", rows: [{ item: "Common pattern, one bowl", price: "$10–40" }, { item: "Complete set, wanted pattern", price: "a few hundred" }, { item: "Rare short-run patterns", price: "thousands (rare)" }], every: 75, range: "check the pattern name", bed: "st_vintagekitchen.3" } }),
  S(9, "A complete nesting set", "av", "av"),
  S(9, "have sold for thousands", "st", "st_baking.2"),
  S(10, "", "c", "HzPyrex3D", { props: { title: "bright vs. faded", fadeAt: 110, verdict: "bright & glossy", fadedLabel: "dishwasher-faded" } }),
  S(10, "Look on the bottom for the Pyrex mark", "bi", "b_pyrexbottom", { p: BI("A vintage milk glass mixing bowl turned upside down on a kitchen counter, the embossed maker's mark and numbers visible on the bottom, an older woman's finger pointing at it."), anim: "the finger traces the embossed letters on the bottom" }),
  S(10, "Sell them locally or online", "st", "st_kitchen.1"),
  S(10, "Then look up the pattern name", "av", "av"),
  // ── 3 · RECETAS
  S(11, "", "c", "HzLotCard", { props: { n: 3, of: 10, title: "The recipe box", where: "the kitchen drawer", bed: "st_vintagekitchen.2" } }),
  S(11, "Most community cookbooks", "bi", "b_churchbook", { p: BI("A worn spiral-bound church community cookbook from the 1960s open on a kitchen table, splattered pages with typed recipes and contributors' names, a wooden spoon resting on it."), anim: "a hand turns a splattered page" }),
  S(11, "Look at the copyright page", "bi", "b_firsted", { p: BI("Close view of the copyright page of an old hardcover cookbook held open in an older woman's hands, the small printed words First Edition visible, the dust jacket edge in frame."), anim: "the fingers smooth the page flat" }),
  S(11, "But some cookbooks are worth real money", "st", "st_cookbook.1"),
  S(11, "that's what collectors want", "av", "av"),
  S(12, "", "bi", "b_recipebox", { p: BI("An old tin recipe box opened on a kitchen counter, stuffed with stained handwritten index cards in faded blue ink, one card pulled up reading Mom's Pot Roast in cursive."), anim: "a hand pulls one recipe card up out of the box" }),
  S(12, "I've seen grown men cry", "st", "st_recipe.1"),
  S(12, "Scan them, and give copies to the family", "hz", "h_scan", { p: HZP("She sits at a kitchen table photographing handwritten recipe cards one by one with a phone, a tin recipe box open beside her, smiling softly at one card.", "an older family kitchen") }),
  S(12, "but they're your family's history", "av", "av"),
  // ── 4 · LA CAJA DE LA GUERRA
  S(13, "", "c", "HzLotCard", { props: { n: 4, of: 10, title: "The war box", where: "the closet shelf", bed: "b_medalcase" } }),
  S(13, "Medals, patches, ribbons, a uniform", "bi", "b_warbox", { p: BI("An old cardboard shoebox opened on a bed: military medals with ribbons, cloth unit patches, a folded olive uniform shirt, bundles of letters tied with string and black-and-white photos of young soldiers."), anim: "a hand lifts a bundle of letters out of the box" }),
  S(13, "letters home, photographs", "av", "av"),
  S(14, "", "av", "av"),
  S(14, "is worth much more together", "c", "HzLotVsPiece", { props: { lotLabel: "broken apart", lotPrice: "less", pieces: [{ label: "one soldier's named group", price: "much more" }], total: "keep it together", leftTitle: "piece by piece", rightTitle: "together", bed: "b_warbox" } }),
  S(15, "", "av", "av"),
  S(15, "Ask the grandkids", "av", "av"),
  S(15, "If you do sell, go to a reputable militaria dealer", "av", "av"),
];
