SLUG = 'tcmilavad'
exec(open('D:/Proyectos/video2-wt/_narr/dirbase.py', encoding='utf8').read())
lab('b001', 'REPARO LAVADORAS TODOS LOS DÍAS', 'reparo', tone='yellow', dur=2.8)
lab('b002', 'LA QUE PUSE EN MI CASA', 'casa', tone='yellow', dur=2.6)
lab('b004', 'ELECTRÓNICA SIMPLE · PIEZAS ACCESIBLES…', 'electrónica', tone='white', dur=3.0, size=52)
lab('b005', 'LO QUE EVITÉ: TÁCTIL · WIFI · VAPOR', 'evité', tone='red', dur=2.8)
lab('b006', 'SIN MARCAS NI MODELOS', 'marca', tone='white', dur=2.6)
step('b007', 1, 5, 'ELECTRÓNICA SIMPLE')
lab('b008', 'PLACA SIMPLE VS PLACA COMPLEJA', 'placa', tone='white', dur=2.8)
lab('b010', 'PANTALLA TÁCTIL ROTA = CASI UNA NUEVA', 'táctil', tone='red', dur=3.0, size=52)
step('b011', 2, 5, 'PIEZAS ACCESIBLES')
lab('b012', 'FILTRO DE LA BOMBA AL FRENTE', 'filtro', tone='yellow', dur=2.8)
lab('b013', 'CUBA SELLADA: NO SE ABRE', 'sellada', tone='red', dur=2.6)
lab('b014', 'CUBA ATORNILLADA: SE REPARA', 'cuba', tone='yellow', dur=2.8)
step('b016', 3, 5, 'TAMBOR Y RODAMIENTOS')
lab('b017', 'EL GROSOR DEL EJE', 'eje', tone='white', dur=2.4)
lab('b018', 'EL PESO: CONTRAPESOS GRANDES', 'peso', tone='yellow', dur=2.8)
lab('b019', 'EMPUJALA EN LA TIENDA', 'empuja', tone='white', dur=2.6)
step('b020', 4, 5, 'LA GOMA DE LA PUERTA')
lab('b021', 'PLIEGUES PROFUNDOS = AGUA Y MOHO', 'goma', tone='red', dur=2.8)
step('b023', 5, 5, 'REPUESTOS Y SERVICIO')
lab('b024', 'BUSCÁ EL MODELO EN TIENDAS DE REPUESTOS', 'repuestos', tone='yellow', dur=3.0, size=52)
lab('b026', '¿CUÁNTO TARDA UN REPUESTO?', 'tarda', tone='white', dur=2.6)
lab('b027', 'PAREJA: ~7 kg', 'siete', tone='yellow', dur=2.4)
lab('b030', '7 PROGRAMAS · USO LA MITAD', 'programas', tone='white', dur=2.8)
lab('b031', 'FILTRO DE LA BOMBA: CADA 3 MESES', 'meses', tone='yellow', dur=2.8)
lab('b033', 'ANOTO LA FECHA DEL MANTENIMIENTO', 'fecha', tone='white', dur=2.8)
lab('b034', '¿MÁS CARO = DURA MÁS?', 'caro', tone='red', dur=2.6)
lab('b036', 'MENOS FUNCIONES, MEJOR SERVICIO', 'funciones', tone='yellow', dur=2.8)
lab('b037', 'EL AGUA DURA: ENEMIGA', 'dura', tone='red', dur=2.6)
lab('b038', 'RESISTENCIA CUBIERTA DE CAL', 'cal', tone='white', dur=2.6)
lab('b039', 'LA CANTIDAD CORRECTA DE DETERGENTE', 'cantidad', tone='white', dur=3.0, size=52)
lab('b041', 'TORNILLOS DE TRANSPORTE', 'tornillos', tone='yellow', dur=2.6)
lab('b043', 'NIVELAR Y TRABAR LA TUERCA', 'nivelar', tone='white', dur=2.6)
lab('b044', 'DESAGÜE EN ALTO, CON ARCO', 'arco', tone='white', dur=2.6)
slam('b045', [('ERRORES DE COMPRA', 'errores', 'red')], 'errores', size=90, until='b045', off=-0.2)
lab('b046', 'DESCONTINUADO BARATO = SIN REPUESTOS', 'descontinuado', tone='red', dur=3.0, size=52)
lab('b047', 'PENSALO 2 DÍAS · COMPARÁ EN 3 LUGARES', 'tiendas', tone='yellow', dur=3.0, size=52)
lab('b048', 'LAVASECADORAS', 'lavan', tone='white', dur=2.4)
lab('b050', 'FILTRO DE PELUSA EN CADA USO', 'pelusa', tone='yellow', dur=2.8)
lab('b051', 'SI YA ANDA, NO LA CAMBIES', 'cambies', tone='yellow', dur=2.6)
lab('b052', 'REPARÁ SOLO CON PRESUPUESTO DESGLOSADO', 'desglosado', tone='white', dur=3.0, size=52)
lab('b053', 'UNA SEGUNDA OPINIÓN', 'opinión', tone='white', dur=2.4)
slam('b054', [('ELECTRÓNICA SIMPLE', 'electrónica', 'yellow'), ('PIEZAS ACCESIBLES', 'piezas', None), ('TAMBOR · GOMA · REPUESTOS', 'tambor', 'yellow')], 'criterios', size=76, until='b054', off=-0.1)
slam('b056', [('PRÓXIMO VIDEO', 'próximo', 'yellow'), ('LAS LAVADORAS BARATAS QUE SÍ RECOMIENDO', 'lavadoras', 'red')], 'próximo', size=72, until='b056', off=-0.1)
finish()
